### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by Gchorba** [RiotGames/developer-relations#1]
**Preconditions (*)**

- 

- 

Steps to reproduce (*)

- 

- 

Expected result (*)

- [Screenshots, logs or description]

Actual result (*)

- [Screenshots, logs or description]

**Comment by stelar7** [comment]
With the addition of 9cfd85b8bc7eb6ccb48e30d5ccb4624137e119c5, all reports now have this template as default, and as such this can be closed
