### ISSUE TITLE
Champion-mastery-v4 still shows summonerId as the parameter

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#10]
I expect this is supposed to read encryptedSummonerId like the rest of them

![issue](https://i.imgur.com/356afbW.png)

**Comment by jluzonpr** [comment]
Pretty sure I had fixed this already, but let me take a look.

**Comment by jluzonpr** [comment]
I had fixed it but hadn't pushed it live, but now it is live. :)

**Comment by jluzonpr** [comment]
@Gchorba @Strebeck plz close

**Comment by Strebeck** [comment]
Closing Issue, thanks all.
