### ISSUE TITLE
[BUG] LoR: Wild fragment naming inconsistency in the Wallet

### ISSUE THREAD

**Issue by jamester07** [RiotGames/developer-relations#1003]
**Bug Description**  
When you view the Wild fragments inside your wallet it shows the text "Wild Fragment" instead of "Wild Fragments" like all the other fragments.
 
**Problem Description**  
The naming scheme of fragments is not being followed inside the Wallet.

**Expected Result**  
I expect to see "WILD FRAGMENTS" instead of "WILD FRAGMENT"

**Actual Result**  
I saw "WILD FRAGMENT" instead of "WILD FRAGMENTS"

**Developer Impact**  
It makes is slightly unclear what naming convention should be followed regarding fragments.

* Severity: Extremely low

**Preconditions**  
* User must have more then zero Wild Fragments
* User must be logged in

**Repro Steps**  
1. Log in
2. Go to path of champions
3. From the map, click on Switch champion (bottom right)
4. Press the wallet / Nova icon next to WILD FRAGMENTS xxx/500
5. Click on WILD FRAGMENTS

**Issue Comments**  
Bug was found on game-version: live-green-5-10-117, running the latest version of android as of 23/10/2024 on the samsung S23 Ultra

**Comment by geozukunft** [comment]
This repository is only for reporting issues with the API please contact support at https://support.riotgames.com or support@riotgames.com

**Comment by jamester07** [comment]
Issue is not related to the API
