### ISSUE TITLE
[BUG] developer.riotgames.com TLS certificate issues

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#1004]
**Bug Description**  
The recent update to the SSL/TLS certificate of the developer.riotgames.com and associated *.developer.riotgames.com has a certificate chain issue causing trust issues.

**Problem Description**  
The chain that is being provided with the certificate goes to an untrusted CA. Only some browsers can properly infer the correct trust path.

Most chromium based browsers are not able to view these resources due to this issue.

The trusted correct chain is developer.riotgames.com -> HydrantID Server CA O1 -> IdenTrust Commercial Root CA 1.
The chain being provided is developer.riotgames.com -> HydrantID Server CA O1  -> IdenTrust Commercial Root CA 1 (Expired 30 Sep 2024) -> DST Root CA X3 (Expired 30 Sep 2021).

**Developer Impact**  
This causes developers to not be able to correctly view the resources to create applications.

This also effects applications that use the static resources provided by Riot including queues and like.

**Player Impact**  
No direct player impact.

**Repro Steps**  
Visit [https://developer.riotgames.com](https://developer.riotgames.com) on Google Chrome on Windows.

**Issue Comments**  
The certificate itself is good, just the chain needs to be fixed and everything will play nice.

**Comment by lucasMesquitaBorges** [comment]
This issue was fixed. Thanks for reporting it!
