### ISSUE TITLE
[BUG] [LOL] No match data before 30th April 2024 (Match-V5)

### ISSUE THREAD

**Issue by Clemtourte** [RiotGames/developer-relations#1008]
**Bug Description**  
League Of Legends
I am not getting data on matches played before May 30th from API:
MATCH-V5
endpoint: /lol/match/v5/matches/by-puuid/{puuid}/ids

**Problem Description**  
For some puuid, I don't retrieve any matchId before 30th of May when using the endpoint. Though data is well retrieved after 31st of April 2024.

**Expected Result**  
Retrieving the matchIds between a startTime and an endTime

**Actual Result**  
No data is retrieved

**Developer Impact**  
* Frequency: Every API call
* Severity: My webapp and calculations are not up to date

**Preconditions**  
None

**Issue Comments**  
This bug looks a lot like the one documented in issue #644 (from 2022) which was supposed to be fixed.

**Comment by DarkIntaqt** [comment]
Only the last 1000 matches are stored. If the player played more matches in that timeframe, you can't go back any further. This also includes custom games.

If you still believe that this is an issue, feel free to keep this issue opened

**Comment by francois-blanchard** [comment]
I faced the same issue.
I can only get my past 309 matches.

Moreover, the last 9 matches (the oldest ones) are not found when I use the endpoint `/lol/match/v5/matches/{matchId}`.
```json
{
    "status": {
        "message": "Data not found - match file not found",
        "status_code": 404
    }
}
```
For the record, here are the match IDs list not found: `["EUW1_6355940248", "EUW1_6354870478", "EUW1_6343281288", "EUW1_6343216566", "EUW1_6343146806", "EUW1_6343133953", "EUW1_6343048362", "EUW1_6342844078", "EUW1_6342805601"]`

The oldest match I can get information about is the `EUW1_6356400637` and it was created on `Tuesday 11 April 2023 17:20:01.235`.

**Comment by bangingheads** [comment]
There have been issues in the past with custom games and practice tool being included in match history without the games being accessible. The issues were fixed but the match ids linger in match history.

Matches are only held for 2 years most likely there were no games played from December 2022-April 2023 on that account other than these custom games.

**Comment by francois-blanchard** [comment]
Thanks for the answer @bangingheads 👍 
Out of curiosity, where did you find this information?

**Comment by bangingheads** [comment]
There was an announcement went it changed from 3 years to 2 years.

https://www.riotgames.com/en/DevRel/match-history-retention-Change
