### ISSUE TITLE
[Account]  404 Error For RSO client's secret key

### ISSUE THREAD

**Issue by keinpyisi** [RiotGames/developer-relations#1015]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)? 
Krul#Kein
Have you played any of Riot's games or did you just create an account for the Developer Portal?
I have played Valorant.

**Issue Description**  
A clear and concise description of what the issue is.
I wanted to make RSO client for my app. When I try to get the client secrets , It shows 404.
I have been waiting for months now..
Please help

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)
- [x] Waited for months

**Repro Steps**

1. Step 1  Login Into https://beta.developer.riotgames.com/ 

1. Step 2 Go to Manage Apps
1. Step 3 Select your Apps
1. Step 4 And 404 came out

**Issue Context**
Please add any additional context that is useful.

My account name is keinpyisi

My App ID is 705394

<img width="1246" alt="404" src="https://github.com/user-attachments/assets/0e468607-a71b-43bc-a797-9db95db37828">

**Comment by f3ar161** [comment]
@keinpyisi We are checking this issue. I'll let you know once I have an update related to this issue.

**Comment by keinpyisi** [comment]
@f3ar161 thanks. It would be better if you can make this urgent fix.

**Comment by f3ar161** [comment]
hi @keinpyisi your is now enabled and working, let me know if you need anything else.

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/e0fed5d5-116f-4a06-83f7-5724c9f8c7f9" />

**Comment by keinpyisi** [comment]
> hi @keinpyisi your is now enabled and working, let me know if you need anything else.
> 
> <img alt="image" width="1274" src="https://private-user-images.githubusercontent.com/14907413/395705123-e0fed5d5-116f-4a06-83f7-5724c9f8c7f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNDk4NzIsIm5iZiI6MTczNDE0OTU3MiwicGF0aCI6Ii8xNDkwNzQxMy8zOTU3MDUxMjMtZTBmZWQ1ZDUtMTE2Zi00YTA2LTgzZjctNTcyNGM5ZjhjN2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA0MTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNzg0ZDQwYWFlZmI1MmQ2ZTQxNDgyNmM1MjhhYTQ5NGQwMzBlYjQ4ODA3ZmI0ZmIyNjAzZDhhNTYwZmRkYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uh7cO97pkPcePPWdux2rTwopEzhz2Mc_1XGlKTUPRYg">
Thanks you so much. I have confrimed it.
