### ISSUE TITLE
[BUG] Account-V1 consistently returning 503s since 7:00AM UTC 29th November

### ISSUE THREAD

**Issue by JackWillz** [RiotGames/developer-relations#1016]
The Account-V1 APIs (all of them) are returning a 503 error in about 10-15% of calls. 

I have an app that makes around 10,000 calls an hour to the API and our logs are showing a 503 error in 10-15% of the calls. 

I have confirmed with other developers that they are seeing the same issue.

My logs show the issue starting around 7:00AM UTC on the 29th November. 

Urgent action required as causing considerable disruption to all apps that can no longer access basic user data.

**Comment by raimannma** [comment]
Same for me for last 2 days

**Comment by SPeriquetJS** [comment]
Same for me

**Comment by NathanMana** [comment]
Same for me, calls were working fine before.

**Comment by VeryLongNicknameSuchWow** [comment]
Same for me

**Comment by danblock97** [comment]
+1 - In turn its making my current flow return empty data resulting in half working components.

**Comment by geozukunft** [comment]
Hey @lucasMesquitaBorges any chance we could get this one escalated? 
api: account-v1
type: bug/outage
affects: every app that uses account-v1 aka everyone

**Comment by ArcaneIRE** [comment]
Same for me. Rate seems higher than 15% but I've a tiny sample size.

**Comment by aschenkuttel** [comment]
+1

**Comment by serkanbal** [comment]
+1

**Comment by f3ar161** [comment]
Thank you for reporting the 503 errors. We've deployed an update today to address the issue. Please let us know if you continue to experience any problems.

**Comment by raimannma** [comment]
![image](https://github.com/user-attachments/assets/f1e4c054-452c-4710-a33c-f74129699b0a)
Seems good :+1:
