### ISSUE TITLE
[Account] 404 Application Error

### ISSUE THREAD

**Issue by MitchellOliarny** [RiotGames/developer-relations#1019]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
-EsportsClubs#2945
Have you played any of Riot's games or did you just create an account for the Developer Portal?
-Just an account for the portal

**Issue Description**  
A clear and concise description of what the issue is.
When trying to access my RSO Client details I get a 404 screen. This app was a request made after being accepted.

**What I've Tried**
What steps have you tried to resolve the issue.
I have waited for about 2 months.
I have submitted a support ticket on Nov 9 with no response.
I have logged out and back in.
I have used a second device.
I have cleared my cookies.

**Repro Steps**

1. Log into https://beta.developer.riotgames.com/
2. Go to my apps
3. Click on my current app
4. Receive the 404 screen

**Issue Context**
Please add any additional context that is useful.

App ID: 687847

![image](https://github.com/user-attachments/assets/5ab26646-3b7b-4830-b29b-33cc443805ec)

**Comment by f3ar161** [comment]
Hi @MitchellOliarny your application is now enabled. Let me know if you need anything else

<img width="1180" alt="image" src="https://github.com/user-attachments/assets/4f208758-e6fd-4c0a-91f0-f41f2221231f" />

**Comment by MitchellOliarny** [comment]
Thank you!
