### ISSUE TITLE
MessageDto type is outdated in documentation

### ISSUE THREAD

**Issue by supergrecko** [RiotGames/developer-relations#102]
### Preconditions
* Access to the API and a way to request from the API

### Steps to reproduce

1. Request the current ShardData from the Status API

1. Realize the MessageDto has changed from the one documented on the API page

### Expected result
The MessageDto is supposed to match the one in the documentation

### Actual result
There have been some field changes. The `uploaded_at` field is gone and there's a new field named `heading`

**Comment by supergrecko** [comment]
Additional items missing:

ParticipantStatsDto is missing all the `statPerk0-3` titles.

**Comment by MingweiSamuel** [comment]
Seems both these issues still exist

**Comment by RiotTuxedo** [comment]
The documentation has been updated. Thanks for the report. Sorry about the delay on this.

**Comment by RiotTuxedo** [comment]
Duplicate of #79
