### ISSUE TITLE
What's the API for champion Info

### ISSUE THREAD

**Issue by ChenNightLi** [RiotGames/developer-relations#103]
What's the API for champion Info?
I can not find it in the website.

**Comment by supergrecko** [comment]
You can find the champion info here. https://ddragon.leagueoflegends.com/cdn/9.6.1/data/en_GB/championFull.json

Also, there's a community Discord at https://discord.gg/riotapi if you have other questions about the API which isn't necessarily a bug report or a feature request

**Comment by rokit** [comment]
I think a link to this data belongs in the game constants section of the api reference. I mean it's pretty fundamental. And also these:

- Item info
- Rune info
- Mastery info
- Icon info

I'd really appreciate not having to go through the trouble of asking someone on discord for what should be readily available information.

**Comment by supergrecko** [comment]
There's a hidden page, because it's quite outdated, but it has the info which covers that data.

https://developer.riotgames.com/static-data.html

**Comment by MaximeBernard** [comment]
Agree with @rokit 

This should be heavily documented in Game Constants and/or Getting Started. 

And if you want to save you the trouble, just add some route on the API simply fetching the JSON: simple and intuitive.

**Comment by stelar7** [comment]
With static-data added back to the devportal this can be closed @RiotTuxedo
