### ISSUE TITLE
The API Key does not work

### ISSUE THREAD

**Issue by ChenNightLi** [RiotGames/developer-relations#104]
I register a project and get an API KEY for that but that API KEY does not work..
How can I get an API Key that can work for a long time?

**Comment by supergrecko** [comment]
You don't actually get an API Key before your project has been approved. You can read more about this here: https://developer.riotgames.com/application-process.html

I think you might be confusing a project key with your development key because that's the only API key that expires after 24 hours.

**Comment by RiotTuxedo** [comment]
I'm assuming this issue is resolved, though I don't think this is the proper place for this kind of question. In the future, questions like this should be asked in [Discord](https://discord.gg/riotapi).
