### ISSUE TITLE
[Bug] Inconsistency between /league & /position endpoint

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#106]
Hey guys

I just noticed an issue with the /league/ API

For the summoner "AP Yorick Only" (NA), when I call the positions endpoint, I get that the summoner is Diamond 4, in league "f710cc90-2c06-11e9-9d14-c81f66cf2333".
![image](https://user-images.githubusercontent.com/14201457/55686495-445b1e00-5962-11e9-950b-7c5252439e1e.png)

When I call this league, it's in fact a Platinum league (it should be a diamond league)
![image](https://user-images.githubusercontent.com/14201457/55686492-3907f280-5962-11e9-8b8d-b7d91e779553.png)

So it seems there is an inconsistency between those two endpoints. 

Could you have a look ?

Thanks

**Comment by RiotTuxedo** [comment]
I've confirmed your report. Escalated to the Ranked Remastered team. I'll let you know when we get any updates.

**Comment by trebonius0** [comment]
Just a quick update: I've seen the issue in LAN as well

**Comment by RiotTuxedo** [comment]
@trebonius0 Looks like about 9k players in RU, LA1, and NA1 are affected by this. They're already aware of the issue and these players will get moved to an appropriate tier/division in the next couple days. Their true rank should be their individual rank.

**Comment by RiotTuxedo** [comment]
This issue should now be resolved.

**Comment by trebonius0** [comment]
Hello, while it seems to have been fixed for most players, it's still occuring for NA namori

The guy is Diamond 2 in soloqueue, his /positions call returns leagueId d33fbf20-4c6c-11e9-8ae9-c81f66cf135e which is Platinum

Thanks
