### ISSUE TITLE
DATA DRAGON versions.json returns Content-Type: binary/octet-stream

### ISSUE THREAD

**Issue by krisschlickum** [RiotGames/developer-relations#107]
Hi,
my application consumes the versions.json hosted by the data dragon. I received the newest version 9.7.1 on Saturday, 6. April 2019 11:51:48.730. However, today the api call for the versions.json failed because the versions.json is now transferred as Content-Type: binary/octet-stream. 
I am a bit suprised by this change and just wanted to know if the api/versions.json will stay as it is now?

**Comment by RiotTuxedo** [comment]
Looks like the Content-Type is `application/json` now, would you consider this issue resolved?
http://ddragon.leagueoflegends.com/api/versions.json

**Comment by Canisback** [comment]
I get  Content-Type: binary/octet-stream too even now.

**Comment by krisschlickum** [comment]
Hi,
when I klick the link, my browser is downloading the json file. When I check the response headers it is still transferred as Content-Type: binary/octet-stream.
![image](https://user-images.githubusercontent.com/9843628/55794419-789b1f80-5ac5-11e9-9f42-a564f1e031b6.png)

**Comment by MingweiSamuel** [comment]
I'm getting `Content-Type: application/json`

**Comment by krisschlickum** [comment]
@MingweiSamuel That is very strange, can you maybe post a screenshot like the above.

**Comment by WxWatch** [comment]
![image](https://user-images.githubusercontent.com/6795991/55823220-e136cc00-5ac6-11e9-8819-4a8ff2524bd4.png)

**Comment by Querijn** [comment]
Since we haven't come to this conclusion publicly yet: this is most likely NA vs EU. It used to work here in the EU though.

**Comment by molenzwiebel** [comment]
Just confirmed with @WxWatch on Discord that a `curl --head http://ddragon.leagueoflegends.com/api/versions.json` does indeed return a content type of `binary/octet-stream` (even in NA). Most likely the browser cached the response content type. I too consistently get an octet stream.

**Comment by RiotTuxedo** [comment]
Alright I'm looking into it.

**Comment by MingweiSamuel** [comment]
It seems that requesting the page compressed (which is what browsers do) gives the expected application/json
```
$ curl --head 'http://ddragon.leagueoflegends.com/api/versions.json' --compressed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Content-Type: application/json
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD
Access-Control-Max-Age: 3000
Last-Modified: Fri, 05 Apr 2019 20:58:18 GMT
x-amz-version-id: xhYFlr5Gz8ma_kybtC2qsvJMwr29TJfe
Server: AmazonS3
Content-Encoding: gzip
Date: Tue, 09 Apr 2019 16:35:40 GMT
X-Cache: Hit from cloudfront
Via: 1.1 ac2b2afd66b6aef623f9c570e5db36eb.cloudfront.net (CloudFront)
X-Amz-Cf-Id: Nmgvvx0IuYJerwW7sDR7RX4mLS4b0-1cJN5429cKKEtqHPEpeHhqGA==
```

**Comment by RiotTuxedo** [comment]
As an update, we believe this issue should be resolved some time this week when the engineer responsible for ddrag gets time to re-upload the content forcing the type to `application/json`.

**Comment by RiotTuxedo** [comment]
How's it looking friends?

**Comment by Querijn** [comment]
`Content-Type: application/json` on attempt one, browser.
Getting a cache from Cloudfront afterwards

**Comment by MingweiSamuel** [comment]
I'm getting `Content-Type: binary/octet-stream` on non-compressed requests and `Content-Type: application/json` on compressed requests now
https://hastebin.mingweisamuel.com/ufazapoxos.rb
(TBH I don't feel this is a major issue)

**Comment by krisschlickum** [comment]
Hi,
this issue seems to be solved.
thanks for the support.
@RiotTuxedo

**Comment by RiotTuxedo** [comment]
Good to know. Please open up another ticket and reference this issue if the problem returns.
