### ISSUE TITLE
How to get the secret key to develop

### ISSUE THREAD

**Issue by kjasd** [RiotGames/developer-relations#108]
Expired: Mon, Apr 8th, 2019 @ 8:19pm (PT) 
Your key has expired. You must regenerate your API key.

But,regenerate  dose take work

**Comment by RiotTuxedo** [comment]
@kjasd unfortunately this isn't the kind of issue we track in GitHub. Feel free to join our [Discord](https://discord.gg/riotapi) or direct message us on [Twitter](https://twitter.com/RiotGamesAPI).
