### ISSUE TITLE
Share your profile error 404

### ISSUE THREAD

**Issue by MrLeRandom** [RiotGames/developer-relations#109]
Clipboard => https://developer.riotgames.com/oauth2-callback/profile/337907 

![image](https://user-images.githubusercontent.com/24717139/56070157-a9f64280-5d86-11e9-9122-9e4558eb4090.png)

**Comment by supergrecko** [comment]
I think it's because you need to be logged into the dev portal to be able to view profiles, the problem is that this link doesn't work. You can use the link in your address bar to share though.

**Comment by tisbells** [comment]
Closing old issues. This is (as far as I'm aware) no longer a supported feature.
