### ISSUE TITLE
In timeline.Frames.ParticipantFrames key isn't equal to participantId

### ISSUE THREAD

**Issue by heerakli** [RiotGames/developer-relations#111]
For example in match NA 3023745286 I see that for every frame in timeline key in ParticipantFrames object is different from it's participantId
key: 10; participant_id: 8
key: 9;  participant_id: 7
key: 8;  participant_id: 10
key: 7;  participant_id: 9
key: 3;  participant_id: 5
key: 1;  participant_id: 3
key: 5;  participant_id: 1
key: 5;  participant_id: 1
key: 7;  participant_id: 9

Is it known change or a bug? Because key and participantId were the same before

**Comment by RiotTuxedo** [comment]
Took a quick look at this and escalated it to the match history team. At this time, I believe the `key` is the correct value, and the `participantId` is incorrect. Will provide updates as I get them.

**Comment by trebonius0** [comment]
I had an issue with that (I suddenly started to see a lot of Akali botlane Oo). I was taking the key into account (and i was ignoring the participantId)
So, the key is incorrect and the participantId is correct ;)

**Comment by RiotTuxedo** [comment]
@trebonius0 is correct, the participantId is the correct value and the key doesn't always reflect the participantId. From what I hear changes to this haven't been made in a while and scenarios where keys matched the participantId were coincidental or there was something else at play that made these ids align, but you shouldn't expect them to.
