### ISSUE TITLE
[Bug] Inconsistency between /league & /position endpoint (reopening)

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#113]
Creating a new issue since the previous one (https://github.com/RiotGames/developer-relations/issues/106) has been closed

Hello, while it seems to have been fixed for most players, the issue https://github.com/RiotGames/developer-relations/issues/106 still occuring for NA namori

The guy is Diamond 2 in soloqueue, his /positions call returns leagueId d33fbf20-4c6c-11e9-8ae9-c81f66cf135e which is Platinum

Thanks

**Comment by RiotTuxedo** [comment]
@trebonius0 thanks for the report. I'll look into it. I'd suggest assuming their individual rank is correct and they're in the wrong league.

**Comment by trebonius0** [comment]
Yes, the player told me that indeed the positions is correct.

**Comment by RiotTuxedo** [comment]
In the future, let's reopen the original issue instead of creating a new one.

**Comment by RiotTuxedo** [comment]
Alright, now this should be resolved. Thanks for re-reporting.
