### ISSUE TITLE
Issue with Lobby Events 

### ISSUE THREAD

**Issue by regiszanandrea** [RiotGames/developer-relations#114]
Hi,

I think there is an issue with Lobby events, this is the case:

When a player get out of Lobby on Champ Select Screen (Game crashed, Internet problems, and others), there is no event generated for that. Then, we can't say who isn't in the lobby and we can't define a WO.

We only can identify that was a problem with Champ Select Screen because it's generate a GameDissolvedEvent. So, I think PlayerQuitGameEvent should be generated in this case to identify the user that got out of lobby.

Regards.

**Comment by SaSiNO97** [comment]
I have this issue. Can we know when will it be fixed?

**Comment by iDanielWongi** [comment]
Please fix.

**Comment by tisbells** [comment]
Closing out, as this is the same as https://github.com/RiotGames/developer-relations/issues/204. Keeping the newer one because it has more info
