### ISSUE TITLE
/lol/match/v4/matches/{matchId} gameCreation timestamp inaccuracy

### ISSUE THREAD

**Issue by parismav87** [RiotGames/developer-relations#115]
I have noticed that all games I have retrieved from the API that were played in 2019, have inaccurate gameCreation timestamps. 
I have been tracking keyboard and mouse activity for a semi-professional team, and the APM data seems to be aligned with the start & end of the game, if the game is played in 2018. 
For 2019 games, there is an inconsistent 'shift' of approx. 20 minutes. 
Example: https://imgur.com/a/rwP3xa6
I've drawn vertical lines for gameCreation & gameCreation+duration (dashed line).
Regards,
Paris

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported. Feel free to reopen/comment if you feel this is in error.
