### ISSUE TITLE
LCU API swagger docs broken with the new patcher

### ISSUE THREAD

**Issue by Pupix** [RiotGames/developer-relations#117]
This is more of a formality to be able to keep track of the issue. I already informed Tuxedo about this.

----

**The problem**
Since there's not an *official* documentation page for LCU API, many developers, myself included, have been using the swagger docs that come with the client. To enable said docs you could just set the flag `enable_swagger: true` inside the `system.yaml` file, previously located at `C:\Riot Games\League of Legends\RADS\projects\league_client\releases\x.x.x.xxx\deploy`. This worked great with the old patcher because it didn't identify `system.yaml` as *corrupted* when the client started.

With the new patcher this file got moved to `C:\Riot Games\League of Legends` and gets's checked for *corruption* every time the client starts. As soon as you set the flag to enable the documentation the client patches it out.

**Possible solution**
The swagger docs flag should be moved inside the Config directory (which is exempt from the corruption check) somewhere just like the ReplayAPI flag is.

**Temporary workaround**
Reverting back to the old patcher fixes the issue for the time being
https://github.com/Pupix/rift-explorer/issues/34#issuecomment-485089457

**Comment by RiotTuxedo** [comment]
Thanks for the feedback, however this is an unsupported resource. Unsupported resources may be modified or removed without notice. At this time we can't commit any resources to tracking and resolving the issue, however reporting issues with unsupported resources does help raise visibility. We're always interested in hearing about how this issue may affect developers in different ways. Comments and updates help provide context if an opportunity arises to easily address this issue we'll do our best to resolve it but we can't make any guarantees. As such, I'm closing this issue as **unsupported**, but feel free to continue to add context.

**Comment by specuuu** [comment]
hey, nothing helps. enable_swagger: true always makes my client repair even though i change toggles to another date or number instead of 0. Nothing helps.
