### ISSUE TITLE
Tournament endpoint error message

### ISSUE THREAD

**Issue by Canisback** [RiotGames/developer-relations#119]
Small QoL improvement to do there, I was playing around tournament stub code generating endpoint.
When inputed this : 
```
{
  "mapType": "SUMMONER_RIFT",
  "metadata": "",
  "pickType": "BLIND_PICK",
  "spectatorType": "LOBBYONLY",
  "teamSize": 5
}
```
it gives back this : 
```
        "message": "Bad request - The request entity had the following errors:[teamSize must be greater than or equal to 1 (was 0), spectatorType may not be null (was null), mapType may not be null (was null), pickType may not be null (was null)]"
```

Which is quite misleading on the actual error of missing a "S" in "SUMMONERS_RIFT". The problem also happens when you copy paste from the endpoint doc, adding a space before.

tl:dr It would be nice the error response was actually related to the error.

**Comment by RiotTuxedo** [comment]
It's unclear what you mean by `the actual error of missing a "S" in "SUMMONERS_RIFT"`. That looks like  a valid mapType to me.

Can you provide a link to the endpoint doc you're referring to? Are you talking about the reference page with the sample post body?

We can resolve issues to the stub returning faulty information in its error responses.

**Comment by Canisback** [comment]
I screwed, I meant "SUMMONER_RIFT".

I tried for this endpoint : 
https://developer.riotgames.com/api-methods/#tournament-stub-v4/POST_createTournamentCode

**Comment by tisbells** [comment]
Closing out old issues. Feel free to reopen or comment if you are still experiencing this with https://developer.riotgames.com/apis#tournament-stub-v5
