### ISSUE TITLE
Match documentation is missing statPerk fields

### ISSUE THREAD

**Issue by JanOuborny** [RiotGames/developer-relations#128]
The following fields are missing from the documentation of the `/lol/match/v4/matches/{matchId}` endpoint:

- `statPerk0`
- `statPerk1`
- `statPerk2`

**Comment by raitono** [comment]
Duplicate of #98

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported. Feel free to reopen/comment if you feel this is in error.
