### ISSUE TITLE
[Bug] Inconsistency between /league & /position endpoint (rereopening)

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#129]
Hey guys

It seems that some accounts are still affected by the bug I reported as #106 and #113 

The user Poı (NA) is in league 7c286a20-55d1-11e9-bfa1-c81f66dbb56c which is platinum whereas the entries endpoint says he is diamond (and the user told me he is in diamond)
Can you have a look please ?

Thanks

**Comment by RiotTuxedo** [comment]
I've received word these summoners are now correctly seeded.
