### ISSUE TITLE
Feature Request: add gameMode filter to /lol/match/v4/matchlists/by-account/ 

### ISSUE THREAD

**Issue by rokit** [RiotGames/developer-relations#133]
Please allow filtering matchlists on the gameMode. I currently only care about the ARAM gameMode, but after I get the match list, I have to make a call to `/lol/match/v4/matches/{matchId}` just to see what the gameMode is. If a player has 2,000 games and only 200 are ARAM games, then that is 1,800 unneeded api calls.

Considering I'm being rate limited at 100 requests every 2 minutes, 1,500 games would take ~30 minutes just to find the matches I care about.

**Comment by supergrecko** [comment]
You can filter by game queue. The queues can be found at https://developer.riotgames.com/game-constants.html ( scroll down to "Matchmaking Queues" )

https://developer.riotgames.com/api-methods/#match-v4/GET_getMatchlist
