### ISSUE TITLE
Spectator endpoint not returning active game for a player

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#134]
Hey guys

For this player: `"hi im Shuffle" (BR)` , the spectator/v4/active-games endpoint always return a 404, even if the player is in game. 
Can you have a look please ?

Thanks

**Comment by plachenko** [comment]
Works for me. You have to get the encrypted ID with the summoner API first:
https://developer.riotgames.com/api-methods/#summoner-v4/GET_getBySummonerName

then use the ID in /active-games/by-summoner/{encrypted ID} endpoint. 

make sure you're selecting the right regions.
