### ISSUE TITLE
[Bug] Spectator/active-game endpoint returning 404 whereas the player is ingame

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#136]
Hey guys

During the past few days, I've got multiple reports of spectator endpoint in EUNE returning http404 whereas the player was ingame. 

For instance, the player "Valco3" (EUNE) started a game (matchId: 2217846133) on July 5th, 8:28:17AM GMT
On July 5th, 8:29:26 AM GMT I called  https://eun1.api.riotgames.com/lol/spectator/v4/active-games/by-summoner/theEncryptedSummonerId and got a http 404

Impact: the players see them as offline on porofessor.gg and cannot see the data for their match. So porofessor is basically useless in that case

Likelihood. Around 15% of players in the related regions (about 6k unique users affected per day). I got a few dozens of reports, probably the highest number of reports on an individual issue

Could you have a look please ?

Thanks :)

**Comment by trebonius0** [comment]
Same thing happens with "READY TO REAP" (BR)
So it's not limited to EUNE

**Comment by cohenu** [comment]
I also noticed this issue.
user enters to a match - the spectator api returns 404, next game everything is fine (in the same region, queue and summoner) it's very random. variety of queues and regions.
I cannot find any data related between the matches.

In the beginning I thought it's maybe related to a missing player (option to rematch) but I'm not sure anymore

**Comment by trebonius0** [comment]
@RiotTuxedo I've PMed you on Twitter a special URL on porofessor where you can see those "offline detection" in real time. 
This will help you debug it and estimate the amount of issues

**Comment by RiotTuxedo** [comment]
@trebonius0 yea I got it. super useful thanks for this. I should be able to escalate the issue next week with the info you've provided and the page you setup. I'll try and get an update for you all soon.

**Comment by Neamar** [comment]
Can confirm, I've been having the same issues. In my case, BR and LAN are the most impacted.

It seems that spectator works fine for a subset of players, but for some players it always return "404 not in game".

I can also confirm that this started on July 8th:

![image](https://user-images.githubusercontent.com/536844/61877073-8e0a4d00-aeee-11e9-8e1c-9a558f0c34e7.png)

If I break it down by region, LAN, BR and LAS are the most impacted, other regions seem fine (although I do not get a lot of traffic from them):

![image](https://user-images.githubusercontent.com/536844/61877198-cd389e00-aeee-11e9-8fc5-c26f89fe9d06.png)

**Comment by RiotTuxedo** [comment]
@Neamar it's a little unclear what the graph that shows a change on July 8th is indicating. It looks like some number dropped on July 8th, but I'm not sure what that number represents. Is there anything beyond the drop that makes you think something happened on July 8th?

You mention that LAN, BR, and LAS are the most impacted regions, but it looks like the EUW and EUNE are the top regions. Can you clarify this?

**Comment by Neamar** [comment]
Sorry, I did not explain what the graphs were. They're number of people detected in game by the app per region.

The important thing to notice is the drop for LAN, LAS and BR on July 8-9. EUW and EUNE have more players in game in general, but the metric isn't impacted on July and stays relatively constant.

**Comment by Neamar** [comment]
Hello! I'm still getting 4 or 5 emails a day from players in LAS or LAN complaining about the issue.

Do you need more data?
Please let us know if we can help!

**Comment by Querijn** [comment]
They're currently potentially investigating this: https://twitter.com/RiotGamesAPI/status/1157053124441325568?s=19

**Comment by Neamar** [comment]
Nice! Thank you

**Comment by RiotTuxedo** [comment]
LATAM regions had unranked games disabled through spectator-v4 since July 10th as @Neamar reported. Today we've been testing a change to spectator and have enabled spectating for all queues again. Will provide updates on how the testing goes likely at the end of next week.

**Comment by trebonius0** [comment]
Things now seem ok in LATAM

But the error rate increased a lot in the past 24h in *OCE*
Did anything change ?

**Comment by trebonius0** [comment]
Error rate is currently rising in LATAM

**Comment by RiotTuxedo** [comment]
I sent you a message related to your "offline detection" page.

**Comment by trebonius0** [comment]
OCE currently back to normal, but KR is having high error rates (20% during past 3h)

**Comment by RiotTuxedo** [comment]
We've gone through and deployed some changes to spectator in every region. While doing that we came across a miss-configuration that was resolved in the LATAM and OCE regions. All these have been solved. At this time, we believe most of the games where players aren't able to be spectated are because they're in games that aren't spectate-able (practice or custom games). If you find matches that you believe should be spectate-able please record the following information:

* region
* queue
* summoner

**Comment by trebonius0** [comment]
I confirm that it seems to be fixed in LATAM and OCE. I'm still seeing issues with normal and ranked games in EUNE

**Comment by RiotTuxedo** [comment]
We're chasing down another lead, will report back when we expect these issues to be resolved.

**Comment by trebonius0** [comment]
EUNE error rate seems to be back to normal :)

**Comment by RiotTuxedo** [comment]
We did it! Any concerns with closing out this issue?

**Comment by trebonius0** [comment]
Is it ok if we wait a few additional days, just in case erro rrate goes up again ?

**Comment by RiotTuxedo** [comment]
Yep, the engineer on the team is going to see if he can still make a couple small optimizations to hopefully improve how these endpoints work. We'll see if they can find the time to make those adjustments, but he's also asked to keep the issue open while he looks into those.

**Comment by trebonius0** [comment]
OCE rate going back up

**Comment by RiotTuxedo** [comment]
Circling back on this issue. Error rates are all low across every region. Haven't got any additional reports of issues here, so I'm going to go ahead and close this issue out. If the issue does still exist today, go ahead and comment on this thread and we can re-open it. If an issue arises tomorrow, feel free to open a new issue.

**Comment by trebonius0** [comment]
Reopening (https://github.com/RiotGames/developer-relations/issues/165)

**Comment by hyepod** [comment]
Hello guys,

This seems to happen again for the EUW server. all spectator-v4 requests return a 404

Where can we get more information about this?

**Comment by cohenu** [comment]
all spectator-v4 requests return a 404
any update?

**Comment by cohenu** [comment]
@abcdvd I think this issue exists is in all regions

**Comment by MingweiSamuel** [comment]
Current issue is #602, please keep all current discussion there
