### ISSUE TITLE
Sometimes the game is not shown on op.gg or lol.skill, maybe it's not even spectatable.

### ISSUE THREAD

**Issue by notruto1** [RiotGames/developer-relations#137]
Hello! There is a bug or problem that affects sites like lol.skill and op.gg. There is a random chance ( I guess ) that the match won't be detected by these websites. But I'm pretty sure it's not their faults beacause when 1 of them doesen't work, all of them doesen't show that specific game. This issue is happening on EUNE I guess beacause that's my region. 
![image](https://user-images.githubusercontent.com/52568835/60719519-a3640b00-9f30-11e9-85ed-db6fb1011d91.png)
This are 2 games that were not  detected by op.gg :
![image](https://user-images.githubusercontent.com/52568835/60719591-d5756d00-9f30-11e9-9cd7-fa7556684a9c.png)
![image](https://user-images.githubusercontent.com/52568835/60719599-dd351180-9f30-11e9-8a08-32da67612b45.png)

**Comment by supergrecko** [comment]
Possibly related to #136 

Both issues mention EUNE only

**Comment by RiotTuxedo** [comment]
Do these games show up in the game client match history? Is there any thing that's different about these matches than the rest?

**Comment by trebonius0** [comment]
@RiotTuxedo I don't know if they appear in the game client but they do appear in the matchlist endpoint. Nothing different than the rest (this seems to be the same issue as #136)

**Comment by RiotTuxedo** [comment]
Going to close this issue as a duplicate. Please continue the discussion in #136.
