### ISSUE TITLE
Development API Key rate limit grammar error on dashboard

### ISSUE THREAD

**Issue by bommerhondjes14** [RiotGames/developer-relations#14]
"For example, with the above rate limit, you could make 20 requests **every 1 seconds** to both NA and EUW endpoints simultaneously."

On the api request page

**Comment by jjmaldonis** [comment]
What's the mistake here?

Here is the page in question for anyone reading this: https://developer.riotgames.com/api-keys.html

**Comment by bommerhondjes14** [comment]
That is not the page I am referring to, I meant the dashboard. 
The page where you generate a development api key.

**Comment by jjmaldonis** [comment]
Ahh, so this page: https://developer.riotgames.com/

Riot must fill in those values automatically based on the API key limits. That's a pretty minor error and I think it's clear what they mean. I think a #wontfix label is justified here.

**Comment by stelar7** [comment]
changing `seconds `to `second(s)` is the better option imo 
(assuming they dont go for dynamic text change)

**Comment by RiotTuxedo** [comment]
This issue has been resolved and should be in the next release of the developer portal.
