### ISSUE TITLE
TFT ranked league is returned under the LOL endpoints

### ISSUE THREAD

**Issue by Querijn** [RiotGames/developer-relations#140]
TFT ranked data is returned by `/lol/league/v4/`, while you expect to see it under a new game `/tft/league/v4/`, assuming it's considered as a new game.

**Comment by torlenor** [comment]
This is as it should be appearently, see https://www.riotgames.com/en/DevRel/teamfight-tactics-ranked-data

**Comment by RiotTuxedo** [comment]
Yea we're still treating this as a mode within League. If the day comes where we decide to make it it's own game we'll change the prefix in the API.
