### ISSUE TITLE
Patch 9.14: Missing Passives Descriptions Across Multiple Data Dragon Files

### ISSUE THREAD

**Issue by stevezease** [RiotGames/developer-relations#142]
Multiple champions are missing their passive info on the data dragon file for patch 9.14:
ie:
[http://ddragon.leagueoflegends.com/cdn/9.14.1/data/en_US/champion/Caitlyn.json](http://ddragon.leagueoflegends.com/cdn/9.14.1/data/en_US/champion/Caitlyn.json)
[http://ddragon.leagueoflegends.com/cdn/9.14.1/data/en_US/champion/Shaco.json](http://ddragon.leagueoflegends.com/cdn/9.14.1/data/en_US/champion/Shaco.json)

Whereas the 9.13.1 does contain the info.

**Comment by stevezease** [comment]
Wrote a small script to generate all the missing data: 

Here are the champions and the corresponding missing data: 
Amumu is missing both passive name and description
AurelionSol is missing both passive name and description
Azir is missing both passive name and description
Blitzcrank is missing passive name
Caitlyn is missing both passive name and description
Draven is missing both passive name and description
Lux is missing passive name
MasterYi is missing passive name
Mordekaiser is missing passive description
Shaco is missing both passive name and description

Script: 
`async function generateMissingPassives() {
    const ver = '9.14.1';
    const championDataResponse = await fetch(
        `https://ddragon.leagueoflegends.com/cdn/${ver}/data/en_US/champion.json`
    );
    const championDataJSON = await championDataResponse.json();
    const championIDs = Object.keys(championDataJSON.data);
    championIDs.filter(id => {
        const individualChampionDataResponse = await fetch(`http://ddragon.leagueoflegends.com/cdn/${ver}/data/en_US/champion/${id}.json`);
        console.log(individualChampionDataResponse);
        const individualChampionDataResponseJSON = await individualChampionDataResponse.json();
        return individualChampionDataResponseJSON

    });
    console.log(JSON.stringify(championIDs));
    return championIDs;
}`

**Comment by stelar7** [comment]
I made a script for this back in 7.11.

Im guessing most of these issues are still there
https://gist.github.com/stelar7/1b98c86328256ba9f33ec2fde5458bc2

**Comment by Querijn** [comment]
DDragon isn't worked on that much; I wouldn't rely on it too heavily.

**Comment by stevezease** [comment]
I've been leveraging off of Data Dragon  since the deprecation of the static endpoint but haven't really had missing data problems up until now. Not too sure of any reliable alternatives.  I thought this was worth bringing up because the previous patch had the data whereas the current one does not, so I didn't realize this was a recurring issue.

**Comment by Querijn** [comment]
I understand your problem and I share your sentiment. But Ddragon isn't a high priority for Riot right now.

You could take a look at CDragon, a community alternative, but it has different forms of json. They automatically generate this data from the game files.

**Comment by Eghizio** [comment]
It is still missing the Blitzcrank's passive name.
Property name of passive is "".

Partial* data  from:
[http://ddragon.leagueoflegends.com/cdn/10.8.1/data/en_US/champion/Blitzcrank.json](http://ddragon.leagueoflegends.com/cdn/10.8.1/data/en_US/champion/Blitzcrank.json)
*(properties: id, key, name, passive of json.data.Blitzcrank where json is returned object)

`
{
"id": "Blitzcrank",
"key": "53",
"name": "Blitzcrank",
"passive": {
    "name": "",
    "description": "When Blitzcrank's life is brought below 20% health, he activates Mana Barrier. This creates a mana shield equal to 30% of his mana for 10 seconds. Mana Barrier can only occur once every 90 seconds.",
    "image": {
      "full": "Blitzcrank_ManaBarrier.png",
      "sprite": "passive0.png",
      "group": "passive",
      "x": 96,
      "y": 48,
      "w": 48,
      "h": 48
    }
  }
}
`

**Comment by tisbells** [comment]
Closing out old issues - There have been no recent reports on this.
