### ISSUE TITLE
Error 403 in all requests

### ISSUE THREAD

**Issue by GabrielFresatto** [RiotGames/developer-relations#144]

**Comment by Token07** [comment]
Hello there @GabrielFresatto!

A 403 on all requests is probably an invalid API key. Development API keys expire every 24 hours and will create a new key when it's renewed. If it's a production/personal API key it may have been temporarily blacklisted for exceeding ratelimits or possibly a different reason. You should be able to see your API key status in the developer portal.

You can ask other developers for help using  the API on the API community discord. https://discord.gg/riotapi
