### ISSUE TITLE
Ranked lobby ban order

### ISSUE THREAD

**Issue by samhine** [RiotGames/developer-relations#146]
I'd like to be able to see the ban order within a lobby for ranked solo games (perhaps best represented by an ordered list of `participantId`s), mainly to analyse a summoners ban tendencies. 

I believe lobby order used to be donated by participantId (detailed here: https://riotapi.dev/en/latest/specifics.html), but from basic testing this seems to be deprecated.

**Comment by supergrecko** [comment]
You are able to view this data via the League Client APIs for an active champion select.

**Comment by u1615413** [comment]
Perhaps, but I don't have access to client data for the summoners of interest.

**Comment by stelar7** [comment]
This should be avaliable in the API, under the match endpoints...?

**Comment by u1615413** [comment]
The champion IDs banned are available, and the order of these bans (I assume), but the associated participant who selected that ban is not.

**Comment by joshuaolufs** [comment]
I feel like the issue title is not accurate to what you want which seems to be a definitive mapping between players and bans. I would also like this.

Perhaps instead, or in addition to, including the ban info in the TeamStatsDto it could be included in the ParticipantDto as 'championBannedId'.

**Comment by u1615413** [comment]
Any implementation which makes this information retrievable would be fine - defining lobby order is the easiest way I see this happening.
