### ISSUE TITLE
Incorrect timestamps for lastPlayTime field in the champion mastery API

### ISSUE THREAD

**Issue by supergrecko** [RiotGames/developer-relations#15]
### Preconditions

Upon making a request to any of the `champion-mastery/v*/champion-masteries/by-summoner/` the `lastPlayTime` property shows incorrect dates,

### Steps to reproduce

1. Make request to `/lol/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}` or `/lol/champion-mastery/v3/champion-masteries/by-summoner/{summonerId}`

1. Turn the epoch timestamp in the `lastPlayTime` property to a date

### Expected result

The property is supposed to return the epoch date of last time the player played that champion.

### Actual result

The property gives you a completely different date.

The response from the API call (v3)
![image](https://user-images.githubusercontent.com/42585241/49342222-f606dd00-f658-11e8-8873-a5d821e49006.png)

The response from the API call (v4)
![image](https://user-images.githubusercontent.com/42585241/49342264-c1475580-f659-11e8-93bf-e80f92688de7.png)

The timestamp converted into a date timestamp
![image](https://user-images.githubusercontent.com/42585241/49342227-07e88000-f659-11e8-95f3-826361671f8e.png)

Last time I picked Lee (yesterday)
![image](https://user-images.githubusercontent.com/42585241/49342270-dcb26080-f659-11e8-963d-1cd1fdb9466f.png)

**Comment by riottuxedo** [comment]
The issue has been escalated to the team that owns this product. Will update this issue when we receive additional info.

**Comment by Crecket** [comment]
Any update on this? I still notice this behavior both on the V3 and V4 APIs

**Comment by Zlkva** [comment]
I'm using V4 and am getting the same result as OP.

**Comment by Phyxsius21** [comment]
Any update on this one?

**Comment by hxdegawa** [comment]
Encountered the same problem here.

**Comment by inyawfaze** [comment]
Same problem for me, too.

Tried to look up if there was any connection between the lastPlayTime and other games that were played for that champion. There does seem to be some sort of connection to another game.

Please excuse the horrible formatting.

![timedifferencefindings](https://user-images.githubusercontent.com/46511399/57228531-47eecd00-7014-11e9-8194-79d7a36a9917.png)

Would love to see the problem resolved.

**Comment by RiotTuxedo** [comment]
@Crecket @Phyxsius21 It looks like we have a fix for the issue and I'm being told that they'll try to find time to deploy that fix in the coming week. Can't guarantee anything though, the priority on confirming the fix and deploying it could change.

**Comment by RiotTuxedo** [comment]
I believe at this time this issue has been resolved, the summoner that had been previously reported to me now appears to have their champion mastery being updated as expected. If you have additional summoners that are experiencing this issue please submit the following information:

region
summoner name
champion id with invalid timestamp
