### ISSUE TITLE
[BUG]Cannot generate providerId, tournamentId, or t-codes via Dev Portal

### ISSUE THREAD

**Issue by slgbrandonwilliams** [RiotGames/developer-relations#151]
**Describe the bug**  
When submitting valid JSON w/ valid params, currently the developer portal is throwing a 500 error when attempting to generate a valid providerId, tournamentId, or t-code

**Issue Description**  
500 error in response body when attempting to use Dev Portal to generate providerId, tournamentId (w/ valid providerid generated previously), or t-code (using valid tournamentId generated previously)

Edit: This does **not** occur outside of dev portal - seems to be working fine hitting the API directly. 

**Expected Result**  
200 :) 

**Actual Result**  
`{
    "status": {
        "status_code": 500,
        "message": "Internal server error"
    }
}`

**Developer Impact**

* Frequency: Every API call. 
* Severity: Mild annoyance

1. Step 1 - Navigate to dev portal Tournament-V4 or Tournament-Stub-V4 API page : https://developer.riotgames.com/apis#tournament-v4. 
2. Step 2 - Attempt to create a providerId via the dev portal w/ valid json, eg: 
`{
  "region": "NA",
  "url": "https://google.com"
}`
3. Notice error: 
`{
    "status": {
        "status_code": 500,
        "message": "Internal server error"
    }
}`

**Issue Comments**
Possibly related to : 
https://twitter.com/RiotTuxedo/status/1162123064626122752

**Comment by stelar7** [comment]
can confirm this issue only exists on the dev portal. 
calling the same url with same data works fine outside it.

**Comment by thomasmarton** [comment]
This issue seems to happen with the stub endpoints as well

**Comment by RiotTuxedo** [comment]
This issue should now be resolved. Removing tournament tag because it turned out to be unrelated to the tournament API.
