### ISSUE TITLE
my project Status is Pending.what should I do ?

### ISSUE THREAD

**Issue by W2B1** [RiotGames/developer-relations#153]
I applied for a PERSONAL APPLICATION.

but  status is Pending.

How long does the review take?

thank you for your help.

**Comment by W2B1** [comment]
@RiotTuxedo

**Comment by RiotTuxedo** [comment]
This is not the place for questions related to the application process. In the [Discord](https://discord.gg/riotapi), you can ask others or wait until office hours tomorrow.

**Comment by W2B1** [comment]
ok.. ok.. thanks you!
