### ISSUE TITLE
SummonerID - THIRD-PARTY-CODE-V4

### ISSUE THREAD

**Issue by jdgabriel** [RiotGames/developer-relations#154]
What I need to put in order to generate a third party validation code in "THIRD-PARTY-CODE-V4".
I tried to put all available ids for not generating, I am having answer of 400 - Bad request or 404 - Data not found.

How do I generate a code for the user to validate their account on my app? Ty

**Comment by Token07** [comment]
You generate the code yourself using the guidelines on the third-party-code-v4 documentation page:

"Valid codes must be no longer than 256 characters and only use valid characters: 0-9, a-z, A-Z, and -"

The summoner inputs the code you generated for them in their client, and then using third-party-code-v4, you check if the code the summoner has set matches the code you generated.


GitHub issues isn't meant for support. You can join us on discord at https://discord.gg/riotapi for further assistance with the API.
