### ISSUE TITLE
[BUG] Incorrect champion (id) returned from matchlists endpoint

### ISSUE THREAD

**Issue by thisKeeWord** [RiotGames/developer-relations#155]
I'm seeing inconsistent champion id's between /api.riotgames.com/lol/match/v4/matchlists/by-account/ and http://ddragon.leagueoflegends.com/cdn/9.17.1/data/en_US/champion.json. 

**Actual Result**  
<img width="297" alt="Screen Shot 2019-09-03 at 12 03 22 AM" src="https://user-images.githubusercontent.com/13548758/64151539-7c667000-cddf-11e9-95bf-cd546a4a479f.png">
<img width="332" alt="Screen Shot 2019-09-03 at 12 02 52 AM" src="https://user-images.githubusercontent.com/13548758/64151541-7c667000-cddf-11e9-9d34-9f525c5d2746.png">

In the above screenshots, I'm expecting to get back Zed using the champion property returned since that was the champion played during that game. Also to note, Malzahar was not present in that game.

The screenshots below might give better insight regarding the possible bug for champion ids.

<img width="460" alt="Screen Shot 2019-09-03 at 12 17 40 AM" src="https://user-images.githubusercontent.com/13548758/64151981-74f39680-cde0-11e9-95a4-663f2b50ecf9.png">
<img width="941" alt="Screen Shot 2019-09-03 at 12 16 44 AM" src="https://user-images.githubusercontent.com/13548758/64151983-74f39680-cde0-11e9-8758-0fd4fde3ae24.png">
<img width="807" alt="Screen Shot 2019-09-03 at 12 15 36 AM" src="https://user-images.githubusercontent.com/13548758/64151985-74f39680-cde0-11e9-981d-dfb7f01605bd.png">

As this is my first bug report, please let me know if additional information is needed. Thank you!

**Comment by stelar7** [comment]
Can you confirm your summoner name?
From looking at the api, it seems to be `Null`

**Comment by thisKeeWord** [comment]
@stelar7 my summoner name is teehee92

You're right. It seems that I'm getting the match history for the summoner name `Null`. However, when I log the games itself, I'm getting the data for teehee92. It's really odd, but at least I know now that the champion id's aren't the issue. 

I'll dig deeper and will submit a bug report if I find a bug. Thank you!

**Comment by stelar7** [comment]
I just searched up your match history, and it seems to match what you posted in the image.
https://i.imgur.com/r1P00es.png

I'm guessing you mixed the ids, and got a lucky match. 
the field named `accountId` is what you need to use for the match history endpoint

**Comment by Querijn** [comment]
Can we talk about the fact that he looked up Null for the matches?

Honestly, it seems to me that somewhere in the code, there's null passed as an argument

**Comment by thisKeeWord** [comment]
I have a hunch where it may have gone wrong.
