### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CiPrRiAN** [RiotGames/developer-relations#156]
**Describe the bug**  

**Issue Description**  

Please i waintig so much for ARURF !  Implement more fast guys

**Expected Result**  
What were you expecting to happen after you performed the above steps? Include screenshots, logs, or a description.

**Actual Result**  
What actually happened after you performed the above steps? Include screenshots, logs, or a description.

**Developer Impact**

* Frequency: Every API call. Once every ~100 API calls.
* Severity: When it happens, my whole website crashes.
* Cost: Requires me to run X more servers to compensate for the issue costing me on average $200 of additional spend a month.
* Efficiency: Requires me to make 10x more API calls than necessary to compensate for the issue.
* User emails: I get frequent emails from users asking me about this issue.
* Etc

**Player Impact**

* Frequency: Every time the user visits the site, they experiennce this issue. Once every ~100 visits this issue occurs.
* Severity: When this bug happens, a user is unable to use my site. I have 200 visits to my site each day, so it affects 50% of site visits.
* Quantity: There are ~1k players that experience this issue.
* Region: This affects players in NA and EUW.
* Etc

**Preconditions**

* First condition
* Second condition

**Steps to reproduce**

1. Step 1
1. Step 2

**Issue Comments**

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by CiPrRiAN** [comment]
Pleasw , i waiting so much for arurf ! Implement more fast guys

**Comment by Querijn** [comment]
This isn't a place where you can discuss the game. This is for websites like OP.GG to ask questions on how to get League of Legends data.

**Comment by stelar7** [comment]
@RiotTuxedo close please
