### ISSUE TITLE
[BUG] Matchlist season filter does not work

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#157]
**Describe the bug**  
Doing a query for a season older than the current one, returns no data.

**Developer Impact**
Method filters are presented as a reliable source of filtering the data, but when used they dont return any info

**Steps to reproduce**
1. lookup user `fastboyz` on NA
1. See in the full list that there are matches with season 13, 12, 11
1. Add filter season = 11 to the request
1. get back an empty list

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported
