### ISSUE TITLE
[BUG] API Keys showing for Unverified & Pending Apps

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#158]
**Describe the bug**  
API Keys in the dev portal are being shown on the My Groups page (https://developer.riotgames.com/groups/) for unverified/pending apps.

**Expected Result**  
No API key

**Actual Result**  
API Key exposed that isn't activated

**Developer Impact**
Causing confusion for new applications on whether they should continue using development API key or use the inactive key given on this page.

**Player Impact**
None

**Steps to reproduce**
Create new application in unverified or pending state
Look in My Groups Page

**Comment by RiotTuxedo** [comment]
Thanks for this feedback, I've modified the behavior of this page to return the status of your application if it's not approved (doesn't have a valid API key).
