### ISSUE TITLE
[BUG] API getMatch: playerScore3 has a value in an ARAM game

### ISSUE THREAD

**Issue by RobVanDerHeijden** [RiotGames/developer-relations#159]
**Describe the bug**  
Was figuring out the API, saw playerScore0 ->9 in  MATCH-V4 -> /lol/match/v4/matches/{matchId} , and was wondering what it was for.
Asked on the Riot Games API Dev discord, they told me it was used for dominion.
But I saw that playerScore3 has a value in an ARAM game

**Expected Result**  
playerScore0 -> 9 to have the value 0 in ARAM games

**Actual Result**  
matchId: 4178584568 is an ARAM game, yet participants (3,4,5,6,7,8,10) have a value for playerScore3

**Developer Impact**
* Frequency: Every API call.
* Severity: not at all

**Issue Comments**

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported. Feel free to reopen/comment if you feel this is in error.
