### ISSUE TITLE
Match v4 returns a 500 errror on Tournament Code generated matches

### ISSUE THREAD

**Issue by Protroid** [RiotGames/developer-relations#16]
Entering a Match ID that was generated from a tournament code to v4 of the Riot Match API yields a 500 error. In V3, this returned a 200 OK with no issues.

The match I had been testing with was Riot Match 2919559060 on NA1, which had the tournament code of NA045c7-99f695c9-9698-4026-a3a9-591d4315bb0a

This behavior can be replicated on the Riot Dev Portal, as entering this code on both V3 and V4's getMatch call yields the expected results described above.

**Comment by stelar7** [comment]
Can confirm this is an issue.
Alternate datapoint; 3846543054 on EUW

**Comment by Gchorba** [comment]
This issue has been resolved by the Riot API team

**Comment by Protroid** [comment]
Confirming fixed. Thanks!
