### ISSUE TITLE
riotgames api[BUG]

### ISSUE THREAD

**Issue by claudia007fr** [RiotGames/developer-relations#161]
**Describe the bug**  
i want to use riotgames api
**Issue Description**  
how can i post to riotgames to get the api key

**Comment by stelar7** [comment]
Sorry, the riot games api is closed for business at this time. Please contact your local councilman, or similar. /s

Check out https://developer.riotgames.com

**Comment by claudia007fr** [comment]
you sure, it s closed? i cant get the api? :(

**Comment by RayZz-** [comment]
https://developer.riotgames.com/getting-started.html

**Comment by Draycia** [comment]
For future reference, "/s" at the end of a sentence or message denotes sarcasm.

**Comment by claudia007fr** [comment]
> https://developer.riotgames.com/getting-started.html

yes i know this link 
but i cant find how can i get the api

**Comment by Draycia** [comment]
I'd suggest you join the discord for further help.
It'll make it easier for all of us.
https://discord.gg/riotapi

**Comment by claudia007fr** [comment]
> I'd suggest you join the discord for further help.
> It'll make it easier for all of us.
> https://discord.gg/riotapi

thank u but i cant join the group

**Comment by stelar7** [comment]
go here https://developer.riotgames.com/
login.
go here https://developer.riotgames.com/apis

read this https://riot-api-libraries.readthedocs.io/en/latest/

**Comment by Pupix** [comment]
> go here https://developer.riotgames.com/
> login.
> go here https://developer.riotgames.com/apis
> 
> read this https://riot-api-libraries.readthedocs.io/en/latest/

thank u but i cant access the website

**Comment by SirVsbi** [comment]
thank you
