### ISSUE TITLE
[BUG] Adding Members to Groups in Dev Portal requires unencrypted Summoner ID

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#164]
**Issue Description**  
Adding a member to a group in the dev portal requires a Summoner ID. The backend is expecting an unencrypted summoner ID, but through the API you cannot obtain this ID anymore.

You are able to skip this field and then click the "Did you mean" to fill in the Summoner ID as a workaround.

**Expected Result**  
Entering a Summoner ID finds the Summoner

**Actual Result**  
Entering an encrypted Summoner returns Summoner not found

**Developer Impact**
Confuses Developers looking to add members to their group, often going to Discord for help on the issue.

**Player Impact**
None

**Issue Comments**
I think removing this field would be the best result as Groups are not tied to Apps and there is no way of knowing where an encrypted Summoner ID was from.

**Comment by RiotTuxedo** [comment]
Thanks for this report, we'll look into resolving this issue in the coming weeks.

**Comment by RiotTuxedo** [comment]
This has been deployed. Closing.
