### ISSUE TITLE
[BUG] (Reopening) Spectator/active-game endpoint returning 404 whereas the player is ingame

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#165]
Hey guys

(Reopening https://github.com/RiotGames/developer-relations/issues/136)

Since the 9.19 release, I've got multiple reports of spectator endpoint in **OCE** returning http404 whereas the player was ingame.

Currently, it's affecting about 40% of the lookups in OCE. 

Could you have a look please ?

Thanks :)

**Comment by RiotR1cket** [comment]
Hi, I'm an engineer on the team that owns spectator, I saw your message yesterday morning and fixed the issue with our OCE spectator grid (approx 9am PST). Thanks for reporting it! We're still working through the root cause so if you see it again please don't hesitate to reopen this or the other ticket.

**Comment by RiotTuxedo** [comment]
@trebonius0 has this issue been resolved for you?

**Comment by trebonius0** [comment]
Yes :)

**Comment by cohenu** [comment]
is it back since the last patch ?

**Comment by RiotTuxedo** [comment]
This looks to be an unrelated issue. It's affecting a couple services. We're looking into it.
https://twitter.com/RiotGamesAPI/status/1187080155434323968

**Comment by RiotTuxedo** [comment]
@cohenu sorry let me double check something. What kind of errors are you seeing with spectator?

**Comment by cohenu** [comment]
I'm sorry for the delay, Riot API key usage shows on Spectator:

EUN1:
403: 32,468
200: 15,060
404: 1,628
503: 242
500: 35

EUW1:
403: 59,624
200: 35,198
404: 2,625
503: 609

NA:
200: 127,860
404: 9,879

TR1: 
403: 26,916
200: 17,272
404: 832
503: 278
500: 60

BR1:
200: 3,403
404: 432

OC1:
200: 18,118
404: 1,541
500: 9

RU:
403: 2,175
200: 1,195
404: 121
503: 12

LA1:
200: 4,690
404: 291

LA2:
200: 3,468
404: 194

I hope this helps

**Comment by RiotR1cket** [comment]
@cohenu Our metrics show euw/eun/tr/ru have no more 403 responses as of 21 hours ago, let us know if you don't see the same in your metrics.

**Comment by cohenu** [comment]
@RiotR1cket I checked now and the numbers are not growing - I will check again tomorrow and update
Thank you very much guys :)

**Comment by cohenu** [comment]
@RiotR1cket I didn't find any 403 today :)
Thank you!

**Comment by davews156** [comment]
We are getting this today as of about 3 hours ago (5:30 ET) to now.  Discord folks recommended we reopen this issue.

We are currently getting a lot of 403s back.  The Spectator API Usage metrics do NOT show 403s, but we are getting them and a lot of them.  Here are a few examples of Summoner Name, Region, and Timestamp:

Varadon (euw1, Mon, 28 Oct 2019 23:56:07 GMT)
CrafteurGaming (euw1, Mon, 28 Oct 2019 23:57:13 GMT)
GG Rhaykko (euw1, Mon, 28 Oct 2019 23:58:07 GMT)
Wazabie (eun1, Mon, 28 Oct 2019 23:51:20 GMT)

**Comment by MingweiSamuel** [comment]
403 would indicate your API key/authentication failed, so they wouldn't show up in the portal. What % of responses are you getting as 403?

**Comment by trebonius0** [comment]
I've the same issue here
~30% of my calls to spectator get a 403

**Comment by chypriote** [comment]
Same issue here, getting 403 on EUW with both the production key and a newly generated dev key

**Comment by davews156** [comment]
> 403 would indicate your API key/authentication failed, so they wouldn't show up in the portal. What % of responses are you getting as 403?

Hard to say exactly, but about 250 of them in 30 minutes so I'd say at least half.  They do seem to be European regions.

**Comment by cohenu** [comment]
I also have issues with spectator endpoint.
I didn't see 403 in API KEY USAGE but I see 403 when I try to send request to spectator endpoint on a live custom game (ALLOW SPECTATORS = All, I'm using custom game only for testing, users complains on normal and ranked queues too, I'm using production key.)

**Comment by trebonius0** [comment]
@RiotTuxedo any update ?

**Comment by RiotTuxedo** [comment]
Yep, we're aware and looking into it, but I would like to separate these issues. There's three issues being conflated in this issue.

1. The original issue was related to active players in-game returning 404 responses.
2. Then there was an issue where 500s and 503s were being returned from the API.
3. Now there's an issue where 403s are being returned from the API.

I believe all three of these are indicative of separate issues and it's a little confusing when someone says "same" which issue is affecting them. For now, let's limit the conversation in this thread to issue #1 and let's open a separate issue for #3. I believe #2 should be resolved at this point.

**Comment by trebonius0** [comment]
Yeah sorry, my bad. I'm opening another thread for the http 403 :)
