### ISSUE TITLE
API Reference page missing DTOs on v4 APIs

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#17]
Two missing DTO specs on the documentation pages of v4 endpoints:

1. ~~https://developer.riotgames.com/api-methods/#match-v4/GET_getMatchTimeline~~
    - ~~missing `MatchParticipantFrameDto`~~
2. ~~https://developer.riotgames.com/api-methods/#league-v4/GET_getAllLeaguePositionsForSummoner~~
    - ~~missing `LeaguePositionDTO`~~

(the v3 pages do have the DTO specs)

**Comment by MingweiSamuel** [comment]
The above two have been fixed :D

Now the following are missing in `tournament-v4` (but not `tournament-stub-v4`)

- https://developer.riotgames.com/api-methods/#tournament-v4/GET_getLobbyEventsByCode
  - `LobbyEventDTO` (but not missing in `tournament-stub-v4`
- https://developer.riotgames.com/api-methods/#tournament-v4/GET_getTournamentCode
  - `TournamentCodeUpdateParameters` (but not missing in `tournament-stub-v4`)

**Comment by MingweiSamuel** [comment]
The following DTOs are missing in the documentation: (2019-01-23)

  "league-v3.MiniSeriesDTO", (in LeaguePositionDTO)
  "league-v4.LeagueItemDTO", (in /lol/league/v4/leagues/{leagueId})
  "league-v4.MiniSeriesDTO", (in LeaguePositionDTO)
  ~~"league-v4.QueueType"~~, (string enum)
  ~~"league-v4.UUID"~~, (UUID primitive)
  "match-v3.MatchReferenceDto",
  "match-v4.MatchReferenceDto", (in matchlist /lol/match/v4/matchlists/by-account/{encryptedAccountId})
  "tournament-v4.LobbyEventDTO", (in /lol/tournament/v4/lobby-events/by-code/{tournamentCode})
  "tournament-v4.TournamentCodeUpdateParameters" (in body params of /lol/tournament/v4/codes/{tournamentCode})

**Comment by RiotTuxedo** [comment]
Yea this was resolved late last week. Let us know if any others go missing.
