### ISSUE TITLE
[BUG] Missing QueueId 420

### ISSUE THREAD

**Issue by antoncazalet** [RiotGames/developer-relations#170]
Hello,
The queueId '420' is missing in the game constants "QueueId".
[JSON](http://static.developer.riotgames.com/docs/lol/queues.json)
It supposed to be there with  
- QueueId: 420
- Map: Summoner's Rift
- Description: 5v5 Ranked Solo games
- Notes : []

Thanks.

**Comment by RiotTuxedo** [comment]
Thanks for the report. I've also updated queueId 900 to just **URF**. It was previously for **ARURF** but they're reusing the same queueId.
