### ISSUE TITLE
[DOCS] Title Spelled Incorrectly

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#172]
Developer is spelled incorrectly in the title of the new documents

![image](https://user-images.githubusercontent.com/53184036/66954897-e604ab80-f026-11e9-8a6c-0574aecf95fa.png)

https://developer.riotgames.com/docs/portal

**Comment by RiotTuxedo** [comment]
Yea I saw you post this on Discord. You know left-brain stuff. It's fixed in the code, should be reflected on the next deploy.
