### ISSUE TITLE
[BUG] can't login to developer riot by garena account

### ISSUE THREAD

**Issue by iceball1** [RiotGames/developer-relations#173]
I can't login to dev riot portal by garena account
I was login with garena account before, but i can't login now.
This error have after developer portal changed.
I remember in the past , i must login at developer.riotsgame.com/login (or login.developer.riotsgame.com) , but now it redirect to auth.riotsgame.com.
So what do i do.
![1](https://user-images.githubusercontent.com/28520161/66984933-eca62800-f0e5-11e9-87b7-970afea87d82.png)
![2](https://user-images.githubusercontent.com/28520161/66984935-ed3ebe80-f0e5-11e9-9550-e1f769eed390.png)

**Comment by KingRider** [comment]
same happen me! :-( ... support riot are bad service

**Comment by bangingheads** [comment]
Garena isn't supported by the Riot Games API

[https://www.riotgames.com/en/DevRel/sunsetting-the-riot-games-api-garena-beta](https://www.riotgames.com/en/DevRel/sunsetting-the-riot-games-api-garena-beta)

If you'd like to access the APIs for the Riot Games owned regions you can always create another account.

**Comment by tisbells** [comment]
Closing old issues. Garena is no longer supported.
