### ISSUE TITLE
Dev portal default group is named based on login username

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#178]
Not really an issue, but i found it wierd that the default group was named based on my login username and not my summoner name. 

See [this image](https://i.imgur.com/KikXAwJ.png) for an example (tho with login name hidden)

Can this be altered to the summoner name?

**Comment by tisbells** [comment]
Closing out old issues. Product Group default is now "Default Group". Feel free to reopen/comment if you feel this is in error.
