### ISSUE TITLE
Display RGEA information somewhere in the portal

### ISSUE THREAD

**Issue by jonasdaniels** [RiotGames/developer-relations#179]
Sending out the RGEA information only by email is the same as sending out the api key only by email and not allowing you to regenerate a new one.

**Comment by RiotTuxedo** [comment]
I wouldn't consider this a bug, but I'm aligned. It probably should be in there.

**Comment by tisbells** [comment]
Closing out old issues. RGEA in the portal is no longer supported. Feel free to reopen or comment if you feel this is in error.
