### ISSUE TITLE
Will ranked armor upgrades be reflected in the league API for the 2019 ranked season?

### ISSUE THREAD

**Issue by axelgorris** [RiotGames/developer-relations#18]
Looking at the modifications that will be introduced in patch 8.24, I guess there's going to be some changes in the API regarding the Tier/Rank/ArmorUpgrades for a given summoner.

- Will there be Tiers per lane? If so, how will this be reflected in the API?
- Will armor upgrades info be included in Leagues or Summoner endpoints?

I couldn't fidn any info in the developer portal related to this. I would really appreciate some directions on this.

Thanks in advance

**Comment by riottuxedo** [comment]
You can find information on changes in the API from Ranked Remastered here:
https://www.riotgames.com/en/DevRel/ranked-remastered-preseason-changes

Your question related to whether armor upgrades will be included in the API is a little ambiguous. Could you clarify your question?

**Comment by axelgorris** [comment]
Thank you for the response.

What I mean is, will there be any way to check which armor upgrades are available for a given summoner through the API? I've read summoners will achieve armor upgrades through the season, and those will be reflected in its rank icons. I would like to reflect that in my application.

And also, within a few weeks we're going to see tiers per lane right? Will that info also be available through the API? Right now we can only check the overall rank for a summoner.

**Comment by RiotTuxedo** [comment]
My understanding is that as you rank up your armor "upgrades" so you'd be able to track those upgrades through changes in rank. Can you link to the announcement you're specifically referring to and I can confirm.

Tiers per lane, as you called them, is positional ranking. We cover when you can expect those changes in the section of the announcement called **What can you expect at season start?**. I hope to have an update on this announcement soon with additional details and clarifications for positional rankings.

**Comment by axelgorris** [comment]
As far as I know, those armor upgrades are not directly related to the rank increases. Instead, you earn "split points" to get these armor rewards. That's what I understood from this dev diary at least: https://www.youtube.com/watch?v=UDvRhUyHsKA&t=80

**Comment by RiotTuxedo** [comment]
Nice catch. I'll look into it.

**Comment by RiotTuxedo** [comment]
Had a chat with the team and this visualization is calculated client side based on data that currently isn't public; split points. In the future this may change, but for now there won't be a way to determine a player's armor rewards.
