### ISSUE TITLE
[BUG] Spectator/active-game endpoint returning 403

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#180]
Hello

Since yesterday ~9PM GMT, 100% of my calls to the spectator endpoint in EUNE/EUW/RU/TR are returning an HTTP403, and it works in other regions. 
It's not linked to my api key being banned.

Can you have a look please ? :)

Thanks !

**Comment by RiotTuxedo** [comment]
Yea we're investigating. This shouldn't be related to your API key at all, it's related to some of the work being done in the VPC that originally was causing the 500s and 503s. The 5XX errors should be resolved now, but we're taking steps to ensure these requests aren't incorrectly returning 403s to API users.

**Comment by RiotTuxedo** [comment]
I believe this issue should be resolved. @trebonius0 can you confirm?

**Comment by lucasMesquitaBorges** [comment]
Closing old issues. Spectator-v4 active-games currently working for all routing values.
