### ISSUE TITLE
[BUG] LoR Incorrect or missing assets for core set

### ISSUE THREAD

**Issue by S2Ler** [RiotGames/developer-relations#182]
datadragon-core-en_us contains entry for neutral region with icon http://dd.b.pvp.net/core/en_us/img/regions/icon-neutral.png, but there is no icon-neutral.png icon in the bundle.

Same for icon-piltoverzaun.png but the name doesn't match. There is only icon with icon-piltoverzuan.png name.

**Comment by RiotTuxedo** [comment]
I've been informed both these issue should be solved in the next release of LoR data dragon for the next preview patch. I'll leave this issue open until we've confirmed the issue is resolved.
