### ISSUE TITLE
Question: is there way to differentiate accountId, puuid, id?

### ISSUE THREAD

**Issue by Ginden** [RiotGames/developer-relations#184]
I'm writing [library](https://github.com/Ginden/rgac) to contact Riot Games API.

I would like to catch bugs early, on client-side to avoid unnecessary roundtrips to API. Therefore, for PUUID I have code like:
```typescript
static getPuuid(summoner: Summoner | string) {
        assertIsNotEmpty(summoner);
        if (isString(summoner)) {
            if (summoner.length !== 78) {
                throw new Error(`"${summoner}" is not a valid PUUID`);
            }
            return summoner;
        } else {
            return summoner.puuid;
       }
}
```

Can I somehow write similar code for `accountId`, `summonerId` etc.?

**Comment by thomasmarton** [comment]
Not really. These IDs are just the encrypted values of the raw IDs and while PUUID is a UUID (same character length for everyone), the other 2 values are regular numeric IDs (with variable length).

With that said, according to Tux*, the max length for a summoner ID is 63 characters and accountIDs shouldn't be longer than 56 characters (tho I wouldn't advise hard coding them as they might change as league keeps growing)

* source: https://discordapp.com/channels/187652476080488449/379429593829867521/529295034973945906 (Riot API discord)

**Comment by RiotTuxedo** [comment]
I think it's probably okay to hard code these checks, but they're only one sided checks. If you get an id that is <56 characters it could equally be a valid summoner id or a valid account id and there's no way to tell which one it is.

That being said, I wouldn't worry about validating these if the user provides the wrong id to an endpoint and make an API call they will get a 400 error back and the error message should tell you that you provided an invalid id. Granted having a library to tell you before you make an API call would save you the rate limit of invalid requests, but this should only be a problem you solve once. If you send the wrong id, you fix it and then you'll be sending the right ids from that point onward. The checks you're trying to code in might save the user a couple invalid calls but it also is something you can't confirm 100% until making an API call. I'd let the user make their mistake and just forward along the error, but that's just my opinion.

Best case you save them some invalid calls, worse case you're enforcing rules that might not be valid.
