### ISSUE TITLE
[Account Issue] Failed to Retrieve Account Information

### ISSUE THREAD

**Issue by jadeeeeh** [RiotGames/developer-relations#185]
I am trying to use Riot API for the first time. However, after registering the account successfully, I cannot login the developer page. It is shown like this:

![image](https://user-images.githubusercontent.com/57475239/68369760-0b905b00-0176-11ea-8359-a0f7cf21c745.png)

"We failed to retrieve your account information. If repeated attempts are unsuccessful, please try again in a couple hours. We're sorry about the inconvenience."

I am sure I registered the account successfully because I can use this account to play LOL but I cannot use this account to see my developer key.

I met up with this issue yesterday. I try again this afternoon. It still doesn't work. Could anyone help me with that?

**Comment by RiotTuxedo** [comment]
Are you trying to register for the [Developer Challenge](https://www.riotgames.com/en/DevRel/legends-of-runeterra-developer-challenge-announcement)? If so, we might not be able to resolve this issue before that deadline and we'll have to find another way for you to submit your entry.

If not, I'd like to add some additional logging to help debug this issue and get back to you shortly.

**Comment by RayZz-** [comment]
Usually this issue is related to not having a summoner name.

**Comment by RiotTuxedo** [comment]
We do check for several requirements before creating a developer portal account; which include checking for a valid summoner and verified email. I have to double check, but this screen should only appear if we're unable to gather the info we need to verify both these.

**Comment by jadeeeeh** [comment]
> Usually this issue is related to not having a summoner name.

Oh yes. It really works. Thank you very much!

**Comment by jadeeeeh** [comment]
> We do check for several requirements before creating a developer portal account; which include checking for a valid summoner and verified email. I have to double check, but this screen should only appear if we're unable to gather the info we need to verify both these. If everything works as it should, we get back your account info and see that you haven't chosen a summoner name and then provide that feedback to the user.

Thank you very much. I set the summoner name and it works. Thank you very much

**Comment by RiotTuxedo** [comment]
Well thanks for this issue then. We'll need to resolve the issue of not giving the user proper feedback.

**Comment by RiotTuxedo** [comment]
A fix is committed, it'll be reflected in the next release of the Developer Portal.

**Comment by RiotTuxedo** [comment]
Users should receive proper feedback now if they don't have a valid account.
