### ISSUE TITLE
[BUG] TFT API gold value exceeds max integer value

### ISSUE THREAD

**Issue by DoDoSt** [RiotGames/developer-relations#188]
**Describe the bug**  
The gold_left value of some summoners of some matches of TFT is 4294967295 gold. 

**Expected Result**  
The gold of a player should never reach such high values.

**Developer Impact**
I discoverd this bug, cause my database column type to integer and this value exceeds the maximum. I had to change the type to unsigned interger or filter this values before writing to the database.

**Player Impact**
If this is only the conversion error on Riot's side, it is ok, but if a player really had this much gold, this is a critical bug in TFT.

**Steps to reproduce**

For example this matches: 
1. EUW1_4269782856
1. EUW1_4266315034
1. EUW1_4266677243
1. EUW1_4266712616
1. EUW1_4266796835
1. EUW1_4266836572
1. EUW1_4267077096
1. EUW1_4267460801
1. EUW1_4267472195
1. EUW1_4267741844
1. EUW1_4267775443
1. EUW1_4268121973
1. EUW1_4268189403
1. EUW1_4268761915
1. EUW1_4269037817
1. EUW1_4269244213
1. EUW1_4269594173
1. EUW1_4269782856
1. EUW1_4270071393
1. EUW1_4270272978
1. EUW1_4270854282
1. EUW1_4271199194
1. EUW1_4271316530
1. EUW1_4271595378
1. EUW1_4271971944
1. EUW1_4272000860
1. EUW1_4272630986

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
