### ISSUE TITLE
[BUG] TFT API: some matchIds can not be found

### ISSUE THREAD

**Issue by DoDoSt** [RiotGames/developer-relations#189]
**Describe the bug**  
The TFT API for match history returns matchIds, which can not be found. 

**Expected Result**  
The API returns only valid matchIds.

**Actual Result**  
On the `/tft/match/v1/matches/{matchId}` API I got the response code 404 for a matchId, which was returned by the `/tft/match/v1/matches/by-puuid/{encryptedPUUID}/ids` API.

**Developer Impact**
It is not a big problem to solve, as I just have to catch the 404 response.

**Player Impact**
Are this a matches, which summoners actually played, but after that they don't see them in their match history? 

**Steps to reproduce**

1. Get matches of Summoner with puuId dp6mpvsQo6-li6mR_q6KrlH4SQU1gPk9oQF3Isvrlo1vvaCe6P7yHzSdlm2YScVSc7qqjumprEXWSg
1. Get match EUW1_4267983004 of this summoner

Other puuIds/matchIds: 
- PbF_iRFLJ9ubk9-_netQ_brX9GHwnbDGtKJ9kYS5i92OFuB3Je-H9ZfVToqxaV3eI7lSh1l1G6Mw0w / EUW1_4268042175
- JXMvG8qmi4fF2geUyTzSBDYGnClSkIMgpm_s-ufu1R8zyYdag7albqkekF3-r2HTuLnmwWhArFQ-QA / EUW1_4256156329

**Comment by MingweiSamuel** [comment]
Ah, could you post the summoner's names since the puuids are encrypted per API key?

**Comment by DoDoSt** [comment]
Oh, my bad, sry. 
- TFTMaCkMAS / EUW1_4267983004
- Archidog / EUW1_4268042175
- SouthxBomberz / EUW1_4256156329

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
