### ISSUE TITLE
[Feature Request] [LoR] Add game client version in responses

### ISSUE THREAD

**Issue by hazhirg** [RiotGames/developer-relations#193]
Similar to the LoL and TFT APIs, having the game version in the Game Client API can help with handling response schema changes, comparing stats, etc. across game updates.

**Comment by lucasMesquitaBorges** [comment]
Hi, due to this issue being old, I'm not sure if game team added version in Game Client APIs.

Unfortunately DevRel can't take action in issues or feature requests for Game Client APIs. This is mentioned in the docs: https://developer.riotgames.com/docs/lol#league-client-api

> NOTE: We provide no guarantees of full documentation, service uptime, or change communication for unsupported services. This team does not own any components of the underlying services, and will not offer additional support related to them.
