### ISSUE TITLE
[BUG] Cannot interpret spell text for Aatrox, Senna, & others. Champion JSON has a Zero Matrix for all of his ability Effect arrays.

### ISSUE THREAD

**Issue by moscoso** [RiotGames/developer-relations#194]
**Describe the bug**  
It is impossible to evaluate the spell text for certain champions.

For example, Aatrox in his JSON: http://ddragon.leagueoflegends.com/cdn/9.22.1/data/en_US/champion/Aatrox.json

**Issue Description**  
According to https://developer.riotgames.com/docs/lol#data-dragon_champions, every champion has an effect array that helps to interpret spell text. 
The problem it seems is affecting all newer champions that does not follow the {{eN}} {{ aN }} or {{ fN }} placeholders.

**Expected Result**  
Something with values like (One of Amumu's effect matrixes for an ability): 
"effect": [null, [80, 130, 180, 230, 280],
                    [1, 1, 1, 1, 1],
                    [1350, 1350, 1350, 1350, 1350],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0]
                ],
![image](https://user-images.githubusercontent.com/1927628/68988744-e7c1ba80-07f0-11ea-8e13-fcc2ec43fd7e.png)

**Actual Result**  
"effect": [null, [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0]
                ],
![image](https://user-images.githubusercontent.com/1927628/68988737-d5e01780-07f0-11ea-9887-e6868aef5af4.png)

**Developer Impact**

* Frequency: Always
* Severity: Moderate
* Cost: Impossible to evaluate spells for certain champs. Requires to manually input  and guess these values every patch
* Efficiency: Requires me to spend several hours to figure out the values and which variables they correspond to for each champion this affects.

**Comment by BmElectro** [comment]
So is this not an issue or why is it ignored ?

**Comment by Querijn** [comment]
It's ignored because datadragon has no player value

**Comment by benjaminbours** [comment]
Hi @moscoso, can I have more explanation about why this issue is not considered? What does it means datadragon has no player value?

We are talking about the documentation here => https://developer.riotgames.com/docs/lol#data-dragon_champions indicating things that are incorrect for some champs.

To add to the initial issue, there is even an example about the usage of the `vars` array, but for Aatrox or even Darius, its empty.

For Aatrox, there are variable such as `{{ qdamage }}` and `{{ qedgedamage }}` but there are no indication about how to compute the value for each.

Am I missing something or is this documentation outdated?

Thanks in advance,

Benjamin

**Comment by geozukunft** [comment]
Riot prios things based on the so called "player value" which is more or less "if we invest x time/money into a new feature or a bug fix how much player satisfaction (read money) is that going to generate them. The data that is talked about here is no longer used by any of Riots internal teams and the cost of fixing it outweighs the player value it would generate. Thus it won't get fixed. 

I can recommend communitydragon.org
