### ISSUE TITLE
REGA Info

### ISSUE THREAD

**Issue by a1git** [RiotGames/developer-relations#198]
Hi, 

I am asked to display REGA info in the portal, but I do not see anywhere where to get that details or what even to put in the portal. Can't this be shown in the app page itself ?

**Comment by RiotTuxedo** [comment]
Thanks for this feedback. Did you find the information you needed or are you still looking for details? Please provide your app id and I can send the details if you need them.

Long term we'll definitely want to include this info as part of the app, short term we'll likely provide this info as an app note.

**Comment by a1git** [comment]
lol.gd

**Comment by thomasmarton** [comment]
I believe you misunderstood Tux here, your app ID is a numeric ID for each individual app. You can find it in the URL if you go to your application page.
Here's an example of that URL noting where your app ID will be: https://developer.riotgames.com/app/YOUR_APP_ID_IS_HERE/info

**Comment by a1git** [comment]
My app was disabled for not displaying the info. the page https://www.riotgames.com/en/DevRel/rgea says I should have received an email wtih what to put .. but I have not received any such email. I have sent messages, but I have not received any emails on exactly what to display in the website such that the app is enabled again.

**Comment by a1git** [comment]
since its public info, please check appID 58740 and let me know what I need to do. I have been waiting for a long time now with a finished product.

**Comment by Querijn** [comment]
Hey there,

It's not public, Thomas knows the format of the URL. We cannot look at any of the information of your application. 

Some common issues are:
- You have used a throwaway email on your profile. You can see an obfuscated version [here](https://account.riotgames.com/account) after logging in. You'll also be able to modify it.
- You have disabled email notifications [here](https://developer.riotgames.com/my-account).
- It might have ended up in your spam folder.

**Comment by a1git** [comment]
since the code is to be put in the public website, why cannot it be provided here ? as far as I know its a snippet that needs to be in all apps where I need to replace the appid with the app id of my app. Then cannot that code snippet be provided here ?

**Comment by a1git** [comment]
there is no response here, or in the app messages :( .. my project is down

**Comment by tisbells** [comment]
Closing out old issues. RGEA in the portal is no longer supported. Feel free to reopen or comment if you feel this is in error.
