### ISSUE TITLE
[BUG] Pastebin Lambda Function Instructions OOD

### ISSUE THREAD

**Issue by saint-justin** [RiotGames/developer-relations#199]
**Describe the bug**  
The pastebin instructions that come up in the Discord via the .cors command is out of date.

**Issue Description**  
The .cors command returns a pastebin that gives out of date instructions for the code to paste into a user's lambda. In options, the path param (line 22) should be updated to be `path: "/lol/summoner/v3/summoners/" + event['pathParameters']['id'] + "?api_key=" + api_key,`

**Developer Impact**
Makes it immensely difficult for novice developers to set up proxies around CORS for API projects.

**Steps to reproduce**

1. Open Discord
1. Types the `.cors` command into any channel with Botty McBotface
1. Navigate to the AWS Lambda pastbin link

**Comment by lucasMesquitaBorges** [comment]
Issue not relevant to the context of Riot Games API.
