### ISSUE TITLE
Typo on the DevRel announcement

### ISSUE THREAD

**Issue by UghThatGuyAgain** [RiotGames/developer-relations#2]
Preconditions (*)
- Have a browser (not IE, thats pretty unprofessional)
- Navigate to https://www.riotgames.com/en/DevRel/new-comms
- Scroll down to the "lovely chart below"

Steps to reproduce (*)
- Read the "Now I Know!" part, on the section of "DEVELOPER PORTAL"
- Notice "teh" instead of "the"
- Laugh a bit
- Report screenshot to discord

Expected result (*)
- Not misspelling (I heard it was you, Paul)

[Screenshots, logs or description]
Actual result (*)

https://cdn.discordapp.com/attachments/187652476080488449/516794769381523492/unknown.png
`Above is the screenshot of the section I mentioned above.`
https://cdn.discordapp.com/attachments/187652476080488449/516794800889135106/unknown.png
`A zoom in of said issue.`

Also, first issue. Here's to many more (less?) bugs reports in the future, a use out of this GitHub, and some better written reports!

**Comment by Strebeck** [comment]
Typo corrected. 

During the process two other similar bugs were identified and addressed. The web page noted in step two of the report's preconditions has been updated to reflect these changes.

Thanks for flagging this.
