### ISSUE TITLE
v4 MatchList "Exception decrypting when" using prod key

### ISSUE THREAD

**Issue by Gchorba** [RiotGames/developer-relations#20]
From Discussion boards:

```
I've been testing out the v4 endpoints and came across an issue with matchlist.
making the call to the endpoint with my dev key works completely fine via the url:

https://na1.api.riotgames.com/lol/match/v4/matchlists/by-account/l7QTrmt8nJz9lwAIcmDt0xY6uhASHDLae8dM8pIhrjDhfcg?api_key=DEV_KEY

however, changing just the key to my production key results in a 400:

{"status":{"message":"Bad Request - Exception decrypting l7QTrmt8nJz9lwAIcmDt0xY6uhASHDLae8dM8pIhrjDhfcg","status_code":400}}
I double checked my key and made sure its correct, (otherwise i'd be getting 403's). 
The only thing changing in the url is the DEV_KEY => PROD_KEY 
What could be the issue?
```

Comments from Discussion boards:
```
TEA CodenameTim (EUW)

I have the same issue with my productive key. Would be awesome if someone has a solution or any suggestions for that.


Answer by zhugeliangvn (NA) 

I think encrypted accountId by dev key only work with this dev key. If you want use prod key, you must get encrypted accountId by prod key.


CodenameTim (EUW)

Correct me if I'm wrong, but you can't define if you are using a Dev Key or Productive Key. You just add the specific key as a paramenter to your request URL.
```

**Comment by Gchorba** [comment]
https://www.riotgames.com/en/DevRel/player-universally-unique-identifiers-and-a-new-security-layer

Specifically this part: As seen in the annotations for V4 below, the values for account ID, PUUID and id would be different for each key holder, for a given player.
V4
/lol/summoner/v4/summoners/by-name/{summonerName}


{
    "profileIconId": 3777,
    "name": "Riot Git Gene",
    "puuid": "qHn0uNkpA1T-NqQ0zHTEqNh1BhH5SAsGWwkZsacbeKBqSdkUEaYOcYNjDomm60vMrLWHu4ulYg1C5Q",
    "summonerLevel": 58,
    "accountId": "eBe6G4dKRDXpjsqf7WMAx6dB1keDQ9j1p-gtlp83qxs",
    "id": "_Pjl3Oq4ts4RpRHk_1VBsBJCSY0ICpnVAi_DQmmXKz5z",
    "revisionDate": 1543369368000
}


Example of a different user calling the same player:

{
   "profileIconId": 3777,
   "name": "Riot Git Gene",
   "puuid": "iwmnue8i1ITVPpgXMAotlTfh0J_nuNZxUGl8UqxyC3R3r08ZQsH0w9A4quXkAT34nmPM2lXui8j3YQ",
   "summonerLevel": 58,
   "accountId": "p7PLPr6w_bLWEO4FCipeTqQvZ1JWpEk6hUFS3d31--Q",
   "id": "zApn-LewpQeGH_hApnrol0Il5zkrpic3vAgJa1B6E7vK",
   "revisionDate": 1543369368000
}

the account id is different per key

**Comment by DIOGOODELLI** [comment]
Can you understand how you do this?

**Comment by sousa-andre** [comment]
> Can you understand how you do this?

Olá, o que o @Gchorba quis dizer foi que o valor dos 3 Ids retornados pelo summoner-v4 endpoint são relativos à aplicação usada isto é, considerando a chave de desenvolvimento (dev API key) e uma outra chave de aplicação criada através deste link, https://developer.riotgames.com/app-type/ (production key) serão diferentes.

**Comment by DIOGOODELLI** [comment]
Na realidade, meu problema é que eu tenho a chave de produção já, porém a ID vem criptografada, retornando o erro dizendo que preciso descriptografar.

Mas não consigo encontrar em lugar nenhum, como faz isso, ou qual o tipo de criptografia que eles usaram.

**Comment by sousa-andre** [comment]
> Na realidade, meu problema é que eu tenho a chave de produção já, porém a ID vem criptografada, retornando o erro dizendo que preciso descriptografar.
> 
> Mas não consigo encontrar em lugar nenhum, como faz isso, ou qual o tipo de criptografia que eles usaram.

Tu não deves descriptografar os Ids mas sim usa-los da forma que são retornados pelo summoner-v4 endpoint.

**Comment by DIOGOODELLI** [comment]
acho que entendi, minha tentativa era de fazer o seguinte.

Buscar o id do usuário pelo imaginando que já estou usando a api key, de produção aquela que tem mais limite de requisição.

Meu problema é que id, nesse caso vem criptografado, ao menos da forma que estou fazendo acontece isso.

Desse id que buscar o histórico de partida, porém ele retorna que o id precisa ser descriptografado.

Se eu usar a API Key. de desenvolvimento, retorna normal.


Já estou usando essa estrutura para buscar:
/ lol / summoner / v4 / summoners / by_name / {summonerName}



Bem , obrigado pela ajuda, vou continuar estudando aqui.

**Comment by sousa-andre** [comment]
> acho que entendi, minha tentativa era de fazer o seguinte.
> 
> Buscar o id do usuário pelo imaginando que já estou usando a api key, de produção aquela que tem mais limite de requisição.
> 
> Meu problema é que id, nesse caso vem criptografado, ao menos da forma que estou fazendo acontece isso.
> 
> Desse id que buscar o histórico de partida, porém ele retorna que o id precisa ser descriptografado.
> 
> Se eu usar a API Key. de desenvolvimento, retorna normal.
> 
> Já estou usando essa estrutura para buscar:
> / lol / summoner / v4 / summoners / by_name / {summonerName}
> 
> Bem , obrigado pela ajuda, vou continuar estudando aqui.

Como eu já referi, o Id não necessita de ser descriptografado, apenas usas como é retornado pela API como fosse um Id normal.
Cuidado que não podes usar um Id generado por uma API Key numa outra API Key diferente

**Comment by DIOGOODELLI** [comment]
"Cuidado que não podes usar um Id generado por uma API Key numa outra API Key diferente"

Era exatamente esse o meu problema, muito obrigado, demorou mas entendi :D
