### ISSUE TITLE
[Feature Request] Add CN Platform Routing Values

### ISSUE THREAD

**Issue by Knove** [RiotGames/developer-relations#202]
Hi Team,

I am China developer, i want have  CN Platform Routing Values.
https://developer.riotgames.com/docs/lol

If u can't, I want to give me a reason.

Thanks!

Regards,
Knove

**Comment by Querijn** [comment]
https://www.riotgames.com/en/DevRel/sunsetting-the-riot-games-api-garena-beta

**Comment by MingweiSamuel** [comment]
Valid feature request that would be great to have, but probably not going to happen.

For a bit of context, there are the regions run by Riot which have the API, then the regions run by Garena (for Southeast Asia) and Tencent (China). For a while it seemed that Garena was much more likely to get the API than Tencent. However recently even the Garena beta ended (as Q posted). So its seems that API for Tencent is not likely to come in the future either. (However I am not a Rioter and don't know what they will be working on)

**Comment by pison233** [comment]
好兄弟，你现在找到方法了吗

**Comment by tisbells** [comment]
Closing out old issues. Unfortunately this is not a planned feature at this time.
