### ISSUE TITLE
[DATA] How to know whether a player is playing alone or with his friends?

### ISSUE THREAD

**Issue by jadeeeeh** [RiotGames/developer-relations#203]
I want to know whether playing with friends or not will affect the performance of the player. But I failed to find a field indicating the queue type of the player. 

I noticed that there is a "queue" in "/lol/match/v4/matchlists/by-account/{encryptedAccountId}" . 
![image](https://user-images.githubusercontent.com/57475239/70528244-b686a100-1b88-11ea-9ad9-ef9ee34dccae.png)

But it is an "int" type data and I cannot find the explanation of this field in the DOCs.
![image](https://user-images.githubusercontent.com/57475239/70528319-e3d34f00-1b88-11ea-8707-a55446f37de9.png)

If the "queue" here indicates how the player queues, could you please tell me the meaning of each value of "queue"?  If the "queue" is not about the way how the player queues, then how can I know whether the player is DUO or SOLO in unranked matches?

**Comment by supergrecko** [comment]
That is the queue ID, you can find out what queue this is by searching through [this JSON.](http://static.developer.riotgames.com/docs/lol/queues.json) 

Other static data can also be found [here](https://developer.riotgames.com/docs/lol)

You may also be interested in the Riot API Community Discord (https://discord.gg/riotapi)

**Comment by jadeeeeh** [comment]
> That is the queue ID, you can find out what queue this is by searching through [this JSON.](http://static.developer.riotgames.com/docs/lol/queues.json)
> 
> Other static data can also be found [here](https://developer.riotgames.com/docs/lol)
> 
> You may also be interested in the Riot API Community Discord (https://discord.gg/riotapi)

Thank you very much for your reply. It really helps a lot. According to the linkages, queue ID refers to which map the player is using.  But I want to know more details about the composition of the team. For example, if the player is playing DUO ranked game with one friend, I want to know which one of all his four teammates is his friend. But it seems that there is no such field telling about this information. I will try other ways to solve the problem. Thank you very much.

**Comment by sousa-andre** [comment]
> > That is the queue ID, you can find out what queue this is by searching through [this JSON.](http://static.developer.riotgames.com/docs/lol/queues.json)
> > Other static data can also be found [here](https://developer.riotgames.com/docs/lol)
> > You may also be interested in the Riot API Community Discord (https://discord.gg/riotapi)
> 
> Thank you very much for your reply. It really helps a lot. According to the linkages, queue ID refers to which map the player is using. But I want to know more details about the composition of the team. For example, if the player is playing DUO ranked game with one friend, I want to know which one of all his four teammates is his friend. But it seems that there is no such field telling about this information. I will try other ways to solve the problem. Thank you very much.

The friends list of a player is considered private information. The only allowed way to get it is though LCU API.

**Comment by JamieDavidson** [comment]
Bit late to the party, but this data is typically determined by looking at the participants in the player's most recent games.

You can retrieve the most recent 10 games by using the filtering available in the [getMatchlist endpoint](https://developer.riotgames.com/apis#match-v4/GET_getMatchlist):
![image](https://user-images.githubusercontent.com/22443587/72696818-8a6e2080-3b35-11ea-85f5-7816151eb861.png)

Once you have the 10 `gameId`s, you can query them individually with the [getMatch endpoint](https://developer.riotgames.com/apis#match-v4/GET_getMatch) and look at the participants on the player's team.

Participant data looks like this
```
{
    "player": {
        "currentPlatformId": "EUW1",
        "summonerName": "",
        "matchHistoryUri": "",
        "platformId": "EUW1",
        "currentAccountId": "",
        "profileIcon": 3543,
        "summonerId": "",
        "accountId": ""
    },
    "participantId": 5
},
```
Where `participantId` should be the name of the player you're looking at.
Then, finding their team from the participant data:
```
{
    "spell1Id": 12,
    "participantId": 5,
    "timeline": {
        // not interesting for solving this task
    },
    "spell2Id": 7,
    "teamId": 100,
    "stats": {
        // not interesting for solving this task
    },
    "championId": 21
}
```
Where `teamId` is 100 for blue side, 200 for red side, according to the docs.
Once you know which team the player was on, you can look at all the other participants in the game to find the ones on the player's team. Repeat for the last X games and you'll be able to predict (reasonably well, but not perfectly) who the player is queued with.

Best of luck :)

**Comment by lucasMesquitaBorges** [comment]
As the previous comments explained, API doesn't returns if a player is alone or with friends, but you can estimate based on the amounts of previous matches played in the same team with a given player.
