### ISSUE TITLE
THIRD-PARTY-CODE-V4 response 404 not found [BUG]

### ISSUE THREAD

**Issue by emrekececi35** [RiotGames/developer-relations#205]
Describe the bug
###  PART THIRD-PARTY-CODE-V4 endpoint not working  my developer api key
**Issue Description**  
THIRD PARTY-KOD-V4 endpoint not working developper api key but working on other endpoints
encryptsSummonerId: H0SVjlf8GNYCg1Zzh0uqwk4RE30pPZpQ_ufDQ6bEamJScQ
Expected Result
![riot](https://user-images.githubusercontent.com/23164437/70664860-540ecd00-1c7c-11ea-8e6d-b4768e4f6136.jpg)

**Comment by MingweiSamuel** [comment]
Has that summoner set a third party code?

**Comment by emrekececi35** [comment]
no, summoner

> Has that summoner set a third party code?

yes , my fault .sorry.

**Comment by bbanothu** [comment]
> > Has that summoner set a third party code?
> 
> yes , my fault .sorry.

Hey, How do I generate my own third party api code so I can set it on my account?

**Comment by bbanothu** [comment]
> Has that summoner set a third party code?

Hey, How do I generate my own third party api code so I can set it on my account?

**Comment by thomasmarton** [comment]
> > > Has that summoner set a third party code?
> > 
> > 
> > yes , my fault .sorry.
> 
> Hey, How do I generate my own third party api code so I can set it on my account?

You can take a look at this piece to better understand how that API works: https://hexdocs.communitydragon.org/lol/riotapi/1.usingthirdpartycodetoverifyaccountownership
Also this channel is for tracking issues, not for general help, you should join the 3rd party community discord server instead: https://discord.gg/riotgamesdevrel
