### ISSUE TITLE
[Feature Request] All Stubs for Tournament API

### ISSUE THREAD

**Issue by yodigi7** [RiotGames/developer-relations#207]
Would like to have stubs for all of the tournament apis and not just some.

![image](https://user-images.githubusercontent.com/19217358/70685146-1014cb80-1c6e-11ea-9a76-d5efc8eba247.png)

**Comment by simivar** [comment]
This would be very nice! Right now I can't really test my implementation as not all endpoints are available. @RiotTuxedo is there any reason why it's not available or are there any plans to add those endpoints here? :)
