### ISSUE TITLE
[DDragon] Is there a way to omit recommended builds from champion info?

### ISSUE THREAD

**Issue by hundeva** [RiotGames/developer-relations#209]
Take for example the complete set of champions, on the latest available patch: https://ddragon.leagueoflegends.com/cdn/9.24.2/data/en_US/championFull.json

Downloading this json results in a 4282 KB file, which is pretty big. I was looking at the data structure, for Aatrox for example, this section is more than half of the whole json. Leaving out the recommended builds, I would guess that the size would be less than 2 MB.

So the question is, is there any way to omit recommended builds?

**Comment by thomasmarton** [comment]
You can use the regular champion.json file which doesn't have these included:
https://ddragon.leagueoflegends.com/cdn/9.24.2/data/en_US/champion.json

**Comment by hundeva** [comment]
Yeah, that would be an option, though that does not haave skill information, for example. So, alternatively, is there a way to add skill information to that lighter version?

**Comment by thomasmarton** [comment]
Unfortunately these are the only files Riot publishes. Your best bet would be to just download and modify them to your needs and host them yourself. :(

**Comment by hundeva** [comment]
That was what I'm afraid of, I'll think about what to do. Thanks though!

**Comment by RiotTuxedo** [comment]
@hundeva best place for these kinds of questions is in the developer discord. https://discord.gg/riotapi
