### ISSUE TITLE
[BUG] Incorrect trait names on static data

### ISSUE THREAD

**Issue by EvilasioAnisio** [RiotGames/developer-relations#212]
hi, I noticed that traits.json (from tft's static data, set2.zip) have some typos (_eletric_ and _beserker_), which can cause some confusion.

**Comment by RiotTuxedo** [comment]
Thanks for the report. It should be updated when the CDN's cache expires.

**Comment by stelar7** [comment]
@RiotTuxedo You need to close it, not just tag it 😃
