### ISSUE TITLE
I was banned for third-party software, yet I have none.

### ISSUE THREAD

**Issue by Jackvad** [RiotGames/developer-relations#213]
I was logging in to play with friends today to see I was "permanently banned due to the use of third-party software" I understand that mistakes are made so I will not be mad as long as this is fixed. jackvad is my username in LOL BTW.

**Comment by RayZz-** [comment]
The issues here are to do with any Riot Games API and not account/player related issues for support on that please contact player support at https://support.riotgames.com/ or support@riotgames.com

**Comment by stelar7** [comment]
@RiotTuxedo close :)
