### ISSUE TITLE
DDragon's SSL certificate expired

### ISSUE THREAD

**Issue by thomasmarton** [RiotGames/developer-relations#218]
The SSL certificate of ddragon.leagueoflegends.com has expired today.

I can't tell the exact player impact cause some Riot websites (including the official match history) is broken cause of this but others (patch notes as an example) are using a proxy layer between ddragon and the site itself allowing it to still function.

Some 3rd party apps rely heavily on ddragon for static data so it would be nice if you could ask the service owning team to renew the SSL certificate of ddragon.

**Comment by stelar7** [comment]
```
Subject: ddragon.leagueoflegends.com
Issuer: DigiCert SHA2 High Assurance Server CA
Expires on: 8. jan. 2020
Current date: 8. jan. 2020
```

RIP

**Comment by thomasmarton** [comment]
I think this has been fixed. Everybody on the discord said they have the new cert too.
