### ISSUE TITLE
[BUG] Matchlists by account returns inaccurate total games count without high beginIndex parameter

### ISSUE THREAD

**Issue by JamieDavidson** [RiotGames/developer-relations#223]
**Describe the bug**  
When querying the matchlists by account endpoint, `totalGames` is inaccurate unless supplying a higher `beginIndex` and `endIndex`.

Here's the query for my account:
`https://euw1.api.riotgames.com/lol/match/v4/matchlists/by-account/ZjrgZoDg5s1x0b5jCeCOGWzmoQNOgtQdOintpjsZWcWlqPEswL_PJI02`

Which returns my `totalGames` as 194.

Supplying a beginIndex and endIndex of something high, say `123456789`:
https://euw1.api.riotgames.com/lol/match/v4/matchlists/by-account/ZjrgZoDg5s1x0b5jCeCOGWzmoQNOgtQdOintpjsZWcWlqPEswL_PJI02?beginIndex=123456789

Returns the (I hope) accurate number of games I've played.
```
{
    "matches": [],
    "endIndex": 672,
    "startIndex": 672,
    "totalGames": 672
}
```

Querying with indices 125 or above returns 672 games played:
https://euw1.api.riotgames.com/lol/match/v4/matchlists/by-account/ZjrgZoDg5s1x0b5jCeCOGWzmoQNOgtQdOintpjsZWcWlqPEswL_PJI02?endIndex=125&beginIndex=125

124 returns 194 games played:
https://euw1.api.riotgames.com/lol/match/v4/matchlists/by-account/ZjrgZoDg5s1x0b5jCeCOGWzmoQNOgtQdOintpjsZWcWlqPEswL_PJI02?endIndex=124&beginIndex=124

**Developer Impact**
None, workaround is easy but shouldn't be needed.

**Player Impact**
None, my app is for personal use at the moment.

**Comment by bangingheads** [comment]
Duplicate to #55 this has been bugged for a while it is advised to crawl matchlist indexes until no more results.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported. Feel free to reopen/comment if you feel this is in error.
