### ISSUE TITLE
[BUG]LoR positional-rectangles endpoint not properly reporting GameState

### ISSUE THREAD

**Issue by CrabBucket** [RiotGames/developer-relations#226]
**Describe the bug**  
/positional-rectangles api endpoint doesn't properly report the state of the game while accepting rewards.  https://i.imgur.com/cQdUuCX.jpg  While accepting rewards it just reports whatever the last game state was (I assume).

**Issue Description**  
Can't eaily get accurate knowledge when someone is in a menu or in a game.

**Expected Result**  
In the rewards screen it would either report for gamestate like 'Rewards" or "Menus" either would be fine as long as it didn't say "inprogress"

**Actual Result**  
It says "inporgress"
**Developer Impact**

* Frequency: At the end of every game depending on how long the user waits on rewards screen.
* Severity: When it happens, it puts faulty data into the database
* Cost: None

**Steps to reproduce**

1. Poll the local api of Runeterra in the rewards page.
1. Note that it says "inprogress" for gamestate.

**Comment by CrabBucket** [comment]
I figured out a way around it.

**Comment by Querijn** [comment]
It helps telling future googlers to say what you did to avoid this issue in the future.
