### ISSUE TITLE
[BUG] Spectator endpoint returning an finished game

### ISSUE THREAD

**Issue by Canisback** [RiotGames/developer-relations#227]
**Describe the bug**  
Spectator endpoint shows player in game while the game ended (for a long time)

**Expected Result**  
The spectator endpoint should return a 404 (as the player is not in game anymore).

**Actual Result**  
Spectator-wise, the game is still running (160 minutes and counting).
Header and body of the request : https://pastebin.com/i7DhJXcT

**Developer Impact**

* Frequency: First time encountered
* Severity: Inaccurate live game data

**Player Impact**
Maybe affects the client spectator data, no confirmation yet.

**Steps to reproduce**
Request spectator endpoint for summoner REEEEEEÈ (NA) (too late by the time I finished to write this issue)

**Issue Comments**
The gameId gives also a 404 with match endpoint, even hours after the end of the game.

**Comment by tisbells** [comment]
Closing this out as it's very old and we are now on [Spectator-V5](https://developer.riotgames.com/apis#spectator-v5). If you run into this issue in the future, feel free to open a new issue
