### ISSUE TITLE
[BUG] LoR in-game API crashes when requesting static-decklist endpoint

### ISSUE THREAD

**Issue by MoanaBoi** [RiotGames/developer-relations#229]
**Describe the bug**  
When requesting the in game API for "/static-decklist" the API randomly crashes.

**Issue Description**  
When requesting this endpoint the API doesn't answer anything. No access denied or request timeout.

**Expected Result**  
Expecting the API to answer with the deck code and the cards in it if the user is in game or 
`{
  "DeckCode": null,
  "CardsInDeck": null
}`
if the user is not in game.

**Actual Result**  
The API doesn't answer. I went and checked the logs of LoR to see if the crashed was logged and i found the issue here is the pastbin of the logs for the crash:
[https://pastebin.com/CW06Xnn9](url)

**Developer Impact**

* Frequency: It happens around 5 min after the game was launched. When it crashes one time it doesn't answer anymore and the game needs to be restarted to use this endpoint again.
* Severity: When it happens my application just can't work at all because im supposed to be tracking the player through different matches
* Efficiency: My app doesn't work anymore

**Player Impact**

* Frequency: everytime the player would launch the game for more than 5 mins my app wouldn't work.
* Severity: When this bug happens, a user is unable to use my app.

**Preconditions**

* i can reproduce this bug anytime with any deck so no preconditions

**Steps to reproduce**

1. Launch the game
1. Launch a game against an AI for testing
1. Request the "/static-decklist" endpoint (it should work at first)
1. wait around 10 minutes in the game.
1. request the endpoint again.

**Issue Comments**

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by DEPREZR** [comment]
I performed many tests, and local api seems to not work for online matches.
For what I saw when I played some matches versus IA, no problem, api respond.
But from the moment I start an online one, next requests infinitely await.

**Comment by StickyBoi** [comment]
It also crashes versus AI for me at least.

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
