### ISSUE TITLE
Large number of matches reporting lane as NONE and role as DUO_SUPPORT

### ISSUE THREAD

**Issue by timplaw** [RiotGames/developer-relations#23]
https://github.com/RiotGames/developer-relations/issues/19 The issue is that everyone is getting lane->"NONE" and either role->"DUO" or "DUO_SUPPORT"

**Comment by stelar7** [comment]
Its not an issue, its just how the game thinks things are. They might not be correct, but its what the game says is correct.

**Comment by TimLaw1** [comment]
Ok, sorry

**Comment by riottuxedo** [comment]
Is there additional information to support this claim? Are you certain there are no games where the lane is being properly reported? Which queue are these games being played in?

Please provide additional information otherwise we'll have to close this issue.

**Comment by TimLaw1** [comment]
I listed hundreds of GameId's with this issue here: https://discussion.developer.riotgames.com/questions/6814/found-a-game-with-duo-and-duo-support-for-nearly-e.html The website is down right now, but when it comes back up you should be able to check the list by looking at a previous edit (right now there's only a few listed because I thought it was too long).

**Comment by TimLaw1** [comment]
Here are a few, these are from 1000ish games in d5+ NA ranked 5v5 soloq. [2914350120L, 2914513644L, 2914386892L, 2914271860L, 2914016493L, 2914356685L, 2913973462L, 2913999236L, 2914476154L, 2914319230L, 2914340204L, 2914306573L, 2914373009L, 2914544724L, 2914541714L, 2914570487L, 2914566872L, 2914399540L, 2914491450L, 2914349765L, 2914404954L, 2914371466L, 2914260434L, 2914326806L, 2914547237L, 2914742168L, 2914287861L, 2914564917L, 2914439737L, 2917660355L, 2917571011L, 2917623199L, 2917609565L, 2917554514L, 2917605164L, 2917718980L, 2917714065L, 2917676851L, 2917651043L, 2917588171L, 2917557851L, 2917586632L, 2917641713L, 2917661224L, 2917667493L, 2917770473L, 2917735264L, 2917700236L, 2917781594L, 2917670108L, 2917708382L, 2917560989L, 2917653404L, 2917589078L, 2917662897L, 2917710855L, 2917678478L, 2917626362L, 2917715240L, 2917644399L, 2917802409L, 2917814848L, 2917747529L, 2917591870L, 2917792048L, 2917568646L, 2917614126L, 2917680710L, 2917805317L, 2917641126L, 2917806185L, 2917672855L, 2917794928L, 2917793498L, 2917640288L, 2917831999L, 2917618103L, 2917821623L, 2917740991L, 2917636349L, 2917659340L, 2917614801L, 2916383861L, 2916814402L, 2917611254L, 2916892383L, 2915975600L, 2916478724L, 2915480885L, 2917231002L, 2916644135L, 2916417413L, 2915188002L, 2917568801L, 2915153667L, 2913993552L, 2917447717L, 2916527795L, 2916468020L, 2915994937L, 2914636760L, 2917814127L, 2917625585L, 2915263253L, 2916617873L, 2917578067L, 2917090417L, 2915182686L, 2917769089L, 2916811126L, 2915150125L, 2916157152L, 2917701044L, 2915856552L, 2916372276L, 2916369455L, 2916334623L, 2915759658L, 2915760472L, 2915722365L, 2914804328L, 2917828603L, 2916512353L, 2915882601L, 2915508197L, 2915278436L, 2916169148L, 2917086792L, 2917094796L, 2917206527L, 2916353024L, 2916511592L, 2916658261L, 2916462321L, 2915743440L, 2915934858L, 2915871378L, 2915233443L, 2917845500L, 2914447768L, 2917805798L, 2917393371L, 2917096755L, 2915820707L, 2916876031L, 2915029256L, 2917823029L, 2916406451L, 2916411905L, 2917523961L, 2917498770L, 2915932074L, 2915287203L, 2916509469L, 2917843099L, 2915630636L, 2916905157L, 2916936874L, 2917442034L, 2914934216L, 2915945818L, 2916620467L, 2914323517L, 2914411176L, 2914484276L, 2914448950L, 2914368715L, 2914787377L, 2914469420L, 2914805892L, 2914775095L, 2914491407L, 2914393776L, 2914379592L, 2914465140L, 2914529453L, 2917598242L, 2914826872L, 2915928229L, 2917737679L, 2914918091L, 2917467265L, 2917434432L, 2914361206L, 2914460733L, 2917566967L, 2915910965L, 2914978949L, 2915909545L, 2915905015L, 2915788341L, 2914987982L, 2917814792L, 2916129679L, 2915009898L, 2914748654L, 2914972105L]

**Comment by dschow** [comment]
@TimLaw1 We're retiring the discussion forums. We have an announcement talking about our team's communication channels and the purpose of each one going forward. You can read about that here:
https://www.riotgames.com/en/DevRel/new-comms

Onto the issue you reported.

I can look into if you'd like as I agree there's some suspect behavior (at least for the handful of matches I looked at from your list). Specifically in the matches I looked at, it's suspicious that almost every player has been assigned NONE for their lane and DUO_SUPPORT for their role. Before I do spend time digging into this, I do want to clarify something first.

If you're asking for us to look into the suspicious behavior I mentioned above, I can definitely do that, but I would like to first confirm that you understand that both these values are **valid** and it's not uncommon for players to get labeled as such. It is uncommon, however, for all players in a match to get labeled with these values.

**Comment by riottuxedo** [comment]
@TimLaw1 We're retiring the discussion forums. We have an announcement talking about our team's communication channels and the purpose of each one going forward. You can read about that here:
https://www.riotgames.com/en/DevRel/new-comms

Onto the issue you reported.

I can look into if you'd like as I agree there's some suspect behavior (at least for the handful of matches I looked at from your list). Specifically in the matches I looked at, it's suspicious that almost every player has been assigned NONE for their lane and DUO_SUPPORT for their role. Before I do spend time digging into this, I do want to clarify something first.

If you're asking for us to look into the suspicious behavior I mentioned above, I can definitely do that, but I would like to first confirm that you understand that both these values are valid and it's not uncommon for players to get labeled as such. It is uncommon, however, for all players in a match to get labeled with these values.

**Comment by TimLaw1** [comment]
Yeah, Jungle gets "None" for role every time, and here is what stelar said:

This is not an issue.The role field is not the normal role that you might expect, from what ive gathered these are the values;NONE means that they didnt go in a lane DUO means that both of them farmed SOLO means they went alone to a lane DUO_CARRY means that there was 2 people in a lane, and this person farmed DUO_SUPPORT means that there was 2 people in a lane, and this person did not farm
--

**Comment by riottuxedo** [comment]
This is correct. The role indicates the role of the players in a specific lane. It is still really odd for everyone in the game to be labeled DUO_SUPPORT. I saw you closed and reopened this issue, let me know if you'd like like us to look into this.

**Comment by TimLaw1** [comment]
I know you guys are really busy so if you can't get around to it that's fine, but it does seem like a bug (i.e. your software is not supposed to do this at all but it's happening quite often)... I personally can work around the issue and my app is still in the stage of development where I am not super concerned with the size of training data. I think other people might want it to be fixed though.

**Comment by SleepyShoe** [comment]
I'm encountering this issue too. In some games, all 10 players receive DUO_SUPPORT.

Curious to know if any progress has been made on this?

**Comment by supergrecko** [comment]
Probably not high on the priority list. You can look into libraries which resolve this issue though.

Projects like https://github.com/Canisback/roleML or the Medium article https://medium.com/snipe-gg/using-unsupervised-machine-learning-to-assume-positions-in-league-of-legends-8eb142063ea6?sk=cd6d0f214feca14fdf8ac718e17d1346 can help you in the right direction.

**Comment by SleepyShoe** [comment]
Didn't know this existed. Going to look into implementing it, looks helpful. Thank you!

**Comment by RiotTuxedo** [comment]
As an update to this issue, we've mostly moved off these fields internally because of their inaccuracy. We're working to eventually expose additional fields that will should be more accurate.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported, feel free to re-open or comment if you feel this is in error.
