### ISSUE TITLE
[Feature Request] [LoR] Grabbing A Player's Collection

### ISSUE THREAD

**Issue by BlackTecno** [RiotGames/developer-relations#230]
I'm looking for a way for players to grab their entire collection and be able to either share it with a service or friends, either to show off their collection, or ask for help building a deck with the collection they have. 

I was thinking this could also be accessed through the local port similar to how an active deck is grabbed.

**Comment by CptMonkeyFist** [comment]
I would also like this feature. My brother had a decent idea of having a draft mode that you can play against friends, even without the expedition mode rewards and even if it only uses the cards in your collection. I would like to write an app that simulates draft using a player's card collection, but if it requires putting your _entire collection by hand_ then it isn't worthwhile. 
If the api made my collection available to me then I could export my collection, import it in my custom app, use my code to draft a deck from the cards in my collection, then export the code for the draft deck. Of course, if Riot wants to implement this "Expedition with friends" for me, then I suppose I don't need this feature. Although it would be good for deck building apps to determine which cards you need to purchase to finish the decks you design.

**Comment by stelar7** [comment]
+1

**Comment by mbo17210** [comment]
I also want an API call that would let me pull the user's collection. I've been working on an app to compare decklists with the user's collection to see if the deck is something they can make with the cards they have and, if not, what cards they are missing and possible replacement suggestions from the user's collection. It would make it much more convenient for both me and the user if they didn't have to put in their collection by hand

**Comment by Razviar** [comment]
I really support this feature request, access to player's collection is crucial for many different 3rd party services.

**Comment by RiotTuxedo** [comment]
This functionality now exists, but requires the developer to have an RSO client. We'll be providing documentation on these endpoints soon within the developer portal.
https://www.riotgames.com/en/DevRel/rso
