### ISSUE TITLE
[BUG] ddragon realms doesn't update

### ISSUE THREAD

**Issue by cohenu** [RiotGames/developer-relations#233]
**Describe the bug**  
https://ddragon.leagueoflegends.com/realms/euw.json stuck on 10.2.1

**Issue Description**  
`{
    "n": {
        "item": "10.2.1",
        "rune": "7.23.1",
        "mastery": "7.23.1",
        "summoner": "10.2.1",
        "champion": "10.2.1",
        "profileicon": "10.2.1",
        "map": "10.2.1",
        "language": "10.2.1",
        "sticker": "10.2.1"
    },
    "v": "10.2.1",
    "l": "en_GB",
    "cdn": "https://ddragon.leagueoflegends.com/cdn",
    "dd": "10.2.1",
    "lg": "10.2.1",
    "css": "10.2.1",
    "profileiconmax": 28,
    "store": null
}`

**Expected Result**  
new version 10.3.1 was released last week and should be updated in that endpoint

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
