### ISSUE TITLE
[BUG] [Missing DOC] Replay API

### ISSUE THREAD

**Issue by ekv88** [RiotGames/developer-relations#234]
**Replay API**  
In documentation link: https://developer.riotgames.com/docs/lol#game-client_replay-api
Text is celery saying that you need to add some lines in confing in order to enable replay API, but it's not stated which lines?

![image](https://user-images.githubusercontent.com/5781702/74368417-e6923080-4dd3-11ea-8337-7570f1f4bac4.png)

**Comment by RayZz-** [comment]
`EnableReplayApi=1` under the general section. you can just add it at the end of the general section so it should look something like this

```TOML
[general]
Height=1080
Width=1920
EnableReplayApi=1
```

**Comment by tisbells** [comment]
Closing out old issues, this was fixed https://developer.riotgames.com/docs/lol#game-client_replay-api
