### ISSUE TITLE
Ingame API Spectator Support

### ISSUE THREAD

**Issue by ADFX-01-Morgen** [RiotGames/developer-relations#237]
**Ideal Features:**
Player Data:
- All players current total gold
- All players runes
- All players champion stats

Events:
- Kill Events
     - Show damage contribution to kill (not just champion but drake, baron, and herald)
- Ward Placement and Kill Events
     - Location would also be nice but not needed
- Map Transform Event (ex. default to Infernal)

**Comment by c0derMo** [comment]
A big part of this is already possible, have a look at
[https://developer.riotgames.com/docs/lol#game-client-api](https://developer.riotgames.com/docs/lol#game-client-api)

This API does work while you spectate a game. Note, however, that not all of your recommended events are implemented / working right now. (For more info, have a look at #236)
