### ISSUE TITLE
THIRD-PARTY-CODE-V4 | 404 not found

### ISSUE THREAD

**Issue by ddragonDEV** [RiotGames/developer-relations#239]
I was testing the api in third party code and it didn't work, it just works for me with a pure id.

what should it be?
since I want to verify accounts

error 404 : 
![image](https://user-images.githubusercontent.com/37697754/74677125-59b1f300-5196-11ea-90a2-d41eaf5bf89a.png)

other account: 
![image](https://user-images.githubusercontent.com/37697754/74677259-954cbd00-5196-11ea-8372-90fc36ee6fa9.png)

**Comment by Querijn** [comment]
404 means that the code was not set. It sometimes needs a restart of the client. I assume you're Dragon on Discord? In that case we responded to your case, it's unlikely to be a bug. 

Also, your API key is supposed to be secret, don't share screenshots of it.

**Comment by DragooonDEV** [comment]
I have generated 3 times the api, and I have tried several systems to consume it, and even accounts.

So I don't understand what the process for user verification is like.
according to you everything should be fine, but I consult any user from any region and some generate the get and in others not.

**Comment by bbanothu** [comment]
> 404 means that the code was not set. It sometimes needs a restart of the client. I assume you're Dragon on Discord? In that case we responded to your case, it's unlikely to be a bug.
> 
> Also, your API key is supposed to be secret, don't share screenshots of it.
Hello, You said that the code was not. How do i generate a code so that I can add it my account? where do I get my third party verification code from???

**Comment by Querijn** [comment]
Do you mind not doing this? This is unnecessary, and not how you get help with the API.

**Comment by Jankec** [comment]
Hey!
Same issue here. I saved the verification code several times but the API returned 404 and I don't know why. It looks like the client has not saved the verification code.

**Comment by thomasmarton** [comment]
This issue was opened because the third-party-code endpoint is poorly documented and (s)he wanted to be able to understand how it works. It'll most likely be closed due to not being an actual issue.

If you want to learn more about the specific bug you're experiencing, check out #289 as the 404s and the 500s are related.

**Comment by RiotTuxedo** [comment]
This issue should get resolved with patch 10.15.

**Comment by RiotTuxedo** [comment]
This issue was resolved with patch 10.15 along with the issues reported in #289 and #323.
