### ISSUE TITLE
Data Dragon reports the wrong game versions (still 8.23.1 instead of 8.24.1)

### ISSUE THREAD

**Issue by torlenor** [RiotGames/developer-relations#24]
On the Data Dragon the files
https://ddragon.leagueoflegends.com/realms/euw.json
https://ddragon.leagueoflegends.com/realms/na.json
still report 8.23.1 instead of 8.24.1

Current JSON file is (here as an example from euw):
`{"n":{"item":"8.23.1","rune":"7.23.1","mastery":"7.23.1","summoner":"8.23.1","champion":"8.23.1","profileicon":"8.23.1","map":"8.23.1","language":"8.23.1","sticker":"8.23.1"},"v":"8.23.1","l":"en_GB","cdn":"https://ddragon.leagueoflegends.com/cdn","dd":"8.23.1","lg":"8.23.1","css":"8.23.1","profileiconmax":28,"store":null}`

**Comment by Querijn** [comment]
http://ddragon.leagueoflegends.com/api/versions.json is up to date though

**Comment by torlenor** [comment]
It seems they fixed it. Links are now showing 8.24.1 versions. Thanks Riot! :)

**Comment by riottuxedo** [comment]
Updating data dragon requires a manual step, so it is not always updated immediately after a patch is released. Please report any issues that exist more than a couple days after the patch is live in every region.
