### ISSUE TITLE
[BUG] [LOR] API endpoints stop responding

### ISSUE THREAD

**Issue by Razviar** [RiotGames/developer-relations#243]
LOR in-game API for some reason stops responding on any queries after some time. Right after game launch, it works perfectly, returning JSON on endpoints, but after several minutes into the match it just hangs. Any API endpoint is non responsive. After game restart it's back to normal again.

**Comment by tisbells** [comment]
Closing out old issues. No other reports on this issue. If you feel this is incorrect, feel free to comment or reopen.
