### ISSUE TITLE
[BUG]Cannot get "LeaguePoints" from API

### ISSUE THREAD

**Issue by jadeeeeh** [RiotGames/developer-relations#245]
I want to get the player's LeaguePoints from this link : "https://na1.api.riotgames.com/lol/league/v4/entries/by-summoner/"

The response code is 200 but response body is an empty list. Is there something wrong with that? What can I do to get players' LeaguePoints then?

**Comment by stelar7** [comment]
If the array is empty, the summoner is unranked or in placements.

**Comment by triffman33** [comment]
^^ also you should regen your api key before other people see it

**Comment by jadeeeeh** [comment]
> ^^ also you should regen your api key before other people see it

Thank you! I deleted the pic already since I got answer now. Thank you for reminding :D

**Comment by RiotTuxedo** [comment]
Should still regenerate your key if it wasn't a dev key.
