### ISSUE TITLE
[BUG][LOR] API static-decklist NullReferenceException on Expedition mode

### ISSUE THREAD

**Issue by Stanley1551** [RiotGames/developer-relations#246]
**Describe the bug**  
When requesting static-decklist while in an expedition mode match, the in-game API responds with HTTP 500 and a NullReferenceException stack trace.

**Expected Result**  
A similar response when requesting static-decklist when playing Ranked, VS AI, etc.

**Actual Result**  
The response body: https://pastebin.com/ZLE7FZsa
Postman screenshot: https://imgur.com/eRn59qk
In-game screenshot: https://imgur.com/ESCq1hN

**Developer Impact**
* Frequency: Every API call when the user plays expedition mode.
* Severity: When it happens, my application is unable to produce any meaningful information.

**Player Impact**
The player is not able to monitor their deck on any game in expedition mode.
* Frequency: Every time the player plays expedition mode and tries to monitor the deck.
* Severity: When this happens, my application is not able to use the monitoring feature.

**Preconditions**
* First condition: Third-party tools checkbox is ticked in the settings.

**Steps to reproduce**

1. Be in an expedition mode match.
1. Make static-decklist in-game API call.

**Comment by RiotTuxedo** [comment]
I've added this to the list of feedback we'll be passing along to the LoR team. Will follow up if I get any more info.

**Comment by tisbells** [comment]
Closing out old issues. No other reports on this issue. If you feel this is incorrect, feel free to comment or reopen.
