### ISSUE TITLE
[BUG] (Reopening) Spectator/active-game endpoint returning 404 in OCE whereas the player is ingame 

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#248]
Hey guys

(Reopening #165 )

The spectator endpoint in OCE returns http404 whereas the player was ingame 100% of the time.

Could you have a look please ?

Thanks :)

**Comment by stelar7** [comment]
@RiotR1cket

**Comment by RiotR1cket** [comment]
Thanks for the report, this was broken for a different reason than usual (misconfiguration following a hardware migration) and I believe I fixed it as of 4 hours ago from the timestamp of this message, please confirm and close or let me know if you're still seeing issues. I am going to double check our metrics tomorrow to make sure all game servers are still sending the data.

**Comment by trebonius0** [comment]
Yes, seems to be fixed
