### ISSUE TITLE
Unable to view API Key usage through the Developer Portal

### ISSUE THREAD

**Issue by Ares-C** [RiotGames/developer-relations#25]
It always returns "OH NO! THERE IS NO DATA TO DISPLAY FOR THE ABOVE FILTER(S)".

**Comment by vguzmanp** [comment]
The message is now "Failed to executed request" 😕

**Comment by RiotTuxedo** [comment]
This issue has been resolved.

**Comment by fitthienngoc** [comment]
My app details show "Region" is "none".
I don't see option for Method!
 I'm try "Run" in "API KEY USAGE" tab but it failed..
Support me please! Thanks you!
