### ISSUE TITLE
[BUG] SUMMONER-V4/getBySummonerName returns same identifiers for same player name but different region

### ISSUE THREAD

**Issue by davidchea** [RiotGames/developer-relations#251]
**Describe the bug**
https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerName returns same ```puuid```, ```accountId``` and ```id``` for the same player name but in a different region.

**Issue Description**  
I have these two URLs:

```https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/okusen```
```https://eun1.api.riotgames.com/lol/summoner/v4/summoners/by-name/okusen```

They just have the same player name and they are two different players from two different regions (**Europe West** and **Europe Nordic & East**).

Then, the two JSON responses respectively:
```
{
    "profileIconId": 4275,
    "name": "Okusen",
    "puuid": "KFM4xJBwzy7T-rytrj9J8lGx0QduGLsBJ-WY9xdx4Q9cZNvxXCSNv_k4YQdfPgQjS52ppwlO_f9vhA",
    "summonerLevel": 121,
    "accountId": "PsopchdPCOnlQJB4AjXZ6TCrHuEZ9JlMqZMrDP6iAtznGQ",
    "id": "zYkVlVUGHDuDmbfo1lmU0neHdpQdqxBNJ-hHMunqC__2K-4",
    "revisionDate": 1583882906000
}
```
```
{
    "profileIconId": 25,
    "name": "Okusen",
    "puuid": "KFM4xJBwzy7T-rytrj9J8lGx0QduGLsBJ-WY9xdx4Q9cZNvxXCSNv_k4YQdfPgQjS52ppwlO_f9vhA",
    "summonerLevel": 30,
    "accountId": "PsopchdPCOnlQJB4AjXZ6TCrHuEZ9JlMqZMrDP6iAtznGQ",
    "id": "zYkVlVUGHDuDmbfo1lmU0neHdpQdqxBNJ-hHMunqC__2K-4",
    "revisionDate": 1495766289000
}
```

**Expected Result**  
The ```puuid```, ```accountId``` and ```id``` should not be the same.

**Actual Result**
They have the same identifiers so this is incorrect.

**Player Impact**
Wrong information displayed by my app.

**Issue Comments**
I don't know what else to say, if you have any questions, please let me know.

**Comment by thomasmarton** [comment]
I believe you're missing a key piece of information here. Neither of those IDs are guaranteed to be unique. Those 2 accounts most likely belong to the same person and that person did a region transfer from EUNE to EUW.

summonerId and accountId are guaranteed to be unique on a per region basis. (so you won't find 2 summoners with the same ID on EUW)

PUUID is guaranteed to be unique globally but if a user transfers regions, the 2 accounts will have the same PUUID. 

So if you'd like to have unique IDs, you should prefix each of those with a region ID as well

**Comment by davidchea** [comment]
I know for sure it is not a region transfer because it is my brother's account (he is EUW).

It is very annoying because the request https://developer.riotgames.com/apis#tft-match-v1/GET_getMatchIdsByPUUID does not differentiate EUW and EUNE, we can only choose between ```europe```, ```asia``` or ```americas``` like this:

```https://europe.api.riotgames.com/tft/match/v1/matches/by-puuid/KFM4xJBwzy7T-rytrj9J8lGx0QduGLsBJ-WY9xdx4Q9cZNvxXCSNv_k4YQdfPgQjS52ppwlO_f9vhA/ids?count=20```

With this ```puuid```, it returns the EUW profile.

However, [LoLCHESS.GG](https://lolchess.gg/) does not seem to have this problem as they display different data for these two players so I probably miss something but I really don't know what.

**Comment by thomasmarton** [comment]
The TFT match endpoints have a different regional configuration. Specifically speaking about the TFT match endpoints, it will just group your matches. So both EUNE and EUW should appear there. Maybe lolchess does filtering on their end to compensate for the difference.

**Comment by davidchea** [comment]
https://developer.riotgames.com/apis#tft-match-v1/GET_getMatch

How do they do filtering as there is only the ```puuid``` to identify a player in a match?

**Comment by thomasmarton** [comment]
In TFT's case, every gameId is prefixed by the region they were played on

**Comment by davidchea** [comment]
Ohhh, I missed that. Thank you!
