### ISSUE TITLE
[BUG]`total_damage_to_players` returning 0 from TFT matches API

### ISSUE THREAD

**Issue by MMA15** [RiotGames/developer-relations#253]
All the match data returned for TFT from  GET `/tft/match/v1/matches/{matchId}` is returning a value of 0  for `total_damage_to_players`.

This started happening right after Set 3 was released.

We call this API very often for our site https://zelos.gg. We make challenges for League and TFT players were they can earn points and earn rewards based on very simple competitions, missions or achievements. Right now, with TFT `total_damage_to_players` returning 0, every player is getting a score of 0 and is complaining that their match is not being processed properly.  So the impact of this is pretty high for our site.

This data from a recent user and it shows 0 for `total_damage_to_players`
https://pastebin.com/n9Dd9rMJ

You can reproduce this issue everytime you input a matchId into `tft/match/v1/matches/{matchId}`

EDIT
This is also the case for `players_eliminated` field,  it is returning 0.

**Comment by RiotTuxedo** [comment]
Hey all, they're looking into this. They believe a fix should be in for patch 10.8.

**Comment by tisbells** [comment]
Closing old issues. No recent reports.
