### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when logging into riot portal on API Page

### ISSUE THREAD

**Issue by Okohedeki** [RiotGames/developer-relations#256]
**Description:**

When trying to log into the Riot Games Portal on the API page I get redirected to the logout page. The network tab shows that I am getting redirected to the logout page 40ish times. It looks like it repeats the request twice which can be seen in the network tab photo attached.

 This is only on the Riot Games API page, I am not having this issue on the mobile app, TFT app, client, or main page. 

Another thing is that after I log in and get the logout redirect error If I try and go back to the API page it sends me back to the logout page unless I clear all my cookies. If I clear my cookies it lets me go back to the main page

**What I tried**
1.) I have tried logging out of all Riot Portals and this did not solve the issue. 

2.) Incognito Mode. The same issue redirects to the logout page

3.) Clearing cookies on mobile and web browsers. 

4.) Mobile-only login - same issue. 

5.) Different computer - same issue.

**Steps to Reproduce**
Not sure how to reproduce this error on another machine.

I have attached a screenshot of the network tab and HAR JSON files with the data in the network tab. 

![Network Tab](https://user-images.githubusercontent.com/18506634/77261341-14785980-6c4b-11ea-8f84-04eefaf8dfbc.png)
[HAR file.zip](https://github.com/RiotGames/developer-relations/files/4366406/HAR.file.zip)

**Comment by RiotTuxedo** [comment]
Thanks for the report. Looking into this. Can I get your summoner name (Tuxedo) or riot id (Tuxedo#AYAYA)?

**Comment by Okohedeki** [comment]
My summoner name is IssaHawtCoco.

**Comment by Okohedeki** [comment]
My previous summoner name is richhoods. I do not believe I tried to sign into the api page using this summoner name but I may have long ago and do not remember

**Comment by RiotTuxedo** [comment]
Thanks, I'll look into it and post any updates here.

**Comment by RiotTuxedo** [comment]
Alright you should be good to go. Thanks for reporting your issue!
