### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by skyeskyest** [RiotGames/developer-relations#258]
**Issue Description**  
A clear and concise description of what the issue is.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.
I can't log it in to test my code, maybe i sent too many request before, so they banned me? That was a bug from my code, I already fixed it as well. Thanks

**Comment by bangingheads** [comment]
Are you receiving an error/error code? Are you having an issue with logging into the portal or using the endpoints on the portal?

**Comment by RiotTuxedo** [comment]
@skyeskyest Do you know your summoner name or riot id?
