### ISSUE TITLE
[DOCS][BUG] clash-v1.TournamentPhaseDto registration/startTime should be LONG (not INT)

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#259]
`TournamentPhaseDto.registrationTime` and `startTime` are reported as type `int`, but the values they contain are ~2^40, so they should be type `long` like other millisecond timestamps in the API.

Name | Data Type | Description
-- | -- | --
id | int |  
registrationTime | int |  
startTime | int |  
cancelled | boolean

**Comment by RiotTuxedo** [comment]
Yep it was meant to be. I must have done something wrong. I'll look into it.

**Comment by RiotTuxedo** [comment]
Docs updated.
https://developer.riotgames.com/apis#clash-v1/GET_getTournaments
