### ISSUE TITLE
[BUG] Api matchlist returning error 404 when have no games

### ISSUE THREAD

**Issue by rogervieiraa** [RiotGames/developer-relations#261]
**Bug Description**  
Api matchlist returning error 404 when have no games

**Problem Description**  
The api `/lol/match/v4/matchlists/by-account/{encryptedAccountId}`  , has an opitional parameter beginTime, my goal is  to return the newst games from an account, so I use the timestamp from the last game plus one.
Works fine if the player has news games, but with has no new games the api return error:
`{"status":{"status_code":404,"message":"Not found"}}`

**Expected Result**  
I expected to return a standart result but with no matches:
`{"matches":[],"startIndex":0,"endIndex":0,"totalGames":0}`

**Actual Result**  
`{"status":{"status_code":404,"message":"Not found"}}`

**Developer Impact**

* Frequency: Every API call for player who doesnt have new games
* Severity: When it happens, I need to do a special handle of events
* Cost: 0

**Player Impact**
My app isnt in production

**Preconditions**

* Player refresh match history page
* No new games was founded

**Repro Steps**

1. Call api `/lol/match/v4/matchlists/by-account/{encryptedAccountId}`
1. Send as parameter a timestamp for the last game plus one

**Issue Comments**

**Comment by KnutZuidema** [comment]
That's not necessarily a bug. 
From [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.5.4):
> The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource

If no games exist for the requested interval sending a 404 response is fine IMO.

**Comment by rogervieiraa** [comment]
Thank, I will close
