### ISSUE TITLE
BUG? spectate mode is disable

### ISSUE THREAD

**Issue by iremboztepe** [RiotGames/developer-relations#265]
i couldnt find any announcement for this so i assumed that it is a bug?

**Comment by kodbilenadam** [comment]
I would suggest using the ISSUE_TEMPLATE before opening an issue. We need to know "Steps to Reproduce" the issue and other information.

**Comment by RiotTuxedo** [comment]
This issue should now be resolved.
https://github.com/RiotGames/developer-relations/issues/266#issuecomment-614245571
