### ISSUE TITLE
Explenation for endpoint ' /lol/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}' is wrong

### ISSUE THREAD

**Issue by remco555** [RiotGames/developer-relations#267]
Endpoint ' /lol/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}'

Has the description : ChampionMasteryDTO - This object contains single Champion Mastery information for player and champion combination.

This is wrong because this is the description for the next endpoint for which you also need to add champion id. Please change it to

 ChampionMasteryDTO - This object contains all champion mastery entries sorted by number of champion points descending

**Comment by c0derMo** [comment]
In my opinion, the documentation is fine, the endpoint '/lol/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}' returns a _List_ of ChampionMasteryDTO's, as it's stated.

**Comment by MingweiSamuel** [comment]
The current documentation is correct, no change is needed:

> **Return value: List[ChampionMasteryDTO]**
> 
> **ChampionMasteryDTO** - This object contains single Champion Mastery information for player and champion combination.
