### ISSUE TITLE
[BUG] I've been given a Beta but the client doesn't recognize my account

### ISSUE THREAD

**Issue by AnatoliaMaster** [RiotGames/developer-relations#268]
**Bug Description**  
When I introduce my credentials, the game doesn't recognize my account as a beta holder.

**Problem Description**  
I just can't join the game.

**Comment by thomasmarton** [comment]
Unfortunately this issue tracker isn't for issues like yours. This tracker is for 3rd party developers (for example the builders of OP.GG or U.GG) who are interested in building apps, discord bots, websites, etc. around the Riot ecosystem and you won't be able to get help here.

I'd recommend going to https://support.riotgames.com/hc/en-us and selecting the game you're having issues with. They should be able to sort this out for you.
