### ISSUE TITLE
[Feature Request] [Valorant] In Depth Player Statistics 

### ISSUE THREAD

**Issue by Frazl** [RiotGames/developer-relations#269]
Hi, 

Thanks for taking the time for taking feature requests for the Valorant dev community. I have some ideas, most are probably already going to be done, but it helps in case they're not so here are some mini user stories.

I'd like to be able to query a player by ID and retrieve "generic" stats to build a dashboard of information of how they're progressing overtime.

I'd like to be able to query between unranked and ranked games.

I'd like to be able to have access to the same stats as are available in the post match screen available on an api endpoint including the cool tips you see at end of round about enemies blinded etc.

I'd like to be able to have Headshot information for a player within a game(something which I consider large and don't see yet unless it's hiding in the post game screen). 

I'd like to be able to pull positional information that happened during key events (i.e. kills, plants) and I would like to be able to request a map image that can be used to display this positional information. 

--

Some similar to #262 which is a great request! 

I would like a simple API for starting, stopping, creating, ending and resuming with a given state, a custom match. Obviously sometimes things go wrong when running tournaments and such so being able to tell the game to resume with this state is really nice. 

I would like to be able to run a custom game and read the all chat within that game. Again useful for commands like above. 

-- Other -- 

I'd love to see some form of aggregated stats on a stats screen within a menu if possible, I think it would be great and also great to have on an API! It'll save my puny VM instances :)  

I'd like to be able to give a user a hashed string of a crosshair and for them to be able to enter it within the game.

On an aside - I love the current statistics within the game of Valorant, my favorite is probably the best round highlight. I'm excited for match replies if and when they're coming so I can replay my best moments! I also cant wait to dig into all the data this game can possibly release 👍

**Comment by baimurzin** [comment]
is there Valorant API already we ca use?

**Comment by Frazl** [comment]
@baimurzin there's none yet released but you can request a production key for a valorant app. I also recommend the dev discord for the latest updates - https://discord.gg/riotgamesdevrel
:) 

From the valorant discord -
```
There are no APIs available for VALORANT just yet. We don't have a date either, but Riot said we won't be getting anything before the game launches worldwide. If you'd like to keep yourself up-to-date, I'd recommend turning on notifications for #announcements rather than periodically asking here.
```

**Comment by baimurzin** [comment]
@Frazl Thanks! 

what is a production key?  what is it for?

**Comment by thomasmarton** [comment]
The Riot API uses API keys to identify who you are and enforce your rate limits. We have 2 different types of API keys:
- Production API key: This is what you'd get for anything that wouldn't qualify for a personal key
- Personal API key: This is what you'd get if all you're looking for is a dev key that doesn't expire every 24 hours. (maybe a widget on your personal website, a command in your twitch chat rather than a public product anyone can use) These keys can't get higher rate limits as they are designed to help one, maybe 2 people out

**Comment by MRuy** [comment]
Valorant is released. Ranked is live. What about a API?

**Comment by Querijn** [comment]
Commented yesterday by Tuxedo: Working on them. Hope to have something soon, but there's a bunch of stuff demanding attention and we have to wait on other teams signing off on any dependencies we need to make these APIs public. Today office hours, meetings, and maybe app reviews. Yesterday handling emergent requests and updating TFT static data. We're close.

**Comment by tisbells** [comment]
Closing out old issues. This was resolved. Feel free to reopen or comment if you feel this is in error.
