### ISSUE TITLE
Tournament Stub V4 - createTournamentCode - Wrong documentation

### ISSUE THREAD

**Issue by prscampbell** [RiotGames/developer-relations#27]
https://developer.riotgames.com/api-methods/#tournament-stub-v4/POST_createTournamentCode
Example shows the allowedSummonersId as an object, where it should be an array.

**Comment by tisbells** [comment]
Closing out old issues. Tournament Stub V4 has been replaced with https://developer.riotgames.com/apis#tournament-stub-v5
