### ISSUE TITLE
[BUG] No API key usage reporting

### ISSUE THREAD

**Issue by MasterCassim** [RiotGames/developer-relations#273]
Looking at the API key usage reporting, I always get the following message: 

-> **OH NO! THERE IS NO DATA TO DISPLAY FOR THE ABOVE FILTER(S)**

Although I'm clearly making queries successfully. The HTTP request to the /metrics endpoint returns the following error message:

-> "reason": "unable to authenticate user [svc-devrel] for REST request [/last_24h/_search]"

Is this a known bug?

**Comment by RomainJMend** [comment]
Same for me. Id be interested to see how to solve this too.

**Comment by lucasMesquitaBorges** [comment]
Hey, this resource was deactivated.
