### ISSUE TITLE
[BUG] Can't use Replay API on Garena

### ISSUE THREAD

**Issue by Hobfest** [RiotGames/developer-relations#274]
**Bug Description**  
League director cannot be used 

**Problem Description**  
After adding EnableReplayApi=1 on [general] they league director or the FPS cam tool does not work/ does not show 
I attempted to repair league. Still no results
Reinstalled league. still no results. the League director does not work 

**Expected Result**  
after i put EnableReplayApi=1 i expect the camera tool to work.

**Actual Result**  
The camera tool does not show or work 

**Developer Impact**
as a video editor. it affects my projects and videos

**Player Impact**
as a content creator it discourages content creators to create more content for league of legends 

* Severity: When this bug happens, a user is unable to use the camera tool 

* Quantity: so far there are few players experiencing this issues 
* Region: This affects players in Garena Server so far 
* Etc

**Preconditions**

* First condition
* Second condition

**Repro Steps**

1. Step 1
1. Step 2

**Issue Comments**
Please fix as soon as possible please.

**Comment by tisbells** [comment]
Closing old issues. Garena is no longer supported.
