### ISSUE TITLE
[Feature Request][In-game API] Add championId field to allPlayers

### ISSUE THREAD

**Issue by xEcEz** [RiotGames/developer-relations#276]
**Feature description**
Add the `championId` field to the `allPlayer` array, as it is the only consistent identifier for a given champion. 

Currently we need to rely on the `championName` field and perform a lookup to get the corresponding `championId`. Given that the names are actually localized based on the client's language, this is really messy.

**Comment by lucasMesquitaBorges** [comment]
This issue is old and I'm not sure of the current status of the existing endpoint, or if this field was added.

Unfortunately DevRel can't take action in issues or feature requests for Game Client APIs. This is mentioned in the docs: https://developer.riotgames.com/docs/lol#league-client-api

> NOTE: We provide no guarantees of full documentation, service uptime, or change communication for unsupported services. This team does not own any components of the underlying services, and will not offer additional support related to them.

**Comment by geozukunft** [comment]
This issue talks about the Ingame API also known as the Live Client Data API which is listed under the section of Game Client APIs and not League Client APIs under which the not for no support is listed. 

As the topic of this feature request is specifically about https://developer.riotgames.com/docs/lol#game-client-api_live-client-data-api and not the League Client API known by everyone as LCU which obviously is not supported and never has been. Does this mean now that the Ingame API which looking back at past times or now on the docs website does not have a specific disclaimer about not having any support is officially unsupported (and use at your own risk) and with that setting the documentation on the DevPortal as incorrect?
![image](https://github.com/RiotGames/developer-relations/assets/20288857/2f3319e4-16a2-4bcf-b716-c7d13f8f906b)
