### ISSUE TITLE
Undocumented feature for matchlists/by-account end point?

### ISSUE THREAD

**Issue by snowst** [RiotGames/developer-relations#28]
v3 and v4  matchlists/by-account end point works with only a begindate optional parameter supplied even though the documentation says it won't. Also the one week max range is not being adhered to, it's returning everything after that date range. Is this an undocumented feature that we can rely on or an accident? If it was a feature, the API documentation should be updated and acknowledged.

**Comment by RiotTuxedo** [comment]
Yep the Implementation Details for the getMatch endpoint do say this. These were the behaviors indicated to us when we originally released matchlist. At this point I would expect that this behavior will continue to remain. Specifically, there's no one week limitation and the endpoint will return matches if only a beginTime is provided without an endTime.

**Comment by RiotTuxedo** [comment]
The documentation on the reference page has been updated. As such, I'm considering this issue resolved. Let us know if there's anything else.

**Comment by RiotTuxedo** [comment]
Two new issues related to this have since popped up; #48 and #50. The documentation on this has been further clarified.
