### ISSUE TITLE
[Question] Linking games in my DB to the ones returned by Riot API callback

### ISSUE THREAD

**Issue by asivaneswaran** [RiotGames/developer-relations#280]
**Question**  
I am working on a project that will use the tournament API and create match codes for a tournament. I created the tournament provider got the tournament code and was able to get the matches code. My issue is on the callback from Riot. I am lost on how to link the game from the callback to the ones in my database. Is `shortCode` the same as the `match id/code` that I got earlier?

Thanks,

**Comment by thomasmarton** [comment]
This repository is for bug reports and feedback on the APIs Riot offers, not really for questions like yours.
I'd recommend joining the discord server Riot has with a giant 3rd party developer community: https://discord.gg/riotgamesdevrel

PS: shortCode is the tournament code

**Comment by asivaneswaran** [comment]
Hey thanks, I tried joining the discord before posting but I don't have access to any channels :(

**Comment by Querijn** [comment]
What's your discord user name? Let me check what's up

**Comment by asivaneswaran** [comment]
@Querijn It's Phenom
