### ISSUE TITLE
Can't have my email verified and access to the Riot Games Developer Portal

### ISSUE THREAD

**Issue by CarlosTerrades** [RiotGames/developer-relations#283]
I dont know if this is the place to ask for help but i already tried the support twitter and looked for some support email but got no response.

Basically, i created my Riot account some days before the Valorant Twitch Drops started and now i have been trying to enter the Devs Portal but it says my email is not verified yet. I click the "re-send email" and nothing arrives to my mail and of course, nothing arrived back when i created my account in the first place. Spam box checked.

My Riot username is: imcolorblindsry

I would love to have some help here. Thank you.

**Comment by RiotTuxedo** [comment]
This is unfortunately the wrong place :( I believe player support is taking a little longer due to the certain circumstances. You should get a response and they should be able to help you.
