### ISSUE TITLE
[BUG] Astronaut Teemo shows wrong splash image

### ISSUE THREAD

**Issue by Susko3** [RiotGames/developer-relations#284]
**Bug Description**  
Astronaut Teemo skin shows default Teemo splash image.

**Problem Description**  
The splash art located at [https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_4.jpg](https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_4.jpg) shows regular Teemo, but the splash is for the Astronaut Teemo skin (skin 4)

I first noticed the issue at the [Teemo champion page](https://eune.leagueoflegends.com/en-pl/champions/teemo/). If you scroll to skins, the Astronaut Teemo skin shows regular splash art.

Digging more, I downloaded the latest dragontail. In `dragontail-10.9.1/img/champion/splash/Teemo_4.jpg` and `dragontail-10.9.1/img/champion/tiles/Teemo_4.jpg` Astronaut Teemo is still shown as the default splash. Strangely, in `dragontail-10.9.1/img/champion/loading/Teemo_4.jpg` Astronaut Teemo is shown correctly.

**Expected Result**  
All of the Astronaut Teemo images show Astronaut Teemo.

**Actual Result**  
Some of the Astronaut Teemo images show the default Teemo art.

**Developer Impact**

* Frequency: Every API call, since this is a static image always served the same.
* Severity: When it happens, the wrong image is displayed.

**Player Impact**

* Frequency: Every time the user visits the [OFFICIAL leagueoflegends.com](https://eune.leagueoflegends.com/en-pl/champions/teemo/) site, they experience this issue.
* Severity: When this bug happens, the wrong image is displayed.
* Quantity: All of the players who visit the site experience the issue.
* Region: This affects players in all regions.

**Preconditions**

* Working internet connection

**Repro Steps**

1. Visit https://eune.leagueoflegends.com/en-pl/champions/teemo/
1. Scroll to skins
1. Observe the wrong image displayed for Astronaut Teemo

**Issue Comments**

No additional comments.

**Comment by loveteamore** [comment]
"dragontail-10.10.3208608.zip" also includes the issue.

Pulsefire Ekko
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ekko_28.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_28.jpg

Pulsefire Fiora
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Fiora_41.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiora_41.jpg

Pulsefire Lucian
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Lucian_18.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_18.jpg

Pulsefire Lucian Prestige Edition
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Lucian_19.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_19.jpg

Pulsefire Pantheon
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Pantheon_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pantheon_16.jpg

FPX Thresh
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Thresh_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_15.jpg

Lunar Goddess Diana
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Diana_2.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_2.jpg

Toxic Dr. Mundo
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/DrMundo_1.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_1.jpg

Cottontail Fizz
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Fizz_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fizz_8.jpg

Demacia Vice Garen
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Garen_14.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_14.jpg

Bewitching Janna
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Janna_13.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_13.jpg

Worldbreaker Maokai
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Maokai_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Maokai_16.jpg

Blood Moon Pyke
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Pyke_9.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_9.jpg

PROJECT: Pyke
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Pyke_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_16.jpg

Astronaut Teemo
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Teemo_4.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_4.jpg

Lancer Stratus Wukong
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/MonkeyKing_6.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MonkeyKing_6.jpg

Imperial Xin Zhao
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/XinZhao_2.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/XinZhao_2.jpg

**Comment by Querijn** [comment]
I recommend working around this issue by using an alternative external source - https://www.communitydragon.org/

You can find all game and client files here - straight from the source, the game itself. You can report any bugs here: https://discord.gg/yNFG5yk

**Comment by RiotTuxedo** [comment]
Team is aware and I believe this will be resolved in the next release of ddrag.

**Comment by Susko3** [comment]
I've checked https://ddragon.leagueoflegends.com/cdn/dragontail-10.11.1.tgz
The issue is fixed!
