### ISSUE TITLE
[BUG] TotalPlayerScore always null

### ISSUE THREAD

**Issue by leonardossattin** [RiotGames/developer-relations#285]
Hello!
I noticed that the TotalPlayerScore of my matches are always zero, is that a issue?

**Comment by Querijn** [comment]
Hey there!

Nope. This is a variable used for a gamemode called Dominion, which was removed many years ago. You won't find a dominion match in the history since it only goes back two years exactly.

**Comment by leonardossattin** [comment]
Oooh, ok. Thanks!
Is there a variable that i can use to get the rank after match? Like S+, B-, etc?

**Comment by stelar7** [comment]
That info is considered private by Riot, and as such is not returned in the API

**Comment by leonardossattin** [comment]
Ok, thanks ^^
