### ISSUE TITLE
[BUG][DOCS] Missing field in docs

### ISSUE THREAD

**Issue by whyando** [RiotGames/developer-relations#288]
**Bug Description**  
The field "game_variation" is not documented on developer.riotgames.com/apis#
for the tft-match-v1 endpoint

Here is a sample of real api response which includes game_variation
```
"info": {
        "game_datetime": 1587749742531,
        "game_length": 2275.833984375,
        "game_variation": "TFT3_GameVariation_BigLittleLegends",
        "game_version": "Version 10.8.317.8137 (Apr 17 2020/16:09:11) [PUBLIC] <Releases/10.8>",
        "participants": [       ...
```

However this field is not documented at https://developer.riotgames.com/apis#tft-match-v1/GET_getMatch

**Developer Impact**
low

**Player Impact**
low

**Preconditions**
every time (since set 3)

**Comment by MingweiSamuel** [comment]
https://github.com/MingweiSamuel/Riven/issues/9
https://github.com/MingweiSamuel/riotapi-schema/commit/195f9b309c74a052d292020dbd958d747a9fe849

**Comment by RiotTuxedo** [comment]
The documentation has been updated with this field.
https://developer.riotgames.com/apis#tft-match-v1/GET_getMatch
