### ISSUE TITLE
[BUG] Third party code endpoint is returning http500 (RU & EUW)

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#289]
100% of the calls to the third party code endpoint is returning http 500 in RU and EUW 
The issue seems to have started May 5th at 7pm CET.

It prevents user from validating their accounts on my websites. 

Could you check what is going on ?

Thanks !

**Comment by FlorianMifsud** [comment]
https://developer.riotgames.com/api-status/ => is ok but still down

**Comment by HeuHax** [comment]
Seems to be working now after many days with problems. Can you confirm? @trebonius0

**Comment by FlorianMifsud** [comment]
> Seems to be working now after many days with problems. Can you confirm? @trebonius0

EUW its ok thanks

**Comment by trebonius0** [comment]
Http500 seem to have dropped quite a lot. 
But I'm now seeing them in BR, LAN and LAS

**Comment by Sircretions** [comment]
I'm getting reports of this in LAS, has this been fixed for just EU?

**Comment by RiotTuxedo** [comment]
As of 8am PT, this issue should now be resolved.

**Comment by molenzwiebel** [comment]
Looks like this might be broken again. I am getting multiple reports of it not working, and I can personally confirm that EUW continues to return 404 for my account even after setting a code and restarting/re-entering the code a bunch of times.

**Comment by HeuHax** [comment]
Yep - i'm seeing this as well!

**Comment by castanhob** [comment]
It is also returning 404 for BR, same issue.

**Comment by Fistashk0** [comment]
Still now works. Got 404 every response.

**Comment by castanhob** [comment]
Can something be done about this? We don't want to rely on icon change to verify accounts like many other platforms. :disappointed:

**Comment by Xorboo** [comment]
Subscribed, would be glad if someone could fix that

**Comment by SquirePug** [comment]
This has affected our High School League in Australia. Our entire sign up flow is broken and students can not be enrolled into teams without us essentially undoing our entire authorisation process.

How long is this going to stay broken?

**Comment by HeuHax** [comment]
@SquirePug we changed the verification flow to use Summoner Icon instead - much easier and most importantly, stable :)

**Comment by SquirePug** [comment]
Given its not designed for that, I would hardly call using an unrelated API call to achieve a non-intednded outcome, is far from stable.

**Comment by HeuHax** [comment]
You can call it what you want, but the matter of fact is that the current situation is not stable and hasn't been for a long time. This endpoint is super important and if you can't rely on it, it's basically useless. We've lost around 7000 users due to this. I for one am not going back until i know for certain it's not going to break randomly at every small patch.

**Comment by TheRazvy** [comment]
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data. For EUNE

**Comment by summonerriftofficial** [comment]
same issue here

**Comment by LambertArno** [comment]
We are experiencing the exact same issue. We've lost many users to this issue, so it would be nice to have this resolved as quickly as possible.

**Comment by raziEiL** [comment]
RU returning 404

**Comment by FlorianMifsud** [comment]
> RU returning 404

EUW1 too

**Comment by ChronoBrake** [comment]
EUN1 return 404 ...

**Comment by Querijn** [comment]
We're aware this happens on every single region. Please stop posting if it happens to you too, because it happens to everyone, on every region. Your comments aren't helping.

**Comment by molenzwiebel** [comment]
As per Querijn's own recommendation, posting a comment to ensure that this keeps getting attention. It's officially been a month since the endpoint broke, and while I understand that with COVID and the endpoint being a hack on top of a hack it's not the easiest to fix, it's franky getting ridiculous that an official endpoint can be broken for so long with barely any updates.

**Comment by MitchellRomney** [comment]
Verifying ownership of a Summoner is a core part of the on-boarding for my web application. I had to search around to find this thread, outlining that this endpoint has been down for over a month now with no indication of this through the API endpoint or anywhere else.

Is there any updates on the progress of this? If it may still be many weeks before this can be addressed, I'll need to figure something else out in the mean time.

**Comment by RiotTuxedo** [comment]
Update here. brimil01 was able to look into this issue and helped submitted a change that we hope will resolve the problem.

**Comment by LambertArno** [comment]
@RiotTuxedo So when will this fix be live?

**Comment by Querijn** [comment]
This is, if the review is accepted, in the next game patch. If the default release cycle is upheld, it will happen between the 21st and the 22nd of July, 2020. Specifically for EUW, this would be the night between the 21st and the 22nd.

**Comment by RiotTuxedo** [comment]
Patch 10.15 just completed in OCE and so far third-party-code-v4 is working as expected. I'll continue to check the other regions as the patch rolls out.
