### ISSUE TITLE
[BUG] Incorrect Splash Art for Lunar Goddess Diana

### ISSUE THREAD

**Issue by JustNrik** [RiotGames/developer-relations#292]
**Bug Description**  

The end point: `http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_2.jpg` returns the default skin of Diana instead of Lunar Goddess.

**Problem Description**  

Explained above

**Expected Result**  

Lunar Goddess Diana Spalsh Art

**Actual Result**  

Default Splash Art

**Developer Impact**

Hard to debug since I can't check every single skin of the game to see if it's correct

**Player Impact**

Misinformation

**Preconditions**

None

**Repro Steps**

1) goto `http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_2.jpg`

**Issue Comments**

None, just fix it

**Comment by MingweiSamuel** [comment]
#284 probably related
