### ISSUE TITLE
[BUG] ddragon for 10.10.1 doesn't exist

### ISSUE THREAD

**Issue by loveteamore** [RiotGames/developer-relations#295]
**Bug Description**  
there is no data for version 10.10.1.

**Problem Description**  
"versions.json"
https://ddragon.leagueoflegends.com/api/versions.json

**Expected Result**  
・versions.json
["10.10.1","10.9.1","10.8.1","10.7.1","10.6.1","10.5.1","10.4.1","10.3.1","10.2.1","10.1.1","9.24.2"...]
・dragontail-10.10.1.tgz
https://ddragon.leagueoflegends.com/cdn/dragontail-10.10.1.tgz

**Actual Result**  
・versions.json
["10.10.3208608","10.9.1","10.8.1","10.7.1","10.6.1","10.5.1","10.4.1","10.3.1","10.2.1","10.1.1","9.24.2"...]

**Comment by thomasmarton** [comment]
This change has been announced before, but it was put on hold.
https://twitter.com/RiotGamesDevRel/status/1238229162336202752

**Comment by loveteamore** [comment]
thank you for the notice.
