### ISSUE TITLE
[DOCS][BUG] LOR SEA region, VAL new platforms

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#296]
![lor-ranked-v1 SEA platform](https://cdn.discordapp.com/attachments/187652476080488449/710641116906520607/unknown.png)

[lor-ranked-v1.getLeaderboards](https://developer.riotgames.com/apis#lor-ranked-v1/GET_getLeaderboards) is showing a `SEA` region (south east asia I assume). Maybe its appearance is a mistake, but if not it is missing from the [regional routing values list](https://developer.riotgames.com/docs/lol#_regional-routing-values). (Also this list is only in the LoL section when it also applies to LoR and TFT).

**Comment by RiotTuxedo** [comment]
With the launch of Legends of Runeterra, the team has chosen to expose the ranked leaderboard for the SEA region. I'll make sure to update the docs.

**Comment by MingweiSamuel** [comment]
Also posting VAL's new platforms: `"APAC" | "BR" | "EU" | "KR" | "LATAM" | "NA" | "PBE1"` so we don't need to create a new issue

**Comment by MingweiSamuel** [comment]
And for people's reference here are the different region sets used by the endpoints:
```
br1 | eun1 | euw1 | jp1 | kr | la1 | la2 | na1 | oc1 | ru | tr1
br1 | eun1 | euw1 | jp1 | kr | la1 | la2 | na1 | oc1 | pbe1 | ru | tr1
americas | asia | europe | sea
americas | asia | europe
americas
apac | br | eu | kr | latam | na
```

**Comment by MingweiSamuel** [comment]
For people's reference here are the region sets and their endpoints:
```json
{
  "br1 | eun1 | euw1 | jp1 | kr | la1 | la2 | na1 | oc1 | ru | tr1": [
    "champion-mastery-v4",
    "champion-v3",
    "clash-v1",
    "league-exp-v4",
    "league-v4",
    "match-v4",
    "spectator-v4",
    "summoner-v4",
    "tft-league-v1",
    "tft-summoner-v1",
    "third-party-code-v4"
  ],
  "br1 | eun1 | euw1 | jp1 | kr | la1 | la2 | na1 | oc1 | pbe1 | ru | tr1": [
    "lol-status-v3"
  ],
  "americas | asia | europe | sea": [
    "lor-ranked-v1"
  ],
  "americas | asia | europe": [
    "tft-match-v1"
  ],
  "americas": [
    "tournament-stub-v4",
    "tournament-v4"
  ],
  "apac | br | eu | kr | latam | na": [
    "val-content-v1",
    "val-match-v1"
  ]
}
```

**Comment by tisbells** [comment]
Closing out old issues. SEA serves as the correct shard for LoR APAC (previously Asia + SEA) and this is documented in the endpoint. Feel free to reopen or comment if you feel this is in error.
