### ISSUE TITLE
[BUG] "current..." field in participantIdentities are wrong and misleading

### ISSUE THREAD

**Issue by karaeren** [RiotGames/developer-relations#299]
**Bug Description**  
There are some summoners that transferred their accounts hence they got new accountId's. I found that, when looking at the match data, the "current..." fields such as "currentAccountId" does not represent the real value all the time.

**Problem Description**  
When you get a summoner on SummonerV4 and use the accountId on /lol/match/v4/matchlists/by-account/ to get the match list of that summoner, you can get games on different regions, which is expected. But the issue is when you parse a game from a different region to where the user is, things get clunky. Here are some of the problems I have encountered so far:
1. User transfers from A region to B region, resulting in accountId and platform change. When you query the games of the user played on A region, you can get the old accountId and platform on all the respected fields (accountId, currentAccountId, platformId, currentPlatformId). I have seen this issue on a friend's matches who **recently** transferred from TR to EUW. The said issue I encountered is from a game from 2 months ago (TR, gameId=970492794).
1. User transfers from A region to B region, resulting in accountId and platform change. When you query the games of the user played on A region, you can get the accountId and platformId user had previously on the "current" fields (currentAccountId, currentPlatformId) and the "actual current" values on the default field (accountId, platformId). Not sure if this is a bug because the current in there might have been a reference to the time where the game was played but it's definitely misleading. The said issue I encountered is from a game from 1 year ago (EUW, gameId=4019805185)

**Expected Result**  
accountId and platformId on each participant on participantIdentities on a match object to give the accountId and the platformId of the summoner when the game was played.
currentAccountId and currentPlatformId on each participant on participantIdentities on a match object to give the accountId and the platformId of the summoner as of right now.

**Developer Impact**

* No Data: Basically removes the data of the summoners when they transfer to a different region, or at best, makes it harder to parse the data. Sometimes it becomes impossible to identify a participant (example 1 on problem description).

**Player Impact**

* No Data: On a site about where the past data is parsed and analyzed, players lose a significant amount of data of their own...

**Preconditions**

* User plays on region A
* User transfers to region B

**Repro Steps**
1. Get a Summoner object on SummonerV4 for a user that has transferred recently (for my tests, 2 months to 1.5 years, but probably applies to wider range of people)
1. Get their accountId
1. Get their entire matchlist with the accountId
1. Get each match and check participantIdentities for accountId

**Comment by RiotTuxedo** [comment]
Thanks for the detailed report. Was super helpful. I agree it might be confusing that the fields are prefixed with `current`. In the future, I expect that most services will key off a player's puuid instead of their account or summoner id, so hopefully we can avoid the confusion of region transfers.

**Comment by ERENKYI** [comment]
> Thanks for the detailed report. Was super helpful. I agree it might be confusing that the fields are prefixed with `current`. In the future, I expect that most services will key off a player's puuid instead of their account or summoner id, so hopefully we can avoid the confusion of region transfers.
> 
> That being said, I don't want to change the current response structure for this endpoint while it's in use just to resolve this confusion. I'll add documentation to clarify this and hopefully we'll eliminate this issue completely in future iterations of the match history service.

That's nice to hear. But what about the first issue where both fields (current and default) showing the old values (before region transfer)? Is this some sort of a caching issue (since the only example is in a 2 months old game) and will it be getting a fix in the near feature?

**Comment by RiotTuxedo** [comment]
The `currentAccountId` will be the accountId of the player when the game was played. The `accountId` is the original accountId before server transfers. I've updated the documentation to better reflect this.
https://developer.riotgames.com/apis#match-v4/GET_getMatch
