### ISSUE TITLE
Multiple match-v3 endpoints missing from the API key usage graph

### ISSUE THREAD

**Issue by Derpthemeus** [RiotGames/developer-relations#3]
The API usage chart under https://developer.riotgames.com/apps is missing most of the methods under the match-v3 API. Requests made to any match-v3 endpoint will be counted in the graph when filtering is disabled, but when filtering is set to match-v3, only requests made to the `/lol/match/v3/matchlists/by-account/{accountId}` endpoint will be counted.

Migrated from https://discussion.developer.riotgames.com/questions/5519/methods-missing-from-the-api-usage-graph.html

**Comment by Syavel** [comment]
Seems like it's not working for v4 : i did some requests to  /lol/match/v4/matches/{matchId} / /lol/match/v4/matchlists/by-account/{encryptedAccountId} / /lol/summoner/v4/summoners/by-name/{summonerName} and i got no results at all 
![image](https://user-images.githubusercontent.com/32241006/49410365-94339980-f764-11e8-92e0-0cf1b02c45b3.png)

**Comment by tisbells** [comment]
Closing out old issues, matchV3 no longer supported
