### ISSUE TITLE
[Account] I can`t login

### ISSUE THREAD

**Issue by hanbeon** [RiotGames/developer-relations#300]
**Account Information**
Region : KOR
ID : whdans4141
Summoner Name : Hanbeon

**Issue Description**  

I had a development token for my ID a few months ago and used api.
I recently tried to develop again using the API, but I can't log in.
When I logged in, I attached an alert window that was displayed.

"INVALID ACCOUNT"
"You`ve logged in successfully, but your account is in a funky state so we need to take a look."
"We`re sorry about the inconvenience."

What more do I need to do to fix this?

**Comment by thomasmarton** [comment]
In case anyone comes across the same issue, here's a few things you can do:
- Double check that your email has been verified
- Make sure you have a summoner name set (even if you don't plan on using the LoL APIs)
- Make sure you play through all the tutorial levels in league (even if you don't plan on using the LoL APIs)
This usually resolves a good chunk of account related issues.
