### ISSUE TITLE
[BUG] [CRITICAL]

### ISSUE THREAD

**Issue by galo00** [RiotGames/developer-relations#301]
**Bug Description**  
I try to enter games and it does not allow me instead of entering it it sends me critical error messages

**Problem Description**  
I try to enter games and it does not allow me instead of entering it it sends me critical error messages

![Anotación 2020-05-25 041337](https://user-images.githubusercontent.com/65894884/82799558-d7ddff80-9e3f-11ea-8e2f-8a5d85b514aa.png)
![Anotación 2020-05-25 041405](https://user-images.githubusercontent.com/65894884/82799559-d8769600-9e3f-11ea-9dd3-370965aa921f.png)
![Anotación 2020-05-25 041255](https://user-images.githubusercontent.com/65894884/82799560-d90f2c80-9e3f-11ea-97fa-e948198fc64d.png)

**Comment by Querijn** [comment]
Close cheat engine

**Comment by Querijn** [comment]
Also this is not the place for your question

**Comment by galo00** [comment]
I don't have a cheat engine,
srry I did not know that :/
