### ISSUE TITLE
[BUG] match history site stopped working due to new ddragon versioning

### ISSUE THREAD

**Issue by iaace-NA** [RiotGames/developer-relations#302]
**Bug Description**  
https://matchhistory.na.leagueoflegends.com/en/ shows a blank page. Attempting to load a match history link to a specific match also loads a blank page. The page attempts to load dragonmagic.js at https://ddragon.leagueoflegends.com/cdn/10.10.32161768608/js/dragonmagic.js `403`.

**Expected Result**  
Match history list or Match information

**Actual Result**  
Blank page.

**Player Impact**
* Frequency: Every time the user visits the site, they experience this issue.

**Comment by tisbells** [comment]
Closing old issues, this site is no longer supported.
