### ISSUE TITLE
[BUG] TFT set3 traits.json missing data

### ISSUE THREAD

**Issue by Canisback** [RiotGames/developer-relations#305]
**Bug Description**  
Field "style" on brawler last rank is missing.

**Problem Description**  
We are missing some data.

**Expected Result**  

`
    "sets": [
      {
        "style": "bronze",
        "min": 2,
        "max": 3
      },
      {
        "style": "gold",
        "min": 4
      }
    ]
`

**Actual Result**  

`
    "sets": [
      {
        "style": "bronze",
        "min": 2,
        "max": 3
      },
      {
        "min": 4
      }
    ]
`

**Developer Impact**
Need to update manually the file.

**Player Impact**
None

**Preconditions**
None

**Repro Steps**
1. Download the set3.zip : https://static.developer.riotgames.com/docs/tft/set3.zip
1. Look at the traits.json file

**Issue Comments**
None

**Comment by RiotTuxedo** [comment]
Thanks for the report. This should now be resolved.
