### ISSUE TITLE
[BUG] CDN Images

### ISSUE THREAD

**Issue by shawkitajima** [RiotGames/developer-relations#308]
**Bug Description**  
http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_8.jpg
returns same image as
http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_13.jpg

**Problem Description**  
Wrong image is being returned by cdn

**Expected Result**  
http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_13.jpg should return Bewitching Janna

**Actual Result**  
http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_13.jpg returns Sacred Sword Janna

**Developer Impact**

* Frequency: Every API call
* Severity: Minimal
* Cost: Low
* Efficiency: None
* User emails: None

**Player Impact**

* Frequency: Every time the user visits the site, they experience this issue. 
* Severity: Minimal
* Quantity: Minimal
* Region: All users

**Comment by shawkitajima** [comment]
This issue also affects the skins in league's website:
https://na.leagueoflegends.com/en-us/champions/janna/

**Comment by MingweiSamuel** [comment]
#284 #292 Appears to be fixed with the new ddragon release for 10.11

**Comment by RiotTuxedo** [comment]
I believe this issue has been resolved. If you're still experiencing problems, please leave a comment in the issue otherwise I'll be closing this out as solved in the next week.
