### ISSUE TITLE
[BUG] bugs on ddragon 10.11.1

### ISSUE THREAD

**Issue by loveteamore** [RiotGames/developer-relations#309]
**Bug Description**  
・dead link in https://developer.riotgames.com/docs/lol#data-dragon
・incorrect images in dragontail-10.11.1.tgz

**Actual Result**  
dead link: "Latest https://ddragon.leagueoflegends.com/cdn/dragontail-10.11.1.zip"

Astronaut Bard
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Bard_8.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_8.jpg

Astronaut Gnar
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Gnar_15.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gnar_15.jpg

Astronaut Poppy
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Poppy_16.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Poppy_16.jpg

The Thousand-Pierced Bear
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_6.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Volibear_6.jpg

Volibear
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_0.jpg

Thunder Lord Volibear
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_1.jpg

Northern Storm Volibear
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_2.jpg

Runeguard Volibear
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_3.jpg

El Rayo Volibear
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_5.jpg

**Developer Impact**
Frequency: Every API call.

**Comment by RiotTuxedo** [comment]
I believe this issue has been resolved. Let us know if you find any others.
