### ISSUE TITLE
Developer Portal doesn't lets you use arrays for parameters with Set[type] type

### ISSUE THREAD

**Issue by ERENKYI** [RiotGames/developer-relations#31]
For example, while making a matchlist call, you can't use multiple queueId's on the portal.

**Comment by stelar7** [comment]
fixed with the update? @RiotTuxedo

**Comment by FiniteRealityTech** [comment]
I'm finishing up another project at the moment. I'm glad to know it's fixed. If it's still a problem, I will return and describe the issue. Thank you!

**Comment by RiotTuxedo** [comment]
Comma separated list can be used to create a set now.
https://twitter.com/RiotTuxedo/status/1162123064626122752
