### ISSUE TITLE
Spectator documentation

### ISSUE THREAD

**Issue by FlorianMifsud** [RiotGames/developer-relations#310]
**Bug Description**  
there is no documentation for encryptionKey (https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerName)

**Problem Description**  
There are documents from 2014 but I doubt that this is up to date https://gist.github.com/themasch/8375971

**Comment by tisbells** [comment]
Closing this as it is very old. SummonerName endpoints have been removed.
