### ISSUE TITLE
[BUG] TFT-MATCH-V1 CompanionDto Docs Missing

### ISSUE THREAD

**Issue by Abion47** [RiotGames/developer-relations#313]
In the "/tft/match/v1/matches/{matchId}" endpoint under ParticipantDto it lists a field of type CompanionDto, but this class doesn't have any documentation on that page or any other API page I can find.

**Comment by MingweiSamuel** [comment]
#275 has:

**tft-match-v1.CompanionDto**
Name | Data Type | Description
-- | -- | --
skin_ID | int |
content_ID | string |
species | string |

Also I have http://www.mingweisamuel.com/riotapi-schema/tool/ swagger spec which fixes a few quirks like this one

**Comment by RiotTuxedo** [comment]
Gonna close this as a duplicate. I'll add the info for companiondto, but without static data being built for tft I'm not sure if there's a great way to surface the complete list. I'll see if this is something we can eventually get included for tft static data.
