### ISSUE TITLE
[BUG] Auto Champion Selection API Doesn't Work

### ISSUE THREAD

**Issue by SaeronMeng** [RiotGames/developer-relations#314]
**Bug Description**  
I can execute the API request `/lol-champ-select/v1/session/actions/{id}` without error, everything goes okay, but my league client cannot react to my operation.

**Expected Result**  
Usually, when I use:
```
PATCH /lol-champ-select/v1/session/actions/7 HTTP/1.1
Host: 127.0.0.1:43677
Authorization: Basic cmlvdDotdU1sb1o0RjJsendiRkphYnhsUUZn
Content-Type: application/json

{
	"data": {
		"championId":1
	}
}
```
It should help me choose Anne as my champion. 

**Actual Result**  
However, my champion icon is still blank, even though I can do patch without error (it returns nothing). When I choose a champion manually and use `POST /lol-champ-select/v1/session/actions/7/complete`, it can work.

**Developer Impact**
* Severity: I cannot continue my development if this problem cannot be solved.

**Preconditions**
My OS: Windows 10
Server: Tencent, Mainland China

**Issue Comments**
I do not know if there is something wrong with my request, or you should fix the bug. Thank you so much.

**Comment by thomasmarton** [comment]
The LCU API is a completely unsupported API. This means if you encounter a bug like this, you're completely on your own and Riot will most likely not fix the bug as that API is meant for internal consumption only.

**Comment by SaeronMeng** [comment]
Now I know where I get wrong, sorry to bother you. I'll close this issue.

**Comment by he429134733** [comment]
请问大佬是怎么解决选择英雄的，我使用/lol-champ-select/v1/session/actions/29  patch 这个接口的时候是提示
![image](https://user-images.githubusercontent.com/44768024/131224600-991f429e-256f-48dc-b7fe-993cf5305adb.png)

**Comment by paaksing** [comment]
@he429134733 

LCU （英雄联盟更新客户端）接口不是官方维护的对外接口，这意味着当你遇到这些问题的时候，你只有自己想办法解决，拳头基本不会搭理这些问题因为本身就是内部消耗
