### ISSUE TITLE
Pending product's response taking too long

### ISSUE THREAD

**Issue by iago-silva** [RiotGames/developer-relations#316]
Riot ID: CITH#BR1
App ID: 442317

I've submit a APP to PRODUCTION API KEY and done verification since at 24/05/2020 and nothing happens.

Already tried send messages by app's messages and account messages, but nothing response...

What do i do?

**Comment by TheGuyDanish** [comment]
Disclaimer, I'm not Rioter, this is just the stuff I've heard.

You could try joining the Developer Relations Discord ([https://discord.gg/riotgamesdevrel](https://discord.gg/riotgamesdevrel)) and asking during the next office hours (on Friday). Though at the moment, key applications are delayed by the circumstances in the world. The best outcome is just to wait.

**Comment by RiotTuxedo** [comment]
Hang tight. We'll get to your application.
