### ISSUE TITLE
[BUG] Revision date on summoner end point returns in seconds when it should be in ms

### ISSUE THREAD

**Issue by hingston** [RiotGames/developer-relations#317]
**Bug Description**  
Revision date on https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerName should be in MS
`
Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change
`
But is now appearing as seconds.

Example for summoner Linux on EUW:
```
{
    "id": "REMOVED",
    "accountId": "REMOVED",
    "puuid": "REMOVED",
    "name": "Linux",
    "profileIconId": 3351,
    "revisionDate": 1591750119,
    "summonerLevel": 113
}
```

**Problem Description**  
This breaks all code that uses this.

**Expected Result**  
Revision date to be returned in MS like it states in the documentation and does for match timestamps.

**Actual Result**  
Revision date returned in seconds

**Developer Impact**
Breaks existing code

**Player Impact**
None

**Preconditions**
None

**Repro Steps**
Go to: https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerName
Request summoner name Linux on EUW

**Issue Comments**
None

**Comment by RiotTuxedo** [comment]
The summoner service has undergone some changes over the years. I believe the documentation is just out of date. I wouldn't rely on `revisionDate` as a reliable way of determining completed games anymore. I'll update the docs.

**Comment by hingston** [comment]
This change happened within the last 48 hours as I started to receive exceptions because of it for the first time in 3 years.

**Comment by RiotTuxedo** [comment]
Oh that's my mistake. I spaced and gave the response that was meant for #318. I'll see what's up with revision date.

**Comment by RiotTuxedo** [comment]
Thanks for the report. We're hoping to have this behavior reverted soon. It's Friday, so no deploys today. Will update when the change goes out. The issue is in the service, not the data so one the fix is deployed all timestamps will be returned in ms.

**Comment by RiotTuxedo** [comment]
The fix is on the PBE. It's expected to go live later this week.

**Comment by hingston** [comment]
This is still happening on LAN, LAS and BR
