### ISSUE TITLE
[BUG] Revision date doesn't update when a match is completed

### ISSUE THREAD

**Issue by hingston** [RiotGames/developer-relations#318]
This might be related to #317 but not sure when this started. I think after crawling over some users this started some time ago as there are many match dates after summoner revision dates.

**Bug Description**  
When a player finishes a game the revision date timestamp on the summoner endpoint is not updated.

Summoner revision date from docs:
`
Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change
`

Here it states that it should update when a summoner finishes a game. This used to be the case in 2017 when my app was developed. Some point since then it stopped happening. You can tell by randomly crawling summoners and seeing if they have their latest match timestamp at some point after the last time their summoner revision date timestamp was updated.

**Problem Description**  
See above.

**Expected Result**  
Summoner revision date timestamp is updated when their match is complete like it used and like it says it will in the docs.

**Actual Result**  
Revision date timestamp isn't updated after a match finishes.

**Developer Impact**
You can't check a revision date to see if you need to check for new matches, this means you will always have to check matches which is more costly. You could check a revision date and compare with cache/database to see if you can avoid requesting match history.

**Player Impact**
None

**Preconditions**
None

**Repro Steps**
Check summoner revision timestamp, finish a game, check again and it is the same.

**Comment by RiotTuxedo** [comment]
The summoner service has undergone some changes over the years. I believe the documentation is just out of date. I wouldn't rely on `revisionDate` as a reliable way of determining completed games anymore. I'll update the docs.

**Comment by RiotTuxedo** [comment]
The documentation has been updated to the following:

```
Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: summoner name change, summoner level change, or profile icon change
```
