### ISSUE TITLE
[BUG] [LoR] [Android] Game Client API not working after last update

### ISSUE THREAD

**Issue by Siniliote** [RiotGames/developer-relations#319]
**Bug Description**  
Attempt to access the client API via the web browser (http://127.0.0.1:21337/static-decklist, and other API urls) : i obtained an inadequate response.
Game in progress in background.
It worked previously with another version game. 

**Problem Description**  
I don't have access to API information.

**Expected Result**  
GET http://127.0.0.1:21337/static-decklist
``{
  "DeckCode": null,
  "CardsInDeck": null
}``

**Actual Result**  
GET http://127.0.0.1:21337/static-decklist
/static-decklist not found

**Developer Impact**
* Frequency: Every API call.
* Severity: When it happens, my whole app doesn't receive information.

**Preconditions**
* Lauch game
* Lauch browser and access url api

**Comment by stelar7** [comment]
The endpoints on mobile is not a supported feature; https://discordapp.com/channels/187652476080488449/633905002976378881/705931426222309466

**Comment by Siniliote** [comment]
Thx, for your response. It's permanently deleted?

**Comment by RiotTuxedo** [comment]
@Siniliote It looks like it unfortunately. This is the quote that @stelar7 is linking to:
> I wouldn't rely on the existence of mobile endpoints. That's something we experimented with but I don't believe we'll continue to support it (for some of the same backgrounding issues you all have already identified!).
> Riot Exis

**Comment by hamirshekhawat** [comment]
What are the plans to introduce a mobile specific method? Maybe logging?
