### ISSUE TITLE
Killing Spree Stat

### ISSUE THREAD

**Issue by MarlonWelter** [RiotGames/developer-relations#32]
The in-game voice starts calling the 3. consecutive kill without deaths in between a "killing spree". However, in the match stats the field "killingSprees" already increases at 2 kills. Would be great to clarify which definition of killing spree is correct.

**Comment by RiotTuxedo** [comment]
Leading up to the holidays these kind of conversations can get lost. As such, I'm removing the escalation tag, I'll raise this concern with the team that owns match history in the new year.

**Comment by MarlonWelter** [comment]
any update on this?

**Comment by Querijn** [comment]
The team is still on holiday until the seventh, so that might be unlikely.

**Comment by Querijn** [comment]
Brought it up with Tuxedo, let's hope we can get it re-escalate it to the related team. :)

**Comment by RiotTuxedo** [comment]
I'll get an answer to what we truly consider a killing spree. The work to resolve this inconsistency would have to get prioritized, but at least you'll know what a true "killing spree" is.

**Comment by RiotTuxedo** [comment]
The in-game call out, which is purely cosmetic, occurs after three kills. Bounties start after two kills.
