### ISSUE TITLE
[BUG] TFT set3update champion.json wrong data

### ISSUE THREAD

**Issue by Canisback** [RiotGames/developer-relations#320]
**Bug Description**  
Ekko traits has "Infiltrato" instead of "Infiltrator".

**Problem Description**  
Crash when trying to link traits.

**Expected Result**  

`
   {
    "name": "Ekko",
    "championId": "TFT3_Ekko",
    "cost": 5,
    "traits": [
      "Cybernetic",
      "Infiltrator"
    ]
  }
`

**Actual Result**  

`
  {
    "name": "Ekko",
    "championId": "TFT3_Ekko",
    "cost": 5,
    "traits": [
      "Cybernetic",
      "Infiltrato"
    ]
  }
`

**Developer Impact**
Need to update manually the file.

**Player Impact**
None

**Preconditions**
None

**Repro Steps**
1. Download the set3update.zip : https://static.developer.riotgames.com/docs/tft/set3update.zip
1. Look at the champion.json file

**Issue Comments**
None

**Comment by RiotTuxedo** [comment]
Thanks for the report.
