### ISSUE TITLE
[BUG] [LoR] Positional Rectangles reports transformed champion cards incorrectly

### ISSUE THREAD

**Issue by ronbos** [RiotGames/developer-relations#321]
**Bug Description**  
Associated champion cards (upgraded champion, champion spell) are not reported correctly by positional-rectangles

**Problem Description**  
See bug description

**Expected Result**  
Associated card codes should be used when champion is transformed into spell or upgraded

**Actual Result**  
Champion continues to be reported using basic code, or is reported with the basic spell code when in hand

**Developer Impact**
* Frequency: Almost all the time.
* Severity: Breaks down the card tracking logic

**Player Impact**
None

**Preconditions**

Same champion in hand and on the board
Champion upgrade on the board

**Repro Steps**
Example:
1. Have two Lux in hand
2. Play one Lux
3. Second Lux in hand is transformed into a spell, but it is reported as 01DE032 "Prismatic Barrier", not as 01DE042T1 "Lux's Prismatic Barrier"
Second example (less impactful for tracking):
1. Upgraded champion is reported as basic, e.g. upgraded Lux is still 01DE042, not 01DE042T2

**Issue Comments**

**Comment by tisbells** [comment]
Closing out old issues. No other reports on this issue. If you feel this is incorrect, feel free to comment or reopen.
