### ISSUE TITLE
[BUG] Match History won't working properly .

### ISSUE THREAD

**Issue by RIOT-Panko** [RiotGames/developer-relations#322]
**About:** Match History on LeagueOfLegends's website have some bugs.

**Bug Description**  
1- Old-Ingame Map.
2- Map doesnt show us the "Champion Kills" or "Building Kills" . 
3- Player builds Section won't working.

**Problem Description**  
Ingame-map is old version and doesn't work properly.

**Expected Result**  
The new Summoners Rift map working properly and player builds section working properly too.

**Actual Result**  
Old ingame-map + doesnt working and player build section doesnt working properly too.
![Screenshot_2](https://user-images.githubusercontent.com/63587234/85068009-4782a880-b1ba-11ea-891c-4ac1c0d3ccac.png)

**Player Impact**

* Frequency: Everytime

* Severity: The users can't see their statistic.
* Quantity: Every player who uses LeagueofLegends website.
* Region: Every Region.

**Issue Comments**
A simple bug but it is important and it is easy to fix.

**Comment by RiotTuxedo** [comment]
Unfortunately, this issue isn't related to any developer resources so our team wouldn't be able to properly escalate this issue. You could report it to [player support](http://support.riotgames.com), if you'd like.
