### ISSUE TITLE
[BUG] Typo in your general policies

### ISSUE THREAD

**Issue by alexander-vielhauer** [RiotGames/developer-relations#324]
**Bug Description** 
I noticed a typo at https://developer.riotgames.com/policies/general
_Your must post the following legal boilerplate to your product in a location that is readily visible to players_ first word should be _You_
You might also want to add a colon(?)

Sorry if this does not belong here. Please let me know where I should've reported this instead.

**Comment by RiotTuxedo** [comment]
Thanks for the report.
