### ISSUE TITLE
[BUG] LEAGUE DIRECTOR

### ISSUE THREAD

**Issue by GTDanielGT** [RiotGames/developer-relations#325]
TRANSLATOR: HELLO! THE LEAGUE DIRECTOR DOES NOT ALLOW ME TO FILL IN THE BOX THAT ALLOWS ME TO USE THE PROGRAM, I CAN USE THE 3D MODE WITHIN THE GAME, BUT IT DOES NOT ALLOW ME TO USE THE ADVANCED OPTIONS OF THE "LEAGUE DIRECTOR" PROGRAM, I HOPE THAT THEY CAN HELP ME WITH THE PROBLEM, THANK YOU

![league](https://user-images.githubusercontent.com/67404923/85653977-5910f800-b673-11ea-8083-332ebc3f2011.png)

**Comment by RiotTuxedo** [comment]
Unfortunately, this isn't the place for assistance on how to get league director running. If you'd like you can join the Developer Discord and ask for assistance there.

https://discord.gg/riotgamesdevrel
