### ISSUE TITLE
[BUG] set3update traits.json missing styles (set3.5)

### ISSUE THREAD

**Issue by momongah** [RiotGames/developer-relations#326]
**Bug Description**  
 set3update traits.json missing and incorrect styles

**Problem Description**  
A couple of traits which have chromatic styles for the final tier are missing said style in set3.5 traits.json
The list of traits missing a chromatic field from my findings are:
**8 battlecasts**, **6 celestials**, **8 chronos**, **9 star guardians**  

Also a few of the traits are missing new added tiers in set3.5 or have incorrect styles tiers:
- 3 **cybernetics** should be **bronze** but it's listed **silver**
- 2 **mana-reavers** should be **gold** but it's listed **bronze**
- 2 **snipers** should be **bronze** but it's listed **gold**, also missing 4 **gold**

**Expected Result**  
`{ key: "celestial", sets: [ { style: "bronze", min: 2 }, { style: "gold", min: 4}, { style: "chromatic", min: 6}, ]}`

**Actual Result**  
`{ key: "celestial", sets: [ { style: "bronze", min: 2 }, { style: "silver", min: 4}, { style: "gold", min: 6}, ]}`

 [set3update json file](https://static.developer.riotgames.com/docs/tft/set3update.zip)

**Comment by RiotTuxedo** [comment]
Thanks for the report. This has been resolved.
