### ISSUE TITLE
[BUG] About "apis#lor-ranked-v1/GET_getLeaderboards"

### ISSUE THREAD

**Issue by wangyi041228** [RiotGames/developer-relations#328]
Reporting some "bugs" in my opnion and sorry for my English.

BUG #1
"apis#lor-ranked-v1/GET_getLeaderboards" updates once every hour, FIRST UPDATED TIME ranges from XX:00:14 to XX:08:59. The range is too wide.

BUG #2
The response usually changes between new value and old value around updating time. CHANGED TIME ranges from  XX:00:30 to XX:51:51  It's unsafe for developers to get correct data.

Here're my logs in last 3 hours.

2020-07-01 UTC+8

EU 01:02:42
EU 01:02:51 (x)
EU 01:04:05
EU 01:04:26 (x)
EU 01:04:49
NA 01:06:31
NA 01:06:42 (x)
AS 01:06:55
NA 01:08:44
NA 01:08:54 (x)
NA 01:09:13
NA 01:09:33 (x)
NA 01:09:42
SE 01:09:45
NA 01:09:52 (x)
NA 01:10:59
NA 01:11:09 (x)
NA 01:11:19
NA 01:11:28 (x)
NA 01:11:39
NA 01:11:48 (x)
NA 01:13:09
SE 02:00:13
EU 02:00:21
NA 02:06:57
AS 02:07:35
AS 02:08:11
AS 02:08:20
SE 03:00:48
EU 03:01:14
EU 03:01:23 (x)
EU 03:01:41
EU 03:02:01 (x)
EU 03:02:19
EU 03:02:28 (x)
EU 03:06:20
EU 03:06:29 (x)
EU 03:06:48
NA 03:06:56
EU 03:06:57 (x)
NA 03:07:04 (x)
EU 03:07:07
NA 03:07:14
EU 03:07:15 (x)
EU 03:08:04
AS 03:08:14
EU 03:08:23 (x)
EU 03:08:32

**Comment by tisbells** [comment]
Closing out old issues. We've received no additional reports, but if this is still an issue, feel free to reopen/comment.
