### ISSUE TITLE
Inconsistent Summoner ID Name Prefix /lol/summoner/v4/summoners/{encryptedSummonerId} (abandoned / banned account?)

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#33]
~~Only happens on my ChampionMaster Flair API key: https://developer.riotgames.com/app/212114/info~~
happens in general

For user `50550639DEL1` (NA) with summoner ID `50550639`  
encrypted summoner id `rvudpW-FK13pBz3B6cQigdC-NG2vt8rQ-RYZGIBIUDvSxf8`

Calling the by summoner id endpoint gives a corrupted summoner name:  
https://na1.api.riotgames.com/lol/summoner/v4/summoners/rvudpW-FK13pBz3B6cQigdC-NG2vt8rQ-RYZGIBIUDvSxf8
```js
{
	"id": "rvudpW-FK13pBz3B6cQigdC-NG2vt8rQ-RYZGIBIUDvSxf8",
	"accountId": "lWCQw2OBo2zu2DoTLlJVGhiLs2j0JuSNowthaKcy5mJg28E",
	"puuid": "0iAk55tfpRmJRKVzwAd7bysVyDW8HQRHPQn957zyvfdIFOFJI2u-eLMKuuQatW9uUmRIyCEI-yOx1g",
	"name": "rvudpW-FK13pBz3B6cQigdC-NG2vt8rQ-RYZGIBIUDvSxf8DEL1", // here
	"profileIconId": 1665,
	"revisionDate": 1499151682000,
	"summonerLevel": 30
}
```

This only happens in the `/lol/summoner/v4/summoners/{encryptedSummonerId}` operation, the other three return the expected json (by-name, by-puuid, by-account)

```js
{
	"id": "rvudpW-FK13pBz3B6cQigdC-NG2vt8rQ-RYZGIBIUDvSxf8",
	"accountId": "lWCQw2OBo2zu2DoTLlJVGhiLs2j0JuSNowthaKcy5mJg28E",
	"puuid": "0iAk55tfpRmJRKVzwAd7bysVyDW8HQRHPQn957zyvfdIFOFJI2u-eLMKuuQatW9uUmRIyCEI-yOx1g",
	"name": "50550639DEL1", // OK
	"profileIconId": 1665,
	"revisionDate": 1499151682000,
	"summonerLevel": 30
}
```

**Comment by jluzonpr** [comment]
@Querijn they're not done after the fact for the actual encryption, but we had added an extra security filter where if it catches a known id before the response gets sent, we would encrypt it. We disabled it for summoner for now while we figure out a better way to do it for these endpoints.

tl:dr should be fixed
