### ISSUE TITLE
[DOCS] val-match-v1 "MatchDto" name collision

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#332]
First off, thank you so much for the hard work on the Valorant APIs!  
I have a small issue which I'm sure will be easy to fix: currently there are two different DTOs named `MatchDto` which could lead to some confusion. First one is the top level object returned by `getMatch`, and the other is the list item returned by `getMatchlist`, so I think the later one could be renamed to `MatchReferenceDto` or something similar.

Again, thanks for the hard work!

**Comment by CeH9** [comment]
I agree it might be confusing, but every modern serializaion tool supports custom name mapping e.g. 
``` kotlin
@SerializedName("original_name")
var myCoolName: String
```

**Comment by MingweiSamuel** [comment]
This is actually completely cosmetic and outside of the serialized JSON, I'm just referring to the names given to the different DTO "classes"

**Comment by RiotTuxedo** [comment]
I'll update the name of the DTOs to avoid this collision.

**Comment by MingweiSamuel** [comment]
Hey Tux, could you double check this since I still see `val-match-v1/GET_getMatch` returns `MatchDto` while `val-match-v1/GET_getMatch` returns a list of a different `MatchDto`?

**Comment by RiotTuxedo** [comment]
Actually updated now.
