### ISSUE TITLE
[BUG] PUUID not updated

### ISSUE THREAD

**Issue by FlorianMifsud** [RiotGames/developer-relations#337]
**Bug Description**  
/lol/summoner/v4/summoners/by-name/{summonerName} return 404 while the user exists

**Problem Description**  
I have the PUUID of the player it returns the nickname to me when I pass the nickname it returns me 404

**Expected Result**  
Player info

**Actual Result**  
Error 404

**Developer Impact**
* Frequency: Every API call.
* Severity: the player cannot be found on the site ( error 5XX)
* Cost: X
* Efficiency: X
* User emails: x

**Player Impact**

* Frequency: on my cron script
* Severity: my script shutdown
* Quantity: 1 player at the moment
* Region: EUW

**Issue Comments**
The PUUID gives me a nickname.

When I try via /lol/summoner/v4/summoners/by-name/{summonerName} it returns 404 error (see screen) 
When I try via /lol/summoner/v4/summoners/by-account/{encryptedAccountId} return Solary Narkuss
When I try via /lol/summoner/v4/summoners/{encryptedSummonerId} it returns 404 error

The account has been rename
![brave_ZZe8xE2Pyf](https://user-images.githubusercontent.com/54841233/87805423-93764b00-c855-11ea-9767-68961f5f5725.png)

**Comment by RiotTuxedo** [comment]
Sorry I wasn't able to look into this right when you reported it. It looks like the issue resolved itself as now querying by the puuid properly returns `Solary Narkuss`. Let me know if this happens to you again.

As a note for me, your appId is `407614`.

**Comment by FlorianMifsud** [comment]
It seems fixed, thanks

**Comment by FlorianMifsud** [comment]
Hello;

I reopen because I still have this problem; name not update
Req: https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/A%20Big%20Cotelette
`{"id":"xGqCscLknoqGTKsYdjyb9DB6OV4blQzuPn3uuoBDVxtodaI","accountId":"ULLf7f21zYkk9gXpxeJBA6P8I7JbKlzf2r81lIzMbUiFpt4","puuid":"dYTA592SQuHWsL1FokGUd4MNdrI_PGbWUTc_UxahBW9qzeBGilLDCjB3pks09UXOp7LoLWYUXW_LDA","name":"A Big Cotelette","profileIconId":4497,"revisionDate":1598272921000,"summonerLevel":144}`
Req: https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-puuid/dYTA592SQuHWsL1FokGUd4MNdrI_PGbWUTc_UxahBW9qzeBGilLDCjB3pks09UXOp7LoLWYUXW_LDA
`{"id":"xGqCscLknoqGTKsYdjyb9DB6OV4blQzuPn3uuoBDVxtodaI","accountId":"ULLf7f21zYkk9gXpxeJBA6P8I7JbKlzf2r81lIzMbUiFpt4","puuid":"dYTA592SQuHWsL1FokGUd4MNdrI_PGbWUTc_UxahBW9qzeBGilLDCjB3pks09UXOp7LoLWYUXW_LDA","name":"TheghostTracker","profileIconId":4497,"revisionDate":1597872302000,"summonerLevel":144}`
req; https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/TheghostTracker
`{"id":"xGqCscLknoqGTKsYdjyb9DB6OV4blQzuPn3uuoBDVxtodaI","accountId":"ULLf7f21zYkk9gXpxeJBA6P8I7JbKlzf2r81lIzMbUiFpt4","puuid":"dYTA592SQuHWsL1FokGUd4MNdrI_PGbWUTc_UxahBW9qzeBGilLDCjB3pks09UXOp7LoLWYUXW_LDA","name":"TheghostTracker","profileIconId":4497,"revisionDate":1597872302000,"summonerLevel":144}`

2 different nicknames 2 puuid/id/accounits/etc identical

**Comment by RiotTuxedo** [comment]
Thanks for this. I've confirmed this unexpected behavior. The last game doesn't update the revision date anymore as far as I'm aware. I've escalated this issue to the team.

**Comment by RiotTuxedo** [comment]
The team is aware and is working on a fix.
