### ISSUE TITLE
[Docs] IP's tournaments

### ISSUE THREAD

**Issue by FlorianMifsud** [RiotGames/developer-relations#338]
For tournaments, is it possible to have the IPs to use? To whitelist the IPs and prevent it from being blocked by the different firewalls

![brave_LAc7oRYirp](https://user-images.githubusercontent.com/54841233/87879818-475e0e80-c9ed-11ea-96bb-533927708ff1.png)

**Comment by tisbells** [comment]
Closing out old issues. I'm not sure what IPs you are referring to. If you are still experiencing issues with this, feel free to reopen or comment with additional information.
