### ISSUE TITLE
[BUG] [VAL] 

### ISSUE THREAD

**Issue by Wishmesh** [RiotGames/developer-relations#339]
**Bug Description**  
`/val/content/v1/contents` returns wrong info for one particular item - `Oni Shorty Level 5\r\n(Variant 1 Black)` is translated as Sheriff in German:
```
                "de-DE": "Sheriff – Oni Level 5\n(Variante 2, Schwarz)",
                "en-GB": "Oni Shorty Level 5\r\n(Variant 1 Black)",
```
Also, Oni Shorty Levels 6 and 7 are translated incorrectly.

**Expected Result**  
All translations should match the weapons.

**Actual Result**  
Translating Shorty results in Sheriff.

**Developer Impact**

* Frequency: Every API call
* Priority: Low

**Comment by Wishmesh** [comment]
Just noticed, that Variants also does not match. The `Variante 2, Schwarz` should be `Variante 1, Schwarz`

**Comment by tisbells** [comment]
Closing out old issues and we've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
