### ISSUE TITLE
[DOCS] LoL Game Constants JSONs missing newer additions

### ISSUE THREAD

**Issue by aPinat** [RiotGames/developer-relations#340]
Game constants JSONs over on https://developer.riotgames.com/docs/lol are out of date and cause issues in libraries that use them to parse API responses using the given ids.

Missing from what I can tell are:
- `SEASON 2020` in `seasons.json`
- queueId `1300` for the current Nexus Blitz in `queues.json`
- gameMode `NEXUSBLITZ` for the current Nexus Blitz in `gameModes.json`
- mapId `22` for Convergence TFT map in `maps.json`
- (queueId `1111` for 1v0 TFT testing queue)

**Comment by MingweiSamuel** [comment]
I've created www.mingweisamuel.com/riotapi-schema/enums/ which contains the updated enums as well as annotated names and descriptions
https://github.com/MingweiSamuel/riotapi-schema/issues/16

**Comment by aPinat** [comment]
@MingweiSamuel Small error there: Queue `1110` is still TFT Tutorial and`1111` (really that number) is that internal TFT 1v0 testing queue.

**Comment by MingweiSamuel** [comment]
Good catch, fixed. Where did you get that JSON from, the LCU?

**Comment by aPinat** [comment]
yeah: `/lol-game-queues/v1/queues`

**Comment by ciabo14** [comment]
Hey Folks, 

do you know if and when the static data will be updatad in the official repository (https://developer.riotgames.com/docs/lol) as well?

**Comment by IcyDefiance** [comment]
Game modes for the new tutorials are also missing:
* TUTORIAL_MODULE_1 (Welcome to League)
  * https://na1.api.riotgames.com/lol/match/v4/matches/3432145099
* TUTORIAL_MODULE_2 (Power Up)
  * https://na1.api.riotgames.com/lol/match/v4/matches/3432116214
* TUTORIAL_MODULE_3 (Shop for Gear)
  * https://na1.api.riotgames.com/lol/match/v4/matches/3432156790

**Comment by MingweiSamuel** [comment]
@IcyDefiance Updated the mirror http://www.mingweisamuel.com/riotapi-schema/enums/gameModes.json

**Comment by Zelgadis87** [comment]
Static data is still referring to Season 2019 as the current ranked season: http://static.developer.riotgames.com/docs/lol/seasons.json ..

**Comment by AoshiW** [comment]
@Zelgadis87 i don't think they will be updated it.

https://developer.riotgames.com/apis#match-v4/GET_getMatchlist
season|   | Set[int] | [DEPRECATED] This field should not be considered reliable for the purposes of filtering matches by season.
-- | -- | -- | --

**Comment by Zelgadis87** [comment]
@AoshiW Mhmm, that's for the filter parameter, not for the returning match data, which instead have no notes.. Anyway, I suppose you are right, since it's been two years since the last update.. I imagine they have deprecated the season concept entirely from the APIs? I don't really get it why, nor I can find any other reliable data for calculating stats by season...

**Comment by RiotTuxedo** [comment]
We're moving to tracking seasons by timestamp. This will need to be added to the documentation, but until then hopefully this helps.

```
All times in Pacific Time

Shard  |   Season 2019 Start  |   Season 2019 End    |   Season 2020 Start  |   Season 2020 End
---------------------------------------------------------------------------------------------------
OC1    | 2019-01-23 11:00:00  | 2019-11-18 05:01:00  | 2020-01-09 09:00:00  | 2020-11-09 05:00:01
JP1    | 2019-01-23 11:10:00  | 2019-11-18 07:01:00  | 2020-01-09 11:00:00  | 2020-11-09 07:00:01
KR     | 2019-01-23 11:10:00  | 2019-11-18 07:01:00  | 2020-01-09 11:00:00  | 2020-11-09 07:00:01
RU     | 2019-01-23 16:00:00  | 2019-11-18 13:01:00  | 2020-01-09 17:00:00  | 2020-11-09 13:00:01
TR1    | 2019-01-23 19:00:00  | 2019-11-18 13:01:00  | 2020-01-09 17:00:00  | 2020-11-09 13:00:01
EUN1   | 2019-01-23 18:00:00  | 2019-11-18 15:01:00  | 2020-01-09 19:00:00  | 2020-11-09 15:00:01
EUW1   | 2019-01-23 21:00:00  | 2019-11-18 16:01:00  | 2020-01-09 20:00:00  | 2020-11-09 16:00:01
BR1    | 2019-01-23 23:00:00  | 2019-11-18 19:01:00  | 2020-01-09 23:00:00  | 2020-11-09 19:00:01
LA2    | 2019-01-24 00:00:00  | 2019-11-18 19:01:00  | 2020-01-09 23:00:00  | 2020-11-09 19:00:01
LA1    | 2019-01-24 02:00:00  | 2019-11-18 22:01:00  | 2020-01-10 02:00:00  | 2020-11-09 22:00:01
NA1    | 2019-01-24 03:00:00  | 2019-11-19 00:01:00  | 2020-01-10 04:00:00  | 2020-11-10 00:00:01
```

**Comment by MingweiSamuel** [comment]
QueueIDs are still a bit weird and sometimes out of date. There are a few different sources of truth that all have different subsets of queues ids:
https://github.com/MingweiSamuel/Camille/issues/36#issuecomment-663157095

**Comment by RiotTuxedo** [comment]
I'll see if I can go through the other sources and add anything that makes sense. The constants files are manually updated, so if you're using them in a project you should have a default fallback for an unknown queue, gamemode, etc.
