### ISSUE TITLE
[BUG] Minor typo in Data Dragon static files

### ISSUE THREAD

**Issue by Extractum11** [RiotGames/developer-relations#341]
http://ddragon.leagueoflegends.com/cdn/10.14.1/data/en_US/champion/MissFortune.json

skin ID# 21018 is named "Bewitching Miss Fortune ", has an extra space at the end. Should be "Bewitching Miss Fortune".

**Comment by tisbells** [comment]
Closing out old issues. We're not aware of this being a problem in newer patches, but feel free to reply or reopen if this is not the case.
