### ISSUE TITLE
[Feature Request] [LoR] [Android] Client API

### ISSUE THREAD

**Issue by hamirshekhawat** [RiotGames/developer-relations#343]
LoR Android Client API had some issues and it has been closed now. What is the plan for a future replacement of the APIs? Is there any WIP? By when can we expect an update on this issue?

**Comment by tisbells** [comment]
Closing old issues, this is no longer a supported API.

**Comment by AoshiW** [comment]
hey @tisbells , can you elaborate a bit on what you mean by "no longer a supported API"?

You mean:
1. this API is no longer supported on Android
2. the entire In-game API is no longer supported?


If it's 2. can you add a note about it to the documentation?

**Comment by Cypherous** [comment]
LoR is supported on the web API's

https://developer.riotgames.com/apis#lor-deck-v1 etc

**Comment by tisbells** [comment]
Sorry for the confusion - Existing [LoR APIs](https://developer.riotgames.com/apis) are still supported as normal, but Developer Relations is unable to guarantee support/updates for the [game client APIs](https://developer.riotgames.com/docs/lor#game-client-api). Nothing is changing, we just don't manage the game client APIs - although we still report up anything majorly blocking these services. We will clarify this in our docs.
