### ISSUE TITLE
[BUG/SUGGESTION] match-v4.getMatch returns invalid PlayerDTO for bots

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#344]
Example match: https://na1.api.riotgames.com/lol/match/v4/matches/3251803350

The API returns questionable PlayerDTO data in the bots' participant identities:
```json
{
	"participantId": 6,
	"player": {
		"platformId": "",
		"accountId": "0",
		"summonerName": "Ashe",
		"currentPlatformId": "NA1",
		"currentAccountId": "0",
		"matchHistoryUri": "/v1/stats/player_history//0",
		"profileIcon": 0
	}
}
```
Most of this data is invalid, and the summonerId field is missing. I think it would be better to just omit the field for bots.

```json
{
	"participantId": 6
}
```

This makes it easier to check for bots and would help developers catch some bugs that would result from reading the invalid data. The downside of this change would be that some developers may already have accounted for the invalid data.

related: https://github.com/RiotGames/developer-relations/issues/44

**Comment by RiotTuxedo** [comment]
Won't be changing this in the current version of the API, but maybe in the future. I've written this feedback down, so I'm closing this topic. Feel free to re-open it if this issue still persists in match-v5.

**Comment by MingweiSamuel** [comment]
Sounds perfect, thanks
