### ISSUE TITLE
[BUG] [LoR] Incorrect return data type

### ISSUE THREAD

**Issue by AoshiW** [RiotGames/developer-relations#345]
**Bug Description**  
`lor-ranked-v1/GET_getLeaderboards` returns  bad date type for `lp`

**Expected Result**  

![image](https://user-images.githubusercontent.com/48525283/89499511-6f58ba80-d7c0-11ea-9e98-a55eb67beef5.png)

**Actual Result** 
![image](https://user-images.githubusercontent.com/48525283/89499601-90b9a680-d7c0-11ea-96d8-e40d0df9f54b.png)

**Preconditions**
if you check the output using "developer.riotgames.com" you will see Expected Result
if you check the output  in web browse, you will see Actual Result

**Comment by LightshieldDotDev** [comment]
Might this be your browser changing the variable? Have you tried it with a different browser/postman/script?

**Comment by Krissalyce** [comment]
JSON only has a Number type. There is no int or float in JSON. To JSON, 2808.0 and 2808 is identical.

**Comment by AoshiW** [comment]
> Might this be your browser changing the variable? Have you tried it with a different browser/postman/script?

I don't think the browser would change the variable (if that's true, why is `rank` an integer and `lp` not?)
i tried  edge, google, Camille (C# lib) 
(Exception from Camille)
![image](https://user-images.githubusercontent.com/48525283/89559195-9db4b500-d815-11ea-8767-8abd5cf636ac.png)


> JSON only has a Number type. There is no int or float in JSON. To JSON, 2808.0 and 2808 is identical.

Thanks for info, i didn't know that! But for JsonSerializer in C# 2808.0 and 2808 isn't identical.

So if it's not a bug, should I close this issue?

**Comment by eyJhb** [comment]
> JSON only has a Number type. There is no int or float in JSON. To JSON, 2808.0 and 2808 is identical.

JSON might not differentiate between the two, but when the API guarantees a int it should NOT use any decimal places and actually give a int to the end user.

Languages like Go will not work, when trying to Unmarshal `2808.0` to a int, as it is not a int.

Besides this, it is just wasting bandwidth on making the programmers life hell. So this should be fixed, as it is a bug, and does not conform with the API descriptive.
