### ISSUE TITLE
[BUG][VAL] Contents endpoint return Forbidden

### ISSUE THREAD

**Issue by akinncar** [RiotGames/developer-relations#347]
**Bug Description**  
When I try to use https://ap.api.riotgames.com/val/content/v1/contents, I get forbidden result. 

**Expected Result**  
Expect to see content results

**Actual Result**  
```
{
    "status": {
        "message": "Forbidden",
        "status_code": 403
    }
}
```

**Developer Impact**
* I can't get 200 response either by sending parameters or not by sending

**Comment by thomasmarton** [comment]
Friendly reminder: Developer API keys expire every 24 hours (most probable cause)

**Comment by akinncar** [comment]
Thank's for a fast response, this was really the problem, I reseted API key and works great now.
