### ISSUE TITLE
What is the status of the ally shielded/healed statistic and will it ever be added to match v4?

### ISSUE THREAD

**Issue by stevezease** [RiotGames/developer-relations#35]
It has been multiple months since the [ally shielded/healed stat](https://i.imgur.com/3xGHReq.png) was introduced to League of Legends. Multiple threads sprang up in the discussion board in the coming months, asking when the statistic will be incorporated into the Match API( V3 at the time). None of the threads ended up receiving a conclusive answer. 

Sometime mid-October 2018, without warning, the stat itself disappeared from the post game stat page. 

What is the status of the statistic, and will it ever be added to match v4?

**Comment by iaace-NA** [comment]
Still waiting for this.
Developer impact: can't accurately measure enchanter support game impact
User impact: support impact on the game is undervalued

**Comment by Blangzo** [comment]
bump, ally shielding is still in post-game stat page, but not in match v4
