### ISSUE TITLE
[BUG] Volibear tiles have not been updated in CDN

### ISSUE THREAD

**Issue by itachi42** [RiotGames/developer-relations#351]
**Bug Description**
Some of Volibear's tiles have not been updated since he was reworked.

**Problem Description**
At least the following tiles do not match the corresponding skin :

- https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_0.jpg
- https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_1.jpg
- https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_2.jpg
- https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_3.jpg

I think the others are ok.

**Expected Result**
The links and the tarball should show the correct tiles

 **Actual Result**
The actual result are the previous tiles before Volibear was reworked

**Comment by RiotTuxedo** [comment]
This is being looked into. Should be resolved in 10.18.

**Comment by MingweiSamuel** [comment]
(You can leave this open until the fix is deployed)

**Comment by itachi42** [comment]
@MingweiSamuel Well 10.18.1 is available and contains the fixes.
Isn't that considered as deployed? 
Thanks

**Comment by MingweiSamuel** [comment]
Ah mb

**Comment by itachi42** [comment]
Yeah I guess you were thinking of this one.
https://github.com/RiotGames/developer-relations/issues/348
