### ISSUE TITLE
[DOCS][BUG] tft-match-v1/GET_getMatch TraitDto docs missing `style` (int) field

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#354]
Via @AoshiW

Actual response:
![image](https://user-images.githubusercontent.com/6778341/91085467-59d9f200-e602-11ea-8fc5-c885649a7219.png)

Docs:  
https://developer.riotgames.com/apis#tft-match-v1/GET_getMatch

Name | Data Type | Description
-- | -- | --
name | string | Trait name.
num_units | int | Number of units with this trait.
tier_current | int | Current active tier for the trait.
tier_total | int | Total tiers for the trait.

**Comment by RiotTuxedo** [comment]
Thanks for the report. The documentation has been updated.
