### ISSUE TITLE
[Documentation] Dev portal VAL-MATCH-V1 MatchInfoDto

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#355]
**Problem Description**  
Wrong data type specified on documentation section

**Expected Result**  
```
matchInfo | MatchInfoDto
```
**Actual Result**  
```
matchInfo | List[MatchInfoDto]
```
**Developer Impact**
Can cost half hour of debug for developers who cannot execute the endpoint. If the dto can include both return List or Object, then would be nice to be documented in description

**Comment by RiotTuxedo** [comment]
Thanks for the report. Documentation has been updated.
