### ISSUE TITLE
[BUG] VAL dto wrong dto name and/or sudden change of returned dto object name

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#358]
## Expected outcome:
KillDto (in dev portal)
```
gameTime
roundTime
```
## Actual outcome since August 31st:
Returned KillDto
``` 
timeSinceGameStartMillis
timeSinceRoundStartMillis
```
## Developer impact
HAHAHAHA

**Comment by MingweiSamuel** [comment]
Well at least the names are more descriptive

**Comment by RiotTuxedo** [comment]
The documentation has been updated to reflect this. Sorry about the unexpected change.
