### ISSUE TITLE
[DOCS][BUG] match-v4.ParticipantStatsDto docs missing `statPerk0`, `statPerk1`, `statPerk2`

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#359]
Pulling out of the comment on #102 

**ParticipantStatsDto** docs missing the fields ([link](https://developer.riotgames.com/apis#match-v4/GET_getMatch)):

Name | Data Type | Description
-- | -- | --
... | ... | ...
perk0 | int | Primary path keystone rune.
perk0Var1 | int | Post game rune stats.
... | ... | ...
perk5Var3 | int | Post game rune stats.
perkPrimaryStyle | int | Primary rune path
perkSubStyle | int | Secondary rune path

Actual JSON:
![image](https://user-images.githubusercontent.com/6778341/91916249-841a5800-ec71-11ea-8ef3-c297c8c716c6.png)

For these runes I believe:
![image](https://user-images.githubusercontent.com/6778341/91916514-30f4d500-ec72-11ea-82b9-60d4f6854d18.png)

**Comment by RiotTuxedo** [comment]
The documentation has been updated. Thanks for the report. Sorry about the delay on this.
