### ISSUE TITLE
Unable to filter by server names (not region codes) at the API Key Usage tab.

### ISSUE THREAD

**Issue by tcaram** [RiotGames/developer-relations#36]
At the API Key Usage Tab you can filter by region codes (NA1, EUW1) and by server names (NA, EUW), the latter one doesn't seem to be working. It always says: "OH NO! THERE IS NO DATA TO DISPLAY FOR THE ABOVE FILTER(S)".

**Comment by stelar7** [comment]
might be related to #25 ?

**Comment by tcaram** [comment]
Resolved.
