### ISSUE TITLE
[BUG] League director not connecting to replay.

### ISSUE THREAD

**Issue by AitoXD** [RiotGames/developer-relations#362]
**Bug Description**  
my replay API is enabled and i can't find an issue, but the league director software won't connect to my replays. I've marked off the boxes, and set EnableReplayApi to 1

**Problem Description**  
League director isn't connecting to replay with api enabled

**Comment by bangingheads** [comment]
This is a duplicate of #356 as they both have the same root cause

**Comment by SettoMain** [comment]
I have the Same problem I don't know how to fix it
