### ISSUE TITLE
[BUG] DDragon severely out of date

### ISSUE THREAD

**Issue by Querijn** [RiotGames/developer-relations#363]
**Bug Description**  
DDragon is out of date, patch 10.16 being the latest.

**Expected Result**  
DDragon 10.18

**Actual Result**  
DDragon 10.16

**Developer Impact**
Every developer is behind 2 patches

**Player Impact**
Players have to suffer websites with old ddragon data

**Preconditions**
DDragon CDN has to be up

**Repro Steps**
1. Go to http://ddragon.leagueoflegends.com/api/versions.json.
2. Check the first element of the array.

**Comment by RiotTuxedo** [comment]
Patch 10.17 was skipped. There wasn't a patch 10.17, but rather a 10.16b patch which was a micropatch. As such, we're going directly from 10.16 to 10.18 which just got released today. If there are any other questions related to this lmk, otherwise I think we can close this one out.
