### ISSUE TITLE
[BUG] Third Party Verification not working clientwise

### ISSUE THREAD

**Issue by klinger2709** [RiotGames/developer-relations#364]
**Bug Description**  
Currently there is an error when inserting a code into the Verification Input in the league client which says "Verification has failed. Please try again later." in client.

**Problem Description**  
That means people currently cannot use the 3rd-party verification

In order to get this problem i just did the following: 

> log into LoL Client 
> Go to Settings 
> Go to Verification
> Insert anything as code
> Get error message

**Comment by PixelHir** [comment]
![image](https://user-images.githubusercontent.com/7670940/92990464-0d852200-f4dd-11ea-97e8-4873aff261da.png)
Can reproduce on the first try, is it broken for everyone though?

**Comment by Querijn** [comment]
Yeah it cancels instantly for me too.

**Comment by ChronoBrake** [comment]
Hey,
EUNE same error. 
Regards

**Comment by FlorianMifsud** [comment]
EUW Too [#289 ](https://github.com/RiotGames/developer-relations/issues/289) same problem ?

**Comment by vremes** [comment]
So far it looks like this works again, tested on EUW1 and EUN1.
