### ISSUE TITLE
[DOCS][BUG] New `val-match-v1.getRecent` docs have wrong return type

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#366]
https://developer.riotgames.com/apis#val-match-v1/GET_getMatchlist

Currently says:
> **Return value: string**

Should be something like (maybe not named RecentMatchesDto):

> **Return value: RecentMatchesDto**
> 
> **RecentMatchesDto**
> Name | Data Type | Description
> -- | -- | --
> currentTime | long | Current time in epoch seconds
> matchIds | List[string] | List of match ID strings

**Comment by RiotTuxedo** [comment]
This issue should now be resolved.
