### ISSUE TITLE
[BUG] TFT API - trait data incorrect on set 4

### ISSUE THREAD

**Issue by whyando** [RiotGames/developer-relations#367]
The data returned by the tft match api is sometimes incorrect.

EXAMPLE
For example the game `https://asia.api.riotgames.com/tft/match/v1/matches/KR_4649692542`
participant 7/8

The player is lvl 9, has a FoN and has 9 units: TFT4_Nidalee, TFT4_Vayne, TFT4_Wukong, TFT4_Teemo, TFT4_Thresh, TFT4_Jinx, TFT4_Aatrox, TFT4_Sejuani, TFT4_Jhin
(and he has no trait spat items)

If we add up the expected traits for all those units we get:
{ Warlord: 1,
  Sharpshooter: 5,
  Dusk: 2,
  Divine: 1,
  Set4_Vanguard: 4,
  Set4_Spirit: 1,
  Fortune: 2,
  Cultist: 2 }

But the traits section says:
{ Cultist: 2,
  Divine: 2,
  Dusk: 2,
  Fortune: 2,
  Set4_Adept: 1,
  Set4_Enlightened: 1,
  Set4_Spirit: 1,
  Set4_Vanguard: 4,
  Sharpshooter: 6,
  Warlord: 1 }

Notably we have an extra Adept, Enlightened, Sharpshooter and Divine.
My theory is that this player had a 10th unit on his board: irelia which accounts for the missing Adept, Enlightened + Divine.
Then I think his chosen unit had doubled Sharpshooter trait.

DEVELOPER IMPACT:
we really want to present cool info about chosen, and since it's not in the api, we look for other ways to derive it
however because of bugs like this, we cannot

**Comment by RiotTuxedo** [comment]
I know this issue was posted first, but I'm going to use the second issue #368 because I believe it describes the issue more accurately.
