### ISSUE TITLE
[BUG] Chosen Trait Disappears in TFT Match History

### ISSUE THREAD

**Issue by SamGuthrie** [RiotGames/developer-relations#368]
**Bug Description**  
[TFT] When a player goes out and has to wait for combat to finish, their chosen trait is removed and does not show up in their match history. The bug can be seen clearly in this vod: https://www.twitch.tv/videos/742643401?t=18h11m27s

**Problem Description**  
Without the chosen traits being recorded accurately, tools cannot be developed to help players understand and adapt to the new mechanic. Match histories are also frequently inaccurate because of this.

**Developer Impact**
* Frequency: ~50% of match histories are inaccurate (High)
* Severity: Medium - cannot produce new features

**Player Impact**
* Frequency: All site visitors cannot see accurate Chosen statistics
* Severity: Low, however many players are interested in this data
* Region: All

**Preconditions**
* Have a chosen on your team
* Get eliminated before other players have finished combat

**Comment by RiotTuxedo** [comment]
The team is aware of this bug. I'll provide updates as I get them.

**Comment by SamGuthrie** [comment]
Looks like its fixed now, Thanks team!
