### ISSUE TITLE
[BUG] tft-league-v1 endpoints return http 204 instead of 404 or empty list when no data

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#369]
**Bug Description**  
If a **NA (?)** TFT league is empty, calling the endpoint returns 204 instead of the usual 404 which the rest of the RGAPI use.

> For example, the public API convention if there is no data matching the request is to return a 404 with a standard error response body. However, some services return a 204 with an empty response body instead. We use transforms to convert the 204/empty body to a 404/error body before sending the response to the caller.

[link](https://technology.riotgames.com/news/riot-games-api-transforms)

Meanwhile, EUW looks like this: https://euw1.api.riotgames.com/tft/league/v1/challenger
```json
{
    "tier": "CHALLENGER",
    "entries": []
}
```

**Developer Impact**
One more rare edge case which needs to be considered.

**Repro Steps**
1. Need a TFT league to be empty
2. Make a request to the league (right now the following are empty:)
   - https://na1.api.riotgames.com/tft/league/v1/challenger
   - https://na1.api.riotgames.com/tft/league/v1/grandmaster

**Comment by MingweiSamuel** [comment]
Updated, it seems NA behaves differently than EUW

**Comment by RiotTuxedo** [comment]
Thanks for bringing this to our attention. The default behavior should be to return a 200 and an empty list. I believe the league responses already account for this. Haven't seen this issue show up for apex tiers. We'll be making an update to the response of apex tiers to standardize the response to what EUW is currently returning.

**Comment by RiotTuxedo** [comment]
This should be resolved now.
