### ISSUE TITLE
The V3 reference refers to the old forum (a dead link)

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#37]
See [champion-mastery-v3](https://developer.riotgames.com/api-methods/#champion-mastery-v3) for example

> This API is being deprecated on 1/28/19. Please use champion-mastery-v4 as a replacement.
> https://discussion.developer.riotgames.com/questions/4269/verification-system.html

**Comment by RiotTuxedo** [comment]
Wrong link in the clipboard. Should be correct now.
