### ISSUE TITLE
[DOCS] DDragon examples do not match DDragon schema

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#370]
**Champion Passive Assets**

The docs have a "sanitizedDescription" key where this does not exist in DDragon.

**Champion Ability Assets**

The docs have in order "name","key","description","sanitizedDescription","image"
DDragon has "id","name","description","tooltip"..."image"

"key" and "sanitizedDescription" are not keys for a spell. "key" would be "id" and sanitizedDescription does not exist.

**Comment by lucasMesquitaBorges** [comment]
Docs updated to reflect the data dragon fields. Thanks for reporting this.
