### ISSUE TITLE
[BUG] Rate limits inconsistency

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#371]
# Bug Description
Small Rate limits either DOES NOT actually match the returned `X-Rate-Limits` headers or server side counter messed up harder than spaghetti. Doing request asynchronously is very common to hit the smaller limit (dev key 20:1 limit). I am gonna show a list of problems and showing the expected and actual results (all tested using dev key that hits 20:1 limit). Keep in mind that test are done on remote server that has < 20 ms latency.

## Test 1  
* Limit is set using the `Date` headers returned by the first call.

**Expected Result**  
Every 20 calls should be all successful by waiting after the set limit using `Date` header.

**Actual Result**  
First 20 calls gets through it, second chunk of 20 calls returns 429 at the 10th call always. The returned `retry-after` is of 2 seconds (how in the world a 20:1 limit would return a 2 second retry). Calls after the 40th 429s randomly.

## Test 2
* Limit is set using the `Date` headers returned by the first call adding an extra 0.5 second.

**Expected Result**  
Every 20 calls should be all successful by waiting after the set limit using `Date` header.

**Actual Result**  
First 20 calls gets through it, second chunk of 20 calls returns 429 at the 10th call always. The returned `retry-after` is of 2 seconds, and some of them 1 second (prob the extra 0.5 second added). Calls after the 40th 429s randomly (less).

## Test 3
* Limit is set using the `Date` headers returned by the first call adding an extra 1 second. This is aimed to not take the second bulk because it might cross the request to it, so adding 1 second will take the third bulk which is supposed to be clean.

**Expected Result**  
Every 20 calls should be all successful by waiting after the set limit using `Date` header.

**Actual Result**  
First 20 calls gets through it, second 20 calls 429s randomly after the 10th call. The returned `retry-after` is of 1 second (prob the extra 1 second added). Calls after the 40th 429s randomly (little).

## Test 4
* Limit is set using the `Date` headers returned by the first call adding an extra **2** second.

**Expected Result**  
Every 20 calls should be all successful by waiting after the set limit using `Date` header.

**Actual Result**  
As expected, but with the big delay added obv.

# Short Insight
I started experiencing this problem last month with the LEAGUE-V4 endpoint which has similar small limits as the dev key 20:1, which did not bother me because it happens randomly in small scale, until today when I was redoing the unit test on the same project without modification since last month started to see this random 429 coming out of no-where. I don't really know how can the 10 calls after first 20 calls passes while the next 10 doesn't (they are in the same bulk of 20 calls), even adding 1 second to the limit so it can take a next empty bulk, it still gives random 429. While adding 2 seconds to it solves the thing, so either the `retry-after` or the delay added to make it work seems to look like 30:3 instead of 20:1 limit.

**Developer Impact**
Dev key doesn't have much impact because they are bottlenecked by the bigger rate limits, but production key that hits the LEAGUE-V4 and other endpoints that has small limits can add up unjustified delays to execution times.

**Preconditions**
* The limit to hit is of small range of time (1~2 seconds).

**Comment by RiotTuxedo** [comment]
Can you include the response headers of your request? Like so:

curl -v http://na1.api.riotgames.com/lol/summoner/v1/summoners/by-name/RiotTuxedo?api_key=

```
< Content-Type: application/json;charset=utf-8
< Date: Mon, 21 Sep 2020 22:47:02 GMT
< Date: Mon, 21 Sep 2020  22:47:02 GMT
< X-App-Rate-Limit: 20:1,100:120
< X-App-Rate-Limit-Count: 1:1,1:120
< X-Riot-Edge-Trace-Id: 51ac8385-cd84-46b4-bbdd-12aa0efde391
< Content-Length: 52
< Connection: keep-alive
```

**Comment by paaksing** [comment]
@RiotTuxedo Sorry for the late response, I've got freetime today, here is the response headers. If you want the response headers that shows the 429 with a 2 second backoff I can do it with a script later.
```json
{
    "Content-Encoding": "gzip",
    "Content-Type": "application/json;charset=utf-8",
    "Date": "Thu, 24 Sep 2020 23:54:37 GMT, Thu, 24 Sep 2020  23:54:37 GMT",
    "Vary": "Accept-Encoding",
    "X-App-Rate-Limit": "20:1,100:120",
    "X-App-Rate-Limit-Count": "2:1,17:120",
    "X-Method-Rate-Limit": "30:10,500:600",
    "X-Method-Rate-Limit-Count": "1:10,17:600",
    "X-Riot-Edge-Trace-Id": "78f492e4-b744-4b8a-b14e-df72d2f8c7e3",
    "transfer-encoding": "chunked",
    "Connection": "keep-alive"
}
```

**Comment by RiotTuxedo** [comment]
Ah yes, sorry. If I could get the headers specifically when you get a 429 that'd be super useful.

I'm not sure if it's necessary to cut off 20% of the limit. That is a good way to make sure you don't bump into the limit, but it shouldn't be necessary if you're keeping track of the rate limits via the headers.

**Comment by paaksing** [comment]
@RiotTuxedo Here is the response header and the Logs by Pyot showing the what request is made.

```python
<CIMultiDictProxy('Content-Type': 'application/json;charset=utf-8', 'Date': 'Fri, 25 Sep 2020 00:34:18 GMT', 'Date': 'Fri, 25 Sep 2020  00:34:18 GMT', 'Retry-After': '2', 'X-App-Rate-Limit':
'20:1,100:120', 'X-App-Rate-Limit-Count': '21:1,36:120', 'X-Method-Rate-Limit': '2000:60', 'X-Method-Rate-Limit-Count': '36:60', 'X-Rate-Limit-Type': 'application', 'X-Riot-Edge-Trace-Id': 'de9df483-ea1e-4059-95b8-790fb36c1caf', 'Content-Length': '62', 'Connection': 'keep-alive')>

[Trace: LOL > RiotAPI] WARNING: The server responded with non service 429 Rate Limited, interrupts your task if this persists. Origin: <NA1 summoner_v4_by_id: ix52MVMksAafCNZJoW-UEIZZtuhtU7vAlLeBYFkxkTpqNYQ>, Inmediate backoff: 2 seconds.
```
Request made: `<NA1 summoner_v4_by_id: ix52MVMksAafCNZJoW-UEIZZtuhtU7vAlLeBYFkxkTpqNYQ>`

**Comment by RiotTuxedo** [comment]
@paaksing if we look at the headers there's a couple things we notice:
```
X-Rate-Limit-Type: application
X-App-Rate-Limit: 20:1,100:120
X-App-Rate-Limit-Count: 21:1,36:120
Retry-After: 2
```

First, **X-Rate-Limit-Type** tells us that you exceeded your application rate limit (vs method rate limit or service rate limit).
Second, **X-App-Rate-Limit** and **X-App-Rate-Limit-Count** show us what rate limit was exceeded. **X-App-Rate-Limit** tells us there's two application rate limits `20:1` means 20 requests per 1 second and `100:120` means 100 requests per 2 minutes. **X-App-Rate-Limit-Count** shows the counts for each of these rate limits. `21:1` means the app made 21 calls in 1 second (which is where the rate limit was exceeded) and `36:120` says 36 calls were made in the last 2 minutes.
Lastly, **Retry-After** tells you when you can expect the rate limit to be reset. Definitely a little odd that the value isn't 1, but it does look like rate limiting is working as expected in this case.

Which test above do you believe illustrates the issue shown in the call you shared the headers for?

**Comment by paaksing** [comment]
That is the test 1 I made, I made the same exact test again. As you can see the first 20 calls didn't have problem at all, problem started at the second half of the 20 calls. which I don't get HOW can it 429 at `36:120` if its clearly still on the middle of the second 20 calls. Somehow the first 20 calls went off to the second 20 calls.

**Comment by paaksing** [comment]
This issue doesn't have much impact and only happens on limits that has small timers which could be caused by latency roundtrips, but my rate limits checks for the headers before making concurrent calls. That said the first 20 calls went off, I make 1 request to check for the headers before actually making another 19 calls.

**Comment by paaksing** [comment]
After telling myself 100 times "This should be my spaghetti code, this should be my spaghetti code again". After dealing with hours on it, I've finally managed to find the bug on the rate limiter which was causing the inconsistency. Now the the limits are all working as expected even without a single millisecond added. Closing this ...
