### ISSUE TITLE
[REQUEST] Keybind All TFT Actions

### ISSUE THREAD

**Issue by tk-png** [RiotGames/developer-relations#375]
Allow players to control TFT primarily with keybindings instead of the heavy mouse-oriented style which it's currently in. If not, I would like to know if it would be legal for me to personally create some kind of overlay that would give me this feature.

Vim-esque keybinding options like moving champions on and off the board, buy and sell etc based on what tile the champions are on.

**Comment by RiotTuxedo** [comment]
This isn't the place to ask questions related to products that you're working on. You can ask in the [Developer Discord](http://discord.gg/riotgamesdevrel) or in an app note.

That said, this kind of product wouldn't be allowed.
