### ISSUE TITLE
[VAL] PUUID returned from the match endpoint gives 404 when passed to account-by-puuid endpoint

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#376]
**Bug Description**  
Some players from Valorant matches are impossible to find via the player from puuid endpoint (/riot/account/v1/accounts/by-puuid/{puuid})

**Problem Description**  
1. Lookup game `2e527b76-7f32-426d-b19b-f48e5641d44f` on KR 
2. Find the Sage player
3. Try to look them up via the by-puuid endpoint

**Expected Result**  
The account data.

**Actual Result**  
404

**Comment by RiotTuxedo** [comment]
Working as intended. The account was deleted.

**Comment by stelar7** [comment]
Could we get a different status code to differentiate "this account has never existed", and "this account was deleted"?
ie. 404 vs 204
