### ISSUE TITLE
[Account]

### ISSUE THREAD

**Issue by Alantlb** [RiotGames/developer-relations#379]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
A: Username: Oyashin, Summuner name: Alantlb
Have you played any of Riot's games or did you just create an account for the Developer Portal?
A: I have played League of Legends, but when I logged in with my account for the developer portal, it said that my account has been disabled.

**Issue Description**  
A clear and concise description of what the issue is.
A: When I logged in with my account for the developer portal, it said that my account has been disabled, even thugh it was my first time.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by RiotTuxedo** [comment]
Should be good now.

**Comment by Alantlb** [comment]
It's working now! Thank you!
