### ISSUE TITLE
[DOCS][BUG] lor-match-v1.MatchDto missing in docs

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#380]
https://developer.riotgames.com/apis#lor-match-v1/GET_getMatch

Has "Return value: MatchDto" but no information on what MatchDto is. I assume it matches the example JSON here: https://www.riotgames.com/en/DevRel/legends-of-runeterra-match-history

**Comment by RiotTuxedo** [comment]
Ah yea I think I [pinged](https://discordapp.com/channels/187652476080488449/633905002976378881/761353458049482802) the wrong person. It'll be updated soon.
