### ISSUE TITLE
[BUG] [LoR] lor-match-v1/GET_getMatch return 404 on matchID from "friend challenge"

### ISSUE THREAD

**Issue by AoshiW** [RiotGames/developer-relations#381]
**Expected Result**
The match data.

**Actual Result**  
404

**Developer Impact**
`Lor-match-v1/GET_getMatchIdsByPUUID` returns a `matchID` for which there is no data.

**Comment by RiotTuxedo** [comment]
We should have had documentation that made this more clear, but for now we've specifically chosen to exclude challenges from the lor-match-v1 API. The ideal implementation of this is that the matches don't show up in the matchlist, but for now these matches return a 404 as if they never existed.
