### ISSUE TITLE
[FEATURE REQUEST] Game Duration missing from LOR-MATCH 

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#383]
## Feature Request Description
Return game length.

## Expected Implementation
A concise length of the game.

## Actual Implementation
We tell the user "hey this game is an average of 10~15 min" or not even at all.

## Developer Impact
* A few bytes less of space on the json

**Comment by RiotTuxedo** [comment]
@paaksing this was considered and unfortunately purposefully excluded. This could change in the future, but for now I'm going to close this feature request.
