### ISSUE TITLE
[Account] gerback67 

### ISSUE THREAD

**Issue by gerback67** [RiotGames/developer-relations#385]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

**Issue Description**  
A clear and concise description of what the issue is.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by gerback67** [comment]
In league of legends mobile I cannot connect with the server it is always says yordle cannot be found ,please fix my account  gerback67

**Comment by Hi-Ray** [comment]
Hey there!

This isn't the page to ask for help for help with things like that
please contact support through support@riotgames.com or go to either 

https://support.riotgames.com/hc/en-us 
or 
https://support-wildrift.riotgames.com/hc/en-us.

We ask that you close this issue as this is where issues regarding
the Riot Games API (A tool which provides data to sites like op.gg)
are posted. 

Posting with issues regarding support or gameplay issues will simply
be ignored and most likely be closed anyway, It is advised you contact 
support with the details provided above.

Kind Regards
