### ISSUE TITLE
[FEATURE REQUEST] Adding player gold values.

### ISSUE THREAD

**Issue by ANN0Y1NGHACKER** [RiotGames/developer-relations#387]
Hi,

I was looking around in the live client API and LCU but couldn't find a request that returns the total gold on a team. I was wondering if `/liveclientdata/playerlist` can return player gold as well.

Thank You

**Comment by RiotTuxedo** [comment]
@ANN0Y1NGHACKER this was considered and unfortunately purposefully excluded. This could change in the future, but for now I'm going to close this feature request.

**Comment by themaxdavitt** [comment]
@RiotTuxedo would you be willing to provide the reasoning for why gold values were excluded? I was looking to develop a dynamic stream overlay using the Live Client Data API and not having access to that data severely limits its usefulness.

**Comment by LightshieldDotDev** [comment]
Its a value that isn't available to a player while playing the game so I can see reasoning behind it being excluded at least in live games (not so much in spectator).

However by now I believe Blitz.gg has created something that even tracks enemy gold values (This might be done through calculating minion + passive + kills) so I think this is a variable that could be reintroduced.

**Comment by GetPastTheMonkey** [comment]
The Mobalytics in-game overlay shows player and team gold, but I believe they use the combined costs of the purchased items to get a rough estimate. You might be able to cook something up yourself using the same method.

**Comment by elliejs** [comment]
I don't speak for Riot. I do know their stance has been roughly anything you can do on paper you can do with a program. Even accurate total team gold gives more information about pressure and team lead than anything you can get from being a person in game. So calculating approximate gold from item costs, takedowns, etc. makes sense -- you could do it with a piece of scrap paper -- but getting exact team gold values is super human.

**Comment by LightshieldDotDev** [comment]
While I agree with the general "you can do that on a piece of paper" approach, you can't do gold for all 10 player during the game on paper while considering where the gold is coming from, passive gold, turret plates gold, kill gold, shared assists gold, etc.

Maybe believable if you had some insanely well prepped premade datasheet to just fill in but even that takes away from your focus extensively.

**Comment by RiotTuxedo** [comment]
These values were excluded mostly based on the principle of the game's design. Gold values aren't displayed in-game. Why? You'd have to ask the designers, but exposing data that the designers decided to obfuscate is the concern here.

As for apps that implement this kind of functionality, it'll depend on their implementation. If we determine there is a competitive advantage being created, we might ask these features be removed from these apps.
