### ISSUE TITLE
[BUG] Longest Time SpentLiving

### ISSUE THREAD

**Issue by FlorianMifsud** [RiotGames/developer-relations#389]
**Bug Description**  
If the game lasts 50 min and the player dies at only 10 min, the longestTimeSpentLiving will be 600 seconds not 2400 exemple match 4870039388, Sharrked last die: at 8min; "longestTimeSpentLiving": 255 game duration 1597

**Expected Result**  
longestTimeSpentLiving: ~1117

**Actual Result**  
longestTimeSpentLiving: 255

* Frequency: Every API call.
* Severity: My game is buggy because the person has to guess if the person stays alive X minutes*

**Comment by RiotTuxedo** [comment]
I'm not sure if I fully understand what you mean by this.

> My game is buggy because the person has to guess if the person stays alive X minutes*

Also to confirm, this is an issue with League of Legends match-v4 API, correct?

**Comment by FlorianMifsud** [comment]
> Also to confirm, this is an issue with League of Legends match-v4 API, correct?

Yep; look this match https://euw1.api.riotgames.com/lol/match/v4/matches/4870039388
`
"gameDuration": 1597,
"stats": {
                "participantId": 5,
                "win": true,
                "assists": 18,
                "largestKillingSpree": 4,
                "largestMultiKill": 1,
                "killingSprees": 1,
                "longestTimeSpentLiving": 255,
                "statPerk2": 5002
            },`
The last death is 8 min,so longestTimeSpentLiving should be at 1117

**Comment by LightshieldDotDev** [comment]
This seems to, at least in the example provided, be an issue that there is no value calculated between last death and end of game.

Times are calculated from start -> first death as well as death x -> death x +1.
> if the player does not die it also remains at 0;
Seems to trigger a count for each death event.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported, feel free to re-open or comment if you feel this is in error or is impacting Match-V5
