### ISSUE TITLE
The gameType parameter is not populated correctly for the 2nd and 3rd tutorials

### ISSUE THREAD

**Issue by Colliflower** [RiotGames/developer-relations#39]
**Preconditions**
- This result can be seen on either the match-v3 or match-v4 endpoints.
- Game was played on NA1.

**Steps to reproduce**
- Play the 2nd or 3rd tutorial
- Find the matchId through the matchlist endpoint
- Look up the match info by the matchId on the match-v3 or match-v4 endpoint

**Expected Result**
- gameType is TUTORIAL_GAME

**Actual Result**
- gameType is MATCHED_GAME

**Example matches**
2nd tutorial: https://na1.api.riotgames.com/lol/match/v4/matches/2936222804
3rd tutorial: https://na1.api.riotgames.com/lol/match/v4/matches/2936207791

Additional note, the gameMode fields are TUTORIAL_MODULE_2/3, which aren't listed as a possible values in the GAME MODES table here https://developer.riotgames.com/game-constants.html

**Comment by lucasMesquitaBorges** [comment]
Closing old issues. `match-v3` and `match-v4` were deprecated.

If you have questions or issues about `match-v5` feel free to open a new issue.
