### ISSUE TITLE
[BUG] LOR card types are missing from the DD globals file

### ISSUE THREAD

**Issue by catsclaw** [RiotGames/developer-relations#391]
**Bug Description**  
The translations for card types are missing from the DD globals file

**Problem Description**  
The documentation states "The global.json file contains sets of values that are reused throughout various cards. This includes keywords, rarities, regions (otherwise known as factions), spell speeds, and card types." but, checking the global file at https://dd.b.pvp.net/1_12_0/core/en_us/data/globals-en_us.json there are no card types listed.

**Expected Result**  
I expected to find the translations

**Comment by paaksing** [comment]
It makes NO sense to include the card types as it only has 2 possible values: "Unit" and "Spell" and it HAS NO translation for those types, all cards uses the ENGLISH card type. If you wish this to be included open a FEATURE REQUEST instead.

**Comment by catsclaw** [comment]
They've already added "Landmark" to the game, and I can assure you it's not called "Landmark" in Portuguese or Russian or Korean. And I can promise that, because I checked the cards.

It would be nice to get icons for the different card types as well; I notice the art for monuments has one, so I assume there's one for the other card types even if it's not on the cards.
