### ISSUE TITLE
[DOC] Spectator v4 featured games missing field in documentation

### ISSUE THREAD

**Issue by simivar** [RiotGames/developer-relations#392]
**Bug Description**  
While looking at [Spectator v4 featured games docs](https://developer.riotgames.com/apis#spectator-v4/GET_getFeaturedGames) object `FeaturedGameInfo` doesn't have  `gameTypeConfigId` field that is returned by API

**Problem Description**  
`gameTypeConfigId` field should be part of the documentation of `FeaturedGameInfo` class

**Expected Result**  
`gameTypeConfigId` field should be part of the documentation of `FeaturedGameInfo` class

**Actual Result**  
no `gameTypeConfigId` field in `FeaturedGameInfo` class fields list

**Developer Impact**  
Unlisted field/property can be aproblem when working with API as:
- developers can miss that such property exists
- developers must guess what type this property has
- developers must guess what this property means
- developers can't be sure that it's expected and will not be deleted

**Comment by simivar** [comment]
The same is true for `skinIndex` property of `Participant` class, it's missing from the documentation

**Comment by AoshiW** [comment]
**Preconditions**
Use developer key

**Comment by paaksing** [comment]
`skinIndex` might get deleted since MATCH-V4 doesn't have it, this issue will be more suited with a [DOC] prefix instead of a [BUG] prefix since it is working just not documented. We normally assume things that are not documented will be deleted at some time and not include that field into any consideration.

**Comment by MingweiSamuel** [comment]
As far as I can tell these fields are no longer returned slash `gameQueueConfigId` is used now.

**Comment by tisbells** [comment]
Closing this out as Spectator-V4 was deprecated in favor of Spectator-V5. `gameQueueConfigId` is available in Spectator-V5.
