### ISSUE TITLE
[BUG] Missing "miniSeries" property of League v4 API

### ISSUE THREAD

**Issue by simivar** [RiotGames/developer-relations#396]
**Bug Description**  
In the documentation of League v4 endpoints it says that `LeagueItemDTO` has `miniSeries` (MiniSeriesDTO) property but it is not returned by any of the requests. 

**Problem Description**  
Missing property from API response

**Expected Result**  
`miniSeries` property in the response
or marked property as optional 
or removed property from documentation 

**Actual Result**  
no `miniSeries` property

**Comment by AoshiW** [comment]
if summoner don't have promo series (e.g. from `silver II` to `silver I`) this field is exclude from response

**Comment by tisbells** [comment]
Closing out old issues as this was answered - If this is still an issue feel free to reopen or comment.
