### ISSUE TITLE
[BUG] A dude has a 8-char tagLine, so that this dude is 404 from by-riot-id/{gameName}/{tagLine}

### ISSUE THREAD

**Issue by wangyi041228** [RiotGames/developer-relations#398]
"gameName": "breeze of wind",
"tagLine": "HMSLIVLY"

This dude has a 8-char lagLine, so that this dude is 404 from GET /riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}.
This dude is participants[0] in LoR match_id 9324f343-5297-44b5-b06e-d02cee485b4b.

**Comment by wangyi041228** [comment]
23-char gameName

"gameName": "IS1181f4355098916af9677"
"tagLine": "NA1"

participants[0] in LoR match_id
f43aeaa2-194d-40a1-a40c-894fe1929eed

**Comment by RiotTuxedo** [comment]
Thanks for this report. Sorry it took so long to acknowledge. We're looking into it.

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
