### ISSUE TITLE
Some documentation pages contain links to removed APIs

### ISSUE THREAD

**Issue by Derpthemeus** [RiotGames/developer-relations#4]
https://developer.riotgames.com/item-sets.html - Contains links to lol-static-data-v1.2

https://developer.riotgames.com/tournament-api.html - Contains a link to https://developer.riotgames.com/api-methods/#tournament-provider-v1/GET_getLobbyEventsByCode (not v3)

Issue migrated from https://discussion.developer.riotgames.com/questions/1299/out-of-date-information-in-api-documentation.html

**Comment by RiotTuxedo** [comment]
The documentation has been updated. Considering this issue resolved.
