### ISSUE TITLE
[BUG] 404 Error on Recent Match for TFT-Match-V1

### ISSUE THREAD

**Issue by waslo** [RiotGames/developer-relations#400]
**Bug Description**  
Match ID NA1_3636415523 returns a 404 error code.

**Problem Description**  
When looking up Mean Mister Kien's TFT history (ign: mean mister kien), it returns
`[
    "NA1_3636471415",
    "NA1_3636415523",
    "NA1_3635900536"
]`

When checking `NA1_3636415523` (2nd match ID) against TFT_Match_V1, it's returning a 404 error. The 1st and 3rd match both return proper responses.

**Expected Result**  
I expected a 200 or 503 response code.

**Actual Result**  
[In the League client, the match just shows up as a blank. The match was never cached on lolchess for Kien, and as far as I can tell they just skip it.](https://media.discordapp.net/attachments/728011676456321124/771079137569013810/unknown.png)
The API returns a 404 error.

**Developer Impact**  
This match was not causing issues 5 hours ago, it suddenly started throwing 404. The code to check if 10 ranked matches have been played in the last week by a specific player was able to parse this match. It seems that the matchID was either introduced recently, or the match data was deleted.

With the match unable to be checked for queue ID to see if it's ranked/normal, this makes it impossible to guarantee that there have been 10 ranked games played in the last week.

* Frequency: Every API call.

**Player Impact**  
* Quantity: This is the only player in the top 170 with this issue at the moment, but it popped up suddenly, so unknown how prolific it will be..
* Region: This affects players in NA, unknown for other regions.

**Repro Steps**  
Check the match using the match ID through TFT-Match-V1

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
