### ISSUE TITLE
Wild Rift provides official api？

### ISSUE THREAD

**Issue by endless001** [RiotGames/developer-relations#401]
I want to get Record information, don't know that riot provides API?

**Comment by RiotTuxedo** [comment]
This is a question better suited for the [Discord](https://discord.gg/riotgamesdevrel). We typically handle technical issues/requests here. If you'd like you can follow our [Twitter](https://twitter.com/RiotGamesDevRel) or [blog](https://www.riotgames.com/en/DevRel) for announcements.
