### ISSUE TITLE
[BUG][DOCS] tft-match-v1.UnitDto missing field "chosen"

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#403]
`tft-match-v1.UnitDto` docs are missing the field `"chosen"`

https://europe.api.riotgames.com/tft/match/v1/matches/EUW1_4899709674
```json
{
  "character_id": "TFT4_Sylas",
  "chosen": "Set4_Brawler",  <---
  "items": [],
  "name" :"",
  "rarity": 1,
  "tier": 2
}
```

Via @whyando https://github.com/MingweiSamuel/Riven/issues/20

**Comment by RiotTuxedo** [comment]
The [documentation](https://developer.riotgames.com/apis#tft-match-v1/GET_getMatch) has been updated.
