### ISSUE TITLE
[BUG] tft-match-v1.UnitDto 'name' field empty string

### ISSUE THREAD

**Issue by whyando** [RiotGames/developer-relations#404]
The unit name field is an empty string.
Frequency: every time recently.

https://europe.api.riotgames.com/tft/match/v1/matches/EUW1_4899709674

{
  "character_id": "TFT4_Sylas",
  "chosen": "Set4_Brawler",  
  "items": [],
  "name" :"", <---
  "rarity": 1,
  "tier": 2
}

**Comment by RiotTuxedo** [comment]
Can you elaborate on the impact of this bug? It's been a little inconsistent for a while, but for now it's a low priority to fix because of it's low impact.

**Comment by whyando** [comment]
Low impact

The lack of this field doesn't hinder me, but it is fairly exposed to anybody using this API.

**Comment by RiotTuxedo** [comment]
I've added a note to the [documentation](https://developer.riotgames.com/apis#tft-match-v1/GET_getMatch) that this field is often left blank.

**Comment by tisbells** [comment]
Closing old issues; this was resolved
