### ISSUE TITLE
[LOR][Feature Request] Making the LOR Match API fail if the player is in-game to remove any possible in-game unfairness 

### ISSUE THREAD

**Issue by dahmadjid** [RiotGames/developer-relations#407]
currently using the LOR Match API it can be used as cheating or making a match unfair where player-1 can view the match history of player-2 while in-game. Thus giving player-1 an advantage over player-2 by viewing the decks he played with.
Of course I know that you would need both the tagline and the game name to access that data but its possible to guess the tagline if its the default region one (mine is EUW when im in EUW) so this kind of unfairness can happen for some players.
To remove this possibility all together, making the API request fail if the player is in game makes viewing the match history only available to view your own personal match history and not giving you a possible advantage against other players

**Comment by bangingheads** [comment]
Making the API request itself fail wouldn't solve any issue as matches can be cached. As well as having matches fail would cause a lot of confusion.

This would end up more of a developer policy problem than a technical problem.

**Comment by tisbells** [comment]
Closing out old issues. Scouting is in general against the LoR policy and there is no live data in the API.
