### ISSUE TITLE
champion-v4 (champion-rotation) not available

### ISSUE THREAD

**Issue by torlenor** [RiotGames/developer-relations#41]
I'm sorry if I missed something, but the champion-rotation endpoint for v4 is not available. If there is another (new) way to retrieve this information, please make a note on the champion-v3 api reference page.

**Comment by Colorfulstan** [comment]
Afaik (but I might have missed something too), only endpoints that have breaking changes are moved to v4.
The remaining stay in v3 (at least for now) as they can stay as they are.

Uneffected Endpoints should be all of those, that do not include any Account- or SummonerIds.

**Comment by dschow** [comment]
Only APIs which are changing because they include player ids are being versioned up. The champion-v3 endpoint is still the most current API and will remain in place.

**Comment by RiotTuxedo** [comment]
Only APIs which are changing because they include player ids are being versioned up. The champion-v3 endpoint is still the most current API and will remain in place.
