### ISSUE TITLE
[BUG] [VALORANT]

### ISSUE THREAD

**Issue by raffibaihaqy** [RiotGames/developer-relations#412]
**Bug Description**  
Jett on haven

**Problem Description**  
there's a bug with jett that u can see opponent at 'c long' from the top of the roof with sage wall and updraft 2x

<img width="645" alt="bug_jett_haven" src="https://user-images.githubusercontent.com/42157989/99152470-98002280-26d4-11eb-946b-be3ebd81c1ca.png">

**Comment by Querijn** [comment]
This is not the right place for these kind of requests.

Also, this might be a shocking concept, but you can look over walls.

**Comment by Daved-byte** [comment]
hmm interesting 
lemme try this one 😜
