### ISSUE TITLE
[BUG][TFT] CompanionDTO missing from the docs 

### ISSUE THREAD

**Issue by simivar** [RiotGames/developer-relations#413]
**Bug Description**  
In docs of TFT Match version 1 CompanionDTO is missing: https://developer.riotgames.com/apis#tft-match-v1/GET_getMatchIdsByPUUID

**Comment by MingweiSamuel** [comment]
https://github.com/RiotGames/developer-relations/issues/275

**Comment by MingweiSamuel** [comment]
#487

**Comment by tisbells** [comment]
Closing, covered in https://github.com/RiotGames/developer-relations/issues/487. Will update there if changes are made.
