### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 312612396** [RiotGames/developer-relations#415]
I play LOL with the JP server and that have system error and crash dump.
they want me to share the file with the development team.
[PKMC09C.zip](https://github.com/RiotGames/developer-relations/files/5577735/PKMC09C.zip)

**Comment by Hi-Ray** [comment]
Hey there!

This isn't the page to ask for that for help with things like that
please contact support through support@riotgames.com or go to either

support.riotgames.com/hc/en-us
or
support@riotgames.com

We ask that you close this issue as this is where issues regarding
the Riot Games API (A tool which provides data to sites like op.gg)
are posted.

Posting with issues regarding support or gameplay issues will simply
be ignored and most likely be closed anyway, It is advised you contact
support with the details provided above.

Kind Regards
