### ISSUE TITLE
[BUG] [LOL] match-v4 - Total games value for matchlist given account ID is not correct

### ISSUE THREAD

**Issue by AlterEchoes** [RiotGames/developer-relations#417]
**Bug Description**  
When using the above API, the "totalGames" amount is not precise

**Problem Description**  
When the above API is run with no Indexes specified, the total number of games that is returned differs from the total number of games returned when the same API is run with indexes

**Expected Result**  
A higher number of games when the API is run without indexes

**Actual Result**  
Less number of games than the actual ones

**Developer Impact**  
The total number of games is not precise

**Frequency**
Every API call

**Comment by supergrecko** [comment]
I assume you're using `/matchlists/by-account/{encryptedAccountId}`? This is a known problem as noted in the documentation (https://developer.riotgames.com/apis#match-v4/GET_getMatchlist).

> There is a known issue that this field doesn't correctly return the total number of games that match the parameters of the request. Please paginate using beginIndex until you reach the end of a player's matchlist.

**Comment by AlterEchoes** [comment]
Hi, i missed that warning line, sorry for the post then.
