### ISSUE TITLE
[BUG] [LoL] Replay API - interfaceChat setting does not work

### ISSUE THREAD

**Issue by pattersttv** [RiotGames/developer-relations#418]
**Bug Description**  
After a chat event happens in spectator, the chatbox reappears even if previously disabled by setting "interfaceChat" = false. Any calls to set "interfaceChat" = false during this time whilst the chatbox is open has no visible ingame effect.

**Expected Result**  
After setting "interfaceChat" =  false, the chatbox should no longer appear for any reaosn.

**Actual Result**  
After setting "interfaceChat" =  false, the chatbox continues to appear following a chat event.

**Developer Impact**  

* Frequency: Every API call.
* Severity: Low (Chatbox can be hidden behind other things for esports usage)
* Cost: N/A
* Efficiency: N/A

**Repro Steps**  
1. Start spectating
2. Send a request disabling chat (interfaceChat = false)
3. Wait for a chat event (first blood, item purchase, etc)
4. It reappears.

**Comment by tisbells** [comment]
Closing out old issues. We've received no recent reports of this. Feel free to reopen or comment if you feel this is in error.
