### ISSUE TITLE
[BUG] Missing all Ornn item upgrades in Data Dragon's "item.json"

### ISSUE THREAD

**Issue by 1337MARCEL** [RiotGames/developer-relations#419]
**Bug Description**  
I am missing all Ornn item upgrades since the release of the preseason item changes in Data Dragon's `item.json` for both patch [10.23](https://ddragon.leagueoflegends.com/cdn/10.23.1/data/en_US/item.json) and [10.24](https://ddragon.leagueoflegends.com/cdn/10.24.1/data/en_US/item.json).

**Problem Description**  
Data Dragon's `item.json` does not include data about any Ornn item upgrade.

A list of all Ornn item upgrades:
|ITEM ID|ENGLISH ITEM NAME|
| ------------- |-------------|
|7000|Sandshrike's Claw|
|7001|Syzygy|
|7002|Draktharr's Shadowcarver|
|7003|Turbocharged Hexperiment|
|7004|Forgefire Crest|
|7005|Rimeforged Grasp|
|7006|Typhoon|
|7007|Wyrmfallen Sacrifice|
|7008|Bloodward|
|7009|Icathia's Curse|
|7010|Vespertide|
|7011|Upgraded Aeropack|
|7012|Liandry's Lament|
|7013|Eye of Luden|
|7014|Eternal Winter|
|7015|Ceaseless Hunger|
|7016|Dreamshatter|
|7017|Deicide|
|7018|Infinity Force|
|7019|Reliquary of the Golden Dawn|
|7020|Shurelya's Requiem|
|7021|Starcaster|
|7022|Seat of Command

**Expected Result**  
I expect the `item.json` to include all items that are available in the game.

**Actual Result**  
The `item.json` does not include data about any Ornn item upgrade.

**Player Impact**  
Player's are missing their by Ornn upgraded items.

Screenshot of sites that uses Data Dragon as a data source for items, where they are only able to display 3/4 items.
![image](https://user-images.githubusercontent.com/16888873/100230173-a5fc4180-2f25-11eb-8323-76ce9f353a26.png)

![image](https://user-images.githubusercontent.com/16888873/100230069-7fd6a180-2f25-11eb-844f-70574377bea5.png)

Screenshot of a site that uses Community Dragon as a data source for items, where they are able to display 4/4 items.
![image](https://user-images.githubusercontent.com/16888873/100229755-05a61d00-2f25-11eb-9b13-e08404c438ed.png)

**Comment by 1337MARCEL** [comment]
Issue remains on the latest release ([10.25.1](https://ddragon.leagueoflegends.com/cdn/10.25.1/data/en_US/item.json)).

**Comment by chielteuben** [comment]
Issue still exists on [11.1.1](https://ddragon.leagueoflegends.com/cdn/11.1.1/data/en_US/item.json) sadly.

**Comment by RiotTuxedo** [comment]
The team is aware. But it doesn't look like the fix will be in place for 11.2.

**Comment by ClaudeyCloud** [comment]
Issue still exists on 11.4.1 D:

**Comment by 1337MARCEL** [comment]
Issue is solved on [11.9.1](https://ddragon.leagueoflegends.com/cdn/11.9.1/data/en_US/item.json). Time to remove the workaround. Thanks Rito. 🏆

**Comment by thisKeeWord** [comment]
Though resolve on 11.9.1, the upgrades are missing in [11.18.1](https://ddragon.leagueoflegends.com/cdn/11.18.1/data/en_US/item.json).

**Comment by PrevotYann** [comment]
Still missing on 12.1.1

**Comment by thisKeeWord** [comment]
New one opened here: #590
