### ISSUE TITLE
[BUG] Loading screen critical crash

### ISSUE THREAD

**Issue by Darkspeedster** [RiotGames/developer-relations#420]
**Bug Description**  

**Problem Description**  
A clear and concise description of what the problem is.

**Expected Result**  
What were you expecting to happen after you performed the above steps? Include screenshots, logs, or a description.

**Actual Result**  
What actually happened after you performed the above steps? Include screenshots, logs, or a description.

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call. Once every ~100 API calls.
* Severity: When it happens, my whole website crashes.
* Cost: Requires me to run X more servers to compensate for the issue costing me on average $200 of additional spend a month.
* Efficiency: Requires me to make 10x more API calls than necessary to compensate for the issue.
* User emails: I get frequent emails from users asking me about this issue.
* Etc

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

* Frequency: Every time the user visits the site, they experiennce this issue. Once every ~100 visits this issue occurs.
* Severity: When this bug happens, a user is unable to use my site. I have 200 visits to my site each day, so it affects 50% of site visits.
* Quantity: There are ~1k players that experience this issue.
* Region: This affects players in NA and EUW.
* Etc

**Preconditions**  
What conditions must be met in order for this bug to occur?

* First condition
* Second condition

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Step 1
1. Step 2

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by Darkspeedster** [comment]
When i try to play league of legends i cant load into the loading screen, the client is working as usual but before i get to the loading screen i get a critical error

**Comment by Token07** [comment]
Hello there.

Please ensure you read all of the README.md, specifically this part:
> Verify that the issue you are about to report relates to the Riot Games Developer Ecosystem and is not a game bug (for game bugs please go here).

**Comment by RiotTuxedo** [comment]
For the reasons @Token07  mentioned, this question isn't suitable for this channel.
