### ISSUE TITLE
[BUG] [LOL] /lol/match/v4/matches/{matchId}

### ISSUE THREAD

**Issue by draphikas** [RiotGames/developer-relations#421]
**Bug Description**  
Role and Lane are not set correctly

**Problem Description**  
We should have 5 participants at one different role but sometimes there are 2 junglers, 3 supports or nothing in the same team

**Expected Result**  
{
"platformId": "EUW1",
"gameId": 4945772035,
"champion": 134,
"queue": 420,
"season": 13,
"timestamp": 1606229110690,
"role": "DUO",
"lane": "NONE"
}n.

**Actual Result**  
{
"platformId": "EUW1",
"gameId": 4945772035,
"champion": 134,
"queue": 420,
"season": 13,
"timestamp": 1606229110690,
"role": "DUO",
"lane": "MIDDLE"
}

**Other example (2 junglers same team in Summoner's Rift)**
Match ID: 4906054293
{
            "participantId": 2,
            "teamId": 100,
            "championId": 39,
            "spell1Id": 4,
            "spell2Id": 12,
            "stats": {...}
            "timeline": {
                "participantId": 2,
                "creepsPerMinDeltas": {
                    "10-20": 6.4,
                    "0-10": 7.199999999999999,
                    "20-30": 6
                },
                "xpPerMinDeltas": {
                    "10-20": 468.79999999999995,
                    "0-10": 462.5,
                    "20-30": 422.20000000000005
                },
                "goldPerMinDeltas": {
                    "10-20": 484.4,
                    "0-10": 352.29999999999995,
                    "20-30": 312.5
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.75,
                    "0-10": 0.9500000000000002,
                    "20-30": -0.3500000000000001
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 15.350000000000023,
                    "0-10": 139.05000000000007,
                    "20-30": -386.1499999999999
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1540.5,
                    "0-10": 674.9000000000001,
                    "20-30": 1096.4
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 408.6999999999998,
                    "0-10": 144.85000000000005,
                    "20-30": 34.35000000000008
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },
        {
            "participantId": 3,
            "teamId": 100,
            "championId": 76,
            "spell1Id": 4,
            "spell2Id": 11,
            "stats": {...},
            "timeline": {
                "participantId": 3,
                "creepsPerMinDeltas": {
                    "10-20": 1.4,
                    "0-10": 0.9,
                    "20-30": 1
                },
                "xpPerMinDeltas": {
                    "10-20": 710.7,
                    "0-10": 447.29999999999995,
                    "20-30": 401.6
                },
                "goldPerMinDeltas": {
                    "10-20": 685.9,
                    "0-10": 346.1,
                    "20-30": 427
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.75,
                    "0-10": 0.9500000000000002,
                    "20-30": -0.3500000000000001
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 15.350000000000023,
                    "0-10": 139.05000000000007,
                    "20-30": -386.1499999999999
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 964.5999999999999,
                    "0-10": 717.2,
                    "20-30": 1300.7
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 408.6999999999998,
                    "0-10": 144.85000000000005,
                    "20-30": 34.35000000000008
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },

**Developer Impact**  
Can't define correctly the opponent champion of my players or if they played the right lane / got autofilled

* Frequency: Between once every 5 and 10
* Severity: When it happens, it's just annoying
* Cost: Nothing, just bad information

**Comment by Token07** [comment]
See #252

**Comment by Token07** [comment]
and #23

**Comment by draphikas** [comment]
Oh, I didn"t see, thanks
So I supposed I can close this
