### ISSUE TITLE
[BUG] Skin Boost

### ISSUE THREAD

**Issue by Tortudereli** [RiotGames/developer-relations#423]
**Bug Description**  
Skin boost is enabled when the /lol-champ-select/v1/team-boost/purchase POST request is sent, even if not enough RP is available.

**Comment by sousa-andre** [comment]
Riot knows about it. They probably won't fix until players start overusing it.

**Comment by tisbells** [comment]
Closing old issues, there have been no recent reports of this. Feel free to reopen if you are still experiencing problems with this.
