### ISSUE TITLE
[BUG][LOL] MatchV4 by tournament code endpoint returns 504

### ISSUE THREAD

**Issue by milanstojanovic88** [RiotGames/developer-relations#424]
[Matches by tournament code](https://developer.riotgames.com/apis#match-v4/GET_getMatchByTournamentCode) API endpoint returns the response with the code 504.

When checked manually, on the API Documentation page, with same parameters, we can see that the match data actually exists. However, when trying to fetch the data using PHP curl functionality, for some matches, we get an error (504).

Is there any way to get around this problem?

**Comment by bangingheads** [comment]
504 is a gateway timeout error. You will need to have error handling on your side to retry your call if you hit a timeout.

**Comment by milanstojanovic88** [comment]
Thank you for the fast reply.

That's exactly what we are doing. We are attempting to fetch the data for each match up to 5 times, over the period of 1 hour, until success. Evidently, for some matches, we are not able to get the data even after the 5th time.

How long does the timeout usually last?

**Comment by paaksing** [comment]
@milanstojanovic88  504 doesn't _last_, just retry a second time and it should go through, your case is weird, please check your code

**Comment by milanstojanovic88** [comment]
Nothing wrong with the code. It's a simple HTTP request that we are making, using the correct credentials, and sending proper parameters for match_id and tournament_code.

It works for most of the matches, but for couple of them, it fails up to 5 times with the same error: 504.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported, feel free to re-open or comment if you feel this is in error.

**Comment by AoshiW** [comment]
@tisbells  you forgot to close the issue.

**Comment by tisbells** [comment]
ty, actually closing this time :)
