### ISSUE TITLE
[BUG?] Valorant matchlist resets once in a while

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#426]
**Bug Description**  
Fetching the matchlist for a player only gives back some of the games played, possibly limited to the latest season?

**Expected Result**  
All games returned, or some sort of pagination.

**Developer Impact**  
* Frequency: Every API call. 

**Player Impact**  
Players expecting to see all their stats will only see some of their games

**Comment by tisbells** [comment]
Closing old issues - VAL match history is limited to roughly the last 100 matches.
