### ISSUE TITLE
[BUG] Wrong response from featured-games in the Spectator api

### ISSUE THREAD

**Issue by luanpiegas** [RiotGames/developer-relations#427]
**Wrong response from Spectator v4**  
Endpoint returns wrong games for the region specified.

**Problem Description**  
When fetching LA1 or LA2 games, the api returns BR1 games in the featured-games endpoint

**Expected Result**  
When 
GET https://la1.api.riotgames.com/lol/spectator/v4/featured-games?api_key={API_KEY}
or
GET https://la2.api.riotgames.com/lol/spectator/v4/featured-games?api_key={API_KEY}
The response should be:
"platformId": "LA1",
or 
"platformId": "LA2",

**Actual Result**  
"platformId": "BR1",

**Developer Impact**  
In my chromium based browser extension, this bug show wrong games in the game list, from the wrong region.

* Frequency: Every API call.
* Severity: LAN and LAS games are wrong
* Cost: 0
* Efficiency: Not aplied
* User emails: Not aplied

**Player Impact**  
Not aplied

**Preconditions**  
Every /spectator/v4/featured-games from la1 and la2

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. GET https://la1.api.riotgames.com/lol/spectator/v4/featured-games?api_key={API_KEY}
1. check "platformId": in the gameList object.

**Comment by RiotTuxedo** [comment]
Hey @luanpiegas,

These three regions utilize the same spectator cluster. As a result, the featured games returned from the service for these regions can contain games from any of these three regions. This is working as expected.
