### ISSUE TITLE
[BUG] Empty summonerName on some summoner infos

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#428]
Hey there

I've noticed the following issue a few days ago. Not sure when the bug started. 

The _summoner/v4/summoners_ endpoint "name" field can sometimes be empty. For instance the summoner with encrypted summonerId "eXGw6DuQR7Nyvdl0MPl3_XNrdkPgdSFyyWv9NR1g6L5_gW9B4PRbe2YB1g" in OCE. 

This bug makes the player not searchable (therefore the data for those players can not be found) on any website. 
I've identified around 2000 accounts affected by this issue atm. It's quite hard to get an actual count as I've added sanity checks to reject such accounts from my database (as they were creating other issues... An empty name is not something I handled well)

All the accounts I checked seem to be very new accounts (only a few intro games played in the last few days)

Thanks guys !

**Comment by trebonius0** [comment]
After investigation, I'm 99% sure that the vast majority of those accounts are created and operated by bots. 
Email me or DM me on discord if you want the complete list of those accounts. 

Thanks

**Comment by RiotTuxedo** [comment]
This is a known issue. There's some changes already being worked on to require players to create a summoner name before playing any more games. Those are tentatively scheduled to go out in 11.2, after that point if you continue to players in games with no summoner names feel free to reopen this issue.
