### ISSUE TITLE
[BUG] Mastery API : Tokens Earned information expired ?

### ISSUE THREAD

**Issue by itachi42** [RiotGames/developer-relations#429]
**Bug Description**  
When asking RIOT API for champion masteries, it seems the Tokens Earned information is not kept indefinitely 

**Problem Description**  
Tokens Earned field is returned with **0** while champion level is 7. Normally to rearch level 7 you have to earn 5 tokens.

**Expected Result**  
 ```
   {
        "championId": 17,
        "championLevel": 7,
        "championPoints": 839619,
        "lastPlayTime": 1566940933000,
        "championPointsSinceLastLevel": 818019,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 5,
        "summonerId": "*************"
    }
```
**Actual Result**  
```
    {
        "championId": 17,
        "championLevel": 7,
        "championPoints": 839619,
        "lastPlayTime": 1566940933000,
        "championPointsSinceLastLevel": 818019,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "*************"
    }
```

**Issue Comments**  

Is the information only kept for 2-3 years ? 
Not really sure this is a bug or just a normal behaviour.
Couldn't find the information about the persistence of such data.

**Comment by bangingheads** [comment]
This is not a bug. Your tokensEarned is the earned tokens at the current championLevel.

You need 2 on level 5 to advance to 6, then it would reset to 0, you need 3 to advance to 7, then it would reset to 0.

**Comment by itachi42** [comment]
Great answer.
Thank you !

**Comment by RiotTuxedo** [comment]
I've updated the documentation on the reference page to make this more clear.

> The token earned for this champion at the current championLevel. When the championLevel is advanced the tokensEarned resets to 0.
