### ISSUE TITLE
champion-mastery-v4 incorrectly encrypts lastPlayTime when it matches numeric summoner id

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#43]
Summoner: `B0Y NEXT D00R`
Region: `LA2`
Summoner ID: `40930`

Request: https://la2.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-summoner/d4lQv3Uv50MwiqXfK0SNJn7nOwLbDyumGliYNqEsMDY (app 212114, but works on any key)

Invalid response (not even valid JSON):
```json
{
	"championId": 42,
	"championLevel": 5,
	"championPoints": 22695,
	"lastPlayTime": 153085d4lQv3Uv50MwiqXfK0SNJn7nOwLbDyumGliYNqEsMDY00,
	"championPointsSinceLastLevel": 1095,
	"championPointsUntilNextLevel": 0,
	"chestGranted": false,
	"tokensEarned": 0,
	"summonerId": "d4lQv3Uv50MwiqXfK0SNJn7nOwLbDyumGliYNqEsMDY"
}
```

Assuming the `lastPlayTime` should be `1530854093000` (Thu Jul 05 2018 22:14:53 GMT-0700 (Pacific Daylight Time))

**Comment by stelar7** [comment]
related to #33 maybe?
