### ISSUE TITLE
[BUG] 503 Service Unavailable - GET val/content/v1/contents

### ISSUE THREAD

**Issue by kdefives** [RiotGames/developer-relations#430]
**Problem Description**  
Sometimes, when i call GET https://eu.api.riotgames.com/val/content/v1/contents the error 503 Service Unavailable occurs.

**Expected Result**  
This should not occurs.

**Developer Impact**  
Script failed due to this error. I had to implement a "retry" feature as a workaround on my application script.

* Frequency: I tested with a script every 15 minutes and it happens few times per day.
* Severity: When it happens, my script is crashing. But the severuty is not huge because we can implement a workaround.
* Cost: none
* Efficiency: Require to manage this errors on our application side.
* User emails: none (back-office scripts)
* Region: I use EUROPE cluster as my server is hosted in Europe.

**Repro Steps**  

1. Step 1 : Do a GET Curl to https://eu.api.riotgames.com/val/content/v1/contents

**Notes**

If you want more details about:
- when it happens exactly
- the X-Riot-Edge-Trace-Id 
- or something else to debug, do not hesitate to ask me!

**Comment by tisbells** [comment]
Closing out old issues and we've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
