### ISSUE TITLE
["Riot Sign On"Function] 

### ISSUE THREAD

**Issue by hiimayu** [RiotGames/developer-relations#432]
Hello :) Can developers apply for "Riot Sign On"?  
I find you provide this funtion by official blog:  https://riotgames.com/en/DevRel/rso 
I wanna apply it for our app, and I don't know how to access, pls help.

**Comment by Token07** [comment]
Greetings!
This issue tracker is exclusively for bugs within the scope of the DevRel team. Lack of access to RSO is not a bug.

And as it sounds like you already have an app, the appropriate forum for your inquiry would be to add an app note in the developer portal, but per the linked article:

> Do not submit a request for an RSO client. There are no applications, and we will not respond to asks from developers about this service. Our team will reach out to developers as we expand who has access.
