### ISSUE TITLE
[Feature Request] API to access the store / night market

### ISSUE THREAD

**Issue by elizabethnguyen** [RiotGames/developer-relations#433]
Hi there! I thought this would be a fun idea and I didn't think I've seen it requested in the issue tracker :)

---
As a user, I would like to be able to see what items are in my store/night market so that I can watch for daily deals/sales on items that I want to buy.

I'd like to be able to build a mobile application that allows players to see what items are in their store and market without having to log onto the client. Stretch goals would be to allow users to set notifications for specific cosmetics that they want to buy, as well as being able to see all cosmetics that have been historically available.

Ideas I have about the requests / return types:

* This could solely be for reads - actions such as purchasing could still be kept in the client. 
* Providing a static image of the item as a P0, but potentially being able to expand to displaying the variants and cosmetic levels of items (videos) as a nice-to-have, with maybe even a model viewer as a far-off stretch goal.

Calling an API to return a PlayerDTO may contain a ShopDTO which contains many OfferingDTOs.

An OfferingDTO may contain the following:

```
type Offering struct {
    currentPrice int
    originalPrice int // for discounts (i.e. bundle deals)
    priceIcon string 
    itemType string // enum for gun, card, buddy, etc.
    staticImageUrl string // base64, s3 link, etc.
    timeRemaining int64
    bundleName string // to tie bundles together
    variants []Offering
    levels []ItemLevels
}
```

I wrote this up sort of quickly, but this was just a general idea of what I think would be really cool if it could be provided \o/

Thanks for taking a look and interested in hearing your thoughts!

**Comment by WoodTangClan** [comment]
I agree this would be awesome.  Being able to check the store on mobile would be a huge plus.

**Comment by tisbells** [comment]
Hey there - Closing out old issues. Store checker is not currently a planned feature addition, but thank you for the suggestion!
