### ISSUE TITLE
[DOCS] Missing keys in PlayerDto of VAL-MATCH-V1/matches/*

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#435]
## Problem Description**  
`gameName` and `tagLine` is missing on the docs. Originally matches doesn't return these 2 values but since a few months ago it started returning them without a notice. And yet docs didn't reflect the change in like forever.

## Actual Dto
```
puuid | string |  
teamId | string |  
partyId | string |  
characterId | string |  
stats | PlayerStatsDto |  
competitiveTier | int |  
playerCard | string |  
playerTitle | string
```

## Expected Dto
```
puuid | string |  
gameName | string |  
tagLine | string |  
teamId | string |  
partyId | string |  
characterId | string |  
stats | PlayerStatsDto |  
competitiveTier | int |  
playerCard | string |  
playerTitle | string
```

**Comment by RiotTuxedo** [comment]
Thanks for the report. The documentation has been updated.
