### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by Leejung8763** [RiotGames/developer-relations#436]
**Account Information**
leejung8763

**Issue Description**  
When I log in Riot Developer Portal, I've got 
"You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on Twitter, during office hours on Discord, or create an GitHub issue." message.

**What I've Tried**
What steps have you tried to resolve the issue.
I just logged out in the Developer Portal.

**Comment by RiotTuxedo** [comment]
Are you still experiencing this issue? Would you mind trying to relog again?
