### ISSUE TITLE
[SECURITY LEAK] All VALORANT endpoints has no CORS validation

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#437]
## Security Leak Description  
All VALORANT endpoints returns `"Access-Control-Allow-Origin": "*"`

## Developer Impact
If there is no CORS validation -> Random braindead devs will just put API keys on client side without any restrictions (browser) -> Riot team starts experiencing random api keys leaking -> SHUT DOWN THE API AND WE GO EAT ____.

## Repro Steps
Just make a request.

## Issue Comments
It shouldn't have impacted much since it's still limited, but ... please give a bit more attention, everything in the Riot Third Party Community is sliding away in some way, sadly.

**Comment by RiotTuxedo** [comment]
Thanks for the report. This has been resolved.

**Comment by kdefives** [comment]
@RiotTuxedo Does it means now we have to set the correct Origin header on client side when we are doing an API call? 
Specially, in case of program running on server side for which we are not using any browser (or. Curl).

**Comment by thomasmarton** [comment]
@kdefives CORS is enforced by the browser, server side software (curl, node, etc.) don't enforce it. The goal with not supporting CORS is to prevent people using the API from the browser which would leak (and eventually blacklist) their API key.
