### ISSUE TITLE
[BUG] If a match ends while Viego is as another champions, the items displayed in the match json will be the ones from the "other champion"

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#438]
**Bug Description**  
If a match ends while Viego is as another champions, the items displayed in the match json will be the ones from the "other champion". Example on match BR-2168052719: Viego has Hecarim's items

**Expected Result**  
I would expect the items to be the Viego's ones. 

**Actual Result**  
The items are the ones from the champion he was transformed as

**Frequency**
100% repro rate in this particular case

**Player Impact**  
The player will see incorrect data in his match history, and the aggregated data for Viego will be slightly incorrect due to that issue

Thanks

**Comment by RiotTuxedo** [comment]
I'm hearing that there should be a fix for this in 11.3. Tomorrow would you mind checking to see if this bug still occurs?

**Comment by trebonius0** [comment]
I'll run some analysis on the data I download for a few days and let you know

**Comment by trebonius0** [comment]
@RiotTuxedo Doesn't seem to be fixed. 
Match NA-3772435619 Viego has Samira items (and he didn't buy those during the game)

**Comment by RiotTuxedo** [comment]
Following up on this. Thanks for the report.

**Comment by paaksing** [comment]
Timeline is also giving incorrect data, which breaks a bunch of apps that shows item purchasing order. Using that same id, when he posseses another champion, all his items gets destroyed, then destroys all the items of the possesed champion afterwards. There is no events when he gains back his own items. Either we need a flag that this was triggered by his passive, or not take record of these events at all.
```json
{
    "type": "ITEM_DESTROYED",
    "timestamp": 1564304,
    "participantId": 4,
    "itemId": 6672
},
{
    "type": "ITEM_DESTROYED",
    "timestamp": 1564304,
    "participantId": 4,
    "itemId": 3153
},
{
    "type": "ITEM_DESTROYED",
    "timestamp": 1564304,
    "participantId": 4,
    "itemId": 6333
},
{
    "type": "ITEM_DESTROYED",
    "timestamp": 1564304,
    "participantId": 4,
    "itemId": 3111
},
{
    "type": "ITEM_DESTROYED",
    "timestamp": 1564304,
    "participantId": 4,
    "itemId": 3044
},
{
    "type": "ITEM_DESTROYED",
    "timestamp": 1564304,
    "participantId": 4,
    "itemId": 1037
}
```

**Comment by dschow** [comment]
I've let the team know.

**Comment by RiotTuxedo** [comment]
I've let the team know.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported, feel free to re-open or comment if you feel this is in error.
