### ISSUE TITLE
[BUG] Image in pack (Samira)

### ISSUE THREAD

**Issue by d-osuch** [RiotGames/developer-relations#439]
**Bug Description**  
Bug image in assets from Developer Portal

**Problem Description**  
I downloaded packs from developer portal and Samira image was bad for assets. Samira had Sett image.

**Expected Result**  
Can you fix it?

**Comment by GetPastTheMonkey** [comment]
Duplicate of #372 

Additionally, @bangingheads is keeping a list of incorrect DDragon images in #348

**Comment by tisbells** [comment]
Closing old issues; resolved
