### ISSUE TITLE
Error 403 on every request in the dev portal [BUG] 

### ISSUE THREAD

**Issue by Eminooo** [RiotGames/developer-relations#440]
If i try to search for a summoner in Match-V4 or Summoner-V4 i always get error 403

I have created the dev account and refreshed the API-Key (btw im using a developement api-key).

See picture
<img width="762" alt="screen 2" src="https://user-images.githubusercontent.com/77936324/105640680-934bad80-5e7f-11eb-950f-a11564dbe1bb.PNG">
<img width="633" alt="screen 1" src="https://user-images.githubusercontent.com/77936324/105640682-93e44400-5e7f-11eb-86ce-c6c2a35e4e4b.PNG">

**Comment by Draycia** [comment]
Please remember to redact your token when sharing screenshots :)

**Comment by Eminooo** [comment]
forgot to blur that out...
I've refreshed it now, does not fix the issue :(

**Comment by ddiera** [comment]
issue only affects development keys

app-specific approved keys still work fine

**Comment by drshark** [comment]
Same problem here!

**Comment by chrissnyman** [comment]
Same problem here, only on EUW it seems

**Comment by RiotTuxedo** [comment]
We're looking into it.

**Comment by HusseinHroub** [comment]
Made new account and same issue, only at EUW1 and EUN1

**Comment by HusseinHroub** [comment]
Made new account and same issue, at EUW1, EUN1, JP1, KR, RU and TR1 regions.

**Comment by azandaki** [comment]
Same here, API calls to EUW1, EUN1, JP1, KR, RU and TR1 regions response is 403, rest of the regions are normal.

**Comment by dawidstefaniak** [comment]
Facing the same issue with dev keys.

**Comment by RiotTuxedo** [comment]
Hey all. I've confirmed this issue will affect any new apps as well as any key changes for apps served from the europe and asia clusters (EUW1, EUN1, JP1, KR, RU, TR1, EUROPE, ASIA, etc). There won't be any need to report if this issue is affecting more people (cause right now it'll affect everyone).

I'll post any updates as we get them.

**Comment by RiotTuxedo** [comment]
This issue should now be resolved. If you're still experiencing issues, let us know.

**Comment by arionminina** [comment]
Thank you for your effort.

**Comment by StachuuToJa** [comment]
@RiotTuxedo Still same problem.

**Comment by RiotTuxedo** [comment]
What's your riot id or summoner name?

**Comment by StachuuToJa** [comment]
itsmestachu. only summoner api works great.

**Comment by RiotTuxedo** [comment]
Just gave it a try, looks like it's working to me. Maybe you can hop into the developer discord to get help debugging your issue.
