### ISSUE TITLE
[BUG] JSON not parsing on the API on every region

### ISSUE THREAD

**Issue by arionminina** [RiotGames/developer-relations#442]
Everytime I try to execute an request on the website, in the response body this is shown: parsererror: SyntaxError: Unexpected token & in JSON at position 1

I expected a normal response body with all the information, but this came out instead.
![image](https://user-images.githubusercontent.com/74980331/106109484-e193d180-6149-11eb-8318-de5d368cb556.png)

This happens every API call and it cant let me proceed even when building my app in Python.

**Comment by RiotTuxedo** [comment]
Thanks for the report. This should be resolved now.
