### ISSUE TITLE
[BUG] LCU api lol-ranked/v1/ranked-stats/{puuid} return 0 losses

### ISSUE THREAD

**Issue by PainterHalver** [RiotGames/developer-relations#445]
**Bug Description**  
Wrong information

**Problem Description**  
When search for certain summoner, the "losses" data is always 0. If query self or high elo players (Challenger) it works fine but not for lower tiers.

**Expected Result**  
![image](https://user-images.githubusercontent.com/73751932/106724687-1799ef80-663b-11eb-818f-573ccd714e98.png)

**Actual Result**  
![image](https://user-images.githubusercontent.com/73751932/106724795-3ef0bc80-663b-11eb-9e46-231a0b721edc.png)

**Developer Impact**  
Can't find a way to include winrate

* Frequency: Every API call. 
* Severity: Irritating

* Region: Tested on VN and JP clients

**Repro Steps**  
1. Get puuid from /lol-summoner/v1/summoners
1. Plug it in /lol-ranked/v1/ranked-stats/{puuid}

**Comment by RiotTuxedo** [comment]
We don't offer any support for LCU APIs per our documentation.
https://developer.riotgames.com/docs/lol#league-client-api
