### ISSUE TITLE
Web match history summoner highlight not usable since V4

### ISSUE THREAD

**Issue by xxxxxaaaaaaaannnn** [RiotGames/developer-relations#45]
Hello,

Since V4, it's not possible to use the matchhistory web portal with the highlighted summoner because of account id encryption. Like I already pointed out on #13, the matchHistoryUri remains plain text, but that would only work if the summoner didn't change to another region.

For example : 

https://matchhistory.euw.leagueoflegends.com/en/#match-details/EUW1/2885900831/229854008?tab=overview

For the highlight to work, you need the game id (duh) and account id : https://matchhistory..../#match-details/EUW1/<game id>/<account id>?tab=overview

Now, about that specific summoner : 

https://euw1.api.riotgames.com/lol/summoner/v3/summoners/by-account/229854008
```
{
    "profileIconId": 523,
    "name": "<snip>",
    "summonerLevel": 30,
    "accountId": 229854008,
    "id": 92386816,
    "revisionDate": 1495770992000
}
```

This summoner originated from TR1, if you get a look on his last match

The V3 allowed us to figure out the correct URL

https://euw1.api.riotgames.com/lol/match/v3/matches/2885900831
```
            "player": {
                "currentPlatformId": "EUW1",
                "summonerName": "<snip>",
                "matchHistoryUri": "/v1/stats/player_history/TR1/458328",
                "platformId": "TR1",
                "currentAccountId": 229854008,
                "profileIcon": 523,
                "summonerId": 92386816,
                "accountId": 458328
            },
```

but on V4 : 

https://euw1.api.riotgames.com/lol/match/v4/matches/2885900831
 ```
           "player": {
                "currentPlatformId": "EUW1",
                "summonerName": "<snip>",
                "matchHistoryUri": "/v1/stats/player_history/TR1/458328",
                "platformId": "TR1",
                "currentAccountId": "yRQwmjW8_tg<snip>z4OHdeJ4mPg",
                "profileIcon": 523,
                "summonerId": "_ySUTd5U09B8<snip>181_9wGJ7fMeQ",
                "accountId": "xz5L037eb<snip>79gWie8f8p4"
            },
```

??

**Comment by Querijn** [comment]
Underlying issue seems that the matchHistoriUri seems to use platformId rather than currentPlatformId?

**Comment by supergrecko** [comment]
@Querijn yup, my account (which originated from NA, currently on EUW) has its match history url on NA. `https://matchhistory.euw.leagueoflegends.com/en/#match-history/NA1/235255249`. If you click on any of these matches you will be linked to a match details for EUW.

**Comment by tisbells** [comment]
Closing out old issues. Match-v3/v4 is no longer supported, feel free to re-open or comment if you feel this is in error.
