### ISSUE TITLE
[BUG] MATCH-v4 can't use PRODUCTION API KEYS?

### ISSUE THREAD

**Issue by Lemon71** [RiotGames/developer-relations#450]
**Problem Description** 
I use the api "/lol/match/v4/matchlists/by-account/{encryptedAccountId}"

it works withs development api key, but return 400 when I use my production api key, the other api is success with this key.

if there any mistake in my setting? I didn't set any optional QUERY PARAMETERS.

![image](https://user-images.githubusercontent.com/32609874/107843125-70b80f00-6e03-11eb-9498-cb50e63354d6.png)

![image](https://user-images.githubusercontent.com/32609874/107843128-79104a00-6e03-11eb-91f9-dc9f56ddd797.png)

**Comment by RiotTuxedo** [comment]
You might be able to get assistance on the [Discord server](https://discord.gg/riotgamesdevrel). GitHub isn't the place to debug issues.
