### ISSUE TITLE
[REQUEST] Some questions about LoL "ParticipantStatsDto"

### ISSUE THREAD

**Issue by Leejung8763** [RiotGames/developer-relations#451]
I will use Riot API data for making app, so I look into data these day.
I have some questions about **playerscore#** and **perk#var#** which is in ParticipantStatsDto.
Especially, **playerscore#** has no descriptions and each **perk#** has 3 var but, descriptions are same("Post game rune stats.").
So, I wonder what those are meaning.
![image](https://user-images.githubusercontent.com/50440358/107929951-b3bde200-6fbd-11eb-84ce-522c3828f62c.png)

**Comment by geozukunft** [comment]
You can ask that sorta stuff on the Discord server https://discord.gg/riotgamesdevrel
