### ISSUE TITLE
System error

### ISSUE THREAD

**Issue by meowranda** [RiotGames/developer-relations#452]
**Bug Description**  
A critical error has occurred and the process must be terminated.

**Problem Description**  
I can't proceed to the game as soon as the game starts or the loading screen starts

* Frequency: Every time the user visits the site, they experiennce this issue.
* has been happening everytime I start a game even in practice tool

* Region: Philippines
* C:\Users\Rouelle\AppData\Local\Temp\PKMFC51.tmp

**Comment by kodbilenadam** [comment]
This GitHub is related to Riot Games API issues. Please refer to Riot Games support https://support.riotgames.com/ for ingame issues.
