### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Famine73** [RiotGames/developer-relations#455]
Im honestly not sure what happened but I was asked to make a memory dump and send the file to the dev team due to an error of some sort so I will attach the file

**Comment by LightshieldDotDev** [comment]
Hey there!

**TLDR: No help/support at all will be given and this issue will be closed**

This isn't the page to ask for that for help with things like that
please contact support through support@riotgames.com or go to

https://support.riotgames.com/hc/en-us

We ask that you close this issue as this is where issues regarding
the Riot Games API (A tool which provides data to sites like op.gg)
are posted.

Posting with issues regarding support or gameplay issues will simply
be ignored and most likely be closed anyway, Lorem ipsum dolor sit amet, 
consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore 
et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
 ullamco laboris nisi ut aliquip ex ea commodo consequat. 
It is advised you contact support with the details provided above.

Kind Regards

**Comment by Famine73** [comment]
Sorry i didnt know
