### ISSUE TITLE
[BUG] Invalid tournament code

### ISSUE THREAD

**Issue by Noobnoobwoduels** [RiotGames/developer-relations#458]
**Bug Description**  
After getting a code for EuW and Eune, it says "error joining game"

**Problem Description**  
Cannot manage tournaments properly.

**Expected Result**  
Tournament codes must work tk be abke to play them

**Actual Result**  
What actually happened after you performed the above steps? Include screenshots, logs, or a description.

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call. Once every ~100 API calls.
* Severity: When it happens, my whole website crashes.
* Cost: Requires me to run X more servers to compensate for the issue costing me on average $200 of additional spend a month.
* Efficiency: Requires me to make 10x more API calls than necessary to compensate for the issue.
* User emails: I get frequent emails from users asking me about this issue.
* Etc

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

* Frequency: Every time the user visits the site, they experiennce this issue. Once every ~100 visits this issue occurs.
* Severity: When this bug happens, a user is unable to use my site. I have 200 visits to my site each day, so it affects 50% of site visits.
* Quantity: There are ~1k players that experience this issue.
* Region: This affects players in NA and EUW.
* Etc

**Preconditions**  
What conditions must be met in order for this bug to occur?

* First condition
* Second condition

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Step 1
1. Step 2

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by RiotTuxedo** [comment]
Closing because a duplicate issue was created #457
