### ISSUE TITLE
During development, we have 5 questions about tft api usage.

### ISSUE THREAD

**Issue by hiimayu** [RiotGames/developer-relations#459]
1,How to transfer "profileicon id" to pictures for tft? For example, my tft name is xiaopaoxiaopao in NA region. I found my profileiconid is 29 throught api, but it cannot match my icon in game. I found profileicon. jason in data dragon. But I think this is for league of legends not for tft.

**Comment by hiimayu** [comment]
Q2: Can TFT be playable cross-server/region for same account? (e.g. between EUW and NA)
For example, sometimes I want to play with my friends in EU, and sometimes I want to play with friends in NA.

Q3: Which api name can be used for seperate normal game or rank game?

Q4: We want to offer "total game time", "Win Rate", "Top4 Rate","Avg. Rank" for gamers. Is it possible that we get these info via one api, without query seveal apis and culculate data?

Q5: Can we have more flexible "Rate Limits"? For now our "rate Limits" is 500 requests every 10 seconds, but we have 2000ppl online at sametime. We are afraid it's not enough.
----
please help, thank you!~

**Comment by bangingheads** [comment]
Hello,

This Github is for issues surrounding the Riot Games API and not for questions.

If you would like to ask questions you can join the Riot Games Third Party Discord Server: https://discord.gg/riotgamesdevrel

**Comment by hiimayu** [comment]
> Hello,
> 
> This Github is for issues surrounding the Riot Games API and not for questions.
> 
> If you would like to ask questions you can join the Riot Games Third Party Discord Server: https://discord.gg/riotgamesdevrel

I don't have permission to send messages in that channel QAQ.
And the messages we left 4days before were noone replied yet.  We want to launch our new funtion asap, please understand~

**Comment by RiotTuxedo** [comment]
You can DM me on discord to help you get settled with the discord server, but if we start answering general questions here everyone will use it for that purpose and this repo is solely meant to report and track issues.
