### ISSUE TITLE
Champion Mastery V4 / by-summoner/{encryptedSummonerId}/by-champion/{championId} Displays incorrect summoner ID

### ISSUE THREAD

**Issue by supergrecko** [RiotGames/developer-relations#46]
### Preconditions

When you make a request to the endpoint it is supposed to return the summoner Id that was passed with the request (the one you looked up). The response body returns a completely different encrypted summoner id.

### Steps to reproduce

1. Create a request to `https://developer.riotgames.com/api-methods/#champion-mastery-v4/GET_getChampionMastery`

1. Enter your summoner ID and a champion ID

1. Make the request and read off of the response body

1. Notice that the summoner Id in the response is not equal to the one you sent

### Expected result

It's supposed to return the summonerId of the account you queried. Documentation also says `Summoner ID for this entry.`. 

### Actual result

The summoner id in the response does not match the one sent
![image](https://user-images.githubusercontent.com/42585241/50421721-d40d0e80-0842-11e9-976c-46ad0ee92415.png)

**Comment by RiotTuxedo** [comment]
Thanks for the report. This issue should now be resolved.

**Comment by jluzonpr** [comment]
Should be fixed. Now returns `"0"`
