### ISSUE TITLE
[BUG] The certificate for *.b.pvp.net has expired

### ISSUE THREAD

**Issue by CuriouserThing** [RiotGames/developer-relations#463]
**Problem Description**  
The certificate for *.b.pvp.net expired on Fri, 12 Mar 2021 12:00:00 GMT

**Developer Impact**  
Assets hosted by Data Dragon are unavailable without bypassing SSL, which may break some apps altogether.

**Comment by RiotTuxedo** [comment]
Thanks for the report. I've escalated this to the team.

**Comment by RiotTuxedo** [comment]
Should be resolved now.
