### ISSUE TITLE
[BUG] Spectator-V4 Returns 404 for europe and asia spectator grid

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#464]
Spectator-V4 is returning 404 not found for all regions included in the european & asian spectator grid. American servers are returning properly.

This causes any apps relying on live data from the API to break.

**Comment by trebonius0** [comment]
@RiotTuxedo this is affecting all the regions now. This is basically affecting hundreds of thousands of Porofessor users

**Comment by cohenu** [comment]
@RiotTuxedo Can you please fix this as soon as possible? This is affecting hundreds of thousands of our users.

**Comment by RiotTuxedo** [comment]
Spectator was disabled due to a bug. We're looking into it.

**Comment by RiotTuxedo** [comment]
This should be resolved now. Let me know if we can close out this issue.

**Comment by primus852** [comment]
Can confirm, runs smoothly in my project. Thank you!

**Comment by cohenu** [comment]
Thank you @RiotTuxedo

**Comment by trebonius0** [comment]
Working everywhere but in OCE @RiotTuxedo

**Comment by trebonius0** [comment]
This issue seems to be coming back now in every region

**Comment by primus852** [comment]
It's still working on EUW

**Comment by RiotTuxedo** [comment]
@trebonius0 looking into it.
@primus852 is working or isn't working?

**Comment by primus852** [comment]
@RiotTuxedo 
- EUW works on every single one I checked
- NA had issues a few minutes ago, but I can't find any issues now (sorry for the confusion)

**Comment by RiotTuxedo** [comment]
@trebonius0 OCE should now properly return results for any new games starting up.

**Comment by trebonius0** [comment]
Thanks @RiotTuxedo 
My monitoring seems a bit off atm. I'm checking it and I'll let you know if everything looks good by a few hours

Thanks for the fix !

**Comment by trebonius0** [comment]
Update @RiotTuxedo 
Everything seems correct. 
I still have 2-3% of games incorrectly detected as offline, but all of those seem to be some weird custom games

So I guess it's not an issue

Thanks for the heads up and the fix !
