### ISSUE TITLE
LOR-MATCH-V1 Endpoint of EU server are almost 503 for more than 10 hours. Please fix them. Thanks.

### ISSUE THREAD

**Issue by wangyi041228** [RiotGames/developer-relations#465]
LOR-MATCH-V1 Endpoint of EU server are almost 503 for more than 10 hours. Please fix them. Thanks.

**Comment by wangyi041228** [comment]
It's OK now. Thanks.

**Comment by RiotTuxedo** [comment]
Thanks for the report. We're aware and working on it. You may see increased latency until the issue is completely resolved.
