### ISSUE TITLE
LOR-MATCH-V1 Endpoints of EU server are almost 503 for more than 1 hours. Please fix them. Thanks.

### ISSUE THREAD

**Issue by wangyi041228** [RiotGames/developer-relations#466]

**Comment by paaksing** [comment]
It's working for me tho. Next time provide a bit more context than "Please fix them"

**Comment by RiotTuxedo** [comment]
Closing until there's more information. From our end, there's a handful of 503s, but the large majority of requests are resulting in 200s.
