### ISSUE TITLE
[BUG][DOCS] Nonsense dropdown for val-ranked-v1/GET_getLeaderboard `size` query parameter

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#468]
**Bug Description**  
In the developer portal, for the `val-ranked-v1/GET_getLeaderboard` the `size` query parameter (of type integer) has three dropdown values: `0`, `200`, and `"RANGE"`. Of course, `"RANGE"` results in 400, presumably it should be a text box for any integer 1 to 200.

https://developer.riotgames.com/apis#val-ranked-v1/GET_getLeaderboard

**Comment by RiotTuxedo** [comment]
This should be resolved now.

**Comment by MingweiSamuel** [comment]
Thanks Tux!
