### ISSUE TITLE
[BUG] [VAL] Some leaderboard players missing puuid, gameName and tagLine

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#469]
## **Bug Description**  
Some leaderboard players does not return puuid, gameName and tagLine from val-ranked-v1. Below sample is found on act `ab57ef51-4e59-da91-cc8d-51a5a2b9b8ff` on index of around 40~50.

## **Expected Result**  
```json
...
        {
            "puuid": "swStCia3uFmGtKqHD-yVT0-1wmOjBGl1DlHxz4-1i9swTJnW4FVppoy-DjrLmTbJziFSvKIbTOnv5A",
            "gameName": "BAZIX",
            "tagLine": "WKEY",
            "leaderboardRank": 45,
            "rankedRating": 663,
            "numberOfWins": 64,
            "competitiveTier": 24
        },
        {
            "puuid": "some-whatever-puuid-that-is-missing",
            "gameName": "who-is-this-guy",
            "tagLine": "goose",
            "leaderboardRank": 46,
            "rankedRating": 657,
            "numberOfWins": 140,
            "competitiveTier": 24
        },
...
```

## **Actual Result**  
```json
...
        {
            "puuid": "swStCia3uFmGtKqHD-yVT0-1wmOjBGl1DlHxz4-1i9swTJnW4FVppoy-DjrLmTbJziFSvKIbTOnv5A",
            "gameName": "BAZIX",
            "tagLine": "WKEY",
            "leaderboardRank": 45,
            "rankedRating": 663,
            "numberOfWins": 64,
            "competitiveTier": 24
        },
        {
            "leaderboardRank": 46,
            "rankedRating": 657,
            "numberOfWins": 140,
            "competitiveTier": 24
        },
...
```

## **Developer Impact**  
- `AttributeError`s going brrrrr
- `undefined`s going brrrr
- 3 more lines to write.
- I have no idea who is that player, therefore can't do lossless leaderboard.

**Comment by RiotTuxedo** [comment]
This is documented on the reference page.
https://developer.riotgames.com/apis#val-ranked-v1/GET_getLeaderboard
![image](https://user-images.githubusercontent.com/30917923/113523019-13665180-955a-11eb-9b6f-a9f4c290b62e.png)

This is what these players look like in the client.
![image](https://user-images.githubusercontent.com/30917923/113523013-0b0e1680-955a-11eb-90e3-9b0c6a6a73ff.png)

**Comment by paaksing** [comment]
Ohh thanks, sorry I missed that

**Comment by stelar7** [comment]
So.. They are anonymous in the api, but not the game? @RiotTuxedo

**Comment by RiotTuxedo** [comment]
They're anonymous in the game. Anonymous players are listed as "Secret Agent"
