### ISSUE TITLE
firstBloodAssist in matches API always false

### ISSUE THREAD

**Issue by xxxxxaaaaaaaannnn** [RiotGames/developer-relations#47]
Hello,

It might be a known issue, but the field **firstBloodAssist** is always false, in every match I checked for every one in the game in match API v3 or v4.

`    "participants": [
        {
            "stats": {
...
                "firstBloodAssist": false,`

Regards,

**Comment by RiotTuxedo** [comment]
@xxxxxaaaaaaaannnn are there any other fields that always return false?

**Comment by tisbells** [comment]
Closing out old issues. Match-v3/v4 is no longer supported, feel free to re-open or comment if you feel this is in error.
