### ISSUE TITLE
[BUG] Sett's passive image (full) on DDragon API is that of ChoGath

### ISSUE THREAD

**Issue by Vianpyro** [RiotGames/developer-relations#470]
**Bug Description**  
Sett's passive full image available on DDragon API is that of ChoGath.

**Problem Description**  
When we load Sett's JSON file and execute a query (or open from a web browser) on the image of his passive we get the image of Cho'Gath's passive.

**Expected Result**  
I expected to get the image of Sett's passive.

**Actual Result**  
I got the image if ChoGath's passive, with a different name.

**Developer Impact**  
I'm developing a website for me and a few friends using DDragon requests to fetch the latest data, and the image of Sett's passive isn't the one that should be displayed.

* Frequency: Every API call. Once every 1 API calls.
* Severity: When it happens, the image of Sett's passive is just not his.
* Cost: None.
* Efficiency: Requires me to search the whole API to find manually if there is a way to get the image of Sett's passive automaticaly.
* User emails: I get a few messages on Discord from people asking me to fix it (not a big issue).

**Player Impact**  
It is a minor issue for League of Legends players.

* Frequency: Every time the user visits the site, they experience this issue.
* Severity: When this bug happens, a user see incorrect information about one Champion. I have 150 visits to my site each day.
* Quantity: There are ~50 players that experience this issue.
* Region: This affects players in **every server**.

**Preconditions**  
A request to the API must be done.

**Repro Steps**  
1. Load [Sett's JSON from the DDragon API](https://ddragon.leagueoflegends.com/cdn/11.7.1/data/en_US/champion/Sett.json).
2. Search for "Sett > passive > image > full" and use the name of the image for the next request.
3. Execute a request to [the image of Sett's passive](https://ddragon.leagueoflegends.com/cdn/11.7.1/img/passive/Sett_P.png) and see the result.

**Issue Comments**  
This issue is not a major issue and does not need to be fixed urgently, a fix would be appreciated though.

Image of Sett's passive: ![Sett's passive](https://ddragon.leagueoflegends.com/cdn/11.7.1/img/passive/Sett_P.png)
Image of Cho'Gath's passive: ![Cho'Gath's passive](https://ddragon.leagueoflegends.com/cdn/11.7.1/img/passive/GreenTerror_TailSpike.png)

**Comment by bangingheads** [comment]
This has been resolved in 11.8.1 https://ddragon.leagueoflegends.com/cdn/11.8.1/img/passive/Sett_P.Sett.png

**Comment by Vianpyro** [comment]
Thank you very much for this quick resolution!
