### ISSUE TITLE
[BUG][LOL] match v5

### ISSUE THREAD

**Issue by thisKeeWord** [RiotGames/developer-relations#471]
I noticed that the match v5 API was available. I tried testing `/lol/match/v5/matches/{matchId}` and `/lol/match/v5/matches/by-puuid/{puuid}/ids` using the proper matchId and puuid from the match v4 and summoner v4 APIs along with the newly regenerated API key. 

However, it's returning `{"status":{"message":"Bad Request - Exception decrypting Mqad6hasZn6U6GNfWuxUZZGge7qhMNRSqqTODdRa9cEUXbq9HQ2D-U2WgKGzrRqPdmyiH0MOSdJ2Ag","status_code":400}}`

**Comment by RiotTuxedo** [comment]
What's your appid?

**Comment by thisKeeWord** [comment]
It's 264605, but I was using the development key for v5 (I should have specified)

**Comment by RiotTuxedo** [comment]
That might be the issue. Puuids are uniquely encrypted per app. You can't use the puuids from one app with another.

**Comment by thisKeeWord** [comment]
Gotcha. What about the case for the match v5 api? Are the match ids generated based off the puuid?

**Comment by RiotTuxedo** [comment]
Match ids are slightly different in v5. They're prefixed with the platform id.

{platform id}_{match id}
NA1_0000000000

**Comment by thisKeeWord** [comment]
That's good to know. Thank you!
