### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by pbhorm** [RiotGames/developer-relations#473]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
앙대갈희
Have you played any of Riot's games or did you just create an account for the Developer Portal?
I played LoL

**Issue Description**  
Yesterday my account was inactived.

So I changed to active. and then I can not loggin at dev portal

the message was:
INVALID ACCOUNT
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on Twitter, during office hours on Discord, or create an GitHub issue.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [o] Attempt to log in via "Incognito Mode"
- [o] Clear your browser cookies
- [o] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.
<img width="437" alt="캡처" src="https://user-images.githubusercontent.com/58277293/115813651-831b7e00-a42e-11eb-9c72-31c5e34e4597.PNG">

**Comment by lucasMesquitaBorges** [comment]
Hey @pbhorm I'm tackling old issues. Sorry for not answering this before.

Unfortunately I wasn't able to find your account. If you still need to fix this, re-open this issue with your Riot ID (game name + tagline).

You can get or fill your RiotID in https://account.riotgames.com
