### ISSUE TITLE
[FEATURE? Maybe] League and League-Exp endpoint response is named differently than the filter

### ISSUE THREAD

**Issue by LightshieldDotDev** [RiotGames/developer-relations#474]
The response entries for the league endpoint uses the name `tier` and `rank` but the queue filter on the website (which will be the first thing new user see) uses `tier` and `division`. 

Can we change not the response but at least the website filter naming to match the response so that its a little easier to understand? :)

![image](https://user-images.githubusercontent.com/60757347/115976741-4efca600-a571-11eb-8574-fa2a6f39c1f0.png)

![image](https://user-images.githubusercontent.com/60757347/115976745-5754e100-a571-11eb-9b29-e68bad8dd6f9.png)

**Comment by MingweiSamuel** [comment]
Although this makes sense, it would be a breaking change and mess up a lot of services. Maybe it makes sense to do at the next version bump

**Comment by LightshieldDotDev** [comment]
It would not be a breaking change as what I am suggesting is to change the wording on the website, not the wording in the response. While I do prefer the wording that is currently on the website (division + tier) it would after all break the response so I am happy with settling with consistency across Path Parameter and response.

**Comment by RiotTuxedo** [comment]
Agree this feels inconsistent, but I also agree that this makes the most sense to fix in a version bump. If we wanted to fix this without affecting the response then we'd need to rename the path param from `division` to `rank`, which makes it consistent but less clear. I can add a note to the `rank` field to indicate that this field represents a division within a tier, would that alleviate your concerns?

**Comment by MingweiSamuel** [comment]
(I'm a fan of that change)

**Comment by LightshieldDotDev** [comment]
Sounds good. In the end its mostly about people that are new to the API and then just get even more confused by not knowing whats what. 
Seems like a decent interim solution.

**Comment by RiotTuxedo** [comment]
Hopefully this helps.

![image](https://user-images.githubusercontent.com/30917923/116769473-3f59e300-a9f1-11eb-8146-a1e3092f643e.png)

I'm going to close this issue but tag it as an improvement and we can implement this in a future version of the API for consistency's sake.
