### ISSUE TITLE
[BUG] [TFT] Where is Set 5 static data 

### ISSUE THREAD

**Issue by mario-sm** [RiotGames/developer-relations#475]
Im trying to find set5 static data, and cant find in ddragon or developers portal. Where can i found it ?
Thank you!

**Comment by stelar7** [comment]
Try cdragon: https://raw.communitydragon.org/latest/cdragon/tft

**Comment by mario-sm** [comment]
Thank you!

**Comment by mario-sm** [comment]
@stelar7  and images and assets ?

**Comment by stelar7** [comment]
Look around on it.. this should be the base path http://raw.communitydragon.org/latest/game/assets/

so ASSETS/Maps/Particles/TFT/Item_Icons/Shadow/S_Hand_of_Justice.dds is at http://raw.communitydragon.org/latest/game/assets/maps/particles/tft/item_icons/shadow/s_hand_of_justice.png

**Comment by mario-sm** [comment]
Okey, Solved . Thank you @stelar7 !!!
