### ISSUE TITLE
summoner unique key when summoner name changed

### ISSUE THREAD

**Issue by imjonghyeon** [RiotGames/developer-relations#476]
What's the unique key that can be used when a summoner changes the summoner name?

For example, if the name of the summoner before the change is abcd and the name of the summoner after the change is asdf, 
the user cannot be known if the name is changed. So I want to know what a unique key is.

i use api /lol/summoner/v4/summoners/by-name/{summonerName}

**Comment by RiotTuxedo** [comment]
@imjonghyeon this is a question better suited for [Discord](https://discord.gg/riotgamesdevrel). The issues repo isn't meant for Q&A, but rather a place to report and track issues.
