### ISSUE TITLE
[BUG] Spectator endpoint lagging behind in BR, LAN & LAS since 11.9

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#477]
**Bug Description**  
Since patch 11.9, every night, in LAN, LAS & BR, the spectator endpoint contains outdated data. This only happens during peak hours though. (11pm GMT to 5am GMT)

For instance, on May 2, 12:00:00am GMT, when calling the spectator endpoint for player LAN-PumpkinXx (encryptedSummonerId: bzh-eHFvVL55IV6bd059Tn4nMmhRjNha2ag0hWbwrJ5L), this endpoint returned the data from gameId: 1066995499
Nevertheless, at that time, the player was in game 1067041052.

This doesn't seem to be linked to clash, I've seen that happening on multiple game types
Just last night, this affected at least **140,000** of my calls.

Could you fix this please ?

Thanks !

**Problem Description**  
The spectator endpoint results are outdated

**Expected Result**  
The spectator endpoint should result the actual game the player is in

**Actual Result**  
The spectator endpoint returns the previous game

**Player Impact**  
Porofessor basically doesn't work for those users

Thanks !

**Comment by trebonius0** [comment]
Additional info: this seems to be affecting around 8% of all BR, LAN & LAS games

**Comment by trebonius0** [comment]
@RiotTuxedo Additional info: this seems to be affecting around 8% of all BR, LAN & LAS games

**Comment by trebonius0** [comment]
@RiotTuxedo Additional info: this seems to be affecting around 8% of all BR, LAN & LAS games

**Comment by trebonius0** [comment]
@RiotTuxedo the restart of the spectator grid didn't fix the issue: May 12th at midnight GMT I was still seeing the issue. 
BUT last 2 nights were ok, I didn't have teh issue (maybe 11.10 changed somethng ?)
I'll monitor it during the weekend to see if it comes back

**Comment by trebonius0** [comment]
@RiotTuxedo The issue hasn't come back this weekend, so I didn't have it at all during 11.10
So I'm closing the issue for now, I'll reopen it if it occurs again

Thanks !

**Comment by trebonius0** [comment]
@RiotTuxedo The issue has come back since 11.11
I reopen the issue

**Comment by trebonius0** [comment]
@RiotTuxedo I'm still seeing the issue. Any update ?

**Comment by RiotTuxedo** [comment]
I bumped this conversation internally. Looking into it.

**Comment by trebonius0** [comment]
Things have been better for the past 2 days. I'll monitor that this week and, if everything is good, i'll close the issue

**Comment by trebonius0** [comment]
No error anymore for the past 5 days. Closing the issue :)
