### ISSUE TITLE
[BUG] Imbalanced characters Wild Rift mobile game

### ISSUE THREAD

**Issue by AuraLoredana** [RiotGames/developer-relations#479]
**Bug Description**  
Imbalanced characters

**Problem Description**  
Some characters as: Dr.Mundo, Fizz, Zed, Ezreal, Akali, Twisted Fate, Wu Kong, Janna deal abnormally high damage from early game.

**Expected Result**  
All characters should be balanced, to give the user a fair game.

**Player Impact**  
The impact is especially in Rank, when, because of some characters with too much damage, you loose and makes the game unlikeable.

* Severity: High

**Comment by LightshieldDotDev** [comment]
Hey, thanks for the report. 
Could you please provide us some more info on how to reproduce this bug?

What operating system are you using?
What version of the League Wild Rift app are you using?
Has this bug been appearing for extended periods?
Could you please quantify (precisely) the impact that this has on the game.
Is the issue appearing outside of the game as well?
Could this be an issue not of the system but of you being a whiny bitch?
Have you made sure that other player besides you also experience this issue?
Has this bug been appearing continuously or only rarely?

Thanks in advance

**Comment by sousa-andre** [comment]
**Bug Description**
This is not working as I expect

**Problem Description**
People wrongly reporting bugs related to the game here

**Expected Result**
Everyone should try to read what's in front of their eyes before opening issues like this

**Actual Result**
<insert something here>

*Proposed Solution*
Get good

- Severity: undefined

**Comment by RiotTuxedo** [comment]
@AuraLoredana unfortunately this isn't the place to discuss balance or game design. We only address issues or feature requests related to the Riot Games API and supported third party resources.

**Comment by AuraLoredana** [comment]
Thanks for laughing...Anyways, would be helpful with an email where I could provide feedback. Sorry for bothering with non related bugs. Have a nice day!

**Comment by LightshieldDotDev** [comment]
http://support.riotgames.com/
