### ISSUE TITLE
Match-V4 matchlists/by-account endTime filter causes Bad Request

### ISSUE THREAD

**Issue by M0kY** [RiotGames/developer-relations#48]
### Precondition
1. Operation: `/lol/match/v4/matchlists/by-account/{encryptedAccountId}`
2. Query parameter `endTime` is provided
3. Query parameter `beginTime` is NOT provided

### Steps to reproduce
1. Run operation `/lol/match/v4/matchlists/by-account/{encryptedAccountId}` with following parameters
2. Encrypted `accountId`: grMQPgTIj1lQ61KV-0zCWNLfdj9tJtCTmGOYgARKOtycYw
3. Query parameter `endTime`: 1545609984161
4. Set `REGION` to: EUW1

### Expected Result
As per description of `endTime`

> The end time to use for filtering matchlist specified as epoch milliseconds. If beginTime is specified, but not endTime, then endTime defaults to the the current unix timestamp in milliseconds. If endTime is specified, but not beginTime, then beginTime defaults to the start of the account's match history. If both are specified, then endTime should be greater than beginTime.

when `beginTime` is not provided the result should be a list of matches from the start of the account match history to the provided `endTime` or `404` if there is no data.

In this case if `endTime` is left blank the result contains an array of 100 games.

### Actual Result

```
{
    "status": {
        "status_code": 400,
        "message": "Bad request"
    }
}
```

Edit: C/P-ed wrong error, added region to steps to reproduce.

**Comment by RiotTuxedo** [comment]
This is related to #28. The maximum time range allowed is one week, otherwise a 400 error code is returned.
