### ISSUE TITLE
[BUG] Report - Wild Rift mobile game

### ISSUE THREAD

**Issue by AuraLoredana** [RiotGames/developer-relations#480]
**Bug Description**  
After reporting a user, there is no notification that reflects something has been done.

**Problem Description**  
Please provide some notification, or follow up on the reported users.

**Comment by RiotTuxedo** [comment]
@AuraLoredana as I mentioned in the other ticket you're providing feedback on the game and we only address issues or feature requests related to the Riot Games API and supported third party resources.
