### ISSUE TITLE
[BUG] Valorant ranked ELO points

### ISSUE THREAD

**Issue by thirggy** [RiotGames/developer-relations#482]
**Bug Description**  
ELO points for win/lose are unbalanced in lower ranks. 

**Problem Description**  
Example last season Diamond 1 currently P3 Lost game (Even If Match MVP) -25-30 LOST elo points and if win +14-17 elo points ITS unfair. Example Immortal Lost game -19-23 and win +18-24 its ok but example If you are RADIANT you lose game u get -9-13 points and if u win u get +30-35 points. So example platinum Rank IS super frustrating and unfair to try grind to immortal because you get less elo points when u win(and if you grind yourself PLATINUM3 ---> DIAMOND2 and you play against some DIAMOND 3 AND IMMORTAL RANKS you win yli get +14-17 points and lose u get -25-30 points Even Ur playing against higher Rank players that Ur current Rank IS), and same on people WHO IS immortal and try grind to radiant because They need to win win win win win win while radiant can win lose win lose win lose and still gain lots of ELO points.

**Expected Result**  
I hope riot Will FIX this valorant ranked elo system soon as possible, Its unfair to play against people who has higher  rank than you and gain less elo than them when win and lose More elo than them when you lose game(EXAMPLE DIAMOND2 plays duo with IMMORTAL, DIAMOND2 player lose More elo than IMMORTAL player and gain less elo than IMMORTAL player Even If immortal player has "Bad stats in game and DIAMOND player plays good"). Many people (from Reddit) example IS pretty angry when example you soloque play good every game u win u get a little bit of elo and u lose one game and all your elo gone. This problem is in bronze/silver/gold ranks too super common i used diamond and Immortal and radiant as a example because i Have seen Many streams and clips.

**Player Impact**  
Ranked players are having low motivation to grind/Have fun because ELO system is unfair. Players who are GOLD ranks plays with PLATINUM ranks, The gold ranks will lose More elo than platinum and gain much less too, IT need to Be fixed. Just what ive seen and what ive read.

**Comment by RiotTuxedo** [comment]
@thirggy this channel is focused on reporting issues and new features for the Riot Games API and developer tools. Unfortunately, we don't deal with game balance or meta game systems.
