### ISSUE TITLE
[Account] Pending product's response taking too long 

### ISSUE THREAD

**Issue by imjonghyeon** [RiotGames/developer-relations#484]
Hi^^

My app id is 507085

this is pending 

Please answer me what to do!!

**Comment by bangingheads** [comment]
Hello @imjonghyeon 

This GitHub is for issues surrounding the Riot Games API and not for general questions.

If you have any questions about the API please ask them in the [https://discord.gg/riotgamesdevrel](Discord)

The average turnaround on applications is 20 business days. This time period can vary depending on Riot's schedule.
