### ISSUE TITLE
MATCH-V4/timelines doesn't show an event of the Trinket coming back when Eye of the Herald gets released or timeouts

### ISSUE THREAD

**Issue by BernardoMariano** [RiotGames/developer-relations#49]
## Description
**Trinkets** and the **Eye of the Herald** share exclusively the same slot, and when a player gets the **Eye of the Herald**, an event of `ITEM_DESTROYED` is triggered to his current **Trinket**, but once **Eye of the Herald** is released (_or timeouts_), no event of the **Trinket** getting back is fired.

## Preconditions
Have a match where a player has any kind of Trinket (yellow, red or blue), gets Eye of the Herald and releases it.

## Steps to Reproduce

One can use this match to reproduce: https://br1.api.riotgames.com/lol/match/v4/timelines/by-match/1544553690.

Notice how at `15:41`, **Jax** kills **Rift Herald**, firing two events as follow:
```javascript
{
  "type": "ELITE_MONSTER_KILL",
  "timestamp": 939931,
  "position": { "x": 4528, "y": 10118 },
  "killerId": 5,                          // Jax
  "monsterType": "RIFTHERALD"
},
{
  "type": "ITEM_DESTROYED",
  "timestamp": 942076,
  "participantId": 5,                     // Jax
  "itemId": 3340                          // Yellow Trinket
},
```

And at `16:33`, **Jax** releases **Rift Herald**, firing only one event of:
```javascript
{
  "type": "ITEM_DESTROYED",
  "timestamp": 993807,
  "participantId": 5,                     // Jax
  "itemId": 3513                          // Eye of the Herald
},
```

## Expected Result
I see two options here:
1. It should **NOT** trigger an event of `ITEM_DESTROYED` for Trinkets when a player gets **Eye of the Herald**.
or
2. When a player releases **Rift Herald** (_or it timeouts_), it should trigger not one, but two events on the Match Timeline:
```javascript
{
  "type": "ITEM_DESTROYED",
  "timestamp": Number,
  "participantId": Number,
  "itemId": 3513         // Eye of the Herald
},
{
  "type": "ITEM_BACK",   // Or something better
  "timestamp": Number,
  "participantId": Number,
  "itemId": 3340         // Any trinket itemId
},
```

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported, feel free to re-open or comment if you feel this is in error.
