### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by smirnovDm** [RiotGames/developer-relations#493]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)? - "git stash"
Have you played any of Riot's games or did you just create an account for the Developer Portal? - "Yes, I've been playing for a long time"

**Issue Description**  
I'm about to create an information website  about TFT. I use your API and find summoner by nickname. I can't get how it works, i mean i tried to pass nickname "UrMom" but it returns json with nickname "Ur mom"  - 2 differents nickname. I cant do the logic for this case. Its a bug or feature? help me please
https://developer.riotgames.com/apis#tft-summoner-v1/GET_getBySummonerName
RU region
**What I've Tried**
I'm about to create an information website  about TFT. I use your API and find summoner by nickname. I can't get how it works, i mean i tried to pass nickname "UrMom" but it returns json with nickname "Ur mom"  - 2 differents nickname. I cant do the logic for this case. Its a bug or feature? help me please
https://developer.riotgames.com/apis#tft-summoner-v1/GET_getBySummonerName
- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

I'm about to create an information website  about TFT. I use your API and find summoner by nickname. I can't get how it works, i mean i tried to pass nickname "UrMom" but it returns json with nickname "Ur mom"  - 2 differents nickname. I cant do the logic for this case. Its a bug or feature? help me please
https://developer.riotgames.com/apis#tft-summoner-v1/GET_getBySummonerName
RU region
**Issue Context**
I'm about to create an information website  about TFT. I use your API and find summoner by nickname. I can't get how it works, i mean i tried to pass nickname "UrMom" but it returns json with nickname "Ur mom"  - 2 differents nickname. I cant do the logic for this case. Its a bug or feature? help me please
https://developer.riotgames.com/apis#tft-summoner-v1/GET_getBySummonerName
RU region

**Comment by LightshieldDotDev** [comment]
Spaces are not actually considered when checking for name uniqueness. 

With space == Without space.
