### ISSUE TITLE
[BUG] MATCH-V5 matches/by_puuid doesn't return the correct match ids

### ISSUE THREAD

**Issue by ZeroFTG** [RiotGames/developer-relations#494]
**Bug Description**  
MATCH-V5 matches/by_puuid doesn't return the correct match ids

**Problem Description**  
When getting match lists from the matches/by_puuid endpoint it appears that the most recent result is not the first result in the list. The first X amount of results, it varies, are other matchids that when put into the matches/{matchId} endpoint return a 404.

**Expected Result**  
the first result in the returned list is the most recent match, the 2nd one the 2nd most recent, etc etc.

**Actual Result**  
The first 14 matchids didn't appear to link to any match with all of them returning 404 on the matches/{matchId} end point. for another account the first 4 match ids didn't appear to link to any match with all of them returning 404. 
![Capture](https://user-images.githubusercontent.com/84738603/120013412-99da6500-bfd8-11eb-8f00-8e9cf5d05ab3.PNG)
![E2e87uHWUAc9Btj](https://user-images.githubusercontent.com/84738603/120013432-9fd04600-bfd8-11eb-83f3-399986b252bf.jpg)
![E2e81pUX0AMr7cu](https://user-images.githubusercontent.com/84738603/120013443-a2cb3680-bfd8-11eb-8599-60af541e15f0.png)

**Developer Impact**  

* Frequency: Appears to be about half of all accounts I've tried
* Severity: Just means I can't collect as many games

**Preconditions**  
What conditions must be met in order for this bug to occur?

* puuid must be legitimate

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Use the puuid for the account "VIP Topi" on EUW in match-v5 on the riot api website
2. Attempt to put the first 4 results through the matches/match-id endpoint of all should return 404,
3. Attempt to put the 5th result through matches/match-id and you should get a 200.

**Issue Comments**  
This potential bug was found on 28/05/2021. I am not sure if the bug will persist with the given puuid as the player's match history changes.

**Comment by ZeroFTG** [comment]
Just remembered Puuids most likely vary depending on the key sued, the account to be sued to verify this bug would be "VIP Topi" on EUW.

**Comment by RiotTuxedo** [comment]
The first four games are custom games and are only viewable to the participants. Thanks for the report, this is currently working as intended. I'm looking into ways to make this experience less confusing.

**Comment by ZeroFTG** [comment]
I asked them whether these were custom games. The one with 14 before the actual match said he played no custom games between yesterday and today unless you're saying These are from a different time.
