### ISSUE TITLE
[BUG] League client api /lol-career-stats/v1/summoner-games/{puuid} responds with 404

### ISSUE THREAD

**Issue by fabran99** [RiotGames/developer-relations#495]
My app uses the league client endpoint to get the matchlist for the players in the current game.
**/lol-career-stats/v1/summoner-games/${puuid}**

Now it responds with
```
{ errorCode: 'RPC_ERROR',
  httpStatus: 400,
  implementationDetails: {},
  message: '400' }
```

It is a new endpoint in the league client to get the same data? or it just got removed or something like that?

**Comment by bangingheads** [comment]
As stated in the documentation Client APIs are unsupported by Riot.
`NOTE: We provide no guarantees of full documentation, service uptime, or change communication for unsupported services. This team does not own any components of the underlying services, and will not offer additional support related to them.`

If you need any help regarding client apis you can ask the community questions in `#lcu-api` the Discord:  https://discord.gg/riotgamesdevrel

**Comment by tisbells** [comment]
Closing old issues. The LCU is unsupported.
