### ISSUE TITLE
[Account] hy0u4a Invalid Account

### ISSUE THREAD

**Issue by hy0u4a** [RiotGames/developer-relations#496]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)? 에 임#1111
Have you played any of Riot's games or did you just create an account for the Developer Portal? Yes, Yes.

**Issue Description**  
A clear and concise description of what the issue is.
hy0u4a is my account.
Invalid Account
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on Twitter, during office hours on Discord, or create an GitHub issue.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by lucasMesquitaBorges** [comment]
Hey @hy0u4a I'm tackling old issues. Sorry for not answering this before.
Unfortunately your account was deleted and it's after the the grace period for recovery. Our recovery methods won't be able to restore it.

In order to access devportal you will need to create a new account.
