### ISSUE TITLE
[Account] Pending product's response taking too long

### ISSUE THREAD

**Issue by imjonghyeon** [RiotGames/developer-relations#501]
HI
MY APP ID IS 511281 in korea
PENDING TOO LONG...TT

I know this question doesn't fit here in git
I inquired at discord about that but no response

the pending status has been going on for over a month. please confirm
or tell me how to get next step thank you!!!

**Comment by Token07** [comment]
There are multiple apps that have been pending longer than yours and the delay in approval has been mentioned numerous times on the Discord server. The best thing you can do is continue to wait.

**Comment by Token07** [comment]
Also, your previous issue, #484, which is quite similar to this issue, was closed as it is out of scope for this Github project. 
> I know this question doesn't fit here in git
Please avoid creating additional issues regarding app approval. The appropriate forum for app approval issues is the Discord server.
