### ISSUE TITLE
LoR API card sets do not include Tutorial and Labs cards?

### ISSUE THREAD

**Issue by ProtoFgt** [RiotGames/developer-relations#502]
**Problem Description**  
Currently the API does not serve data related to the Labs and Tutorials, while serving every other card (minus skins for them). I'm looking to hopefully make these sets available.

**Developer Impact**  
Currently, the League of Legends Wikia/Fandom is required to load the game, screenshot the card and crop it out for every time the card changes, rather than an easily accessible PNG. These cards should be provided as supplementary data sets, retroactively if possible, but creates problems with fact checking once the patch has come and gone.

**Player Impact**  
This may cause issues if per-patch data shows inconsistencies and needs quick references. Convenience, really.

**Issue Comments**  
I'm representing the League of Legends Wikia/Fandom in an effort to make data more accessible so we don't have to datamine the game to get such content, or rely on our speed to ensure the card changes don't get missed. I understand this data is not widely needed, but for the Wiki/Fandom it is preferable to have it easily accessible.

I have also added a list of these missing card IDs to the issue.

[List_of_cards_not_in_LoR_API_Updated.txt](https://github.com/RiotGames/developer-relations/files/6744370/List_of_cards_not_in_LoR_API_Updated.txt)

**Comment by RiotTuxedo** [comment]
Just checked with the team and these cards are purposely excluded from ddrag :(

**Comment by ProtoFgt** [comment]
That's unfortunate, thanks for trying though.
