### ISSUE TITLE
LoR API card sets for 0_7_0_33 and 0_8_0_0 are inaccessible

### ISSUE THREAD

**Issue by ProtoFgt** [RiotGames/developer-relations#503]
**Problem Description**  
The LoR API card sets for versions prior to 0_8_2_0 are no longer accessible, and haven't been for quite some time.

**Expected Result**  
Accessing the content via its old link (https://dd.b.pvp.net/datadragon-set1-en_us.zip) or by manually entering version information (https://dd.b.pvp.net/0_8_0_0/set1-en_us.zip) leads to accessing the zip containing card information and images.

**Actual Result**  
Accessing either leads to an Access Denied page.

**Developer Impact**  
This makes particularly old content inaccessible, making it hard to validate per-patch content of a particular range.

**Player Impact**  
Players may not be able to access or reference older content.

**Issue Comments**  
This issue is particularly old but not many people are affected as this is a somewhat niche thing to need to begin with.

**Comment by RiotTuxedo** [comment]
This was intentional. We added versioning to the uri and removed the older sets without a version. These changes were made in alpha before the general release of Legends of Runeterra (version 1.0). There wouldn't have been https://dd.b.pvp.net/0_7_0_33 /set1-en_us.zip or https://dd.b.pvp.net/0_8_0_0/set1-en_us.zip just https://dd.b.pvp.net/datadragon-set1-en_us.zip and I believe it was overridden for each patch, before versioning was introduced.

There may be some individuals that still have these alpha releases of ddrag in the [Discord](https://discord.gg/riotgamesdevrel).

**Comment by RiotTuxedo** [comment]
I see from your other issue this is for the Fandom Wiki site. I'll see if I can get you some of the old sets.

**Comment by ProtoFgt** [comment]
Thanks in advance and my apologies for making 2 tickets here as I felt these were different enough to warrant it.

I do recall this change being intentional but it seems strange since the others prior to 1.0 are still up (0_8_2_0, all the way to 0_9_4_0). I am aware of the overwriting as well but at the very least the final sets for each are fine. Every so often some early ones drop but I ignore these for the most part.

I have copies of 0_7_0_33 and 0_8_0_0 sets in english only and not in their original zips, so it's hard to trust these are from the correct timeframe for each of the specified versions. Additionally, as far as I can tell nobody saved the other languages as well (if they existed, I'm pretty sure they did), so anything outside of english is missing too.
Locales I'd need are: de_de, en_us, es_es, fr_fr, it_it, ja_jp, and ko_kr

I know this is a lot of data to request, but I'm nearly 1TB deep into this anyway so to me it's not much.

**Comment by RiotTuxedo** [comment]
Reach out to me on the Developer Discord and I'll set what I can gather up. Some of the earlier sets didn't even have versioning in ddrag. I'm looking at a set from 11/3/2019 and there's no versions and the paths themselves are just http://dd.b.pvp.net/Set1/en_us/img/cards/01IO012T2.png
