### ISSUE TITLE
[QUESTION]how can I get matchid and puuid to complete the test?

### ISSUE THREAD

**Issue by bh134** [RiotGames/developer-relations#504]
Hi,I'm a rookie.
I'm developing a webapp for the company to obtain VALORANT match data.
I'm lucky I found the api:
    _/val/match/v1/matches/{matchId}
    /val/match/v1/matchlists/by-puuid/{puuid}_
Currently I am still waiting to verify my Production App.
But when I am using Standard API, I don’t know how to get **matchid** or **puuid**.
I found a method in /_riot/account/v1/accounts/me_ again, but it needs Tournaments API.

So how can I get **matchid** and **puuid** to complete the test?

**Comment by Token07** [comment]
This repo is not meant for reporting issues with services and data made available for 3rd party developers to use, not to answer general questions about the API. You'll find more information and examples on the discord server linked in the README on this repo.
