### ISSUE TITLE
[Question/Feature Request] Is MMR available from Riot API league-v4 now?

### ISSUE THREAD

**Issue by jadeeeeh** [RiotGames/developer-relations#505]
In Reddit, I found a post that mmr was available through "API Documentation -> Full API Reference -> League-V3 -> /lol/league/v3/mmr-af/by-summoner/{summonerId}". However, league-v3 is not available anymore and there is no "/mmr-af" under "/league/v4". 
This is the link to the post: https://www.reddit.com/r/leagueoflegends/comments/88gxzg/the_riot_api_now_shows_your_true_mmr_which_riot/?sort=new 

May I ask if the mmr is not available through Riot API now? If it is not available now, I would like to know if it is possible to show mmr in the future. 

Thanks a lot for your help.

**Comment by Querijn** [comment]
Hi jadeeeeh,

This was posted on April Fools, and was a joke developed by the team behind the API. It doesn't exist right now because it used to be nothing but a random number generator with a random geek reference.

**Comment by jadeeeeh** [comment]
> Hi jadeeeeh,
> 
> This was posted on April Fools, and was a joke developed by the team behind the API. It doesn't exist right now because it used to be nothing but a random number generator with a random geek reference.

Understand 😂😂😂. Thanks a lot.
