### ISSUE TITLE
[BUG] [DDRAGON] the maps variables for ddragon all got set to false on patch 11.14

### ISSUE THREAD

**Issue by meesvandongen** [RiotGames/developer-relations#506]
**Bug Description**  
On patch 11.14, all maps values in the ddragon got set to `false`.

**Problem Description**  
I am not able to automatically get item disabled status anymore.

**Expected Result**  
The maps variable in items should have proper values for each map id.

**Actual Result** 
each map id inside maps of each item now has false as value. Also see:
https://patchdiff.lolmath.net/?dataKey=item&originalVersion=11.13.1&modifiedVersion=11.14.1

**Developer Impact**  
I will have to manually keep track of the disabled status of items.

**Player Impact**  
none

**Repro Steps**  
request item.json from ddragon at patch 11.14

**Comment by RiotTuxedo** [comment]
Escalated this. Looks like they fixed it. They're debating re-releasing 11.14.1.

**Comment by RiotTuxedo** [comment]
This bug has been fixed and 11.14.1 has been redeployed. Thanks for the report.
