### ISSUE TITLE
[DOCS][BUG] queue.json missing 1400 Ultimate Spellbook

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#507]
https://static.developer.riotgames.com/docs/lol/queues.json

May be missing others

**Comment by RiotTuxedo** [comment]
Updated

**Comment by MingweiSamuel** [comment]
@RiotTuxedo 

It seems also https://static.developer.riotgames.com/docs/lol/gameModes.json is missing `"gameMode": "ULTBOOK",`

https://github.com/MingweiSamuel/riotapi-schema/pull/26

**Comment by RiotTuxedo** [comment]
Once the cache clears this should be updated as well.

**Comment by MingweiSamuel** [comment]
https://github.com/RiotGames/developer-relations/issues/574
