### ISSUE TITLE
summoner-v4 SummonerDTO add encrypted field info to description

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#51]
Seems a lot of people are initially confused by the documentation for [summoner-v4](https://developer.riotgames.com/api-methods/#summoner-v4/) because based on the descriptions, it's not clear that the fields return the *encrypted* summonerId, accountId, & puuid.

Would be good to add a note to each of those decriptions that they they are the encrypted values used throughout v4

NAME | DATA TYPE | DESCRIPTION
-- | -- | --
puuid | string | PUUID
id | string | Summoner ID.
accountId | string | Account ID.

**Comment by jluzonpr** [comment]
Fixed now. Thx for reporting.

**Comment by MingweiSamuel** [comment]
Great, thanks!
