### ISSUE TITLE
[QUESTION/FEATURE REQUEST] Get match ids by tournaments code Match API v5

### ISSUE THREAD

**Issue by learnWeb3** [RiotGames/developer-relations#511]
Problem Description

Can not get match ids and match related data by tournaments code in match api v5.
As match api v4 will be deprecated on August 23rd i would like to know if there is any way to pull this data apart from the automatic callback.

Match api v4 link :

https://developer.riotgames.com/apis#match-v4/GET_getMatchIdsByTournamentCode

Developer Impact

Match api v4 us planned to be deprecated on August 23rd and i can't find any replacement endpoint to fetch this data in match api v5.

**Comment by RiotTuxedo** [comment]
The new flow would be to use [GET_getMatchIdsByPUUID](https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID) with the `type` query parameter set to `tourney`. This will return all matches played with a tournament code. The match bodies themselves have a field to confirm which tournament code was used to make the match.
