### ISSUE TITLE
403 for every Request [Account] 

### ISSUE THREAD

**Issue by mostafa4460** [RiotGames/developer-relations#516]
Hey guys, my app got approved, so I just switched my from the dev key to the private key, but I keep getting 403 status codes with every request I make now. I am still passing the key in the "X-Riot-Token" header, and the status of my private key is "Approved." I also supposedly have access to all 32 League methods, so that isn't the problem either. What's weird is that the requests work fine when I make them through the Developer Portal, but when I change nothing else in my code but the API_KEY environment value, I get 403 error codes!

**Comment by HaoCherHong** [comment]
@mostafa4460 I think I've encountered the same issue. Did you figure out why?

**Comment by mostafa4460** [comment]
Yea, it's because of the Match-V5 route, which is only accessible via a PRODUCTION API KEY or through the DEV PORTAL currently. If you look at your approved methods, it'll probably have Match-V4 but not V5. V4 is getting deprecated on 09/06/2021 though, so I'd just use Match-V5 in your app and renew the DEV API key every time it expires until next month (that's what I've been doing for the past 2 weeks).
