### ISSUE TITLE
[BUG] MatchV5 matchlist by puuid not returning higher than 990~ IDs.

### ISSUE THREAD

**Issue by MitchellRomney** [RiotGames/developer-relations#517]
**Bug Description**  
When using the MatchV5 endpoint `/matches/by-puuid/{puuid}/ids` and paginating with `?start={page * 100}&count=100`, resulting IDs only go up to around 990 when the Summoner has played many more just this season alone. 

Fetching `?start=900&count=100` only returns around 80-99 IDs, and `?start=1000&count=100` returns `[]`.

**Examples**
> **Server**
> EUW1 
> **SummonerName**
> Sauromat 
> **Season 11 Ranked Solo Matches**
> 2700~
> **Total MatchIDs returned**
> 996

> **Server**
> EUW1 
> **SummonerName**
> Oasisz 
> **Season 11 Ranked Solo Matches**
> 2100~
> **Total MatchIDs returned**
> 998

> **Server**
> EUW1 
> **SummonerName**
> Inhibiteur 
> **Season 11 Ranked Solo Matches**
> 2000~
> **Total MatchIDs returned**
> 985

**Potentially related bug**
Not sure if related (let me know if this should have its own bug report), while fetching `EUW1 Inhibiteur` I received the MatchID of `EUW1_5221813757` which returns completely empty match info like so:
```
{
    gameCreation: 0,
    gameDuration: 1618919109695,
    gameMode: '',
    gameName: '',
    gameStartTimestamp: 0,
    gameType: '',
    gameVersion: '',
    mapId: 0,
    matchId: 'EUW1_5221813757',
    platformId: '',
    queueId: 0,
    tournamentCode: '',
    teams: [],
    participants: [],
}
```

**Expected Result**  
This endpoint should continue to return all MatchIDs up to the point in the past where `MatchV5` stops returning matches (my assumption is that this is definitely before S11).

**Actual Result**  
The endpoint is only returning around 990ish results and then goes blank.

**Developer Impact**  
I'm unable to reliably fetch all games for a Summoner for Season 11 as expected, which then makes subsequent statistic averages for a Summoner's season stats completely inaccurate.

* Frequency: Every API call.
* Severity: Medium, nothing crashes or breaks but I'm unable to fetch thousands of MatchIDs necessary to calculate accurate statistics for the user.
* Cost: None.
* Efficiency: Seemingly no workaround besides hoping these MatchIDs are returned by other Summoners who have played less than 1000 games.

**Player Impact**  
User's who have played 1000+ games have inaccurate statistics and are missing matches.

* Frequency: Infrequent as the % of Summoners who have played 1000+ matches this season are low.
* Severity: Low, nothing breaks but user will notice the season stats are inaccurate.

**Repro Steps**  
1. Find a Summoner who has played more than 990~ games this season.
2. Using the `MatchV5` `/matches/by-puuid/{puuid}/ids` endpoint, attempt to fetch any MatchIDs after the first 1000. ie.  `?start=1000&count=100`

**Comment by geozukunft** [comment]
Tried calling the matchlists of the mentioned players. Can confirm the issue.

**Comment by RiotTuxedo** [comment]
The match list is currently capped at 1k games. Currently I don't foresee us increasing this limit, but if the match list gets rearchitected (something we've considered) then this might be something that's adjusted in the future.

**Comment by Renkon** [comment]
Are there any plans to uncap the match lists endpoint? It'd be really interesting at least to get access to the whole season.

**Comment by Renkon** [comment]
@RiotTuxedo are there any plans to uncap the match lists endpoint? It'd be really interesting at least to get access to the whole season.
