### ISSUE TITLE
[BUG] Access-Control-Allow-Origin Error

### ISSUE THREAD

**Issue by r1ttle** [RiotGames/developer-relations#518]
**Bug Description**  

When sending an API request not including the API key of my approved product, it is probabilistically included in the response header.
"Access-Control-Allow-Origin": "*" does not contain, so it has CORS policy issue

![에러](https://user-images.githubusercontent.com/88995439/129726456-f5362264-d928-4c28-be79-5a1af875261c.png)
![에러2](https://user-images.githubusercontent.com/88995439/129726465-1cfb575c-3f62-496d-a8cd-d7467c93fc91.png)

**Problem Description**  
When sending an API request not including the API key of my approved product, it is probabilistically included in the response header.
"Access-Control-Allow-Origin": "*" does not contain, so it has CORS policy issue

**Expected Result**  
data normally responsed

**Actual Result**  
data don't responsed  probabilistically

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Severity: When it happens, my whole website crashes.

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

* Severity: When this bug happens, a user is unable to use my site. 

**Preconditions**  
What conditions must be met in order for this bug to occur?

* I submit this problem because I don't know :(

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Send AJAX request

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by bangingheads** [comment]
Hi r1ttle,

CORS headers are not included on purpose. If you make a request from the front end of your site you are exposing your API key to your users, which then any of them can use.

You will need a back-end to your website to make the calls then pass the data to your front-end to prevent exposing your API key.

**Comment by r1ttle** [comment]
> Hi r1ttle,
> 
> CORS headers are not included on purpose. If you make a request from the front end of your site you are exposing your API key to your users, which then any of them can use.
> 
> You will need a back-end to your website to make the calls then pass the data to your front-end to prevent exposing your API key.

Should I use node js??

**Comment by bangingheads** [comment]
Node will work if that is your preference, yes.

**Comment by RiotTuxedo** [comment]
The key is the code must be run server side. Javascript is client side. Node, as you suggested, is server side. Doesn't have to be Node, but it must be server side.
