### ISSUE TITLE
[BUG] `killerId` for `TURRET_PLATE_DESTROYED` event is always `0`

### ISSUE THREAD

**Issue by lmachens** [RiotGames/developer-relations#520]
**Bug Description**  
When using the Match Timeline v5 endpoint, every `TURRET_PLATE_DESTROYED` event have a `killerId` of `0`. 

**Problem Description**  
I try to know who destroyed which turret plate, which is not possible. I would expect that it's `0` if it was destroyed at 14:00 or destroyed by minions.

**Expected Result**  
It should have the value of the participant id who destroyed the turret plate.
Examples:
`https://europe.api.riotgames.com/lol/match/v5/matches/EUW1_5417995850/timeline?api_key=`
`https://europe.api.riotgames.com/lol/match/v5/matches/EUW1_5422395721/timeline?api_key=`

**Actual Result**  
```json
{
  "killerId": 0,
  "laneType": "BOT_LANE",
  "position": {
    "x": 10504,
    "y": 1029
  },
  "teamId": 100,
  "timestamp": 604783,
  "type": "TURRET_PLATE_DESTROYED"
},
```

**Developer Impact**  
I added trophies for [Trophy Hunter](https://th.gl/) which requires knowing who destroyed which turret plate.
These trophies are not working right now.

**Preconditions**  
Have a match where a turret plate was destroyed by a player.

**Repro Steps**  
1. Investigate this match (with your API key): `https://europe.api.riotgames.com/lol/match/v5/matches/EUW1_5422395721/timeline?api_key=`
1. Search for `TURRET_PLATE_DESTROYED` events

**Comment by dwynish** [comment]
Hi,

Any update on this subject?

**Comment by lmachens** [comment]
It looks like this is still an issue

**Comment by JoschuaGoetz** [comment]
It seems they actually fixed this issue. 
I can see games with `killerId` being something else than 0. But i haven't verified if they are accurate/complete.
Example game: KR_6156833442.

This first happened with games on the 20th september 2022

**Comment by lmachens** [comment]
> It seems they actually fixed this issue. I can see games with `killerId` being something else than 0. But i haven't verified if they are accurate/complete. Example game: KR_6156833442.
> 
> This first happened with games on the 20th september 2022

Thank you, I can approve this

**Comment by germanitxu** [comment]
Hello! 
I found another iteration of this bug, when using Match Timeline endpoint, some events have `killerId` of `0` .
Example of result for game id `EUW1_6832164434`:

```JSON
{
  "bounty": 0,
  "buildingType": "TOWER_BUILDING",
  "killerId": 0,
  "laneType": "TOP_LANE",
  "position": {
      "x": 4318,
      "y": 13875
  },
  "teamId": 200,
  "timestamp": 797980,
  "towerType": "OUTER_TURRET",
  "type": "BUILDING_KILL"
},
```

This is not an isolated case in the timeline result, but I have test other matches to see if it persists
