### ISSUE TITLE
[BUG] Unable to invite friends to join practice mode

### ISSUE THREAD

**Issue by yh4922** [RiotGames/developer-relations#522]
**Bug Description**  
Unable to invite friends to join practice mode
Through the client API lol-lobby/v2/lobby to create a practice mode room, invite friends to start the game, too many people return errors

This is what ROIT deliberately did, or is it an unexpected bug

**Comment by Querijn** [comment]
Seems so, the Practice Mode only allows for a single person, so if the lobby has one already, it won't allow for another. It seems a deliberate action, since this was recently abused for clickbait Youtube content.

**Comment by yh4922** [comment]
> Seems so, the Practice Mode only allows for a single person, so if the lobby has one already, it won't allow for another. It seems a deliberate action, since this was recently abused for clickbait Youtube content.

Too bad. Clickbait Youtube content, when did this happen, I want to know

I really want to play practice mode with my friends

**Comment by Querijn** [comment]
https://www.youtube.com/watch?v=BYMHpY83kRY

**Comment by yh4922** [comment]
> https://www.youtube.com/watch?v=BYMHpY83kRY

I understand that someone created a practice mode with the client API, recorded a video on YouTube and told everyone that he modified the game client code, did these comments have a bad effect on roit?

Don't know if my understanding is correct😂

**Comment by Querijn** [comment]
Sure

Main takeaway is that the behaviour is correct, seems intentional, and therefore not a bug. Could you close the ticket?

**Comment by yh4922** [comment]
OK, thanks
