### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by LunaYi101** [RiotGames/developer-relations#523]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

sandboxapi

**Issue Description**  
A clear and concise description of what the issue is.

When I attempted to log in, it simply says that my account is an invalid account.

**What I've Tried**
What steps have you tried to resolve the issue.

Contact riot developer relations twitter + discord.

- [v] Log out of the Developer Portal
- [v] Attempt to log in via "Incognito Mode"
- [v] Clear your browser cookies
- [v] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

This problem occurred around 3~4 weeks ago. At first, riot developer portal was in vacation, but next didn't receive any reply.
Not sure what is going on.

**Comment by RiotTuxedo** [comment]
The following article should help.
https://support-leagueoflegends.riotgames.com/hc/ko/articles/360044383973-%EC%A0%9C-%EA%B3%84%EC%A0%95%EC%9D%B4-%EC%9E%A0%EA%B2%BC%EC%8A%B5%EB%8B%88%EB%8B%A4-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC-%ED%95%98%EB%82%98%EC%9A%94-
