### ISSUE TITLE
[BUG] Getting random 400's

### ISSUE THREAD

**Issue by hectorgabucio** [RiotGames/developer-relations#525]
**Bug Description**  
Hey, I'm getting randoms 400 on LOL API responses. 

**Problem Description**  
I'm running a league crawler that keeps all ranked summoners from EUW updated. Once a day, the crawler dies because of a random error 400 (bad request). Weird because I make a lot of API requests and all of them work but sometimes one fails.

**Expected Result**  
I expect all endpoints to work fine (unless I receive 5xx error). If something server-side fails, I should receive a 5xx not a 400, thats hard to handle.

**Actual Result**  
- I got a 400 when calling this endpoint https://euw1.api.riotgames.com/lol/league/v4/entries/RANKED_SOLO_5x5/BRONZE/II?page=614
- I got a 400 when calling match v5 endpoint https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/YDDCdYHMBkZh-yHRNYrCQmQQVetuA4TmOtVTskO3NtCD9oAOKfKS63z74GUDaQTV5NxaDCHQkgXD3A/ids?count=100&start=0
Logs example: https://pastebin.com/sGdBeBLv

**Developer Impact**  

* Frequency: Low frequency, like 1 of thousands.
* Severity: When it happens, my crawler crashes.
* Efficiency: It slows down my product because it crashes and has to restart.

**Repro Steps**  
No idea, that's the problem, I don't know what is causing it.

**Comment by RiotTuxedo** [comment]
What's your app id?

**Comment by hectorgabucio** [comment]
@RiotTuxedo my app id is 506153
