### ISSUE TITLE
[BUG] Call for a player's match IDs using matchv5 not returning up-to-date matches

### ISSUE THREAD

**Issue by NFeruch** [RiotGames/developer-relations#527]
**Bug Description**  
A call through matchv5's url of the form, "/lol/match/v5/matches/by-puuid/{puuid}/ids", returns old games only, and not that player's actual most recent games played

**Problem Description**  
Getting a list of match IDs via a player's PUUID from matchv5 returns matches that were played over a week ago, and not their most recent ones.

**Expected Result**  
I am expecting to get a list of a player's most recent matches played when calling matchv5's get match ids by puuid

**Actual Result**  
matchv5 returns matches that are a week old from when the player has actually played. The player irl has played 1 day ago, but the API returns matches from 7+ days prior only

**Developer Impact**  
I wish to implement an updating system, so that the player can review their most recent matches, but cannot because matchv5 is returning week-old matches only

* Frequency: Every API call
* Severity: Medium severity, blockade for further development
* Cost: Time that could be spent on advancement of features
* Efficiency: Cannot receive accurate data

**Player Impact**  
If a player wishes to see their most recent matches, they are unable to via the api, which is frustrating

**Preconditions**  
Calling the matchv5 url using a valid API key and valid puuid

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. A call to "https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/CYzJo3m60KnSlIoWnGAhVI7IpUBo2D4DC7hErpatH3FOiMUMjx-ZJXKVkYw-bzeqE_-e0r3QMDr_DA/ids?api_key=API_KEY_HERE&count=50", where "CYzJo3m60KnSlIoWnGAhVI7IpUBo2D4DC7hErpatH3FOiMUMjx-ZJXKVkYw-bzeqE_-e0r3QMDr_DA" is a sample player's puuid, return week old matches consistently. This should not be happening, because irl they have played within the last 7 days

**Comment by summonerriftofficial** [comment]
any updates :(

**Comment by gianmarcozizzo** [comment]
Up

**Comment by ofelipedidio** [comment]
I had this problem a couple of days ago and now it seems to be fixed.

**Comment by idunnololz** [comment]
Still not entirely fixed. See ign "idunnololz" region "na". If you compare the last 20 games returned by match-v4 and match-v5 you can see some games are missing from match-v5

**Comment by Taifunov** [comment]
still doesn't fixed?

**Comment by RiotTuxedo** [comment]
For the most part, we should be in a reasonably good state.

1. We've completed the match reconciliation in all riot regions, so players shouldn't be missing their match history.
2. The read replica the API uses is rarely behind (replication lag) and when it is it's not by much and quickly recovers.
3. We're seeing failed cache evictions where the player's matchlist isn't properly evicted from the cache when a new match is completed. We believe is related to the reoccurring issues resulting in the service returning 503s. We're currently investigating this.

As such, we believe it should be relatively rare for a player's matchlist to be significantly behind (on the order of several matches). At most, we expect the majority of players to have their match list updated within minutes of them completing a match. A small number of players should be affected by the failed cache evictions mention in #3.

**Comment by NFeruch** [comment]
Thank you!

**Comment by tisbells** [comment]
Closing out old issues. This was resolved. Feel free to reopen or comment if you feel this is in error.
