### ISSUE TITLE
[BUG] LOR-MATCH-V1 doesn't return recent matches for some players

### ISSUE THREAD

**Issue by Alessandro-Balconi** [RiotGames/developer-relations#528]
**Bug Description**  
A call to */lor/match/v1/matches/by-puuid/{puuid}/ids* returns recent matches for some players, but old matches for some others.

**Problem Description**  
Getting a list of match IDs via a player's PUUID from LOR-MATCH-V1 does not return the most recent ones.

**Expected Result**  
API calls returns the 20 most recent matches played by a player.

**Actual Result**  
API calls returns 20 matches, but not the most recent ones.

**Developer Impact**  
I'm collecting data to generate reports on the meta of Legends of Runeterra. Being unable to collect recent match data means I'm not able to make these reports. 
Also, a new expansion just launched and ir would be nice to get data about the impact of the expansion on the meta, but right now most players' match history still returns games played before the expansion.

* Frequency: Happens with the majority of the players (not all of them, some are correct).

**Repro Steps**  
As already said, this doesn't happen with every player, but with the majority of them.

1. Step 1: call  */lor/match/v1/matches/by-puuid/{puuid}/ids* using one of the bugged players
1. Step 2: expect to see the most recent matches played by them; but actually I get older matches of the player.

**Issue Comments**  
While this might be a duplicate of #527 (feel free to close if that's the case), I wanted to make sure you guys are aware that LoR match API is experiencing the same issue.

**Comment by RiotTuxedo** [comment]
@Alessandro-Balconi can you be a little more specific here. Can you provide your app id, some puuids, and timestamp of matches. As far as I'm aware, there might have been some match history that was lost for LOR in the last couple weeks, but it should have been isolated to a couple days and not weeks/months.

**Comment by MaouLegna** [comment]
@RiotTuxedo this is an example for the same problem that is happening to me:

ID:506116
the player: dj666x#EUW on EU
puuid: As7Gjo1QsVrJZfEmRYyvUtfNWH3x1lo0ajdL3aP4g9CdTXCiZzAs6F9AO9K09jFMa20MscLWdOAAww
with latest game: a1a53218-6435-49ae-8545-4e8eeb5a3a92
which started at: 2021-08-25T22:14:33.7135542+00:00
But this player reached Master one or two days later so it's clearly missing games.

But the problem is currently happening for example for all Masters players in all 3 shards, if more examples are necessary.

**Comment by RiotTuxedo** [comment]
Ah ha, you've found a bug. We'll be deploying a fix for this soon and it should resolve when these players complete their next match after this bug fix is deployed.

**Comment by paaksing** [comment]
Currently some players has their matchlists behind by 6+ days.

**Comment by Alessandro-Balconi** [comment]
It seems to be fixed now, so I'm closing this. Thanks for quickly addressing the issue 😊
