### ISSUE TITLE
[BUG] When the match v5 would be available for production keys?

### ISSUE THREAD

**Issue by pitzcarraldo** [RiotGames/developer-relations#529]
**Problem Description**  

`/lol/match/v5/matches/by-puuid/` API returns 403 when using a production api key.

**Expected Result**  

403 

**Actual Result**  

200 with correct response.

**Developer Impact**  

Can't migrate to new API with a production key.

**Issue Comments**  

According to the [API doc](https://developer.riotgames.com/apis#match-v5), match v5 api had to be available for production access on Aug 16th. And it says match v4 would be deprecated on Sep 6th as well, which is just in a week from now. But I still can get a correct response from match v5 api `/lol/match/v5/matches/by-puuid/`. I'm receiving only 403. But it works with developer keys. Which is not usable for real products. What is the actual plan for releasing new API for production keys?

**Comment by RiotTuxedo** [comment]
That's my mistake. I've been updating the deprecation date, but I forgot to update the date for production key availability. We're hoping to enable production key access today.
