### ISSUE TITLE
[QUESTION] Undocumented changes to the "Legacy Mode" setting

### ISSUE THREAD

**Issue by xEcEz** [RiotGames/developer-relations#530]
### Question
The last patch introduced a change to the *Legacy Mode* setting that can be toggled in the client ("IN-GAME" > "GAME" > "Prefer XXX Legacy Mode"). The sentence went from *Prefer DX9 Legacy Mode* to "Prefer OpenGL Legacy Mode".

Did you actually swap the legacy render engine to use OpenGL instead of DirectX9? Or is it simply a mistake tied to the setting naming?

**Comment by MasterMann** [comment]
This question is not applicable for this repo. This repository is only for questions regarding third-party application development for the Riot ecosystem, not general player questions.

**Comment by xEcEz** [comment]
I am a third-party developer, and that option could directly impact the performance of my app and users. I hence think it's fair that this question gets answered here given the potential importance of the change.

**Comment by xEcEz** [comment]
Looking more closely into it, it seems that this is not a simple naming change but a proper behavior one.

From `game.cfg`:
```
PreferOpenGLLegacyMode=1
PreferDX9LegacyMode=0
```

That setting used to modify the value of `PreferDX9LegacyMode` while it now affects `PreferOpenGLLegacyMode`, as the client setting name suggests.

Obviously that is a big deal, and I don't understand why no communication has been made about it in the patchnote. If it does affects us in the way we help our users achieve the best performance while using our app, it also affects any League player that used to rely on DX9 and got silently "redirected" to using OpenGL instead.
