### ISSUE TITLE
我发现有部分插件可以实现自动配置召唤师技能的功能，请问有提供这种的客户端的api吗？这个问题已经困扰了我几天了

### ISSUE THREAD

**Issue by he429134733** [RiotGames/developer-relations#531]
我发现有部分公约插件可以实现自动配置召唤师技能的功能，请问有提供这种的客户端的api吗？这个问题已经困扰了我几天了

**Comment by junioryono** [comment]
/lol-champ-select/v1/session/my-selection

**Comment by he429134733** [comment]
那请问，选择英雄和确定英雄是哪两个接口？我也寻找了很久了

**Comment by tisbells** [comment]
Closing old issues. We are unable to support the LCU.
