### ISSUE TITLE
[BUG] When the version 11.17 would be updated in datadragon?

### ISSUE THREAD

**Issue by trialo96** [RiotGames/developer-relations#532]
**Problem Description**  
https://ddragon.leagueoflegends.com/api/versions.json does not contain 11.17.1

**Expected Result**  
[ "11.17.1", "11.16.1", ... ]

**Actual Result**  
[ "11.16.1", ... ]

**Developer Impact**  
Can't get data about version 11.17.1

**Comment by RiotTuxedo** [comment]
Poked some folks. 11.17 should be out now.
