### ISSUE TITLE
[BUG] Datadragon item.json does not have Ornn items

### ISSUE THREAD

**Issue by trialo96** [RiotGames/developer-relations#533]
**Problem Description**  
https://ddragon.leagueoflegends.com/cdn/11.17.1/data/en_US/item.json does not have Ornn items such as Draktharr's Shadowcarver(key: 7002), Typhoon(7006), Bloodward(7008), ...

**Expected Result**  
data for Ornn items
ex) {id: 7006, name: Typhoon, ... }

**Actual Result**  
no data for Ornn items

**Developer Impact**  
want to analyze post-game item efficiency

**Issue Comments**  
If I want to use Ornn item asset, how can I get image like this?
![image](https://user-images.githubusercontent.com/67891553/131779075-367969aa-2262-444c-a637-83d011efb8b8.png)

**Comment by thisKeeWord** [comment]
@RiotTuxedo It still seems to be the case for [11.18.1](https://ddragon.leagueoflegends.com/cdn/11.18.1/data/en_US/item.json)

**Comment by trialo96** [comment]
[11.19.1](https://ddragon.leagueoflegends.com/cdn/11.19.1/data/en_US/item.json) too...

**Comment by trialo96** [comment]
#590
