### ISSUE TITLE
Tournament organization

### ISSUE THREAD

**Issue by CoachOni** [RiotGames/developer-relations#535]
Hello Riot, 
I am wanting to build a tournament that is much like Worlds but just for NA Discord Leagues. I have ready the Tournament Organizer page and all the requirements but it does not clearly communicate about marketing of the tournament. Is it "riot legal" for me to market the tournament?

If all entry fees are used to pay for prize pooling and production costs then would my "organization" be able to profit off of accepting sponsors for the tournament so long as there is no violation that is listed on the na-tournaments page of the policies?
https://developer.riotgames.com/policies/na-tournaments

**Comment by lucasMesquitaBorges** [comment]
Hey, I'm tackling old issues. If this still makes sense, and because is very related to your use case, please contact us via devportal app messages (Go to your apps > Messages tab).
