### ISSUE TITLE
[BUG] Missing MatchTimelineDto spec

### ISSUE THREAD

**Issue by pitzcarraldo** [RiotGames/developer-relations#539]
**Problem Description**  

`match-v4 is being deprecated on Monday, September 13th, 2021. Please use match-v5 as a replacement.`

https://developer.riotgames.com/apis#match-v5/GET_getTimeline

According to API list page, match v4 APIs will be deprecated on September 13th, which is only 2days after from Today.
But still there is no spec of v5 MatchTimelineDto, so that I couldn't migrate my features that uses a v4 timeline API.

I tried to use same dto as v4, but some fields are missing. Is there any plan to extends a deprecation schedule?

**Comment by RiotTuxedo** [comment]
You'll need to migrate without the response documentation in order to ensure uninterrupted service. We're still working on adding the documentation for the timeline.

match-v4 will no longer return any new matches played after Monday, September 13th but it'll remain in place returning static/stale data until Monday, September 27th.

**Comment by MingweiSamuel** [comment]
I have a semi-manually created spec for the timeline DTO here: http://www.mingweisamuel.com/riotapi-schema/tool/

**Comment by 0xdevalias** [comment]
@RiotTuxedo Curious why this issue was closed, as it appears that the docs/spec still aren't updated for this endpoint:

- https://developer.riotgames.com/apis#match-v5/GET_getTimeline

I would have expected that this issue should stay open to track this until it's completed?

**Comment by MingweiSamuel** [comment]
The issue creator closed it erroneously. I have it listed here (as one bullet) though: https://github.com/RiotGames/developer-relations/issues/487
