### ISSUE TITLE
how to convert game data to live streaming?

### ISSUE THREAD

**Issue by An-uking** [RiotGames/developer-relations#54]
Is there such a tool that can convert game data into a live stream so that users can watch the game on the phone? If I use OBS to push the stream, users  can only watch one game at a time, and I need to open the game client. If recording a video is too cumbersome and takes a lot of time

**Comment by RiotTuxedo** [comment]
Hey @An-uking, unfortunately we don't handle open forum questions in this format. This kind of question is best suited for the community Discord. You'll probably get more people than can assist there as well.

https://discord.gg/riotapi
