### ISSUE TITLE
[BUG] Match V5 still responds a different result from Match V4 (Matchlist)

### ISSUE THREAD

**Issue by Clap2rap** [RiotGames/developer-relations#542]
**Bug Description**  
I checked a matchlist response of GamerA played between 2021-08-18T04:59:41Z and 2021-08-18T09:44:55Z.
I used the following endpoints:
- Match-V5 endpoint: /lol/match/v5/matches/by-puuid/{puuid}/ids
- Match-V4 endpoint: /lol/match/v4/matchlists/by-account/{encryptedAccountId}

Each result is as follows:
- Match-V4 result:
` {
    "matches": [
        {
            "platformId": "KR",
            "gameId": 5399930433,
            "champion": 113,
            "queue": 420,
            "season": 13,
            "timestamp": 1629278048806,
            "role": "NONE",
            "lane": "JUNGLE"
        },
        {
            "platformId": "KR",
            "gameId": 5399826552,
            "champion": 59,
            "queue": 420,
            "season": 13,
            "timestamp": 1629276133979,
            "role": "NONE",
            "lane": "JUNGLE"
        },
        {
            "platformId": "KR",
            "gameId": 5399794920,
            "champion": 99,
            "queue": 1020,
            "season": 13,
            "timestamp": 1629275006257,
            "role": "DUO_SUPPORT",
            "lane": "NONE"
        },
        {
            "platformId": "KR",
            "gameId": 5399781867,
            "champion": 117,
            "queue": 420,
            "season": 13,
            "timestamp": 1629273560800,
            "role": "DUO_SUPPORT",
            "lane": "NONE"
        },
        {
            "platformId": "KR",
            "gameId": 5399684493,
            "champion": 234,
            "queue": 420,
            "season": 13,
            "timestamp": 1629270720818,
            "role": "NONE",
            "lane": "JUNGLE"
        },
        {
            "platformId": "KR",
            "gameId": 5399389825,
            "champion": 113,
            "queue": 420,
            "season": 13,
            "timestamp": 1629268230704,
            "role": "NONE",
            "lane": "JUNGLE"
        },
        {
            "platformId": "KR",
            "gameId": 5399386464,
            "champion": 59,
            "queue": 420,
            "season": 13,
            "timestamp": 1629266577020,
            "role": "NONE",
            "lane": "JUNGLE"
        },
        {
            "platformId": "KR",
            "gameId": 5399383044,
            "champion": 113,
            "queue": 420,
            "season": 13,
            "timestamp": 1629264883075,
            "role": "NONE",
            "lane": "JUNGLE"
        }
    ],
    "startIndex": 0,
    "endIndex": 8,
    "totalGames": 8
}`
- Match-V5 result: 
`[ ]`

So I thought it's because of "Match-V5's startTime and endTime options bug" or "Just no data exists(in fact, they exists but not responded) on Match-V5". And I manually tried to find matchlist on Match-V5 and the result(options - start:170, count:100) is as follows:
`
[
    "KR_5403188012",
    "KR_5403087540",
    "KR_5403170051",
    "KR_5402996556",
    "KR_5402608399",
    "KR_5402586344",
    "KR_5402634007",
    "KR_5402601635",
    "KR_5402357048",
    "KR_5401636964",
    "KR_5401632048",
    "KR_5401526975",
    "KR_5401483798",
    "KR_5401379762",
    "KR_5401374946",
    "KR_5401339462",
    "KR_5401315888",
    "KR_5398803874",
    "KR_5398769326",
    "KR_5397815904",
    "KR_5397831455",
    "KR_5397756969",
    "KR_5397712355",
    "KR_5397657625",
    "KR_5397613695",
    "KR_5397569455",
    "KR_5397574364",
    "KR_5395908210",
    "KR_5395961165",
    "KR_5395845613",
    "KR_5395768919",
    "KR_5395733165",
    "KR_5395588234",
    "KR_5395418159",
    "KR_5395396532",
    "KR_5395480522",
    "KR_5394636744",
    "KR_5388633012",
    "KR_5388486857",
    "KR_5388482109",
    "KR_5388416045",
    "KR_5388381560",
    "KR_5387024273",
    "KR_5386887963",
    "KR_5386933083",
    "KR_5386819318",
    "KR_5386776229",
    "KR_5386771120",
    "KR_5386476776",
    "KR_5386453271",
    "KR_5386379179",
    "KR_5386373191",
    "KR_5386281107",
    "KR_5384805508",
    "KR_5384840522",
    "KR_5384755715",
    "KR_5384667881",
    "KR_5384651694",
    "KR_5384557339",
    "KR_5384511563",
    "KR_5382705344",
    "KR_5382649364",
    "KR_5382605938",
    "KR_5382611782",
    "KR_5382584221",
    "KR_5382510659",
    "KR_5382422409",
    "KR_5382268055",
    "KR_5380892643",
    "KR_5380684460",
    "KR_5380561325",
    "KR_5380504735",
    "KR_5380460605",
    "KR_5380383673",
    "KR_5380410179",
    "KR_5380257766",
    "KR_5380292877",
    "KR_5380159625",
    "KR_5379774641",
    "KR_5376059438",
    "KR_5376063188",
    "KR_5375928016",
    "KR_5375910192",
    "KR_5375844205",
    "KR_5375757576",
    "KR_5375740785",
    "KR_5374033864",
    "KR_5374050405",
    "KR_5373932044",
    "KR_5373637797",
    "KR_5373692826",
    "KR_5373438590",
    "KR_5373492661",
    "KR_5373329292",
    "KR_5371988348",
    "KR_5371922536",
    "KR_5371838451",
    "KR_5371904003",
    "KR_5371821074",
    "KR_5371803865"
]
`
There's no KR_5399xxxxxx match ids.

**Developer Impact**
Cannot trust Match-V5's match id list endpoint.
So I must use both V4 & V5(for matchlist played after the deprecation of V4) to get one player's matchlist of certain time span.

**Player Impact**  
None

**Preconditions**  
* Summoner's encryptedPuuid and encryptedAccountId (who played matches quite a lot)
* Time span(about several hours)

**Repro Steps**  
1. Determine arbitrary time span(about several hours after June 16th, 2021).
2. Compare responses between Match-V4 and Match-V5.
3. Some match ids are not present on Match-V5.

**Issue Comments**  
Match-V5 should respond the same Match-V4's match id list data after June 16th, 2021.

**Comment by Clap2rap** [comment]
I just found that "Match-V5's startTime and endTime options bug" also exists because with using startTime & endTime options, Match-V5 responded `[]` but without using those options, there are match ids I want.

In summary:
"Match-V5's startTime and endTime options bug" and "Just no data exists(in fact, they exists but not responded) on Match-V5" both exist!

**Comment by marcmuschko** [comment]
@Clap2rap not sure how it was 9 days ago, but now it is working. 
However, match-v5 requires startTime/endTime parameters as **timestamp in seconds** while match-v4 requires timestamps in miliseconds, I missed that at first as well and got [] responses, maybe that solves your issue?

**Comment by Clap2rap** [comment]
@marcmuschko Thanks! **timestamp options bug** was my misunderstood:)
