### ISSUE TITLE
[BUG] match-V5 missing on https://developer.riotgames.com/api-status/

### ISSUE THREAD

**Issue by geozukunft** [RiotGames/developer-relations#544]
**Bug Description**  
The match-V5 endpoint is missing on https://developer.riotgames.com/api-status/

**Problem Description**  
It's missing

**Expected Result**  
See uptime stats of match-V5 on https://developer.riotgames.com/api-status/

**Actual Result**  
Can't see uptime stats of match-V5 on https://developer.riotgames.com/api-status/ 

**Developer Impact**  
Can't say for sure if match-V5 is having issues

* Frequency: Every time someone opens the website
* Severity: Would be nice to have

**Player Impact**  
No direct impact for players

**Repro Steps**  
1. Open https://developer.riotgames.com/api-status/

**Comment by bangingheads** [comment]
This is also the case for all newer endpoints, primarily all non league of legends endpoints.

**Comment by geozukunft** [comment]
*pings* Maybe we could get this issue solved would also help in a bunch of people coming onto the discord and asking why match-v4 is not working and then linking to that page :|

**Comment by Janmm14** [comment]
Ping. Issue still not solved.

**Comment by Janmm14** [comment]
The API status page also does not contain any status of shard EUW

**Comment by geozukunft** [comment]
yeah the API status page can be seen as deprecated now

**Comment by hingston** [comment]
> yeah the API status page can be seen as deprecated now

Did anything replace it? What's the best way to confirm API status?

**Comment by geozukunft** [comment]
We are working on a community made replacement that determines availbility through periodic requests. Otherwise the best way to know if something is down on Riots side is either this github repo or the #lol-dev chat on the community run Discord server where if there is an outage you'll usually find multiple people talking about it already.

**Comment by tisbells** [comment]
Hiya - That status page was built on very old framework that we had no way to easily update with newer APIs, so we've removed it for now to avoid confusion. A new status page is part of planned improvements for the future.
