### ISSUE TITLE
[BUG] Call for a player's matchlist infomation by accountId using matchv4 not returning up-to-date matches

### ISSUE THREAD

**Issue by syz0223** [RiotGames/developer-relations#547]
**Bug Description**  
A call through matchv4's url of the form, "/lol/match/v4/matchlists/by-account/", returns games 10 days ago only, and not that player's actual most recent games played
**Problem Description**  
A clear and concise description of what the problem is.
Getting a list of match IDs via a player's accountId from matchv4 returns matches that were played over 10 days ago, and not their most recent ones.
**Expected Result**  
What were you expecting to happen after you performed the above steps? Include screenshots, logs, or a description.
I hope to get up-to-date match lists and information via matchv4
**Actual Result**  
What actually happened after you performed the above steps? Include screenshots, logs, or a description.
matchv4 returns matches that are nearly 10 days before the player has actually played. The player irl has played 1 day ago, but the API returns matches from 10+ days prior only
**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.
I hope to implement a system to help players track most recent matches, but cannot because matchv4 is returning 10-day-ago matches only
* Frequency: Every API call
* Severity: This issue is very urgent for me.
* Efficiency: Cannot receive up-to-date data

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.
players are unable to check their most recent matches via the api by using their account id

**Preconditions**  
What conditions must be met in order for this bug to occur?
Calling the matchv4 url using a valid API key and valid account id 

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Step 1: A call to"/lol/match/v4/matchlists/by-account/{encryptedAccountId}"
1. Step 2: only return matches 10 days ago

**Comment by Token07** [comment]
https://twitter.com/RiotGamesDevRel/status/1436011254552805377

https://twitter.com/RiotGamesDevRel/status/1441619249399681027

**Comment by syz0223** [comment]
Thank you for sharing!!!!
