### ISSUE TITLE
[BUG] Match-v5 missing some match ids

### ISSUE THREAD

**Issue by colin-jiang** [RiotGames/developer-relations#548]
**Bug Description**  
Match id from this season is found in match-v4 but match-v5 returns 404 with message: "Data not found - match file not found"

**Problem Description**  
Missing Match id: NA1_3758773131
Match-v5 API call: https://americas.api.riotgames.com/lol/match/v5/matches/NA1_3758773131

Match-v4 API call: https://na1.api.riotgames.com/lol/match/v4/matches/3758773131

**Expected Result**  
Match data

**Actual Result**  
{
    "status": {
        "message": "Data not found - match file not found",
        "status_code": 404
    }
}

**Developer Impact**  
Missing match data when migrating to match-v5

* Frequency: Found this example after few thousand match api calls

**Comment by tisbells** [comment]
Closing out old issues. If you are still experiencing this, please comment or reopen.
