### ISSUE TITLE
[FeatureRequest] Allow custom game custom config

### ISSUE THREAD

**Issue by AzuStar** [RiotGames/developer-relations#549]
Hi.
I wanted to ask if that would be possible to allow creation of customizable lobbies?
For example, POST request to `/lol-lobby/v2/lobby` with body 
```
{"customGameLobby": {
    "configuration": {
      "gameMode": "ARAM", "mapId": 12, "mutators": {"id": 5},teamSize:1
    },
    "lobbyName": "ttw",
    "lobbyPassword": ""
  },
isCustom:true}
```
Yields this error message
```
Couldn't change lobby: Error creating lobby: Error response for POST /lol-login/v1/session/invoke: LCDS invoke to gameService.createPracticeGameV3 failed: Server.Processing, com.riotgames.platform.game.GameModeNotSupportedException : Custom game type disabled
```

The mutator is clearly is just disabled. Ideally, configurable mutators altogether.

**Comment by RiotTuxedo** [comment]
The League Client API isn't a supported resource for third party developer usage.

**Comment by AzuStar** [comment]
Is that possible to configure through developer account then? Does that mean I have to create tournaments to configure mutators? Ir is jt still not possible even with developer account?
