### ISSUE TITLE
[BUG] /lol/match/v5/matches/by-tournament-code/{tournament code}/ids missing endpoint

### ISSUE THREAD

**Issue by mustafashykh** [RiotGames/developer-relations#552]
**Bug Description**  
Need to fetch match ids against a particular tournament code, but can't find the endpoint.

**Problem Description**  
Previously in V4 we had `/lol/match/v4/matches/by-tournament-code/{tournament code}/ids`
But what's the workaround for Match V5.

**Expected Result**  
Match Ids against a particular tournament code

**Actual Result**  
403 Forbidden

**Developer Impact**  
Breaks the current implementation for people using kayn 
https://www.npmjs.com/package/kayn

* Frequency: Every API call.
* Severity: When it happens, match data can't be fetched.
* User emails: mustafaahmed726@gmail.com

**Comment by geozukunft** [comment]
Use the type query in /matches/puuid and select tourney there that will only deliver tournament games. And as soon as you fetch the game which should be the last game played so the first entry you'll get the tournament code in the match_details

**Comment by mustafashykh** [comment]
> Use the type query in /matches/puuid and select tourney there that will only deliver tournament games. And as soon as you fetch the game which should be the last game played so the first entry you'll get the tournament code in the match_details

I have the tournament code but don't have the puuid, I can get the puuid but won't that only return the match ids for a particular player, tho i get your point let me try, Thanks

**Comment by mustafashykh** [comment]
> Use the type query in /matches/puuid and select tourney there that will only deliver tournament games. And as soon as you fetch the game which should be the last game played so the first entry you'll get the tournament code in the match_details

Tested it out worked but really inefficient, :p

**Comment by geozukunft** [comment]
Inefficient but currently the only way of gathering that data

**Comment by RiotTuxedo** [comment]
Ideally this should be a redundancy with the callbacks. The callback has the match id and the matchlist has a method to filter for custom games created with a tournament code.
