### ISSUE TITLE
[BUG] /match/v5/matches/{matchId} return Illegal championId

### ISSUE THREAD

**Issue by windr0id** [RiotGames/developer-relations#553]
matchId:
EUW1_5097684633
EUW1_5097963383

return this:

"championId": 37225015,
"championName": "Camille",

"championId": 37290552,
"championName": "JarvanIV",

"championId": 37290552,
"championName": "Viego",

seems like a type convert error

-------------------------

by the way I found some match data are not found:
KR_5155454970
KR_5192551547
KR_5192550599

**Comment by MingweiSamuel** [comment]
Same with:
```
JP1_273343663
JP1_267836848
JP1_267647303
JP1_268045590
```
from #554

**Comment by MingweiSamuel** [comment]
Ah right
> Prior to patch 11.4, on Feb 18th, 2021, this field returned invalid championIds. We recommend determining the champion based on the championName field for matches played prior to patch 11.4.

**Comment by tisbells** [comment]
Closing old issues. Fix was posted above and there are no recent reports of this issue. Feel free to reply or re-open if you are still having this problem.
