### ISSUE TITLE
match-V5 teamPosition empty [BUG] 

### ISSUE THREAD

**Issue by geozukunft** [RiotGames/developer-relations#554]
**Bug Description**  
In certain games player get assigned the individualPosition `INVALID` and on those participants the teamPosition is an empty string

**Problem Description**  
It is not possible to determine on which lane the participant was playing without cross checking with other participants of the game.

**Expected Result**  
Get as described in the ParticipantDto of /lol/match/v5/matches/{matchId} the teamPosition which is "the best guess for which position the player actually played if we add the constraint that each team must have one top player, one jungle, one middle, etc."

**Actual Result**  
individualPosition is `INVALID` and teamPosition is empty

**Developer Impact**  
I am not able to determine on which lane the player most likely played. 

* Frequency: On games played on JP1 between January - June 2021 ~0.9% of games played by ranked players
* Severity: The collected data is inacurate 
* Cost: No cost apart from inacurate data lowering the quality of the analysis provided to players

**Player Impact**  
The data provided to the player is not fully representing their actually played games anymore. 

* Region: Currently only tested in JP1 (can  test in other regions too)

**Repro Steps**  
Can't say for sure which games are exactly affected below are a few match_ids with the issue. 

List of game ids:

JP1_312062554
JP1_273343663
JP1_326464722
JP1_289504387
JP1_285797147
JP1_268045590
JP1_267836848
JP1_285434511
JP1_307559381
JP1_292569767
JP1_310138781
JP1_300507433
JP1_283568774
JP1_267647303

If needed I can provide a more extensive list of game ids with this issue

**Comment by bangingheads** [comment]
A great majority of these matches are due to the player being AFK. 

AFK:
JP1_312062554
JP1_273343663
JP1_326464722
JP1_289504387
JP1_267836848
JP1_285434511
JP1_307559381
JP1_292569767
JP1_310138781
JP1_300507433
JP1_283568774

individualPosition is set but teamPosition is empty due to AFK slightly after beginning:
JP1_285797147
JP1_267647303

Player was playing:
JP1_268045590

**Comment by geozukunft** [comment]
Would still expect them to get assigned to the lane they were "supposed" to be playing. Or the wording in the docs should be changed cause with the current wording I'd expect to always have all 5 position assigned for SR games

**Comment by davidweatherall** [comment]
Also happening for me,

GameID: EUW1_5733746955

Data for the game:
```
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 1
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 2
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 3
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 4
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 5
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 6
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 7
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 8
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 9
}
{
  teamPosition: '',
  individualPosition: 'Invalid',
  lane: 'NONE',
  role: 'NONE',
  participantId: 10
}
```

**Comment by RicardoVilaca** [comment]
Same here, i've been having this issue a lot recently.
EUW1_5733369184 is an example

**Comment by 1337MARCEL** [comment]
Seems like an issue across all regions 🙃

**Comment by RiotTuxedo** [comment]
> Frequency: On games played on JP1 between January - June 2021 ~0.9% of games played by ranked players

Anyone else have updated estimates of the impact of this? Games and/or percentages per region 👌

**Comment by metasrc** [comment]
> Anyone else have updated estimates of the impact of this? Games and/or percentages per region 👌

Our system has looked at over 500k games across all regions since 6:00 AM PST today and all of them have had invalid entries for teamPosition (the system doesn't validate individualPosition, but I would imagine it is the same for that based on spot-checking a few manually)

**Comment by geozukunft** [comment]
@RiotTuxedo It seems like these are actually 2 different issues. The first one I originally submitted was because a certain percentage of games had the invalid data (Data for games between January 2021 - December 2021 attached below) and a new issue that seems to be affecting present games in the last x days which I can't provide data for as I don't process those.


Data based on games processed between January 2021 - December 2021 all queues except Player vs AI and Tutorial games also excluding games that had any other of the before known match V5 issues.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/vikto/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/vikto/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



platform | total games processed | games affected | percentage of affected games
-- | -- | -- | --
br1 | 22155269 | 554566 | 2,50%
eun1 | 36634729 | 540301 | 1,47%
euw1 | 124973461 | 1546283 | 1,24%
jp1 | 10040990 | 75997 | 0,76%
kr | 147852228 | 1151912 | 0,78%
la1 | 11455929 | 313532 | 2,74%
la2 | 9369563 | 197288 | 2,11%
na1 | 62906017 | 581855 | 0,92%
oc1 | 3757218 | 21254 | 0,57%
ru | 9983325 | 213410 | 2,14%
tr1 | 11914242 | 189384 | 1,59%



</body>

</html>


If needed I can provide the matchIds or more detailed information about affected queues.

**Comment by jafalter** [comment]
We are also experiencing this issue for the majority of games since 12.4 on EUW and KR.

**Comment by 1337MARCEL** [comment]
Seems like you guys addressed the issue ~ 16 hours ago, possibly right in time when Renata got available to play. :D
Thank you!

**Comment by geozukunft** [comment]
Would still appreciate a offical response on the differences in behaviour that is mentioned in the docs and what actually happens.

**Comment by audi0slave** [comment]
Just wanted to confirm that everything is working great so far. Thank you!

**Comment by geozukunft** [comment]
Closing this issue as it seems like there is no desire to fix the docs on this.
