### ISSUE TITLE
[BUG] Duplicated id in maps.json

### ISSUE THREAD

**Issue by trialo96** [RiotGames/developer-relations#555]
**Problem Description**  
https://static.developer.riotgames.com/docs/lol/maps.json has duplicated mapId. (20 for Crash Site and 20 for Convergence)

**Expected Result**  
Maybe,
`
  ...
  {
    "mapId": 20,
    "mapName": "Crash Site",
    "notes": "Odyssey: Extraction map"
  },
  {
    "mapId": 21,
    "mapName": "Convergence",
    "notes": "Teamfight Tactics map"
  },
  ...
`

**Actual Result**  
`
  ...
  {
    "mapId": 20,
    "mapName": "Crash Site",
    "notes": "Odyssey: Extraction map"
  },
  {
    "mapId": 20,
    "mapName": "Convergence",
    "notes": "Teamfight Tactics map"
  },
  ...
`

**Developer Impact**  
Cannot find exact map from map id

**Comment by RiotTuxedo** [comment]
Convergence is mapId 22. This has been updated.
