### ISSUE TITLE
[Account] login error

### ISSUE THREAD

**Issue by headcha** [RiotGames/developer-relations#556]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

summoner name : 연라리연벤
riot potal id : headcha1

**Issue Description**  
developer portal login fail 

INVALID ACCOUNT
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on Twitter, during office hours on Discord, or create an GitHub issue.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by RiotTuxedo** [comment]
The following article should help.
https://support-leagueoflegends.riotgames.com/hc/ko/articles/360044383973-%EC%A0%9C-%EA%B3%84%EC%A0%95%EC%9D%B4-%EC%9E%A0%EA%B2%BC%EC%8A%B5%EB%8B%88%EB%8B%A4-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC-%ED%95%98%EB%82%98%EC%9A%94-
