### ISSUE TITLE
Match V5 "get match id by puuid" returning 401 eventhough i'm using the key properly

### ISSUE THREAD

**Issue by WandersonKnight** [RiotGames/developer-relations#558]
I'm getting a fairly strange response from this request, everything else works, even the other Match V5 calls (matchId, matchId/timeline). I'm from BR1 server.

The minimal reproducible example is (Python 3.9):
```
matchListJsonData = requests.get(f"https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/{playerPuuid}/ids?start=0&count=20?api_key={key}")
matchListRawData = json.loads(matchListJsonData.text)

print(matchListRawData)
```
The "match id by-puuid" request works just fine on the Riot Dev website, but not on my code. 
playerPuuid and the key are properly assigned, they're working as intended on the rest of the code but the "match by-puuid " request doesn't work even if i paste it directly on Google.

Expected result:
The list of last 20 matches Ids.

What i get:
`{'status': {'message': 'Unauthorized', 'status_code': 401}}`

**Comment by LightshieldDotDev** [comment]
Your query is wrong.

**Comment by WandersonKnight** [comment]
> Your query is wrong.

I'm literally copy-pasting what i get from their API. "You're wrong" ufortunately isn't a helpful reply. Stop trolling.

**Comment by MitchellRomney** [comment]
You've put 2 `?` in your url, change the `?` before `api_key` to `&`

```
matchListJsonData = requests.get(f"https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/{playerPuuid}/ids?start=0&count=20&api_key={key}")
```

**Comment by WandersonKnight** [comment]
Thanks!
The `?` worked with everything else, so i (wrongly) assumed it was the same case here.

Problem solved! (:
