### ISSUE TITLE
[DOWNTIME] SPECTATOR GRID FOR KR REGION IS DOWN FOR 2 WEEKS AND COUNTING

### ISSUE THREAD

**Issue by ianhco** [RiotGames/developer-relations#561]
**dESCRIPTION**

![image](https://user-images.githubusercontent.com/58193352/136713873-43b9deea-cd6e-4a92-902e-f57a7884f9d0.png)
![image](https://user-images.githubusercontent.com/58193352/136713893-b8780d65-6744-43bb-a3e0-f494583ae58a.png)
![image](https://user-images.githubusercontent.com/58193352/136713902-c04d2eb1-a40e-4552-80cb-272c99de26b5.png)

**Comment by paaksing** [comment]
2 wEekS aNd cOuNTinG
![image](https://user-images.githubusercontent.com/58193352/137535675-ce22699d-ac51-4383-8db5-93cd7f1f058e.png)
