### ISSUE TITLE
[BUG] /val/match/v1/matchlists/by-puuid/{puuid} returns less data for some players

### ISSUE THREAD

**Issue by hexIV** [RiotGames/developer-relations#565]
Querying certain players match list returns the following keys:

```
"matchId": "XXXXXXXXXXXXXXX",
"gameStartTimeMillis": XXXXXXXXXXXXX,
"teamId": "Red"
```

but for other players the match list does not return the `teamId` key.

Any particular reason why this was removed for some players? `teamId` key helps us identify if the match is a deatmatch or another mode

**Comment by riotstillrampant** [comment]
Hey, just chatted with the VAL team about this. TeamID was deprecated, so you're seeing it inconsistently based on *when* the game was played, before vs after the field was deprecated. That being said, the team agreed to put in a Queue ID in the near future, so keep an eye out for that.

**Comment by hexIV** [comment]
oh okay, understood.

and looking forward for the Queue  ID key!! that's huge for our project, thank you!
