### ISSUE TITLE
[FEATURE REQUEST] TFT Set 6 Augment Data

### ISSUE THREAD

**Issue by SamGuthrie** [RiotGames/developer-relations#566]
Hi,

With the launch of TFT set 6, I was wondering if there are plans to add a player's Augments to the match history data?

**Comment by riotstillrampant** [comment]
It's known work but not prioritized at this time. We're talking to the TFT team about it.

**Comment by SamGuthrie** [comment]
Understood, thanks for the reply. An update when you know if/when it will be implemented would be great!

**Comment by MingweiSamuel** [comment]
Seem to have been added under undocumented `tft-match-v1.ParticipantDto.augments`? #749

**Comment by tisbells** [comment]
Closing old issues, this one was fixed.
