### ISSUE TITLE
[BUG] TFT Sniper / Scholar emblems got same ID

### ISSUE THREAD

**Issue by Floliroy** [RiotGames/developer-relations#567]
Hi, found a bug on the TFT-MATCH api :
Scholar emblem and Sniper emblem got the exact same ID so there is no way to know from the ID in the api answer which ID is which item.

Proof from https://raw.communitydragon.org/11.22/cdragon/tft/en_us.json :
![image_2021-11-04_034931](https://user-images.githubusercontent.com/45274794/140249584-b16ae6c2-6900-4f9b-acdd-767fc62eda74.png)
![image_2021-11-04_034937](https://user-images.githubusercontent.com/45274794/140249593-2fea40c2-e4db-4a6f-8fc1-fb3eacaa53cc.png)

**Comment by Floliroy** [comment]
Still not fixed on new patch https://raw.communitydragon.org/11.23/cdragon/tft/en_us.json

**Comment by Querijn** [comment]
Heya, it might help evaluating the issue's importance if you could explain how this impacts your application. Does it block you from making a feature? Is the output incorrect? Is there a way around it?

**Comment by Floliroy** [comment]
Hi, i want to create a post game image displaying units with their items and traits for all player in the game (a bit like lolchess does).
And so as items are stored by their IDs in the TFT-MATCH api, i cant know if the unit have scholar or sniper emblem cause it is the same ID.

**Comment by Querijn** [comment]
I've edited my comment to add more information, and I feel like you've missed it: raw.communitydragon.org is not a Riot Games product, and therefore is not up to them to fix it. You're better off posting in the CDragon Discord: https://discord.gg/yNFG5yk

Even if it's based on TFT's internal game files, It's unlikely your problem is given any sort of priority to fix it, so I recommend hotfixing it on your side.

**Comment by Floliroy** [comment]
What i mean is that even on TFT-MATCH api the ID are the same for both emblems (i checked it), do yah it is a minor bug, but it is a bug i guess.
Except if you think its legit that an ID isnt unique.

**Comment by Pyrrian** [comment]
I see this bug is also impacting their own client. (29-11-2021)
![image](https://user-images.githubusercontent.com/63145861/143881918-70b171f7-7099-464a-8495-bd707d246e9d.png)

**Comment by mikaeldui** [comment]
> I see this bug is also impacting their own client. (29-11-2021) ![image](https://user-images.githubusercontent.com/63145861/143881918-70b171f7-7099-464a-8495-bd707d246e9d.png)

What's wrong with **Sniper Taric**?

**Comment by Floliroy** [comment]
> > I see this bug is also impacting their own client. (29-11-2021) ![image](https://user-images.githubusercontent.com/63145861/143881918-70b171f7-7099-464a-8495-bd707d246e9d.png)
> 
> What's wrong with **Sniper Taric**?

He used a scholar spat on taric

**Comment by lucasMesquitaBorges** [comment]
Hi, Issue not related to the Riot API. Feel free to re-open if related directly with the TFT Riot API.
