### ISSUE TITLE
[BUG] missing matchlists

### ISSUE THREAD

**Issue by jadeeeeh** [RiotGames/developer-relations#571]
**Bug Description**  
When I search for a player's matchlists within a specific time range by using /lol/match/v5/matches/by-puuid/{puuid}/ids, it always responds with an empty list, even when this player have played games within the time range. 

**Problem Description**  
I tried to find a player's matchlists from 1637078400000 to 1637596800000 by his puuid. This is the request url.
https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/dRi8Sin5w45gjBobLQ108kqM1xMvgYSZxdTe3e3m8p-Uhn5h49bm6v9A63YP7BLNL3mavk_rI7NYQw/ids?startTime=1637078400000&endTime=1637596800000&start=0
 
The response code is 200, but response body is empty. ([])

However, when I check the player's gaming history without setting time range, I can find at least one match within that time range. 
When I using https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/dRi8Sin5w45gjBobLQ108kqM1xMvgYSZxdTe3e3m8p-Uhn5h49bm6v9A63YP7BLNL3mavk_rI7NYQw/ids?start=0 
I can get [
    "NA1_4107800373",
    "NA1_4107698532",
    "NA1_4107117377",
    "NA1_4106370540",
    "NA1_4104754740",
    "NA1_4104712450",
    "NA1_4101727248",
    "NA1_4101739993",
    "NA1_4101619711",
    "NA1_4100295348",
    "NA1_4100036372",
    "NA1_4099523439",
    "NA1_4099259022",
    "NA1_4098696333",
    "NA1_4098217136",
    "NA1_4098060508",
    "NA1_4097148170",
    "NA1_4097193623",
    "NA1_4097078861",
    "NA1_4097048095"
]

The first game in the list ("NA1_4107800373")  occurred at TimeStamp 1637221824000, which is within the time range I set at the beginning (1637078400000- 1637596800000). I tried to delete the endtime using the first url but still get the same result.  

**Expected Result**  
My expected result should be the matchlists finished by the player within specific time range. 

**Actual Result**  
I got an empty list with response code 200. But this player did play the game during that time period.

**Developer Impact**  
This issue is very severe for me as I would like to collect the gaming history for a player within the whole season. I cannot continue my project with this problem. 
* Frequency: Every API call. Once every ~100 API calls.
* Severity: When it happens, my project cannot continue.
* Cost: My dissertation cannot finish. 

**Preconditions**  
This bug happens when developers searching for matchlists within a specific time range.

**Comment by bangingheads** [comment]
Hi jadeeeeh,

This is intentional. If you read the startTime parameter on the developer portal it reads the following:

Epoch timestamp in seconds.

The examples you gave are timestamps in milliseconds, which means you are searching for a range way in the future so you are receiving no games.

**Comment by tisbells** [comment]
Closing out old issues. This doesn't appear to be an API issue, if you feel this is in error, please re-open/comment.
