### ISSUE TITLE
[BUG] RANKED_TFT_DOUBLE_UP shows up in League-V4 response

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#572]
**Bug Description**  
Players who are ranked in the new TFT Pairs game mode show as a response to League of Legends ranks.

This is part of the /lol/league/v4/entries/by-summoner/{encryptedSummonerId} response.

**Problem Description**  
This is an unknown queue for League of Legends and can cause issues in processing ranks.

**Expected Result**  
To show RANKED_TFT_PAIRS in TFT-League-V1

**Actual Result**  
Shows response in League-V4

**Developer Impact**  
An unknown queue is found which can cause some scripts to error out. It also does not contain tier & rank in the response so it does not follow the DTO specification.

**Comment by dan-dr** [comment]
Still happening. Experiencing serious issues because of this in regards to rank

**Comment by Querijn** [comment]
good to know nothing changed during the holidays.

**Comment by molenzwiebel** [comment]
Still happening even after the switch from MMR/points-based ranks to the Iron/.../Challenger system

**Comment by aPinat** [comment]
Said switch in TFT Set 7 marks the introduction a new `queueId` of `1160` and `queueType` `RANKED_TFT_DOUBLE_UP`.
Also: https://github.com/RiotGames/developer-relations/issues/574#issuecomment-1159847974

**Comment by MingweiSamuel** [comment]
I'm actually having trouble reproducing this right now. Does anyone have a summoner name to reproduce this issue? doesn't show up for https://lolchess.gg/profile/na/s%C3%A8tsuko or https://lolchess.gg/profile/na/d%C4%B1shsoap (top rated NA TFT players)

**Comment by aPinat** [comment]
@MingweiSamuel Those two don't have a Double Up rank only classic TFT rank, try https://lolchess.gg/profile/euw/aatale.

**Comment by GuillerLT** [comment]
Is it going to be fixed?

**Comment by tisbells** [comment]
On our radar, will look into it!

**Comment by lucasMesquitaBorges** [comment]
Hey, thanks for reporting this issue.

I added `RANKED_TFT_DOUBLE_UP` in the `tft-league-v1` response.

To avoid breaking existing applications, I will keep `league-v4` returning `RANKED_TFT_DOUBLE_UP` for one more week. 
After Sep/18 only `tft-league-v1` will return `RANKED_TFT_DOUBLE_UP` queue.

**Comment by DarkIntaqt** [comment]
@lucasMesquitaBorges first of all, thank you very much for that change and the clear communication ^^. 
As this is more or less a "breaking change", I think it would be fair to announce something like that on Twitter

**Comment by lucasMesquitaBorges** [comment]
Sure! We planned to make comms in other channels, I forgot to mention this in my previous comment.

Until we sync most of possible developers using the double up queue from league-v4 endpoint we'll keep it returning from both endpoints. The deadline of one week is removed. 

As soon we have the new date I'll post here. (Will be announced in the other channels too).

**Comment by tisbells** [comment]
Hiya - We're giving everyone until **October 3** to make any necessary changes before removing this from `League-v4.` https://twitter.com/RiotGamesDevRel/status/1701723426178650191
