### ISSUE TITLE
[BUG] Several LoR users returning no matches played on lor-match-v1

### ISSUE THREAD

**Issue by sethjwilliamson** [RiotGames/developer-relations#573]
**Bug Description**  
When searching match ids of a user by puuid using lor-match-v1 endpoint, several players return an empty array, as if they have played no games. This seems to be occurring especially common in the masters players of the SEA server. 

**Expected Result**  
When searching the listed puuids, all return an empty array. 
<details>
<summary>Affected Puuids</summary>
<li>"vXBF6-ztirgryXDLkvh6nOWhI1mDPXysHl391VgCupTwOFB0SijfBGeUBEXBGX9ttDsA7HLaXGtkOQ"</li>
<li>"ZKD7V4ddf1hFZ9kFvwepLFMqnhx_UW230U2KmAiJmcf-9T0FT287yVzpEEfGbq3meZBiMLXg4MWM-Q"</li>
<li>"jVXRdwB-VxcDilMQCdhVnv9fOUi2ZtwdJ23qJmQQrVqv9Sb7MeYX17tk9U3t7It5yUmWBcAixD62Wg"</li>
<li>"zFHSEvvLvroqlrdrJMYPa0h9EuPq0LbHrOqS9-mY6UQKoD2_6pxI1wYZgZ9YJSHIxHhkpu_CZeu_bw"</li>
<li>"uTDs_rVNZfjYlEyoRVGU5giLZnpUSrOIXtWTLDu0Ys0vGEdEtk-HpwdanBiwUeKKbjP545qtaY9Amg"</li>
<li>"0kSMm9ys2KcHKJnD1QN-6y5l5rEqvlq1ajKa5cxX_xJduLabDHNfV2yILxb5ylOgK39eArOZLIkIBA"</li>
<li>"bvOmJb7xaWuG714rFC4C0DvIdOrvNfkJPvOjAgHJQcUyUJyAQdtV7EnJs-bAHNa6iIp-VT-DfnResg"</li>
<li>"uubNO33s7YfhfFsaL4jmUR-FpE1ULnb0fTbFQ_nnzJUYiUyOxos_5YUOHCUMLp-Sh6Lz0HeSK_o_ug"</li>
<li>"BPHUbJfo0CqpLeJMLjsMmiaDruux69D9ntwgj58Z-iNQgApwVrzrr1P0tDvF4yEtdUxdBX8MzlWbHw"</li>
<li>"0oHYeuya3Dk7EyqqENwPH4zhmG9tRyzeqtUky5ijVGmY56bl5H-CwE2_D2Y_rbdyFtrrTgRTDKV-1A"</li>
<li>"kc8QdzIMD5AKbXVFARvYoDfZp2mBiV7gyZgQ3Z7e0DmxeHdgOsvD09TeQTarRYhFLKMgnCkm0nsS2Q"</li>
<li>"aHoRrCnpxDZ0vHohu_DCU3YuXKAPMs_6ZFw_V1zm-XsSjSNnQGIL3vOVHNdUd3prTqv-7YJiGk2Puw"</li>
<li>"s8CKP3dkVTDj2fmcpyYrAZA0CkjJBYrliTq9t2HLui0xOtVMjXsmp578t_Fq0-3lvEkyPYWVp6YSmA"</li>
<li>"kVMnzRztT_emIIydoOqJLmX9E5QXQNxVA5woMX3DBZZH_HUc4th9at3uUCg1BGPIyJwsbxo85mYcdA"</li>
<li>"n6RzR0g8Ty6qnB38lJyEq6cEIxT00OYNtQ2CQ_JANcPG7awjgN1iyAjJuwLGU61-sNLoXlgDarU8SA"</li>
</details>

**Actual Result**  
The endpoint should return the match Ids of the matches they have played.

**Developer Impact**  
Although it only seems to have to a select few users, it has happened for every API call to these users.

**Player Impact**  
If a user wants to see their matches, these particular users will be unable to do so. 
This also means that data collected on the masters of SEA server in LOR will be very lacking in matches, causing imprecise data to all users searching for analytics in the SEA server.

**Preconditions**  
Other than these several users listed, I have no idea why these users in particular are experiencing this. 
I have searched several masters players in other server without issue. I have also searched thousands of SEA server users without any issue.

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
