### ISSUE TITLE
[BUG] While in spectator game won't unpause anymore

### ISSUE THREAD

**Issue by MaximilianRu** [RiotGames/developer-relations#577]
**Bug Description**  
While spectating a tournament game. The Spectator view won't unpause anymore.
The game went on as normaly after the pause, the spectator not, two people had the problem in the same game

**Problem Description**  

**Expected Result**  
Being able to watch a tournament game as spectator, and when a game is paused, the game will be correct unpaused after the delay.

**Actual Result**  
Game won't unpause anymore.

**Developer Impact**  
Does not affect me as a developer, but streamer and caster.

* Frequency: Every API call. Once every ~100 API calls.
* Severity: When it happens, my whole website crashes.
* Cost: Cost me a nice stream 
* Efficiency: Nothing 
* User emails: I get frequent emails from users asking me about this issue.
* Etc

**Player Impact**  
Does not affect me as a developer, but streamer and caster.

* Frequency: Every tournament game watched as spectator where the game was paused
* Severity: unable to finish the game, or keep it watching how it should be
* Quantity: Two people in 2 games with tournament code
* Region: tested on EUW.
* Etc

**Preconditions**  
* Tournament Game
*  being a spectator

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Start a tournament game (maybe normal custom)
1. join as a spectator
2. let a player pause the game
3. unpause the game
4. enjoy the endless pause screen

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by Querijn** [comment]
> Does not affect me as a developer, but streamer and caster.
Unfortunately that means this is not the place for your question

**Comment by trebonius0** [comment]
@MaximilianRu While this is not a fixed and I agree that it can be troublesome, there is a workaround: after 30s to 1minute after the loading screen, while it's paused, you can click at the beginning of the timeline and the game will start

**Comment by lucasMesquitaBorges** [comment]
Hi! Thanks for your contact. This is a player platform issue related.

I'm tackling old issues, if this issue is still relevant, please go [here](https://support.riotgames.com/hc/en-us).
