### ISSUE TITLE
Incorrect Game Duration on Games ca. from patch 11.19 backwards

### ISSUE THREAD

**Issue by bigmax1994** [RiotGames/developer-relations#578]
I noticed all games prior to some time around the beginning of November (patch 11.18-11.20) have completely incorrect Game Duration (eg. 1440331 seconds, which would equate to weeks, I think I would remember a game THAT long) even though all players have the same, and a much lower, playTime. 

examples:
"EUW1_5320794552"
"EUW1_5387050527"
"EUW1_5466375678"
etc.

**Comment by bangingheads** [comment]
Please refer to the api reference for the field:

Prior to patch 11.20, this field returns the game length in milliseconds calculated from gameEndTimestamp - gameStartTimestamp. Post patch 11.20, this field returns the max timePlayed of any participant in the game in seconds, which makes the behavior of this field consistent with that of match-v4. The best way to handling the change in this field is to treat the value as milliseconds if the gameEndTimestamp field isn't in the response and to treat the value as seconds if gameEndTimestamp is in the response.

https://developer.riotgames.com/apis#match-v5/GET_getMatch

**Comment by Renkon** [comment]
It would have been interesting to return seconds times 1000 to avoid changing the API contract.... would not have broken responses and avoided changes in most systems.

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
