### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by OdjinTyr** [RiotGames/developer-relations#582]
**Bug Description**  
This is not a Bug just a Quality of Life Request

**Problem Description**  
Farming NPC Jungle Vrs Ally Top/mid Laners.

**Expected Result**  
That ally Players wouldn't farm /steal  my Jungle camps after 2:30m on the clock

**Actual Result**  
High dps champions who get a lead like Yone, will actually Maintain that lead by Farming my Jungle while I'm doing Dragon/Rift/Ganking setting behind.

**Developer Impact**  
I am not a Developer, I just don't seem to have any ability to Request a Developers notice to this issue.

**Player Impact**  
Rage, Unfathomable Rage.   I main Evelynn, I have 2.4million mastery as the Champion. most players can AFK ontop of me to last hit over my head as I'm clearing, so what they will do is Come down While I'm clearing my jungle and Leash/steal the kill at the start of the game, and then Late in the game just outright clear my Jungle as I'm taking/securing River objectives.
the result in the game in question was a level 18 mid lane Yone vrs a level 13 enemy team comp.

* Frequency: Every 4 games or so.

* Region: NA
* Etc

**Preconditions**  
What conditions must be met in order for this bug to occur?
They start Mid/top they kill their Midlaner/top and are low on HP, instead of backing or taking turret plates they will come Steal HP off the Jg camps with autos and steal the Jungle camps from over me.   I run into the issue of, Do I smite to secure (because evelynn loses most of her DMG potential when her empowered E is off cooldown)  which costs me Dragon/Rift or let them steal it. they will then Rotate to Top lane or midlane into a pushed lane to Get a kill and cycle around like that.  While in lane they Kill a double wave crashing into their tower using the level Advantage they get.

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Step 1 Follow your ally Jg, 
1. Step 2 Steal his camp from under him by playing a High Dps/self heal champion with mobility.  in this case run through the Raptor wall as Yone as you farm your level 2 Raptor Camp.
1. Step 3 Return to Lane.

Requested Change.
If I buy the Jungle item, and I have a lead and Kill Minions I get reduced gold/exp to 1 gold
I would like the same to be done for Players who have a lead who attack/kill my jg before 15 minutes.
It's really Frusterating when Your Midlaner farms your Red side, and your Top laner farms your Blue side, while being Invaded by your Enemy Jg, Especially when your trying to Farm Skuttle, Rift or Dragon.

**Comment by thomasmarton** [comment]
> I just don't seem to have any ability to Request a Developers notice to this issue.
This will definitely be the right channel, I'm sure of it :)
Btw. you have a greater chance of a dev noticing this on reddit than on this GitHub, just FYI

**Comment by geozukunft** [comment]
Please close the completly unneccesary issue as it doesn't have anything to do with the API
