### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by TGEcho123** [RiotGames/developer-relations#583]
Just today I could not sign in to my riot account, I've been able to use my Gmail to log in to my riot account but now I do not see the Gmail button that usually appears when I'm logging in, is there any way to fix this issue? When ever I try to sign in using the account I made for league I am greeted with this message, and when I try to make an account it greets me with the same message. I've been trying everything to fix this but I still haven't found a solution.
![Screenshot 2021-12-27 114346](https://user-images.githubusercontent.com/96710335/147432241-34d94cf3-184e-4eae-94c5-49a95d329ff5.png)
?

**Comment by lucasMesquitaBorges** [comment]
Hi! Thanks for your contact. Game issue related.

For game bugs please go [here](https://support.riotgames.com/hc/en-us).
