### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by GocanDC** [RiotGames/developer-relations#586]
**Account Information**
What's your summoner name (Gocan DC) or riot id (e.g., Gocan DC)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?
I am playing league for 9 years.

**Issue Description**  
A clear and concise description of what the issue is.
I am in silver 1 was in gold 4 with this mmr 1036, which is bronze

**Issue Context**
Please add any additional context that is useful.
Can u help me with this problem? Discord Gocan#0301

**Comment by Token07** [comment]
This GitHub repo is not for game support or account issues, only player support can help with those. As player support does not monitor this page, you'll need to open a ticket with player support at: https://support.riotgames.com/hc/en-us
