### ISSUE TITLE
[BUG] VAL-CONTENT with it-IT translation returns 400

### ISSUE THREAD

**Issue by Henrik-3** [RiotGames/developer-relations#588]
**Bug Description**  
When requesting the val-content endpoint with the `?locale=it-IT` query it returns
```json
{
    "status": {
        "message": "Bad request - unknown locale requested",
        "status_code": 400
    }
}
```
even though `it-IT` is in the LocalizedNamesDto list

**Problem Description**  
Italian translations are not available, so i can't use them as translations in my project

**Expected Result**  
A translated content json file like when i request with `locale=de-DE` for example

**Actual Result**  
See Bug Description

**Developer Impact**  
I have to use for only one translation another data source and a different source code to maintain, would be nice to have it all together

* Frequency: Every API call
* Severity: Missing translations for users
* Cost: None
* Efficiency: Requires me to make one more API Call on another data source and another source code to handle it

**Player Impact**  
Users don't have a proper Italian translation

**Repro Steps**  
Do a request to the following URL: `https://eu.api.riotgames.com/val/content/v1/contents?locale=it-IT`

**Comment by 0xGabrielel** [comment]
It's fixed :)

**Comment by Henrik-3** [comment]
Thanks :)
