### ISSUE TITLE
https://developer.riotgames.com homepage still points to https://discussion.developer.riotgames.com

### ISSUE THREAD

**Issue by Pyrolistical** [RiotGames/developer-relations#59]
This link:
<img width="269" alt="screen shot 2019-01-14 at 14 54 58" src="https://user-images.githubusercontent.com/463642/51146680-62eec480-180c-11e9-8fff-404791e09825.png">

**Comment by RiotTuxedo** [comment]
Feels bad. Thanks for pointing this out.

**Comment by RiotTuxedo** [comment]
This was resolved recently. Now points to GitHub.
