### ISSUE TITLE
[BUG] Datadragon item.json does not have Ornn items

### ISSUE THREAD

**Issue by trialo96** [RiotGames/developer-relations#590]
**Problem Description**  
https://ddragon.leagueoflegends.com/cdn/12.1.1/data/en_US/item.json does not have Ornn items such as Draktharr's Shadowcarver(key: 7002), Typhoon(7006), Bloodward(7008), ...

**Expected Result**  
data for Ornn items
ex) {id: 7006, name: Typhoon, ... }

**Actual Result**  
no data for Ornn items

**Developer Impact**  
want to analyze post-game item efficiency

**Issue Comments**  
If I want to use Ornn item asset, how can I get image like this?
![image](https://user-images.githubusercontent.com/67891553/131779075-367969aa-2262-444c-a637-83d011efb8b8.png)

**Comment by trialo96** [comment]
there are no ornn items after 11.18 😢

**Comment by JoschuaGoetz** [comment]
Facing the same issue here. 
A possible workaround is to take the latest versions where the ornn items still exist. As far as i can tell only two ornn items were added after riot "forgot" to include ornn items. New items should be `Equinox` and `Crown of the Shattered Queen`. Latest versions for all other items are: 
| name                         | id   | version |
| ---------------------------- | ---- | ------- |
| Molten Edge                  | 3371 | 10.22.1 |
| Rabadon's Deathcrown         | 3374 | 10.22.1 |
| Zhonya's Paradox             | 3386 | 10.22.1 |
| Trinity Fusion               | 3384 | 10.22.1 |
| Forgefire Cape               | 3373 | 10.22.1 |
| Frozen Fist                  | 3387 | 10.22.1 |
| Might of the Ruined King     | 3389 | 10.22.1 |
| Infernal Mask                | 3379 | 10.22.1 |
| Youmuu's Wraithblade         | 3388 | 10.22.1 |
| Circlet of the Iron Solari   | 3383 | 10.22.1 |
| Luden's Pulse                | 3390 | 10.22.1 |
| Obsidian Cleaver             | 3380 | 10.22.1 |
| Salvation                    | 3382 | 10.22.1 |
| Wooglet's Witchcrown         | 3385 | 9.23.1  |
| Sandshrike's Claw            | 7000 | 11.15.1 |
| Syzygy                       | 7001 | 11.15.1 |
| Draktharr's Shadowcarver     | 7002 | 11.15.1 |
| Turbocharged Hexperiment     | 7003 | 11.15.1 |
| Forgefire Crest              | 7004 | 11.15.1 |
| Rimeforged Grasp             | 7005 | 11.15.1 |
| Typhoon                      | 7006 | 11.15.1 |
| Wyrmfallen Sacrifice         | 7007 | 11.15.1 |
| Bloodward                    | 7008 | 11.15.1 |
| Icathia's Curse              | 7009 | 11.15.1 |
| Vespertide                   | 7010 | 11.15.1 |
| Upgraded Aeropack            | 7011 | 11.15.1 |
| Liandry's Lament             | 7012 | 11.15.1 |
| Eye of Luden                 | 7013 | 11.15.1 |
| Eternal Winter               | 7014 | 11.15.1 |
| Ceaseless Hunger             | 7015 | 11.15.1 |
| Dreamshatter                 | 7016 | 11.15.1 |
| Deicide                      | 7017 | 11.15.1 |
| Infinity Force               | 7018 | 11.15.1 |
| Reliquary of the Golden Dawn | 7019 | 11.15.1 |
| Shurelya's Requiem           | 7020 | 11.15.1 |
| Starcaster                   | 7021 | 11.15.1 |
| Seat of Command              | 7022 | 11.15.1 |

Please correct me if i missed an item or if there is another version available.

**Comment by trialo96** [comment]
`Crown of the Shattered Queen` -> `Caesura` :)

**Comment by rdevnoah** [comment]
there are no ornn items on "12.5.1", "12.6.1"
