### ISSUE TITLE
[BUG] DDragon SSL Certificate expired

### ISSUE THREAD

**Issue by katerlol** [RiotGames/developer-relations#591]
**Bug Description**  
The SSL Certificate of the following URL is expired: https://ddragon.leagueoflegends.com/cdn/9.3.1/data/en_US/champion.json

**Problem Description**  
THis means I cannot savely access the site anymore.

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call. 
* Severity: When it happens, my whole website (https://www.riftq.com/duo) crashes.
*

**Comment by xadamxk** [comment]
Having this issue as well... hopefully the cert gets replaced soon

**Comment by dan-dr** [comment]
same

**Comment by geozukunft** [comment]
everybody has that issue; It'll probably get fixed soon

**Comment by klinger2709** [comment]
I just checked it and it seems to be resolved by now.

**Comment by geozukunft** [comment]
knock knock it has been 13 months and thus the cert is invalid again

**Comment by katerlol** [comment]
I also got the certificate error now again.

**Comment by Allan-Cao** [comment]
Still having problems. Can someone at riot please use auto-renew?

**Comment by spaykit** [comment]
same

**Comment by Pimeko** [comment]
same!

**Comment by geozukunft** [comment]
There is no need for everyone to comment "same" btw the cert is invalid for each and everyone on earth. And it probably won't get fixed on a Sunday or Monday (at 3AM) either just be patient might take a day or two

**Comment by tsevenhuysen** [comment]
Please fix. :)

**Comment by Denidil** [comment]
They REALLY need to be automatically maintaining their certificates instead of this by-hand "oops we forgot to renew" crap

**Comment by katerlol** [comment]
The certificate seems to be renewed again. :) Happy to see you again in 13 months :>

**Comment by Drayken** [comment]
Again
