### ISSUE TITLE
[BUG] summoner-v4 sometime it return missing data

### ISSUE THREAD

**Issue by ahmedsafadii** [RiotGames/developer-relations#592]
**Bug Description**  
summoner name, level, the date is no return

**Problem Description**  
When I search using summoner name, exception happen to tell me that some keys are missing, like name level and ids only returned 

**Expected Result**  
I expect to get the summoner info with the valid JSON.

**Actual Result**  
This is what i got after search by summoner name
![image](https://user-images.githubusercontent.com/6974081/149152558-d119bb78-84f7-4807-b3e9-a763a1814b9f.png)

**Developer Impact**  
Since my first request is to get summoner info, so when this failed the user will no longer see the stats or matches, etc ..

* Frequency: First time, but I think that maybe it will happen later.
* Severity: When it happens, the user can't see his summoner info inside the app
* Cost: nothing
* Efficiency: np
* User emails: np

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

* Frequency: np
* Severity: np
* Quantity: 1
* Region: LA2
* Etc

**Preconditions**  
What conditions must be met in order for this bug to occur?

* Summoner must have league
![image](https://user-images.githubusercontent.com/6974081/149153065-3fed7a7f-e5e9-4bc3-8560-c68a3e5f22f6.png)

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Search for a summoner
1. You will see missing keys inside the response.

**Issue Comments**  
I share some pictures that may help log this for you guys.

![image](https://user-images.githubusercontent.com/6974081/149153352-1d55ef8c-bf40-478a-b706-973ed17b0944.png)

![image](https://user-images.githubusercontent.com/6974081/149153395-ec3fa6ec-9f33-494c-8f04-d7bbc7154857.png)

**Comment by ahmedsafadii** [comment]
<img width="765" alt="Screen Shot 2022-08-31 at 10 19 58 AM" src="https://user-images.githubusercontent.com/6974081/187617399-f798bf8b-d7db-4184-8d4b-c33c2b3f3e7b.png">

Duplicate again.

**Comment by lucasMesquitaBorges** [comment]
Endpoint deprecated after migration to RiotIDs.

See https://github.com/RiotGames/developer-relations/issues/833
