### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by JustusWalter-Helk** [RiotGames/developer-relations#593]
**Bug Description**  
The SSL Certificate of this Website is Expired 
(https://ddragon.leagueoflegends.com/api/versions.json)

**Developer Impact**  
I cannot get the versions.json because the Certifacte has Expired.

- Frequency: Every API Call
- Severity: Cannot get the Latest Version of DDragon

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by Token07** [comment]
Duplicate of #591

**Comment by JustusWalter-Helk** [comment]
Well its another URL

**Comment by Token07** [comment]
> Well its another URL

Certificates are issued to a hostname, which is the same, not a URL.

**Comment by JustusWalter-Helk** [comment]
Oh didnt knew that thanks :D
