### ISSUE TITLE
[URGENT] LOR APAC REGION IS RETURNING 403 FORBIDDEN ON ALL ENDPOINTS

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#595]
As descripted in title

**Comment by xelaadryth** [comment]
Thanks for the report! I've fixed it for now, but note that for Riot API, we officially recommend using `sea` as the official way to get information on the `apac` server now, though we'll be disabling `asia` soon. We hope to switch to `apac` eventually for consistency purposes, but won't be happening quite yet, so while some things may work with it, don't be surprised if you see issues with it.

**Comment by paaksing** [comment]
I have migrated everything to use `sea` instead
