### ISSUE TITLE
Documentation word issue [Spectator-V4 :: active-games/by-summoner/{encryptedSummonerId} ]

### ISSUE THREAD

**Issue by ccppoo** [RiotGames/developer-relations#596]
**Bug Description**  
 
none

**Problem Description**  

[GET_getCurrentGameInfoBySummoner](https://developer.riotgames.com/apis#spectator-v4/GET_getCurrentGameInfoBySummoner)

at Spectator-V4, the return value of **active-games/by-summoner/{encryptedSummonerId}** method says it returns observer**s**

![image](https://user-images.githubusercontent.com/46418312/150625059-493026aa-e619-420e-b1a8-3f94df1649d2.png)

but in description of Observer it says it just contains **a Key**

![image](https://user-images.githubusercontent.com/46418312/150624970-673cfa03-d5fc-4bf0-ac1c-cfdd39f5bc5c.png)

return type of encryption key is `string` not `list` that I expected

and what I actually get from the API is this : 

```json
{
  ...
  "observers": {"encryptionKey": "<key>"},
  ...
}
```

**Expected Result**  

It should be fixed either to 

1)  change the name of key "observer**s**" to "observer" at "Return value: CurrentGameInfo"

e.g) :

![image](https://user-images.githubusercontent.com/46418312/150625222-297e7bef-da8c-41fb-8c62-691e82c3c4a5.png)

2) or fix return type like

```json
{
  ...
  "observers":  [ 
    { "encryptionKey" :  "<key 1>" },
    { "encryptionKey" :  "<key 2>" },
  ...
}
```

**Developer Impact**  

developers will change key name when handling json data from API

**Player Impact**  

None

**Issue Comments**  

is this happening because I'm just not using product API key?

**Comment by bangingheads** [comment]
Documentation wise there is no issue. It has a key of observers which returns the Observer DTO. The Observer DTO contains an object with a key of encryptionKey and a value of the key.

Whether or not that key should be plural doesn't necessarily matter and there are other examples across the API that an s doesn't necessarily mean a list, and changing it would break current apps.

**Comment by ccppoo** [comment]
@bangingheads 
I just want to know If I get product API later, there could be several keys in "observers" field?
and plural matters, that's why documentations exists

**Comment by bangingheads** [comment]
The key helps decrypt the spectator stream, there is only one key per game.

If there could be multiple it would say List[Observer] in the type then there would be multiple.

Nothing changes data structure wise from key to key.

**Comment by ccppoo** [comment]
so then adding a notice beneath **observers** will make others less confused,
I thought there was a difference between developer keys and product keys.
Anyway, thanks for the reply!

**Comment by LightshieldDotDev** [comment]
I don't see how anyone should get hung up on the grammar here.

`observers: "allowed"` and `observers: "disallowed"` would also be valid ways to put it, the same obviously going for 

`observers: "Here's the key for you (you being a plural you)"`

**Comment by ccppoo** [comment]
@LightshieldDotDev good for you
ever had problem with docs?

**Comment by tisbells** [comment]
Closing old issues. We appreciate the feedback but will not be making this change at this time.
