### ISSUE TITLE
No alternative for the article about GDPR on the discussions

### ISSUE THREAD

**Issue by Querijn** [RiotGames/developer-relations#60]
There is no DevRel alternative for the information containing what usernames fall under RTBF, which used to be here, if I remember correctly:
https://discussion.developer.riotgames.com/articles/6291/gdpr-right-to-be-forgotten-compliance.html

Additionally, the announcement on Discord also doesn't contain it.

**Comment by RiotTuxedo** [comment]
BOOM!
https://www.riotgames.com/en/DevRel/gdpr-right-to-be-forgotten-compliance

There's a carousel of announcements on:
https://www.riotgames.com/en/DevRel

The GDPR article is on the last page of the carousel.

I'm considering this issue resolved, please let me know if I misunderstood the issue.
