### ISSUE TITLE
[BUG] Match-V5 returns wrong data

### ISSUE THREAD

**Issue by trialo96** [RiotGames/developer-relations#606]
**Bug Description**  
Match-V5 returns wrong data for teamPosition and individualPosition

**Problem Description**  
```
"individualPosition": "Invalid",
...
"teamPosition": "",
```

**Expected Result**  
```
"teamPosition":"TOP",
```

**Actual Result**  
```
"individualPosition": "Invalid",
...
"teamPosition": "",
```

**Developer Impact**  
cannot get position data

**Issue Comments**  
It seems affect all 12.4 patch matches

**Comment by GetPastTheMonkey** [comment]
Duplicate of #554
