### ISSUE TITLE
Unusual platformId WAS_LA1 in API response

### ISSUE THREAD

**Issue by adfinlay** [RiotGames/developer-relations#61]
If you look at the Match v3 response for game 651437193 in LA1, participantId 8 has `platformId = WAS_LA1`. Is this intentional, and if so, what does it mean?

**Comment by jjmaldonis** [comment]
Here's the response for that participant:

```json
"player": {
    "currentPlatformId": "LA1",
    "summonerName": "Akise Sunkaze",
    "matchHistoryUri": "/v1/stats/player_history/WAS_LA1/201319166",
    "platformId": "WAS_LA1",
    "currentAccountId": 201319166,
    "profileIcon": 873,
    "summonerId": 5021022,
    "accountId": 201319166
},
"participantId": 8
```

I've never seen this before @adfinlay.

**Comment by adfinlay** [comment]
One person on Discord suggested `Maybe it's the latin server before the merge?` - if this is the case, perhaps the docs should be updated to list any possible edge case values that might be returned so that third party libraries can handle all cases. I'm currently working with the RiotSharp library which fails to deserialize the match because of this participant.

**Comment by tisbells** [comment]
Matchv3 no longer supported
