### ISSUE TITLE
[BUG] Response speed of the Korean Region API is being delayed. 

### ISSUE THREAD

**Issue by ggomuk** [RiotGames/developer-relations#611]
**Problem Description**  
There is an issue in which the response speed of the RIOT API(KR) slows down during peak hours.
Renewal work is being delayed a lot.

**Developer Impact**  
Due to the slow renewal of the record, users use it are feeling uncomfortable.

![image](https://user-images.githubusercontent.com/22437277/156009455-c81dfff6-1e80-40e5-9193-02cf2f5247d6.png)

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
