### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Superveve** [RiotGames/developer-relations#612]
Hi

I could not connect to the game, i received a crash report with a file to share;

It seems the format of the share is not fine ...

The name of the file is PKM8248

**Comment by Token07** [comment]
You need to share it with player support not here; This page is only for the issues surrounding the Riot API and related assets.

**Comment by MingweiSamuel** [comment]
Please fill out this form: https://pbr.leagueoflegends.com/euw/en_GB/login and close the issue. Riot developers will not be able to see it otherwise.

**Comment by lucasMesquitaBorges** [comment]
Closing. As @Token07 and @MingweiSamuel mentioned, issues related to player support can be reported in this [link](https://pbr.leagueoflegends.com/euw/en_GB/login).
