### ISSUE TITLE
[Bug]  Match v5 API not have List <challenges DTO>

### ISSUE THREAD

**Issue by zeroheat0930** [RiotGames/developer-relations#620]
**Account Information**
KR.ZeroHeat

**Issue Description**  
Match v5 - challenges no item....

**Issue Context**
why RiotHomepage API -> Match v5 API ->  No challenges??

REQUEST URL json have challenges category.. homepage don't have challenges List DTO

**Comment by MingweiSamuel** [comment]
Some more info in the more general #603

**Comment by tisbells** [comment]
Closing out old issues, dupe of https://github.com/RiotGames/developer-relations/issues/603 and related to https://github.com/RiotGames/developer-relations/issues/633
