### ISSUE TITLE
[BUG] Kassadin's portrait in DDragon 12.6.1 is incorrect

### ISSUE THREAD

**Issue by CurtisGreen** [RiotGames/developer-relations#621]
**Bug Description**  
Kassadin's portrait in DDragon 12.6.1 is an older portrait rather than his current one.

**Problem Description**  
Kassadin's portrait is incorrect.

**Expected Result**  
In 12.5.1 the image is correct like this
 ![](https://ddragon.leagueoflegends.com/cdn/12.5.1/img/champion/Kassadin.png)

**Actual Result**  
In 12.6.1 the image is like this 
![](https://ddragon.leagueoflegends.com/cdn/12.6.1/img/champion/Kassadin.png)

**Developer Impact**  
End users cannot easily tell which champion this is referring to because it's different than the one used in the game.

**Player Impact**  
* Frequency: Every time the image is used for the current patch
* Players will not recognize kassadin

Note: old kassadin looks like zerg

**Comment by bangingheads** [comment]
This is the icon that the client uses in 12.6, it's a new icon as well as default splash.

**Comment by CurtisGreen** [comment]
Lol, guess I jumped the gun. 
Thanks
