### ISSUE TITLE
Normal Draft match disappeared from existence 

### ISSUE THREAD

**Issue by AJEUW** [RiotGames/developer-relations#625]
So one day I played Leona mid by accident but still won (yay) and after the match, it never appeared in my game history yet it shows it in my average mid lane games for the season but when I go look for it says there is an error loading match history. Is there any way to review the game?
![image](https://user-images.githubusercontent.com/103759075/163582223-738836d6-29e6-4c0c-9e5a-8254e175afc0.png)
![image](https://user-images.githubusercontent.com/103759075/163582301-d88611ca-ea5b-45ca-9403-14f5dbbcd0f2.png)
it happened on the 06/04/2022

**Comment by lucasMesquitaBorges** [comment]
Hi! @AJEUW Thanks for your contact. This is a player platform issue related.

I'm tackling old issues, if this issue is still relevant, please go [here](https://support.riotgames.com/hc/en-us).
