### ISSUE TITLE
[BUG] Match exists but matchv5 returns 404

### ISSUE THREAD

**Issue by idunnololz** [RiotGames/developer-relations#627]
**Bug Description**  
The match `NA1_4240314465` clearly exists as evident that it is returned by both `/v5/matches/by-puuid` and `/v5/matches/x/timeline` however `/v5/matches` returns a permanent 404.

**Problem Description**  
`/v5/matches` is bugged for the match `NA1_4240314465`.

**Expected Result**  
`/v5/matches` returns a 200 and the data for the match.

**Actual Result**  
`/v5/matches` returns a permanent 404 error.

**Developer Impact**  
Unsure if other match ids are also bugged but this one will effect any apps that look at `Doublelift`'s match history.

* Frequency: Every API call for `NA1_4240314465`
* Severity: Missing data for one match.
* Cost: N/A
* Efficiency: I have retry logic for 404s, so this will increase calls for `NA1_4240314465` by 5x as I retry 5 times. (404s in the past can be recoverable which is why the retry logic exists)

**Player Impact**  
Players may not be able to see accurate stats.

**Preconditions**  
Match id = `NA1_4240314465`

**Repro Steps**  

1. Match a request to `https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4240314465`
1. Note that it returns 404 instead of 200.

**Issue Comments**  
I am confident this match exists because
1) The match is returned by (the PUUID here is for `Doublelift` `https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/B9eYXjYuyEsjfVpA-crh5l6vQh3zX5ImkouN83T2BOOV1bDqlW3QLQgzr9G7RaEmoYKMB19nSTlLkg/ids?startTime=1641369601&start=0&queue=420&count=100 `.
2) The match timeline actually returns a 200 `https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4240314465/timeline`

**Comment by RiotTuxedo** [comment]
This match is unfortunately gone and lost forever :( This was prior to some of the changes we made to improve match ingestion times. This issue should be behind us, but if you find a match like this that's within 2 weeks of the date it was played we can recover it.
