### ISSUE TITLE
pick order champion select

### ISSUE THREAD

**Issue by flerpan01** [RiotGames/developer-relations#628]
Right now there is no way of linking the puuid to pick order in champion select, nor ban order either, using the API.  The matches-api:V5 (excuse my poor nomenclature) returns `metadata` and `info`. Within the `metadata` participants are given with puuid. However, in the `info` the team data is give with bans, picks and objectives, without championId. Is there a reason why there is no linking between `info` and `metadata`?

My hypothesis is that pick order correlates with winrate. So I've gather 200 odd games from my silver elo (EUW) and there is a trend between winrate and pick order. Of course this is speculative with my tiny sample size. I've attached a figure and the [data](https://github.com/RiotGames/developer-relations/files/8566570/pick_order_sample.csv) collected.

Perhaps I overlooked something and it is possible to link puuid and pick order, in that case let me know :)

I saw this issue was posted already in 2019: https://github.com/RiotGames/developer-relations/issues/192

![winrate](https://user-images.githubusercontent.com/56508609/165384453-a4d9c037-bfce-4c1f-9c88-9913daa1b608.png)

**Comment by tisbells** [comment]
Closing dupes/old tickets. This was also brought up in https://github.com/RiotGames/developer-relations/issues/739, https://github.com/RiotGames/developer-relations/issues/192, https://github.com/RiotGames/developer-relations/issues/146. Keeping the most recent one (739) open
