### ISSUE TITLE
[BUG] 0% availability on Spectator-V4, KR region 

### ISSUE THREAD

**Issue by ohaiibuzzle** [RiotGames/developer-relations#629]
**Bug Description**  
The Spectator-V4 endpoint for the KR region has been down since April 27th and has not come back online.

**Problem Description**  
All requests to the endpoints results in a 503 Unavailable response

**Expected Result**  
Responses data as documented in the API documentations

**Actual Result**  
All 3 API endpoints return HTTP 503 - Service Unavailable

**Developer Impact**  
* Frequency: Every API call.
* Severity: Inability to fetch spectator data

**Player Impact**  
Players may not be able to spectate matches from this region

**Preconditions**  
None

**Repro Steps**  
1. Open the official API reference
2. Do anything related to Spectator-V4 targeting the KR region.

**Issue Comments**  
This appears to be a widespread issue as scouting sites such as op.gg are also unable to fetch any data from the KR region as well.

**Comment by penut85420** [comment]
Since the players in msi 2022 begin practice, hope this issue can be resolved as soon as possible :(

**Comment by ohaiibuzzle** [comment]
> Since the players in msi 2022 begin practice, hope this issue can be resolved as soon as possible :(

At this point I doubt that it’s a coincidence and more likely them actively preventing it from happening by intentionally cutting API access. We (probably) all know how silly they can get as a company

Then again, we have the League of Legends Client Cleanup stuff going on, and I am sure we can all appreciate the *legendary* work they have done there. The API is probably just getting the same treatment

**Comment by Janmm14** [comment]
Issue still happening

**Comment by Janmm14** [comment]
endpoint seems to work again as of right now

**Comment by lucasMesquitaBorges** [comment]
Spectator-v4 for KR had a temporary outage when this issue was opened. The issue was fixed.
If you're still experiencing problems, please open a new issue.
