### ISSUE TITLE
Missing Kayn and Neeko in Champion.json

### ISSUE THREAD

**Issue by francescovallone** [RiotGames/developer-relations#63]
Hi, I'm working with Static Data and even if Champion Mastery V4 gives me 141 as id if i try to get the image of the champ that have that id (Kayn). It doesn't load.

**Comment by supergrecko** [comment]
Are you sure you are using the correct data dragon version? The ones provided on the static-data documentation page are from 6.24.1

**Comment by francescovallone** [comment]
Yes, I'm using 6.24.1 but Kayn (ID 141) And Neeko are missing
This is the code I'm using:
![code](https://user-images.githubusercontent.com/15020233/51473916-fb8dc300-1d7d-11e9-99c7-95223cd7e4db.png)

**Comment by supergrecko** [comment]
That is because in game version 6.24.1 Neeko and Kayn did not exist. Use the latest ddragon version.

**Comment by francescovallone** [comment]
Can you explain how can i use it? I'm new with LoL API :(

**Comment by Draycia** [comment]
http://ddragon.leagueoflegends.com/api/versions.json Get the first entry in this to get the latest version

**Comment by supergrecko** [comment]
Replace the 6.24.1 in the ddragon URL with the latest game version.

**Comment by francescovallone** [comment]
Ok ty <3 you are my savior
