### ISSUE TITLE
[BUG] [LOR] missing matches by puuid

### ISSUE THREAD

**Issue by Program-arg** [RiotGames/developer-relations#630]
Hello, I am the administrator of runeterra.ar I realized that after patch 3.6 that the endpoint "lor/match/v1/matches/by-puuid" is not returning all the games.

Example

match_id: f3a88681-20a9-41b6-bf4f-4640ccfc1089

https://americas.api.riotgames.com/lor/match/v1/matches/f3a88681-20a9-41b6-bf4f-4640ccfc1089

it is the last game of the puuid "U4oq_Ygms7r1AQ3FuYbcNUM5VGMG6sA2MsyIgpaM_LLzI66NT-D84av5Pns0ihJsRriwz527kMYEjw" 
(Vivo#LAS) but this is being returned by the endpoint

https://americas.api.riotgames.com/lor/match/v1/matches/by-puuid/U4oq_Ygms7r1AQ3FuYbcNUM5VGMG6sA2MsyIgpaM_LLzI66NT-D84av5Pns0ihJsRriwz527kMYEjw/ids

I was able to obtain the id of the game through obtaining the rival's game, which in that case did return it

https://americas.api.riotgames.com/lor/match/v1/matches/by-puuid/7huwUz9FiV7L5BJoxd7U8KupkeKHjc5LgVX7JblxcbBJrR7zB_hgn9fipuLMP8rKmCyoFAp8vDssQQ/ids

this happened several times, but I put this specific case that is the last one that I could capture

App Id: ID491022

**Comment by RiotTuxedo** [comment]
We're looking into this. Don't believe any matches have been lost, just an incorrect matchlist being returned.

**Comment by Program-arg** [comment]
Exactly the matches were not lost, only the matchlist does not return them

**Comment by RiotTuxedo** [comment]
Recently shipped a fix that should resolve this issue. Let me know if you see new matches that still don't show up in the player's matchlist.

**Comment by PolgarSupreme** [comment]
THis is happening in LOL as well , I am not sure if this is the case, but happends 1/1000 minimum:

https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/cMrFR7sc9m00grDLFv70U2BuGtIxo1Wa8w2lQDwk1FslvKdVB8Dp0hFZsHPzaQ9vjGJ8ZvhqVL08fQ/ids?queue=420&count=20&
https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/um9wEyoKuM06MQQrhIncoEmsZgJX68KzbL3YUlTmRx7iYPvtVyKSD4nZ-62PNdtYVhiVS0xCgJxMJA/ids?queue=420&count=20&

**Comment by geozukunft** [comment]
@PolgarSupreme I think it would be the best to open up a new issue and fully fill out the form especially with example matchids that are missing and if you are adding puuids please also attach your appid with which you got those puuids so Riot knows which encryption was used alternatively you can just use summoner names as well
