### ISSUE TITLE
[BUG] Several missing custom games

### ISSUE THREAD

**Issue by Nakrum** [RiotGames/developer-relations#634]
### Bug description
Several custom games sinces april 26th are missing when `/v5/matches/by-puuid` with `queue=0` is used, the matches are in the ingame history, but the api doesn't return the games. A few examples: `EUW1_5865994333`,`EUW1_5865994915`, `EUW1_5861952153`.
The puuid used was `22i8epupSHj3KBhn6PijIfG1RiDkNvTGabxKTUQ2aleEVp9WA73toHV3FtDJQNO7UG_QdAx71RCTkQ`
Those are recently played games with ingame history but the api `/v5/matches/` seems to miss them with `Data not found - match file not found`.

### Problem description
Missing custom matches on  `/v5/matches/by-puuid`

### Expected result
`/v5/matches/by-puuid` returns all played custom games correctly

### Actual result
Matches are missing and can't be analysed with `/v5/matches/`

### Preconditions
Example match ids:
`EUW1_5865994333`,`EUW1_5865994915`, `EUW1_5861952153`

### Repro steps
Using `/lol/match/v5/matches/by-puuid/SFRTzS--e3cJo_N3JY7rAETi1Jxro73fqF_ve_6kMXAmA7aMmV9DYCZ9sQiZ8jP8Te3o3nCElb6KYQ/ids?queue=0&start=0&count=20`, last game is `EUW1_5841597087` played april 26th, although ingame history shows played custom games after april 26th. Using games from ingame history like `/v5/matches/EUW1_5865994333` returns `404 Data not found - match file not found`
<details>
<summary>Images</summary>

![InGameHistory5865994915](https://user-images.githubusercontent.com/20783788/168274236-9e2e0959-67be-4ea2-9e30-c60fc12781a2.png)
![InGameHistory586577433](https://user-images.githubusercontent.com/20783788/168274241-41d9a06f-e52c-4e82-aeda-32a6f02e1e1f.png)

</details>

**Comment by geozukunft** [comment]
Custom games are not offically supported by match-v5 and only included accidentially for some time.

**Comment by tisbells** [comment]
Closing old issues. Custom match data is not intended to be available by design.
