### ISSUE TITLE
account issue 

### ISSUE THREAD

**Issue by lulkarmaa** [RiotGames/developer-relations#636]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

**Issue Description**  
A clear and concise description of what the issue is.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by lulkarmaa** [comment]
When I open riot client on my pc and go to account details I sign in without a problem. But then it makes me do a  verification and the email it sends the code to is not mine. I do not know how to change it because every time I try it, it sends a verification code to the other email that is  not mine. Please help

**Comment by Ponita0** [comment]
1 - not the place to report that, better go to player support, not developer-relations 🤷🏻‍♂️ 
2- lmao
