### ISSUE TITLE
accounts/by-puuid endpoint - Bad Request - Exception decrypting

### ISSUE THREAD

**Issue by UROjQ6r80p** [RiotGames/developer-relations#637]
I'm trying to get a user information by PUUID (with Developer Key)

https://europe.api.riotgames.com/riot/account/v1/accounts/by-puuid/e6d9af3b-af24-55f8-adbf-92f68c005771

Why does it give me this error?
`{
    "status": {
        "message": "Bad Request - Exception decrypting e6d9af3b-af24-55f8-adbf-92f68c005771",
        "status_code": 400
    }
}`

Is it even possible to retrieve basic information about user from unencrypted puuid?

**Comment by thomasmarton** [comment]
The endpoint documentation states that it expects an encrypted PUUID and you gave it a raw one.
If you are working with the LCU, you should use summoner names to get the encrypted PUUIDs, if you are doing something else, you are most likely doing something against policies.

**Comment by UROjQ6r80p** [comment]
> The endpoint documentation states that it expects an encrypted PUUID and you gave it a raw one. If you are working with the LCU, you should use summoner names to get the encrypted PUUIDs, if you are doing something else, you are most likely doing something against policies.

Thank you for the reply.
In general I'm trying to get just a username from unencrypted PUUID.

**Comment by Ponita0** [comment]
You can't do that because basically you don't know how is it encrypted, you only know that it's encrypted based on your app id.
So the only usable puuids are the ones which you get from SummonerV4, and only with your key

**Comment by UROjQ6r80p** [comment]
> You can't do that because basically you don't know how is it encrypted, you only know that it's encrypted based on your app id. So the only usable puuids are the ones which you get from SummonerV4, and only with your key

Thank you :)
