### ISSUE TITLE
[BUG] [LOR] Leaderboard is not updated

### ISSUE THREAD

**Issue by Program-arg** [RiotGames/developer-relations#638]
Hello!

The result json returned by the api was not updated from 12/05 approximately (I checked with some developers and they have the same problem) .

endpoint: https://americas.api.riotgames.com/lor/ranked/v1/leaderboards

Americas total players
2330 API
2993 Game

Europe total players
2330 API
2552 Game

Thanks

**Comment by MaouLegna** [comment]
Confirming the issue is still up even after the change to s new season. The leaderboard did not reset and it still reports the values from days/weeks ago

**Comment by MaouLegna** [comment]
The leaderboard is now working properly for both "europe" and "americas"

"sea" on the other hand is still returning the old-fixed state
