### ISSUE TITLE
[BUG] Empty/corrupted MatchV5 data

### ISSUE THREAD

**Issue by rdk31** [RiotGames/developer-relations#642]
**Bug Description**  
In case of the game not starting after champion select (with the system message saying: Your match will start soon. ...) the match still gets created and using matchv5 match list endpoint you can fetch it's id. An example match id with empty/corrupted data: `EUN1_3134516864`

**Problem Description**  
I pulled a match `EUN1_3134516864` and the match data is empty/corrupted.

**Expected Result**  
Not seeing the match in the user's match list.

**Actual Result**  
Because the match data is empty/corrupted, the library I use to fetch it panics.

**Developer Impact**  
The impact is not really big because it's easy to filter these matches out, however I'm reporting this bug so that it might get fixed.

**Preconditions**  
For the match to get corrupted, the game has to not start.

**Comment by geozukunft** [comment]
This might be interesting for @RiotTuxedo

**Comment by MissUwuieTime** [comment]
I experienced this same problem with `BR1_2583580397` when crawling matches.

When comparing the mentioned bugged matches, it appears that the `InfoDto` object is malformed. Every key besides `gameEndTimestamp` and `tournamentCode` is set to either `0`, `''` or `[]` based on their type.
```json
{
    "info": {
        "gameCreation": 0,
        "gameDuration": 0,
        "gameEndTimestamp": 1653205775469,
        "gameId": 0,
        "gameMode": "",
        "gameName": "",
        "gameStartTimestamp": 0,
        "gameType": "",
        "gameVersion": "",
        "mapId": 0,
        "participants": [],
        "platformId": "",
        "queueId": 0,
        "teams": [],
        "tournamentCode": ""
    }
}
```

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
