### ISSUE TITLE
[BUG] [LOR] EU match history data is not updated

### ISSUE THREAD

**Issue by MaouLegna** [RiotGames/developer-relations#643]
Hello,

from around 9:00 CEST the match history for most (if not all) EU players is not being updated.
Could find some games at 7:30 CEST but no more from 9:00
As of now the bugs is affecting the entire population of the seasonal players from last season but any  other players I may have checked seems to have the same issue.

**Comment by lauriys** [comment]
seems like LoL has a similar problem?

**Comment by Program-arg** [comment]
> seems like LoL has a similar problem? ![image](https://user-images.githubusercontent.com/330645/171093284-efdd9412-3d25-4986-ae0c-2f3c727c857c.png) that might explain it

why don't you use the version MATCH-V5?

**Comment by Perdonium** [comment]
> > seems like LoL has a similar problem? ![image](https://user-images.githubusercontent.com/330645/171093284-efdd9412-3d25-4986-ae0c-2f3c727c857c.png) that might explain it
> 
> why don't you use the version MATCH-V5?

MATCH-V5 has the same problem FYI 😞

**Comment by lauriys** [comment]
> why don't you use the version MATCH-V5?

V5 is not on the status list

**Comment by DeadSca** [comment]
Same problem with much users;(

**Comment by MaouLegna** [comment]
The issue has been solved 

(around 18:30 CEST)
