### ISSUE TITLE
[BUG] [VAL] Incorrect leaderboards data for EPISODE 3: ACT 3 on NA and BR regions (VAL-RANKED-V1)

### ISSUE THREAD

**Issue by tamara-lytvynova** [RiotGames/developer-relations#647]
**Bug Description**  
Valorant leaderboards for actId `a16955a5-4ad0-f761-5e9e-389df1c892fb` on NA and BR regions return `"rankedRating": 0`, `"numberOfWins": 0` and no puuid, gameName and tagLine for all players (VAL-RANKED-V1).

**Expected Result**  
I'm expecting to get rankedRating and numberOfWins other than 0, also to get puuid, gameName, and tagLine for non-anonymous players.
I expected a response similar to EU region: GET https://eu.api.riotgames.com/val/ranked/v1/leaderboards/by-act/a16955a5-4ad0-f761-5e9e-389df1c892fb
![Screen Shot 2022-06-07 at 7 39 13 PM](https://user-images.githubusercontent.com/69008940/172437094-7ca0afb4-12f0-4219-a8b2-40bfdb5dae1b.png)

**Actual Result**  
GET https://na.api.riotgames.com/val/ranked/v1/leaderboards/by-act/a16955a5-4ad0-f761-5e9e-389df1c892fb
![Screen Shot 2022-06-07 at 7 44 52 PM](https://user-images.githubusercontent.com/69008940/172437549-5e1717be-cf9c-44f4-a152-71e13cc3b0ee.png)
![Screen Shot 2022-06-07 at 7 45 09 PM](https://user-images.githubusercontent.com/69008940/172437574-4953476b-0185-4e3a-9130-ce4751448b41.png)

There is no actual rankedRating, numberOfWins, puuid, gameName, and tagLine data.
This doesn't look like a temporary issue, as the problem reproduces for more than a week.

GET https://br.api.riotgames.com/val/ranked/v1/leaderboards/by-act/a16955a5-4ad0-f761-5e9e-389df1c892fb
![Screen Shot 2022-06-07 at 7 46 01 PM](https://user-images.githubusercontent.com/69008940/172437773-aaed4dda-d285-4871-a93f-639b8a8d0330.png)

**Developer Impact**  
There is no ability to show leaderboards data for EPISODE 3: ACT 3 on NA and BR regions and use this data for player rating progress.

* Frequency: Every API call.
* Severity: Low.

**Player Impact**  
There is no ability to view leaderboards data for EPISODE 3: ACT 3 on NA and BR regions and view this data in player rating progress.

* Frequency: Low.
* Severity: Low.
* Region: NA and BR regions.

**Preconditions**  
* actId `a16955a5-4ad0-f761-5e9e-389df1c892fb`
* NA and BR regions

**Steps to Reproduce**  
Request leaderboards data for actId `a16955a5-4ad0-f761-5e9e-389df1c892fb` on NA and BR regions 

* GET https://na.api.riotgames.com/val/ranked/v1/leaderboards/by-act/a16955a5-4ad0-f761-5e9e-389df1c892fb
* GET https://br.api.riotgames.com/val/ranked/v1/leaderboards/by-act/a16955a5-4ad0-f761-5e9e-389df1c892fb

**Comment by tisbells** [comment]
Closing old issues. Not seeing new reports of this for newer episodes. Feel free to comment or reopen if you are still having this issue.
