### ISSUE TITLE
Feature request: lolesports.com API

### ISSUE THREAD

**Issue by hundeva** [RiotGames/developer-relations#65]
Currently, there are unofficial ways for accessing esports related data. However, those can break and change at any time, without prior notice, thus making it extremely risky to depend on with a production app. I would like to see an official API.

**Comment by vickz84259** [comment]
For me personally, I don't mind the api being unofficial in the terms that it would change at any time. The lack of any form of documentation or even simply just a listing of all the endpoints available on the esports api is much more taxing. 
It's hard trying to sift through the minified js files or the XHR requests to try and pinpoint what endpoints are being used by a particular page.

What I'm proposing is something similar to what we have for the lcu api. Yes, they are undocumented but at least we have an idea of what endpoints are available.

**Comment by hundeva** [comment]
The League Friends app has received some new, esport related functionalities. This means that there is some kind of API available now. @RiotTuxedo, would you be able to share some insights, is it planned to document it, and/or release it to the public?

I will probably sniff around and check it out anyway, but just in case. :)

**Comment by tisbells** [comment]
Closing out old issues. There are no current plans to provide esports data within the API.
