### ISSUE TITLE
OCE api is down

### ISSUE THREAD

**Issue by whyando** [RiotGames/developer-relations#656]
Might be a pointless report since it's surely known but OCE has been down for about 74 hours.

The only news I could find was this tweet https://twitter.com/RiotGamesDevRel/status/1542196592387584000 about a planned migration.

Any further news, or fix ETA?

thanks

**Comment by geozukunft** [comment]
Are you using SEA instead of AMERICAS as routing value?

**Comment by whyando** [comment]
as far as I know, only match-v5 is migrating to SEA from AMERICAS
the endpoints such as summoner-v4 should be still on oce.api.riotgames.com, which is returning 503

**Comment by geozukunft** [comment]
That's correct then it's just Riots services being Riots services.

**Comment by Supesu** [comment]
any update to this? still down.

**Comment by geozukunft** [comment]
Most of Riot is on a 1 week break I heavily doubt there will be any news about this before people are back in office next week.

**Comment by lucasMesquitaBorges** [comment]
The endpoints for OCE are up. They were fixed after the break.

Is someone still experiencing issues?

**Comment by MrBartusek** [comment]
> Is someone still experiencing issues?

Clash-V1 is still down
```
https://oc1.api.riotgames.com/lol/clash/v1/tournaments
```
```json
{"status":{"message":"Service unavailable","status_code":503}}
```

**Comment by lucasMesquitaBorges** [comment]
Hi @MrBartusek can you re-check please?

**Comment by MrBartusek** [comment]
@lucasMesquitaBorges yup it got fixed

**Comment by lucasMesquitaBorges** [comment]
OCE downtime was fixed. In case of other problem, feel free to open a new ticket.
