### ISSUE TITLE
[BUG] random 503 Service Unavailable - matchv5, every region

### ISSUE THREAD

**Issue by DarkIntaqt** [RiotGames/developer-relations#659]
**Bug Description**  
Sometimes the response of a matchv5 request is 503. It occurred on every region and always random => no rate limit exceeded

**Problem Description, Developer Impact**  
Most developer don't expect a 503 or can't handle it properly (e.g. just retry the request)

**Expected Result**  
503 => 200

* Frequency: Maybe around every 100-200 api calls
* Efficiency: Requires me to run more threads to fetch missing matches
* User "emails": Some users on the DevRel discord experienced the same bug

If someone else has also experienced this issue, maybe with another endpoint, please comment here ^^

**Comment by ItzDerock** [comment]
can confirm, this is occuring intermittently for me too. It's happened once in the last 120 requests to the matchv5 `/matches` endpoint

**Comment by DarkIntaqt** [comment]
Update: After a little bit of crawling more matches, I also found this error code on the summoner api in LA1 and the challenge api at almost every region, as mentioned in #651 
I thought there was only an issue with the large endpoints (europe, sea ... ), but now it happened on every region to me
