### ISSUE TITLE
League Positions V4 uses string QueueType rather than integer QueueId

### ISSUE THREAD

**Issue by jessehallam** [RiotGames/developer-relations#66]
The API `/lol/league/v4/positions/by-summoner/{encryptedSummonerId}` is still using the old, string-typed `queueType` property for `LeaguePositionDTO`.

APIs using string `queueType`

1. `/lol/league/v4/positions/by-summoner/{encryptedSummonerId}` (`LeaguePositionDTO`)

APIs using integer `queueId`

1. `/lol/match/v4/matchlists/by-account/{encryptedAccountId}` (`MatchReferenceDto`)
2. `/lol/match/v4/matches/{matchId}` (`MatchDto`)

**Recommendation**:

Add `queueId` property with integer type to `LeaguePositionDTO`.

**Comment by Linnun** [comment]
I've had this discussion before, and from what I remember the leagues' queueType are not neccessarily identical to any queueIds.
Technically there could be multiple queues scoring towards the same league. I believe this actually was exactly what happened during the removal of Ranked Draft (or was it TeamBuilder?) a couple years ago, when there was an old-style queue and a new-style queue towards the same league.

That being said, I believe this is not a bug. Please try not to confuse a league's queueType with a queueId -- technically they are different things, even though they have a similar name, and (for now) they map 1:1 most of the time.

**Comment by RiotTuxedo** [comment]
@Linnun hit the nail on the head. Though there is a field called *queueType* this is an ENUM that's often  named after a queue, but doesn't actually represent a queue. I realize this is a bit confusing so I'll try to explain this another way. Think of *queueType* like *ladderName*. It's an arbitrary string that represents a specific ladder. This ladder happens to be named *RANKED_SOLO_5x5*. Multiple queues can contribute to gains/losses in a specific ladder. As an example, you could create a ladder called *GLOBAL_RANK* and have every queue in the game contribute LP to that ladder. There's a precedent for this happening too. When dynamic queue was first introduced they had some issues on launch and the ranked experience was toggled between queueId 4 and 410. Both these queues contributed to gains/losses in the *RANKED_SOLO_5x5* ladder for a period of a couple weeks. Ladders and queues typically only have a one to one relationship, but that's not always the case.
