### ISSUE TITLE
[Account] INVALID ACCOUNT

### ISSUE THREAD

**Issue by SungyunPark** [RiotGames/developer-relations#660]
**Account Information**
riot id : etri5671
I just created an account for the Developer Portal

**Issue Description**  
I have tried logging on Developer Portal but it says "INVALID ACCOUNT You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter], during office hours on [Discord], or create an [GitHub issue]"

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [o] Attempt to log in via "Incognito Mode"
- [o] Clear your browser cookies
- [o] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1, I try logging on developer portal
1. Step 2, I got a message "INVALID ACCOUNT You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter], during office hours on [Discord], or create an [GitHub issue]"

**Issue Context**
I have several riot ids that have same issue with this. the riot ids are "etri776", "etripsy5671", and "GAEgosu5781"
I can log on league of legends homepage successfully, but in developer portal I cannot log on.

**Comment by SungyunPark** [comment]
I have tried all the other methods "Attempt to log in via "Incognito Mode"",  "Clear your browser cookies" and "Attempt to login via a secondary device (mobile or different computer)" and those are not working too. Additionally the id "etri5671" got same error

**Comment by lucasMesquitaBorges** [comment]
Hey @SungyunPark I'm tackling old issues. Sorry for not answering this before.

Your account is not active. You will need to follow this [article](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/360037644973-Recover-Your-Account) in order to recover your account.

Feel free to re-open this issue if needed.
