### ISSUE TITLE
[FEATURE REQUEST] Return the matches by tournament code endpoint.

### ISSUE THREAD

**Issue by ElijahKSmith** [RiotGames/developer-relations#663]
### Request

Port the `/lol/match/v4/matches/by-tournament-code/{tournamentCode}/ids` from the `match-v4` API to either the current match or tournament API.

### Reasoning

In `match-v4` there was an endpoint to retrieve a list of matchids generated by a tournament code, but in `match-v5` and `tournament-v4`, there exists no such endpoint.

This means that the only way to now retrieve any additional matches generated with a tournament code (past the initial match which can be retrieved via tournament provider callback) is to poll users' match histories then pull match data to see if a given match was generated with a tournament code. 

And if for some reason you don't know which players are in a given match (for example, if a team entirely substitutes their backup roster in between matches) then you have to listen to lobby events to pull that data, which [the API docs themselves](https://developer.riotgames.com/docs/lol#riot-games-api_tournament-api) note that there is a chance that lobby events get dropped, and then an extra call would be needed to resolve the summonerId in the lobby events to a PUUID which is needed to pull match histories in `match-v5`. This increased complexity in calls has the potential to snowball as the size of a tournament increases and matches occur, which could lead everything to come to a screeching halt when rate limits are reached.

I do know that the recommendation is to only use one tournament code per match, the reasoning being the provider callback only being made once, but from a UX standpoint one tournament code is better. From my own past experience as a team manager and from my colleagues as well that were players/team staff, we have seen our fair share of problems arriving at match time when a team/player is using the wrong tournament code in a series and is waiting in the wrong lobby, causing false forfeit reports and match disputes. This problem is not isolated in our experiences, as some platforms (e.g. Battlefy) have started moving to one-code solutions to alleviate this issue. That way, user error isn't possible for this issue.

Therefore, I believe that this endpoint provides value, not just for myself but also for others that are building with the tournament APIs. Because of the snowbally complexity of the workaround, this solution gets much more costly without the endpoint both in resources and time.

**Comment by zoltanzseli** [comment]
Any update on this?

**Comment by lucasMesquitaBorges** [comment]
Tournament-v4 was deprecated and now you should use tournament-v5.

The v5 have an endpoint to get matches by tournament code.

See: https://developer.riotgames.com/apis#tournament-v5/GET_getGames
