### ISSUE TITLE
[BUG] Star Nemesis FIddlesticks not working on ddragon

### ISSUE THREAD

**Issue by VictorPorlan** [RiotGames/developer-relations#664]
His JSON says that this skin has the number 27, but then when you try to get the jpg it doesn't exist.
https://ddragon.leagueoflegends.com/cdn/12.13.1/data/en_US/champion/Fiddlesticks.json
https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_27.jpg

**Comment by bangingheads** [comment]
Reworked fiddlesticks images are all under FiddleSticks

https://ddragon.leagueoflegends.com/cdn/img/champion/splash/FiddleSticks_27.jpg

The issue relating to it is #83

**Comment by VictorPorlan** [comment]
Thanks a lot, as the issue says, thats kinda inconsistent
