### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by ttataboota** [RiotGames/developer-relations#666]
**Account Information**

-my summoner name is '뿌구리' in KR server
 I create an account for the Developer portal

**Issue Description**  

-I think my Developer portal account banned.
 if i log in Developer portal, 
"INVALID ACCOUNT
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on Twitter, during office hours on Discord, or create an GitHub issue."
so i send you a message to twitter or discord, but i couldn't receive the massage.
I think it may happen that i've tried to use riot api so hard...it's my first time to coding and use api, i request so much data in short time. next i use your api, i'll use 'sleep' or something else. sorry 

**What I've Tried**
What steps have you tried to resolve the issue.

- [o] Log out of the Developer Portal
- [o] Attempt to log in via "Incognito Mode"
- [o] Clear your browser cookies
- [o] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

**Issue Context**
I'm not DDOS attacker or computer! please check my message please! I want to use your good api and check lots of data of league of legend.

**Comment by lucasMesquitaBorges** [comment]
Hey @ttataboota I'm tackling old issues. Sorry for not answering this before.

Checking your account it seems to be in the correct state.
I'm assuming you fixed via player support or other riot channel.

If you still run into issues to use devportal, feel free to re-open this issue.
