### ISSUE TITLE
[BUG] VAL-RANKED-V1 randomly returns 404 spaghetti

### ISSUE THREAD

**Issue by iann838** [RiotGames/developer-relations#669]
## What this is
Request to `/val/ranked/v1/leaderboards/by-act/{actId}` would randomly return 404 for no apparent reason, maybe a late april's fool. Not a "me" issue, this happens even off a simple button press in the riot dev console. I was able to grab the trace id of one of the failed requests here: `X-Riot-Edge-Trace-Id": "5fef3c76-faa9-4935-a7c9-32238b9ce6c`.

## How reproduce
Just randomly make a few request to the endpoint and it will just randomly 404. The params used were act_id=`67e373c7-48f7-b422-641b-079ace30b427` and platform=`eu`.

## How often
Literally every 2 or 3 request on average.

## What this means to us
:slightly_smiling_face::slightly_smiling_face::slightly_smiling_face::slightly_smiling_face::slightly_smiling_face: plz fix or at least make it happen less.

**Comment by geozukunft** [comment]
Nice

**Comment by tisbells** [comment]
Closing old bugs and there are no recent reports of this.
