### ISSUE TITLE
[Account] Login issue

### ISSUE THREAD

**Issue by Gueho** [RiotGames/developer-relations#676]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)? 
**Chickfila**
Have you played any of Riot's games or did you just create an account for the Developer Portal? 
**I did play the game and I would like to access to Developer Portal**

**Issue Description**  
A clear and concise description of what the issue is.
**You've logged in successfully, but your account is in a funky state so we need to take a look.** 

**What I've Tried**
What steps have you tried to resolve the issue.

- [ ] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by f3ar161** [comment]
Hi @Gueho, this issue has been fixed. Can you confirm that you have access to https://developer.riotgames.com/???

**Comment by lucasMesquitaBorges** [comment]
Closing old issues, @f3ar161 fixed this account. If needed feel free to re-open.
