### ISSUE TITLE
[BUG] CHAMPION-MASTERY-V4 API not working??

### ISSUE THREAD

**Issue by AlejandroV01** [RiotGames/developer-relations#677]
**Bug Description**  
Whenever I call the mastery API
https://na1.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-summoner/${SummonerID}?api_key=${API_KEY}
I keep getting 403 error codes.
Is there a problem with the API or something on my side? The API was just working 3 days ago and then suddenly it keeps going into this error.
The error code not only happens on my website but also on the Riot Developer Portal.

**Expected Result**  
I was expecting to successfully retrieve the JSON file from the other end of the URL of the mastery of their champions.

**Actual Result**  
a 403 Error code

**Developer Impact**  
I can not get my personal project to update the mastery of the summoner's champions. Data is missing.

* Frequency: Every API call.
* Severity: When it happens, I retrieve nothing from the API which leads to blank data on my website.

**Comment by bangingheads** [comment]
400 means it's having an issue decrypting the ID.

IDs are encrypted per API key.

This means if you pull a summoner ID with your developer key and try to use it on an endpoint of a personal key it will not work.

Make sure you are getting your IDs from the same key that you are trying to use another endpoint on.

**Comment by AlejandroV01** [comment]
everything is under the same api key. I only have one API Key

**Comment by AlejandroV01** [comment]
nvm, i am getting 403 codes now??

**Comment by Zangoi1** [comment]
Getting the same error along with new 403s on `/tft/summoner/v1/summoners/by-account/` as of today.

When going to these api pages on the [riot games api explorer page](https://developer.riotgames.com/apis#tft-summoner-v1/GET_getByAccountId), it says "CANNOT EXECUTE. THIS API ENDPOINT IS NOT AVAILABLE IN YOUR POLICY". This is new and was not like this 2 days ago.

**Comment by geozukunft** [comment]
Are you using a dev key or an personal key? @Zangoi1 / @AlejandroV01 
Riot seems to have removed a few Endpoints from Developer keys we don't know if it was an accident or wanted behaviour but there has been no communication about either yet.

**Comment by Zangoi1** [comment]
Personal key, I just assumed it was a bug since it seems to be in the same category as other publicly available endpoints

**Comment by AlejandroV01** [comment]
I am using a personal api key / PERSONAL LEAGUE STACK TRACKER. Still getting the error, much like @Zangoi1

**Comment by AlejandroV01** [comment]
fixed it!! My god finally, it was so hidden lol.
Go to your profile in the top right. 
Apps >> Personal League Stack Tracker >> And then use the API key that Is on that page
If you go to the "APIS" Tab you will see that you have access to mastery data on that API rather than that "Development API Key".

**Comment by dmilin1** [comment]
This issue should be reopened until we get a response from Riot confirming that this is intended behavior.

The `CHAMPION-MASTERY-V4` endpoint is returning 403s for all Development API Keys. Production Keys seem to be working fine. It seems unlikely to me that they would disable Development Keys seeing as how they're necessary in order to build the demo required when applying for a Production Key.
