### ISSUE TITLE
[BUG] Endpoints access suddenly removed from development keys scope

### ISSUE THREAD

**Issue by Zangoi1** [RiotGames/developer-relations#679]
**Bug Description**  
Some endpoints returning 403s on development keys. Endpoints are unexpectedly no longer of developer app's policy.

**Problem Description**  
API endpoints `TFT-SUMMONER-V1*` and `CHAMPION-MASTERY-V4` are affected and others might as well. These endpoints, around 3 days ago and prior would return the data as expected. But recently, they return 403 error codes and in the API page show `CANNOT EXECUTE. THIS API ENDPOINT IS NOT AVAILABLE IN YOUR POLICY`.

**Expected Result**  
The API requests should return the expected data for the calls.

**Actual Result**  
A 403 error code was returned.

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call to the affected endpoint. 
* Severity: Extremely high. Unable to build my project due to this bug. New summoner profiles on TFT would not be able to be indexed. 

**Preconditions**  
Developer has to have a developer key, which only seems to be affected.

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Use a developer API key
1. Call `/tft/summoner/v1/summoners/by-account/{encryptedAccountId}` under the affected `TFT-SUMMONER-V1` endpoint.

**Comment by NicholasEwing** [comment]
Can confirm this is also happening on `/tournament-stub/` endpoints as well.

**Comment by Token07** [comment]
It was mentioned on discord that access to the above endpoints with dev keys has been restored.
