### ISSUE TITLE
[Feature Request] Client - pre-match - Show an icon on portraits for champions that you already have a chest with on character select screens

### ISSUE THREAD

**Issue by DimensionWarped** [RiotGames/developer-relations#680]
IE - in the reroll pool of ARAM or over selectable portraits in a normal character select.

**Comment by lucasMesquitaBorges** [comment]
Hi! @DimensionWarped Thanks for your contact. This is a player platform request related.

Please go [here](https://support.riotgames.com/hc/en-us).
