### ISSUE TITLE
[BUG] LCU API returns error message

### ISSUE THREAD

**Issue by Starrycug** [RiotGames/developer-relations#681]
**Problem Description**  
Sometimes call LCU APIs such as '/lol-champ-select/v1/session/timer' or '/lol-gameflow/v1/session', it returns the results as 404.
`{
    "errorCode": "RESOURCE_NOT_FOUND",
    "httpStatus": 404,
    "message": "Invalid function"
}`

I'm sure that I calls them by correct Authorization and params.
When I restart LOL client and retry to call, it will retrurn the correct result with code 200.

**Expected Result**  
I want to know why some of LCU APIs returns 404 sometimes. When it occurs, what should I do except restarting the game client?

**Comment by tisbells** [comment]
Closing out old issues. We are unfortunately unable to support the LCU.
