### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RomanLubushkin** [RiotGames/developer-relations#687]
**Bug Description**  
`/lol-gameflow/v1/session` endpoint doesn't return teams information after game started (`phase: InProgress`). Bug apperated specificly right after patch 12.18.

**Expected Result**  
Response of `/lol-gameflow/v1/session` endpoint returns information about teams at `gameData.teamOne` and `gameData.teamTwo` fields after game started `phase: InProgress`.

**Actual Result**  
Empty arrays returned.
![image](https://user-images.githubusercontent.com/680750/191663796-106ace8a-c7a3-47f0-ba6e-83f768cf2453.png)

**Player Impact**  
Pre-game feature of Mobalytics app is broken.

* Frequency: Every API call.
* User emails: A lot of complains in customer support
* Frequency: Every game
* Severity: Pre-game is very important part of the app, Severity is high.
* User emails: A lot of complains in customer support

**Repro Steps**  
Play normal draft or any other game mode and fetch `/lol-gameflow/v1/session` after game started (loading screen appeared).

**Comment by geozukunft** [comment]
The LCU API is not officially supported and subject to changes all the time

**Comment by f3ar161** [comment]
Hi @RomanLubushkin do you have the code that is consuming the game flow session???? that needs the theamOne and teamTwo??

**Comment by RomanLubushkin** [comment]
Hi @f3ar161 
Yes, we're using flowSession data to identify summoners, their champions, and assigned roles if any during the game. Based on that info we're getting statistics and analytical data from our end.

**Comment by lucasMesquitaBorges** [comment]
Hi, this issue has been fixed in 12.20.1 patch. If you run into some similar error, feel free to follow up or open a new issue.
