### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by VanPrizm** [RiotGames/developer-relations#690]
A bug report and valorant tell me share to riot 
https://drive.google.com/file/d/1zROL3i7C8FcHhlwwcC1r4Qj-owc5X9Wi/view?usp=sharing[https://drive.google.com/file/d/1zROL3i7C8FcHhlwwcC1r4Qj-owc5X9Wi/view?usp=sharing](url)

**Comment by Token07** [comment]
> Welcome to the Riot Games Developer Relations repo. The purpose of this repo is exclusively bug reporting for tools in the Riot Games Developer Ecosystem.
You need to create a player support ticket and share it there.
https://support.riotgames.com
