### ISSUE TITLE
[BUG] Possible lockup of the agent selection API when selecting twice the same agent via API

### ISSUE THREAD

**Issue by NeXiDE** [RiotGames/developer-relations#692]
[removed]

**Comment by RiotTuxedo** [comment]
Really solid report. I'll forward it along to the appropriate people. If you wanna reach out to me on Discord (join the Developer Discord and the gurus can put you in contact with me) I'll see if we can get you a bug bounty for it. Removing it from here for two reasons:

1. This isn't the place to report bugs in the game.
2. It's not ideal to have detailed instructions on how to break the game in a public place like this.
