### ISSUE TITLE
Fiddlesticks centered image has a wrong name on DataDragon CDN [BUG] 

### ISSUE THREAD

**Issue by latra** [RiotGames/developer-relations#693]
**Bug Description**  
When I try to get the Fiddlesticks image from the CDN from `https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Fiddlesticks_0.jpg` (and apparently all the champion skins), seems to be missing, since I'm getting a 403, the same error that I get when I try to get any unexistent champ.

The splash (`https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg`) or loading image (`https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg`) is available 

Also, I can correctly get other champs images from `https://ddragon.leagueoflegends.com/cdn/img/champion/centered/` (like [Ezreal](https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Ezreal_0.jpg) or [Fiora](https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Fiora_0.jpg))

I checked the tarball from the data of 12.10.1, I find that it is saved as "FiddleSticks_0.jpg" (notice the caps on the `S`), and also on other versions like 12.6.1, but the ID from `champions.json`  is in lowercase (`fiddlesticks` instead `FiddleSticks`). Also, I confirmed that Fiddlesticks is available on the URL `https://ddragon.leagueoflegends.com/cdn/img/champion/centered/FiddleSticks_0.jpg` (putting `FiddleSticks` instead `Fidlesticks`).

The same behaivour also happens with other champs, like MasterYi, where `masteryi_0` will return a 403, and `MasterYi_0` will work, but in Master Yi case, the champ ID on `champions.json` is already `MasterYi`

**Problem Description**  
A champion is missing

**Expected Result**  
The address `https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Fiddlesticks_0.jpg`  from the CDN should return the splashart from Fiddlesticks,

or `champions.json` data should be updated to change the ID from `Fiddlesticks` to `FiddleSticks` 

**Actual Result**  
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>JBSRSVC02N4XSAR7</RequestId>
<HostId>{REDACTED}=</HostId>
</Error>
```
**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call
* Severity: I can't dinamically get the champion data, since the ID from `champions.json` does not match with the path from the CDN
* Cost: Requres me to get the centered splashart manually from the tarball, or add some conditionals on my code for specific champs (not cool).
* Efficiency: --
* User emails: --

**Player Impact**  
N/A

**Preconditions**  
N/A

**Repro Steps**  
1. Get `champions.json` file
2. From the file, get `Fiddlesticks` ID (`Fiddlesticks`)
3. Try to get the centered splashart from Fiddlesticks using the indicated ID on `https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Fiddlesticks_3.jpg`
4. You will get a 403
5. Check that Fiddlestick splashart is available on `https://ddragon.leagueoflegends.com/cdn/img/champion/centered/FiddleSticks_3.jpg`

**Comment by DarkIntaqt** [comment]
See #7 - you have to change that manually in your code

**Comment by latra** [comment]
@DarkIntaqt  I think that is not exactly the same case, since Wukong ID is already `MonkeyKing`. So following the statement mentioned by @RiotTuxedo in [his comment](https://github.com/RiotGames/developer-relations/issues/7#issuecomment-445104648) does not work for Fiddlesticks.

The key from Fiddlesticks does not match with the centered key from the CDN.

Also, even if there is something different in Fiddlesticks, there is nosense that this """"""""feature""""""""" only applies to the centered image

**Comment by meesvandongen** [comment]
> Also, even if there is something different in Fiddlesticks, there is nosense that this """"""""feature""""""""" only applies to the centered image

It applies to all fiddlesticks images. The other images just have the old splash art which was not replaced ~3 months ago.

**Comment by pixsaoul** [comment]
Looks like all images are available with the key Fiddlesticks, except the loading image for skin 9.

**Comment by tisbells** [comment]
Closed as a dupe, see https://github.com/RiotGames/developer-relations/issues/83 and https://github.com/RiotGames/developer-relations/issues/7. Will post on #83 if we receive any updates on this.
