### ISSUE TITLE
Hello RiotGames. Would you like more info/videos/material that will shut moonton down??

### ISSUE THREAD

**Issue by ghost** [RiotGames/developer-relations#695]
If so know that I have played mobile Legends for 5 years and I am so entirely fed up with them and have kept records videos and logs of all the wrongful malpractices the do to their customers. Fixed matching/ harassing those that don't comply bugs. Matching imbalance their responses. Also I know your in a lawsuit against them and I would be more than happy to divulge my info.

**Comment by Token07** [comment]
This GitHub page is for the Riot Games API, a tool which provides data to sites like op.gg.

Any Rioters monitoring this page are part of the team that manages the API, and will not be able to help you with support or gameplay issues.

If you're having account related issues or technical problems, contact Riot Games support: <https://support.riotgames.com/hc/en-us>.
If you have a game-related suggestion or feedback, post on the subreddit, or the discord for the relevant game:
<https://discord.gg/lol>
<https://discord.gg/valorant>
<https://discord.gg/legendsofruneterra>
<https://discord.gg/teamfighttactics>
