### ISSUE TITLE
[Account] Login issue

### ISSUE THREAD

**Issue by teamsnowballMinQ** [RiotGames/developer-relations#696]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
- tsbgaja

Have you played any of Riot's games or did you just create an account for the Developer Portal?
- just create an account for the Developer Portal

**Issue Description**  
A clear and concise description of what the issue is.

- I'm having this message when I log in
  **INVALID ACCOUNT
  You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter](https://twitter.com/RiotGamesDevRel), during office hours on [Discord](https://discord.gg/riotgamesdevrel), or create an [GitHub issue](https://github.com/RiotGames/developer-relations/issues/new?template=account_issue.md&title=%5BAccount%5D+).**

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. enter Id and password
2. click login button

**Issue Context**
Please add any additional context that is useful.

**Comment by lucasMesquitaBorges** [comment]
Hey @teamsnowballMinQ  I'm tackling old issues. Sorry for not answering this before.

Checking your account it seems to be in the correct state.
I'm assuming you fixed via player support or other riot channel.

If you still run into issues to use devportal, feel free to re-open this issue.
