### ISSUE TITLE
league/by-summoner api's result has some bugs.

### ISSUE THREAD

**Issue by Apilion** [RiotGames/developer-relations#70]
https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/%ED%83%9C%EB%AF%BC

https://kr.api.riotgames.com/lol/league/v4/positions/by-summoner/??????

return he is in MASTER ( leagueId = 02b21acc-7155-3e13-a409-609de4846bd3 )

```
[
    {
        "leagueId": "02b21acc-7155-3e13-a409-609de4846bd3",
        "leagueName": "Riven's Snipers",
        "queueType": "RANKED_SOLO_5x5",
        "position": "NONE",
        "tier": "MASTER",
        "rank": "I",
        "leaguePoints": 33,
        "wins": 45,
        "losses": 37,
        "veteran": false,
        "inactive": false,
        "freshBlood": true,
        "hotStreak": false,
        "summonerId": "7O4KZyFFftc6dZcIqwpb-X39CiX-yojoFj1gmCj65f-plkM",
        "summonerName": "태 민"
    }
]
```

BUT He is not in league results in master league api.
https://kr.api.riotgames.com/lol/league/v4/masterleagues/by-queue/RANKED_SOLO_5x5

He is in here.
https://kr.api.riotgames.com/lol/league/v4/leagues/02b21acc-7155-3e13-a409-609de4846bd3
( What's this info? )

And search him in league client shows he is in ( DIAMOND II )

![image](https://user-images.githubusercontent.com/47075228/51798195-4dd55500-2252-11e9-8033-476e78b49310.png)

**Comment by ssi10** [comment]
Additional info here.

after 1 hour.

he has 1 win, 1 lose.

his league point(LP) changed to 33 > 55 > 41 ( info from  by-summoner method. )
his ingame(client)  LP also changed to 16 > ?? > 22

**Comment by Apilion** [comment]
Additional info here.

after 1 hour.

he has 1 win, 1 lose.

his league point(LP) changed to 33 > 55 > 41 ( info from by-summoner method. )
his ingame(client) LP also changed to 16 > ?? > 22

**Comment by RiotTuxedo** [comment]
Thanks for the report, this issue should now be resolved.
```
Issue: Some players are displayed as Master when they aren’t and vice versa.
Due to a problem with the underlying tech we’re using to calculate and track rank information we’re sending to the Riot API, we were giving third party sites incorrect data.

Conclusion: We fixed this bug yesterday, January 30 at 5:00 PM GMT-8, so players should be able to see who’s actually Master Tier and who’s not on third party sites.
```
https://boards.na.leagueoflegends.com/en/c/developer-corner/AnObL88Z-ranked-2019-dev-update-2
