### ISSUE TITLE
The size of `profileicon0.png` sprite has grown (too) big

### ISSUE THREAD

**Issue by meesvandongen** [RiotGames/developer-relations#700]
The image is (as of patch 12.21) 480 x 16992 px. Some image software only supports files up to 16384 pixels. Other sprites are cut into smaller pieces, so this one should be too.

**Comment by DarkIntaqt** [comment]
The sprite is just growing larger. I think a single 16mb sprite can prolly be split up into several smaller files

**Comment by tisbells** [comment]
Closing out old issues, there have been no additional/recent reports of this. Feel free to reopen if this is still an issue.
