### ISSUE TITLE
[BUG] /riot/account/v1/accounts/me responds with 500/503

### ISSUE THREAD

**Issue by SidiaDevelopment** [RiotGames/developer-relations#701]
**Bug Description**  
Currently the api endpoint `/riot/account/v1/accounts/me` responds with 500 or 503 errors

I have tested to request data from 2 different servers and my local machine, same results on all of them.

**Developer Impact**  
RSO Endpoint not usable

* Frequency: Every API Call to `/riot/account/v1/accounts/me`
* Services: Routes europas and asia produce this error, americas seems to work

**Comment by brbarnett** [comment]
Our application as of sometime yesterday (at least) has been receiving 404s from that endpoint, not 500 or 503. Similar issue but different status code.

**Comment by kalleth** [comment]
Same for us. 500/503 response codes.

**Comment by wktk** [comment]
I'm on the asia server and experiencing the same issue.  Changing to the americas region seems to be working.

**Comment by rokk1stas1** [comment]
Same for us. Any updates?

**Comment by SidiaDevelopment** [comment]
> Same for us. Any updates?

Use the americas route for this api until its resolved.

**Comment by lucasMesquitaBorges** [comment]
Hi, We had issues in `asia` and `europe` routing for accounts and it's fixed now.

If you run into any issues, feel free to reopen or create a new issue.
