### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by qodlstjd12** [RiotGames/developer-relations#706]
**Account Information**
My summoner nickname is "노스킨장인"
I have played lol for a long time, and I just want to use riot api for my toy project.

**Issue Description**  
I log in Riot developer portal for using api, but I watch warning that my account is invalid.
So, I report this problem.

**What I've Tried**
What steps have you tried to resolve the issue.

- [o] Log out of the Developer Portal
- [o] Attempt to log in via "Incognito Mode"
- [o] Clear your browser cookies
- [o] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by lucasMesquitaBorges** [comment]
Hi, send your riot id + tag in order to verify your account state.
