### ISSUE TITLE
[BUG] Requests hanging for extended period of time

### ISSUE THREAD

**Issue by GriffinWood** [RiotGames/developer-relations#707]
**Bug Description**  
A sizable portion of requests (roughly 2%) are hanging for 60 seconds before completing.

**Problem Description**  
This issue started in the last day or two. It also appears to be fairly consistent (i.e. if I make 100 requests most of the time 2 hang). I also let my service run for an hour and found roughly 2% of requests hung in that time scale as well. 

It does not appear to be related to specific requests (i.e. if I repeat a requests that hung roughly 2% of those will hang again). 

The following end points I am having issues with are:
/lol/match/v5/matches/{matchId}
/lol/match/v5/matches/by-puuid/{puuid}/ids
 /lol/match/v5/matches/{matchId}/timeline

**Issue Comments**  
I have largely been able to alleviate this issue by adding a timeout and trying again, however, this still seemed like something worth flagging.

**Comment by geozukunft** [comment]
I am experiencing the same issue on /lol/challenges/v1/player-data/{puuid}

**Comment by omarali** [comment]
I am experiencing the same issue on:
/lol/summoner/v4/summoners/{encryptedPUUID}
/lol/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}/by-champion/{championId}
/lol/match/v5/matches/by-puuid/{puuid}/ids
/lol/match/v5/matches/{matchId}

**Comment by CurtisGreen** [comment]
I'm also experiencing this issue

**Comment by aramlol** [comment]
Have been experiencing this problem with the match v5 endpoint since the middle of patch 12.21

**Comment by liflovs** [comment]
Same on matchlist. My library should follow the headers rate limit but  still this is happening

**Comment by carrotpai** [comment]
Having the same issue

**Comment by MariuszGG** [comment]
Having the same issue

**Comment by lucasMesquitaBorges** [comment]
Hi, is this issue still happening?

**Comment by geozukunft** [comment]
Can't say for this very moment but it was happening about 3 hours ago when I last checked. On challenges-v1 , summoner-v4 and match-v5 were the endpoints I checked

**Comment by lucasMesquitaBorges** [comment]
Thanks @geozukunft!!
We are working on this issue.

**Comment by CurtisGreen** [comment]
Thanks for looking into this :) 

I can run tests for different endpoints in a few hours if needed 👍

**Comment by lucasMesquitaBorges** [comment]
Hi, sorry for the long time on this issue. We had to go through several dependencies on our gateway.
We made a few changes to mitigate it. Could you check?

**Comment by geozukunft** [comment]
I will run some tests in a couple of hours and will check on the challenges endpoints

**Comment by geozukunft** [comment]
I just checked my app that is doing quite a lot of requests to /lol/match/v5/matches/{matchId} if set on a 5sec timeout I am still getting an unsual amount of Timeouts even when I am requesting in EUROPE from an European server

**Comment by tisbells** [comment]
@geozukunft hey there, are you still experiencing these issues?

**Comment by geozukunft** [comment]
The issues are resolved no meaningfull problems over 1.38bil requests

**Comment by tisbells** [comment]
Cool, closing this out.
