### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by jaehunkim0828** [RiotGames/developer-relations#710]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
'롤고소한다'
Have you played any of Riot's games or did you just create an account for the Developer Portal?

I enjoy playing League of Legends, and I made a project using Lolapi.

**Issue Description**  
A clear and concise description of what the issue is.

I don't know exactly what the problem is, but I had this problem while filling out the form to receive the production api for the project I developed this time.

**What I've Tried**
What steps have you tried to resolve the issue.

- [o] Log out of the Developer Portal
- [o] Attempt to log in via Incognito Mode
- [o] Clear your browser cookies
- [o] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by geozukunft** [comment]
What exactly is your issue?

**Comment by jaehunkim0828** [comment]
It was an error that appeared when the account was deactivated. Activating the disabled account solved the problem.

**Comment by geozukunft** [comment]
Would you be so kind to close the issue please.
