### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by mario-panzera** [RiotGames/developer-relations#713]
_**Account Information**_
Summoner name: supermario64wii
Riot ID: super64wii#mario

_Have you played any of Riot's games or did you just create an account for the Developer Portal?_

I actively play TFT and the occasional ARAM

_**Issue Description**  
A clear and concise description of what the issue is._

When trying to log in, it says my account has been disabled. To my knowledge, I have never signed into the developer portal, and my riot account functions otherwise just fine.

_**What I've Tried**
What steps have you tried to resolve the issue._

- [x] _Log out of the Developer Portal_
- [x] _Attempt to log in via "Incognito Mode"_
- [bro i have so many dont make me do that] _Clear your browser cookies_
- [x but it was still chrome] _Attempt to login via a secondary device (mobile or different computer)_

_**Repro Steps**
_
1. Be me
2. Try to log into developer portal with normal riot account I use almost every day
3. Congrats you're probably seeing the same "account has been disabled" message I'm seeing

_**Issue Context**
Please add any additional context that is useful._

TFA isn't set up, I know sometimes that's required

**Comment by geozukunft** [comment]
if you got access then please close the issue so it doesn't stay open 👍
