### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by comjayoncloud** [RiotGames/developer-relations#719]
**Account Information**

riot id : darkhansa12
i played riot game + created account to use api token

**Issue Description**  
i have tried login on developer portal. but it says "You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter](https://twitter.com/RiotGamesDevRel), during office hours on [Discord](https://discord.gg/riotgamesdevrel), or create an [GitHub issue](https://github.com/RiotGames/developer-relations/issues/new?template=account_issue.md&title=%5BAccount%5D+)."

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1 , I try logging on developer portal
1. Step 2 , got message " i have tried login on developer portal. but it says "You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter](https://twitter.com/RiotGamesDevRel), during office hours on [Discord](https://discord.gg/riotgamesdevrel), or create an [GitHub issue](https://github.com/RiotGames/developer-relations/issues/new?template=account_issue.md&title=%5BAccount%5D+).""

**Issue Context**
I have several riot ids that have same issue with this. the riot ids are "darkhansa12", "darkhansa", I can log on league of legends homepage successfully, but in developer portal I cannot log on.

**Comment by lucasMesquitaBorges** [comment]
Hey @comjayoncloud I'm tackling old issues. Sorry for not answering this before.

Checking your account it seems to be in the correct state.
I'm assuming you fixed via player support or other riot channel.

If you still run into issues to use devportal, feel free to re-open this issue.
