### ISSUE TITLE
Hi riot, My name is Zieq and IGN name is John. Im playing Valorant and really love to play your other games. Last 2 month my account was suddenly got permanent banned by your system, you support said that im using third party software. Meanwhile im not using any hacks, cheats or script. I’ve spend almost 2 years playing valorant, and i do support you guys which means i buy Valorant Point to buy skin. Im very begging that ill get back my account. Right now i cannot do content at tiktok (stream). Ive lost 2 account :  My first account : RDT JohnZieq#chaa This 2nd account : Atilla#6969  I hope soo you guys can fixed this issues, i swear to god i never used any cheats or hacks. Please riot, i need my account back.  I also represented my state (Selangor, Malaysia) for Valorant Tournament and right now i cannot play your games anymore with the account.  Thankyou 🥲[Account] 

### ISSUE THREAD

**Issue by zieqazman** [RiotGames/developer-relations#721]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

**Issue Description**  
A clear and concise description of what the issue is.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by DarkIntaqt** [comment]
I would recommend you to close this issue and contact the player support. 
This GitHub repo is for bugs in an Riot Games related api, not for ban appeals. Also, the maintainer of this GitHub are currently on vacation, it would take several weeks to get any actions taken here (even tho I'm 100% sure they can't help you), so please get in touch the player support instead and close this issue to keep this repository clean. 

Wish you best luck on recovering your account and happy holidays!

**Comment by geozukunft** [comment]
support@riotgames.com or https://support.riotgames.com

**Comment by zieqazman** [comment]
> 

Already submit ticket at support valorant website, it looks like it didnt help to fix this out. Any solution? :(

**Comment by geozukunft** [comment]
Yes by closing this issue as this is 100% not the place for player support related stuff.
