### ISSUE TITLE
[BUG] DataDragon ARAM Clash queueId missing

### ISSUE THREAD

**Issue by DarkIntaqt** [RiotGames/developer-relations#722]
The ARAM Clash queueId is missing on here https://static.developer.riotgames.com/docs/lol/queues.json (should be 720)

Please add something like this into the queues.json file:
```json
{
        "queueId": 720,
        "map": "Howling Abyss",
        "description": "Clash games",
        "notes": null
}
```

**Comment by RiotTuxedo** [comment]
Updated. Thanks for the report.
