### ISSUE TITLE
[BUG] [LeagueEntryDTO] League Entry By Summoner returns Empty always

### ISSUE THREAD

**Issue by dcapape** [RiotGames/developer-relations#726]
**Bug Description**  
LeagueEntryDTO object is returned an empty array since 13.1.1 for any summoner

**Problem Description**  
API is not returning any data about summoners League status on [https://euw1.api.riotgames.com/lol/league/v4/entries/by-summoner/](https://euw1.api.riotgames.com/lol/league/v4/entries/by-summoner/)

**Expected Result**  
A filled object should be returned with Tier and Ranks for the summoner requested

**Actual Result**  
An empty array is returned []

**Developer Impact**  
I cannot get information about which Tier, Rank, Wins, Losses, LP's have any summoner 

* Frequency: Every API call. 
* Severity: My OBS layer has a leak of information
* Cost: Requires me to recode some classes to disable several functionalities to avoid crashes when information is requested
* User emails: I get frequent Discord messages for the information missing

**Player Impact**  
League of Legends players are not impacted

**Preconditions**  
To call the API (only tested on EUW1)

**Repro Steps**  

1. Get a encrypted ID for a Summoner by name https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/
1. Call https://euw1.api.riotgames.com/lol/league/v4/entries/by-summoner/ with the encrypted id retrieved on the last step.

**Comment by DarkIntaqt** [comment]
Ok ok that MIGHT be due to the announced ranked reset yesterday. Please check again in a few days when the first few summoners completed their placement games

**Comment by bangingheads** [comment]
Empty array means not ranked in any queue. You must be fully placed (10 ranked games) before your rank will show in the API.

**Comment by backend-ohdonghyeon** [comment]
The bug is currently being reproduced on Korean servers as well.

**Comment by bangingheads** [comment]
This is not a bug

**Comment by dcapape** [comment]
In that case I think an empty object should be returned instead of an array. Anyway, I close the bug.
