### ISSUE TITLE
[BUG] MATCH-V5  missing list of match IDS

### ISSUE THREAD

**Issue by GuinsooDild0** [RiotGames/developer-relations#728]
**Bug Description**  
When I use the API [/lol/match/v5/matches/by-puuid/{puuid}/ids](https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID) with this PUUID :  GcZuQrbJuFMH8T-52Xo-kfFGhFfifwflvVZ6oe6ZvY9d1zmwJKT7yjJ1dS-Dlmdu56iDt-E8raz0Qw with this parameter : 

start_time = 1641945600 #12 janvier 2022
end_time = 1653517404 #25 mai 2022
queue = 420 
start = 0 
count = 100 
EUROPE

I have find no match in the response body 

**Problem Description**  

The problem is that I have played ranked in this period. 
I have searched one of those games with friend's acc and I have found this one : EUW1_5725185585 where we can see my PUUID is here : and the gameCreation time is : 2022-02-11 20:21:22

 "metadata": {
        "dataVersion": "2",
        "matchId": "EUW1_5725185585",
        "participants": [
            "1DZ4eTyD2m-DPmfI-tM-zQWl-GvP3IlzHr0DPq4MDLSoR6LjXVolZVvCl_DqMoP8q4MSaCmWH2HKuA",
            "k4KRV-ZW0HPGCHA59ErCVqCogr5MFzipcUpVZPh_-c68O0ikP6PRDLgeHVBDwaBwGQjrwz9RuR-kJg",
            "WFiRqMqLWx-DDoNf0SZjySDWzQjbPEasJGID7tt5NqwyQ1omXGy0tDVocZ_ISGQ1U-uhUhttkiSHNg",
            "ETBMmYI4M8VGzeAjwcv8JFlLFmnYqSMlSvvJ2SdAW6a0OWLj6-WkdJxANH6EymzouIa8UmG11R-XLQ",
            "**GcZuQrbJuFMH8T-52Xo-kfFGhFfifwflvVZ6oe6ZvY9d1zmwJKT7yjJ1dS-Dlmdu56iDt-E8raz0Qw"**,
            "H5n3xS38KTfRc4MrUCWc1fDIJTKtSv49bOUG0uoBOmqO81rJHaoJbOZigMYY3D-ANs4lp9G0svCLHw",
            "TOmKTPKe6onkqYg-jshNHogZ5d3KnoMYXZNLXMeJ1Ak3Ci_t5iJ7tjxPZZiRDZ0KRZ-fQh1O9u7g3g",
            "5fzQB134iNdoZtfpTdbGKqxgWcoR7NigwM3hgtAKIK_ICmJ8I69POcC1oyMssrKEv12K1BUTVG3PoA",
            "ZY-enCh56dUjFIi5-3lEpqFJzqx0j0BejvhAs0oLOwG6YJK5eedZUdTvAuBkfqnqGeKnxlg7xxD-5w",
            "RRDifibQ-hLR2mtYipipGnaIy3bT0YP4ym-hLkp--KT2Q0KiKdP-xtdpx-j0LPiKkUd2_Yw18yAQSA"
        ]

**Expected Result**  

I am looking for the list of match IDS missing for my account : from 01/01/2022 (and before) to 01/06/2022 (aprox) 
Normal/Flex and ARAM games are missing too

Looking to understand why thoses games are missing and if it happens a lot of time ? 

**Developer Impact**  

It's a small projet only for me, so not much

**Comment by geozukunft** [comment]
Have you played more than 1000 games since then?

**Comment by GuinsooDild0** [comment]
Yes

**Comment by geozukunft** [comment]
That's the solution then. The match history only goes back for max 1000 games or 2 years whatever limit gets hit first

**Comment by GuinsooDild0** [comment]
Thx for the answer then, sorry it's I could have know that on my own. 
There is no solution to have retrieve those games ?

**Comment by RiotTuxedo** [comment]
The match itself gets held onto for 2 years, but the matchlist for each player is limited to 2 years or the last 1k like geo mentioned. If you know other players in the game and they haven't played more than 1k matches it might be in their match history. Or if you know the game id, you can look it up directly.

**Comment by GuinsooDild0** [comment]
Okay, rly thx for all those answer :o you guys are really nice. If I really want to find those games, can I try to randomly take plat/diam game until I got the list of match missing for my account ? will it be too long ?
