### ISSUE TITLE
[REQUEST] Position in the Leagues V4

### ISSUE THREAD

**Issue by honux** [RiotGames/developer-relations#73]
Is there any change that we could also get the player position whenever searching a league by league id?

eg:
https://kr.api.riotgames.com/lol/league/v4/leagues/02b21acc-7155-3e13-a409-609de4846bd3
<pre><code>    {
    "tier": "MASTER",
    <b>"position": "NONE",</b>
    "leagueId": "02b21acc-7155-3e13-a409-609de4846bd3",
    "entries": [ (...) ]
    }
</code></pre>

With the upcoming updates, allowing players to have more than one rank within a queue, I believe this feature would help all the players.

**Comment by RiotTuxedo** [comment]
Cleaning up house here. We've deprecated positional ranking so this request is no longer relevant.
