### ISSUE TITLE
[BUG] `tournament-stub-v4` 503s (`POST_registerProviderData`)

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#730]
**Bug Description**  
https://developer.riotgames.com/apis#tournament-stub-v4/POST_registerProviderData returns 503 on requests as of 2022/11/28 ([ci run](https://github.com/MingweiSamuel/Riven/actions/runs/3571320200/jobs/6003088646))

**Problem Description**  
A clear and concise description of what the problem is.

**Expected Result**  
`registerProviderData` should return 200 and the provider code

**Actual Result**  
503 service unavailable error

response headers:
```json
{
    "Date": "Sat, 21 Jan 2023 04:21:33 GMT",
    "Content-Type": "application/json;charset=utf-8",
    "Transfer-Encoding": "chunked",
    "Connection": "keep-alive",
    "X-App-Rate-Limit": "20:1,100:120",
    "X-App-Rate-Limit-Count": "1:1,2:120",
    "X-Method-Rate-Limit": "10:10,500:600",
    "X-Method-Rate-Limit-Count": "2:10,2:600",
    "X-Riot-Edge-Trace-Id": "8cf9ca5b-695b-412d-86a6-fe4c0a4068eb",
    "Content-Encoding": "gzip"
}
```

response body:
```json
{
    "status": {
        "message": "Service unavailable",
        "status_code": 503
    }
}
```

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call.
* Severity: I only use the tournament APIs for testing, so low impact for me. High impact for people who use tournament APIs as intended.
* Cost: N/A
* Efficiency: N/A
* User emails: None

**Player Impact** 
Any 3rd party service which uses the tournament APIs is likely affected?

**Preconditions**  
Always happens for me, on both dev and prod API keys

**Repro Steps**  
Post body:
```json
{
"region": "NA",
"url": "https://github.com/MingweiSamuel/Riven"
}
```
Click "execute request"

**Issue Comments**  

Side note, currently tournament regions are: `(Legal values: BR, EUNE, EUW, JP, LAN, LAS, NA, OCE, PBE, RU, TR)`. Curious if the garena regions (and/or korea) will ever be supported.

**Comment by OllieJennings** [comment]
All tournament-stub APIs are giving 503s non-stop

**Comment by OllieJennings** [comment]
@riotstillrampant / @riot-rmarin / @lucasMesquitaBorges or any Rioters able to help out here? we have an app that we want to move to using the production tournament API, but want to fully test on tournament stub first

**Comment by Token07** [comment]
> riotstillrampant / riot-rmarin / lucasMesquitaBorges or any Rioters able to help out here? we have an app that we want to move to using the production tournament API, but want to fully test on tournament stub first

You'll probably be better off just applying for access to the tournament API than waiting for stub to get fixed.

If you're not on the discord, here's a bit of info on callbacks if you're planning on using/relying on them:

> You can find more about tournament callbacks here: <https://developer.riotgames.com/docs/lol#tournament-api_server-callback>
If you are using https, it probably won't work due to a newer certificate in your chain, http is much more reliable. (If the certificate authority in your chain is issued after 2012 it won't work, there are very few issuers who fall into this category)
If you are using a newer uncommon TLD (something other than .com, .net, etc.) verify it is supported on the link above.
Tournament callbacks are only done when the game is fully complete, meaning the nexus has exploded.
You can test your callback endpoint using the sample data provided in the link above.

**Comment by OllieJennings** [comment]
@Token07 So actually already got the tournament access.

Basically just wanting to not spam the main tournament API and get blacklisted whilst doing some internal testing.

**Comment by Token07** [comment]
@OllieJennings It's been down since early December, maybe November. I wouldn't expect it to be fixed any time soon.

**Comment by x-Wawa** [comment]
Yeah already in November I was facing the same issuer and still no answer from the support

**Comment by wyvern800** [comment]
Still experiencing the same error

**Comment by wyvern800** [comment]
Any updates?

**Comment by MingweiSamuel** [comment]
Give it some patience, it's been broken for a long time

**Comment by tisbells** [comment]
Closing this out - Tournament Stub V4 was replaced with [Tournament Stub V5](https://developer.riotgames.com/apis#tournament-stub-v5).
