### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TeamSyncOffical** [RiotGames/developer-relations#735]
**Bug Description**  
Bypass Valorant Chat Restriction
by using unicode spoof you can bypass the chat restriction for VALORANT

**Problem Description**  
A clear and concise description of what the problem is.
Bypassing chat restriction could cause in way more toxicity in the game just by unicode spoofing the text you can bypass it!

**Expected Result**  
What were you expecting to happen after you performed the above steps? Include screenshots, logs, or a description.

For the swear word to actually bypass the chat restriction (which it did)

**Actual Result**  
What actually happened after you performed the above steps? Include screenshots, logs, or a description.

The message actually sent no chat restriction nothing no ****

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Everytime
* Severity: Causes more toxicity
* Cost: 0
* Efficiency: Not very efficent unless you want to be toxic?
* User emails: None

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

Causes more toxicity in the game, I have only tested this in VALORANT but I suppose it works for other riot games

* Frequency: No one really knows this bug I just found it out
* Severity: More toxicity
* Quantity: Every valorant player can get this
* Region: Tested in EU only
**Preconditions**  
What conditions must be met in order for this bug to occur?

* First condition
Going to a website for unicode spoofing then copying the unicode spoofed text and putting it in valorant chat
* Second condition
None

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Going to a unicode spoof website
2. Copying the text
3. Going into VALORANT chat and pasting it 

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

This spoofs the text and makes it so that it tricks VALORANT chat restriction which would cause way more toxicity

**Comment by Token07** [comment]
This is a game bug, and per the README here this is not the appropriate place to report it.

> - Verify that the issue you are about to report relates to the Riot Games Developer Ecosystem and is not a game bug (for game bugs please go [here](https://support.riotgames.com/hc/en-us)).
