### ISSUE TITLE
Match-v4 not respecting beginTime filter on NA1 [Resolved]

### ISSUE THREAD

**Issue by metamilo** [RiotGames/developer-relations#74]
When specifying a beginTime it returns results prior to that time.

working from the following link I used timestamp 1548327600 to filter for matches after patch 9.2
https://github.com/CommunityDragon/Data/blob/master/patches.json

The query looks like this:
`https://na1.api.riotgames.com/lol/match/v4/matchlists/by-account/QsGCstxmkWMaIMdTCZc8wJbOUAHi0-xVe1GggNzzvRGaCg?queue=470&beginTime=1548327600&endIndex=100&beginIndex=0

Here's a small portion of the response:
       ```
 {
            "lane": "NONE",
            "gameId": 2878300961,
            "champion": 161,
            "platformId": "NA1",
            "timestamp": 1538420274382,
            "queue": 470,
            "role": "DUO",
            "season": 11
        },
        {
            "lane": "NONE",
            "gameId": 2878252561,
            "champion": 161,
            "platformId": "NA1",
            "timestamp": 1538413918952,
            "queue": 470,
            "role": "DUO",
            "season": 11
        },
        {
            "lane": "NONE",
            "gameId": 2878250289,
            "champion": 6,
            "platformId": "NA1",
            "timestamp": 1538412000195,
            "queue": 470,
            "role": "DUO",
            "season": 11
        }
    ],
    "endIndex": 100,
    "startIndex": 0,
    "totalGames": 805
}
```
As you can see, it's returning games from before beginTime which shouldn't be the case.

**Comment by stelar7** [comment]
Your timestamp is wrong. (you need to `* 1000`)
