### ISSUE TITLE
[BUG] MatchV5 returning 0 for all "wardsPlaced" attributes (started in Patch 13.3)

### ISSUE THREAD

**Issue by mrdoowan** [RiotGames/developer-relations#740]
**Bug Description**  
All attributes with "wardsPlaced", "controlWardsPlaced", "stealthWardsPlaced", and "detectorWardsPlaced" is returning 0 for every MatchV5 request.

**Expected Result**  
The above attributes should have nonzero values (cuz I expect Master+ players to be placing wards in their solo queue games) for every participant. 

**Actual Result**  
![image](https://user-images.githubusercontent.com/11137073/218278260-228747bc-046e-415a-bada-146cd7e9f0d2.png)
![image](https://user-images.githubusercontent.com/11137073/218278271-4e12227e-ef2e-4c87-9b49-d0331573cd26.png)
![image](https://user-images.githubusercontent.com/11137073/218278292-7e0ce5ee-839b-477c-b74c-26e9d9d789a4.png)
![image](https://user-images.githubusercontent.com/11137073/218278306-bc1dcb0c-8575-4a7f-be5f-271c176e257e.png)

**Developer Impact**  
* Frequency: Every MatchV5 API call.
* Severity: Not severe.
* Cost: No cost.
* Efficiency: No efficiency sacrifice.
* Effect: No effect.

**Player Impact**  
* Frequency: Every time the user visits the site and clicks on a match, they experience this issue. Example with op.gg
![image](https://user-images.githubusercontent.com/11137073/218278406-4e841c74-6a07-425b-a95c-66ac22c66fab.png)
* Severity: Not severe, but it spreads misinformation that players don't place wards (kekw).
* Quantity: Every match in Patch 13.3 is affected.
* Region: Looks like every region.

**Preconditions**  
No preconditions. Just enter in a matchId and you'll see the error.

**Repro Steps**  
Just enter in a matchId and you'll see the error.

**Comment by geozukunft** [comment]
Can confirm the issue

Tags for easier searchability:
_GAMHS_
_match-v5_
_lol_
_wards_

**Comment by alfonsomartinde** [comment]
Confirmed +1 👍 
![image](https://user-images.githubusercontent.com/1211800/218478720-5c137731-82a6-4275-8028-e8645dbfd199.png)

**Comment by Klusio19** [comment]
Can confirm!
I just created smurf account, and there is one begginers mission, to place os destroy 10 wards. And The indicator can't move, after every match, everyone in my team and enemy team has 0 wards placed.
200 years of collective experience 😊

**Comment by trebonius0** [comment]
There is no WARD_PLACED event in timeline anymore too

**Comment by Chejose** [comment]
> There is no WARD_PLACED event in timeline anymore too

Confirmed +1

**Comment by riotstillrampant** [comment]
Fix is slated for the next release FYI, just verified this. Thanks for the reports, folks!

**Comment by mrdoowan** [comment]
As of Patch 13.4, it is fixed! Thank you @riotstillrampant <3
