### ISSUE TITLE
[BUG] Expired Certs on Data Dragon assets

### ISSUE THREAD

**Issue by stevezease** [RiotGames/developer-relations#741]
**Bug Description**  
Certain data dragon asset certificates have expired. 

**Problem Description**  
Attempting to access various data dragon files that start with `https://` lead to the error: `Your connection is not private...`, `ERR_CERT_DATE_INVALID`
For example:
https://ddragon.leagueoflegends.com/cdn/13.3.1/img/champion/AurelionSol.png
https://ddragon.leagueoflegends.com/api/versions.json
https://ddragon.leagueoflegends.com/cdn/13.3.1/data/en_US/item.json

**Expected Result**  
[What were you expecting to happen after you performed the above steps? Include screenshots, logs, or a description.]
Going to these links with the secure https:// URL, should not error out.

**Actual Result**  
The URL results in an `ERR_CERT_DATE_INVALID` error.

**Developer Impact**  
Affects many critical URLs that form the foundation for much of my codebase (many other developers are likely in the same situation).

* Frequency: Many but not all data dragon urls
* Severity: When it happens, my whole website crashes.

**Preconditions**  
None

**Comment by geozukunft** [comment]
Duplicate #591

**Comment by geozukunft** [comment]
The cert has been renewed please close the issue 🙂
