### ISSUE TITLE
[BUG] 503 - Service Unavailable

### ISSUE THREAD

**Issue by LeefGoblin** [RiotGames/developer-relations#746]
**Bug Description**  
Only for the API CALL spectator/v4/active-games/by-summoner/{encrypted-id} it return 503 - Service Unvailable

**Problem Description**  
Only for the API CALL spectator/v4/active-games/by-summoner/{encrypted-id} it return 503 - Service Unvailable
the other API work well; the API status page check is OK; the region is "EUW1"

**Comment by dcapape** [comment]
[/lol/spectator/v4/featured-games](https://developer.riotgames.com/apis#spectator-v4/GET_getFeaturedGames) is returning 503 error for EUW1 in my case

**Comment by DarkIntaqt** [comment]
Champion V3 is also throwing 503s

https://euw1.api.riotgames.com/lol/platform/v3/champion-rotations

**Comment by LeefGoblin** [comment]
Also reported on https://porofessor.gg/

_Due to a Riot outage (the spectator system) in some regions (EUW), live games data are currently unavailable on the website for those regions. The app is unaffected though. Sorry for the inconvenience_

**Comment by DarkIntaqt** [comment]
Seems resolved for me

**Comment by lucasMesquitaBorges** [comment]
This was caused after a maintenance in March, we made a announcement on twitter in the week it got out.
It's fixed now.
