### ISSUE TITLE
[BUG] `lol/clash/v1/tournaments` Always returns 500 for Korea

### ISSUE THREAD

**Issue by CurtisGreen** [RiotGames/developer-relations#747]
**Bug Description**  
When calling `kr.api.riotgames.com/lol/clash/v1/tournaments` it will always return 500 instead of a successful 200 like other endpoints

**Expected Result**  
I expect to see the current schedule for Clash in Korea or an empty array `[]` if there is none.

Example success response from region `br1`:
```json
[
    {
        "id": 93221,
        "themeId": 2,
        "nameKey": "bilgewater",
        "nameKeySecondary": "day_2",
        "schedule": [
            {
                "id": 88481,
                "registrationTime": 1678654800000,
                "startTime": 1678662000000,
                "cancelled": false
            }
        ]
    },
]
```

**Actual Result**  
Actual response from `kr`:
```json
{
    "status": {
        "message": "Internal server error",
        "status_code": 500
    }
}
```

**Developer Impact**  
This API issue does not allow me to display the current (or past) Clash schedule for users to the site.

* Frequency: Every API call
* Severity: Korean players cannot see their clash schedule

**Player Impact**  
Korean players cannot see their clash schedule, and their past clash games cannot be mapped to a given tournament (Ex: determine which clash rewards you have achieved)

* Frequency: Every time a user wants to see the korean clash schedule
* Severity: When this bug happens, korean users cannot use anything related to the clash schedule
* Region: This affects players in KR

**Repro Steps**  

1. Call `kr.api.riotgames.com/lol/clash/v1/tournaments`
1. Receive 500

**Issue Comments**  
Here is the current clash schedule in English, the next closest one is this weekend 3/11.
The schedule in English is here: https://www.leagueoflegends.com/en-us/news/game-updates/league-of-legends-2022-clash-schedule/
And korean here: https://www.leagueoflegends.com/ko-kr/news/game-updates/league-of-legends-2022-clash-schedule/

There are past clash matches for some users and there is a new clash schedule for korea so there should be a corresponding schedule like every other region

**Comment by lucasMesquitaBorges** [comment]
This issue was fixed for KR and it's now returning 200 responses.

Feel free to re-open or create a new issue if needed.
