### ISSUE TITLE
[BUG] [RSO] Error on refresh_token flow

### ISSUE THREAD

**Issue by dvf** [RiotGames/developer-relations#750]
This issue was pointed out by https://github.com/RiotGames/developer-relations/issues/673 but I wanted to re-open it because there are important privacy and security considerations. Namely:

1. We'll know when a user revokes access, and so we can preserve their privacy by destroying their data.
2. User details (like usernames) are kept up-to-date which makes it harder to impersonate users (since usernames can change).
3. Better management of active clients (on Riot's side).

## Context
As part of RSO on-boarding, we received a tutorial doc with steps to refresh the `access_token`, but it throws a `400` on the response.

**Request**
```http
POST https://auth.riotgames.com/token
Authorization: Basic b64(<client_id>:<client_secret>)

{
  "grant_type": "refresh_token",
  "refresh_token": "<refresh_token>"
}
```

**Response**
```
400
{"error":"unsupported_grant_type"}
```

Can someone from the team help shed some light here?

**Comment by f3ar161** [comment]
@dvf refresh token flow is disabled by default. You need to make a request via email.
