### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by eloguh** [RiotGames/developer-relations#753]
In MATCH-V5 -> Get a match timeline by match id

It does not return complete information about the wards placed by the players, in fact in the next game:EUW1_6289505428,  you can check that there is no ward placed and we all know that this is impossible, also if it tells you the wards that have been removed so it doesn't it makes no sense that they don't tell you which wards have been placed. This only happens in some games and I think it's a big mistake, since the information about the games is very incomplete, please answer and give a solution. I already reported the bug before and you ignored me, I am a data analyst in an amateur esports team and a data science student and this type of thing makes the LOL competitive system unable to develop, since there are no means to being able to make the club improve at low competitive levels. I insist please try the ID provided in MATCH-V5 -> Get a match timeline by match id field,  and see for yourself.

The ID provided is from the Europe region, please if not return answer my report, and I will provide you with another one that also returns the incomplete information about the wards.

**Comment by geozukunft** [comment]
Your game is very likely from before Patch 13.4 was deployed which fixed the bug that caused this. As you can see in issue #740 this bug has been fixed since the deployment of patch 13.4

**Comment by eloguh** [comment]
thank you so much
