### ISSUE TITLE
[BUG] Falsely receiving 400 Bad Request in Match-V5

### ISSUE THREAD

**Issue by fabiandiez** [RiotGames/developer-relations#759]
**Bug Description**  
`/lol/match/v5/matches/by-puuid/{puuid}/ids` returns 400 bad request stating it was unable to decrypt the summoner puuid when using an app key - selecting development keys for the exact same call in the API returns 200.

**Problem Description**  
I am receiving responses like the following from `/lol/match/v5/matches/by-puuid/{puuid}/ids`
```json
{
    "status": {
        "message": "Bad Request - Exception decrypting 6GgoMkABlqymeINn7Xb9G8FloSgC2A4w38f7IpcFnTugqOU_j58WpgdBcu6F63ymNkXlicng4fQvsw",
        "status_code": 400
    }
}
```
this happens ONLY when using app credentials - not using a development API key. The app has access to this specific endpoint, so permissions should be a non-factor. As this is reproducable on https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID the client is also not at fault here.

**Expected Result**  
Receiving the match history regardless of which API keys I select.

**Actual Result**  
Received an error stating the puuid cannot be decrypted - even though it was not changed in between API calls.

**Developer Impact**  
This currently blocks the development of my app. It happens on every single API call.

**Repro Steps**  
1) Head over to https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID
2) Enter a puuid, i.e. `6GgoMkABlqymeINn7Xb9G8FloSgC2A4w38f7IpcFnTugqOU_j58WpgdBcu6F63ymNkXlicng4fQvsw`
3) Select region `EUROPE`
4) Select an app to execute against instead of development API keys
5) Select include API key to either header or query param
6) Hit execute

I am receiving the response mentioned before at that point. If I switch back to development API keys, the request completes without an issue.

**Comment by fabiandiez** [comment]
Thanks, this makes sense! Is this documented anywhere? I don't think this information should be hard to find - one paragraph on https://developer.riotgames.com/docs/portal#web-apis_api-keys would have prevented the confusion.
Anyways, thanks for your help.

**Comment by Versifiction** [comment]
> IDs are encrypted per application.
> 
> You will need to gather new IDs from your personal/production application.

I'm facing the same issue but didn't understand your answer, what should I do ?

**Comment by geozukunft** [comment]
Hey there! So it seems like you stumbled upon the infamous case of the mischievous PUUIDs. These little fellas have a secret power—encryption. But not just any encryption, mind you. No, no, they're like chameleons of the digital world, changing their encryption based on the application they're associated with.

Think of it as a special encryption suit tailored exclusively for each app. Just like you wouldn't wear a tuxedo to a casual beach party (unless you're a very fancy penguin), PUUIDs don't like to mix and mingle between different applications. They're quite picky about their company, you see.

So, imagine this scenario: you have two apps, let's call them App A and App B. App A has PUUIDs encrypted using its own unique encryption key, and App B has PUUIDs encrypted using a completely different key. These PUUIDs are like sworn enemies, refusing to dance together in the digital ballroom.

Now, if you try to mix PUUIDs from different apps, it's like throwing a wild house party where everyone's wearing different costumes—total chaos! They won't recognize each other, and they'll just stand around, feeling awkward and confused. We certainly don't want that, do we?

To make things work, you need to fetch fresh PUUIDs from the new key for each specific app. It's like getting a new set of keys to a different castle. Each app has its own magical kingdom to unlock, and the PUUIDs are the secret keys that grant you access.

So, my friend, remember: don't play matchmaker with PUUIDs from different apps. They're not compatible, no matter how hard we try to convince them. Let them stick to their own encrypted realms and keep the digital peace.

Hope this lighthearted explanation clears things up for you! Happy coding, and may your PUUIDs dance gracefully within their designated applications!
