### ISSUE TITLE
[Account] Match-V4 Return 403 Forbidden

### ISSUE THREAD

**Issue by Camelllia** [RiotGames/developer-relations#760]
**Account Information**
Unfortunately, the tags on my Riot account are private, and I've been playing League of Legends since season 5 until now.

**Issue Description**  
I tried to use the Match V4 in the KR region but returns 403 Forbidden.

**What I've Tried**
1. I tried getting a Riot API key reissued.
2. I've tried both ways of putting the API key into a parameter or a header.

**Repro Steps**
1. Received a product type API key from Riot
2. AccountId has been obtained using the Product Type API Key in the API whose endpoint is **https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/{summonerName}**
3. The API KEY was inserted as a parameter for the URL whose endpoint is [https://kr.api.riotgames.com/lol/match/v4/matchlists/by-account/{accountId}](https://kr.api.riotgames.com/lol/match/v4/matchlists/by-account/{accountId}).
4. Even though the API key was the same as the one used in step 2, I was able to receive 403 Forbidden as a response in step 3.

**Step 3 Result**
`{
    "status": {
        "message": "Forbidden",
        "status_code": 403
    }
}`

**additional comments**
I wonder if the Match-V4 API I used in Step 3 has been terminated.
I've seen other people's code using the API up until recently on Github.
Why do I get 403 Forbidden even when using the Product Type API?

**Comment by Token07** [comment]
Match-v4 is no longer listed as a valid endpoint on the developer portal has been gone for nearly 2 and a half years. Use match-v5 as a replacement.

**Comment by Camelllia** [comment]
> 
thank you
