### ISSUE TITLE
[BUG] All APIs 502s 

### ISSUE THREAD

**Issue by geozukunft** [RiotGames/developer-relations#761]
**Bug Description**  
Still trying endpoints but as far as I can tell currently atleast all league related servers AMERICAS, ASIA, EUROPE, SEA and the platform endpoints are responding with Bad Gateway 502

**Problem Description**  
API response Bad Gateway 502

**Expected Result**  
Not have 502s 

**Actual Result**  
502s

**Developer Impact**  
Cannot use the API

* Frequency: Every API call. Across all endpoints
* Severity: Everything offline that needs access to the API

**Player Impact**  
Cannot use any services at the moment that need access to not yet cached data

* Frequency: Every time the user visits the site, they experiennce this issue.
* Severity: When this bug happens, a user is unable to use my site. This affects all websites so you know the numbers on how many people this affects.
* Quantity: Every player who uses a product using the API
* Region: This affects players globally.

**Preconditions**  
None 

**Repro Steps**  
1. Make a request to any League API endpoint.

**Issue Comments**  
Still trying to figure out if it affects more than just league but considering that it is all 502s I am assuming that the whole API infra is down.

Labels:
#API
#League
#Bug

**Comment by geozukunft** [comment]
TFT Endpoints are affected as well

**Comment by geozukunft** [comment]
Account-V1 is affected as well
For the VAL endpoints all platforms are affected as well
LOR Endpoints are down as well

**Comment by renja-grotemeyer** [comment]
I can confirm that

**Comment by geozukunft** [comment]
The API died at around 19:30 UTC according to my logs

**Comment by Nielsje7019** [comment]
yeah the API has been down for like an hour now but they will do there best to get it up again.

Also when the API is back up try to get your endpoints back you might not have 502's 😉

For now we all just have to be patient and the API status can be checked at anytime at: https://developer.riotgames.com/api-status/ 

Have an amazing day!

**Comment by geozukunft** [comment]
The API Status paged you linked has been out of date for more than 3 years by now. And is no longer correctly reflecting all endpoints 😉

**Comment by Nielsje7019** [comment]
> The API Status page you linked has been out of date for more than 3 years by now. And is no longer correctly reflecting all endpoints 😉

I see my bad 😂 Thanks for pointing it out to me i didn't noticed it before posting it lol But in any case i hope your issues may be solved soon

**Comment by lucasMesquitaBorges** [comment]
Hi, we are aware of the APIs went down and we're working to fix it ASAP.

Sorry for the inconvenience

**Comment by lucasMesquitaBorges** [comment]
The API is healthy again, I will keep monitoring it.
Thanks for everyone reporting on this

**Comment by geozukunft** [comment]
Looks healthy on my side as well. Will rename the issue so it is clear that it was all APIs that were affected. And close the issue for now and reopen in case it happens. 


Putting a request for maybe a post mortem on technology.riotgames.com here 😃
