### ISSUE TITLE
[BUG][Tournament-v4] Stats callbacks are not being sent after completed matches

### ISSUE THREAD

**Issue by zoltanzseli** [RiotGames/developer-relations#762]
Summary
We stopped receiving callbacks from the RIOT API after games were played today (2023.04.30).

Steps to Reproduce

Generate a tournamentId w/ a valid callback URL that can receive callbacks
Play a game with t-codes
Notice that the callback does not come via the valid URL

Expected Result
Expecting a callback from RIOT w/ stats to the callback URL provided

Actual Result
We are not receiving callbacks after games are played.

Reproduction Rate
100% (16/16)

Notes:
Please let me know if you'd like me to reproduce it on demand.

Severity:
High

**Comment by tisbells** [comment]
No exact timeline unfortunately, but we expect this should be resolved by early August.

**Comment by nexusacademypro** [comment]
If just query the player using match-v5 and filter for type TOURNEY and then check the tournament-id as part of the matches response. Could that be how it works?

**Comment by seju-play-vs** [comment]
Any update on this? We're experiencing this issue as well, but our outage began on ~May 6, 2023.

**Comment by Vexrax** [comment]
+1 We started seeing this issue this week aswell with some of our newer tournaments that we created

**Comment by tisbells** [comment]
Heyo, I have an update! Tournament-V4 will be replaced by Tournament-V5 on October 11, 2023. Check out our blog post for more details. https://www.riotgames.com/en/DevRel/tournament-v5-is-coming

**Comment by lucasMesquitaBorges** [comment]
Closing because tournament-v4 was deprecated. Use tournament-v5.

If you have issues with tournament-v5, check the pinned: https://github.com/RiotGames/developer-relations/issues/828
