### ISSUE TITLE
[FEATURE REQUEST] A request to make player's account level available to fetch from the Valorant API

### ISSUE THREAD

**Issue by Xant1234** [RiotGames/developer-relations#765]
Hi,

my team and I are working on an application that uses RIOT's Valorant API. To bring our product to its full potential, we must be able to obtain `player's account level` from the API. Currently, there is no such data available. We need this data to make our anti-cheat system which will separate players who may be suspected of smurfing so as to ensure fairness for all our users.

Can we ask to add Valorant player's account level to the API? if yes, can you estimate the time needed to do so?

Thank you

**Comment by Token07** [comment]
This doesn't sound like a supported use case for the Valorant API.

**Comment by Xant1234** [comment]
What do you mean? I was redirected here from the Riot Games Third Party Developer Community Discord server when I asked where can I make a request to add more data to the Valorant API.

**Comment by RiotTuxedo** [comment]
First, ensure the developer relations team is aware you're running pay-to-enter challenges. Second, I'll look into adding account level to match details, it'll show the account level of a player before they started the match (so it'll always be one match behind) but it should be an easy way to expose this kind of data. I'll need to check with gameplay to ensure we're fine sharing this value, but short of that I'll see if I can get this added.

**Comment by Xant1234** [comment]
Hi @RiotTuxedo 

Thank you for your message and sorry for my late response as I was away last week.

We have been granted the green light to run pay-to-enter challenges in League of Legends and Valorant from the RIOT's developer relations team via the developer portal. Please let me know if you need proof so I can send you some screenshots of our messages.

Do you happen to have any updates on the account level of a player in VALORANT?

**Comment by RiotTuxedo** [comment]
It's going through product review now. Adding account level has implications for scouting and harassment that are being considered.

**Comment by Xant1234** [comment]
Okay, thanks for the update! I hope the review will be successful :)
