### ISSUE TITLE
[BUG] League match-v5 returns incomplete data for one game id

### ISSUE THREAD

**Issue by thebetioplane** [RiotGames/developer-relations#766]
**Bug Description**

Match ID `NA1_4654423727` seems to be missing data compared to other matches. In particular the only valid field appears to be `gameEndTimestamp`. The rest of the fields are empty strings, zero, or empty list.

**Problem Description** 

When I execute:

```shell
curl -H "X-Riot-Token: $TOKEN" -X GET 'https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4654423727'
```

The response after formatting is:

```json
{
  "metadata": {
    "dataVersion": "2",
    "matchId": "NA1_4654423727",
    "participants": [
      "EZ6k4HEyKwQtHwV2ANVmF4-wluUR8hEJpvBH7tTAadxcx9RwUU4w5Fmo6O--0be8ngZnYADYIzh2Ng",
      "R64HMSiJnn8aspQGan6GuVcyvM9_tv7_FBpTWrftr6S-mHOKgSrLqaf_nEF9D0mWlWzMoLb3gSCYWg",
      "XhmQoZazXaVg3GZCdNeZRy9Zn33nctmTBgH3uS6NClfkvgk41Ay-oWXggUOmBw2XDihaX_kUlsJf1g",
      "Z4D5u_xzbmEsIRMJu3N7eKP-zZtE8bUnkRPG4Av_52wLAl1AeffyOCTbm_t0xsQ4MWpDEbeeB0qrnQ",
      "0cEEOXbF4bgxAUg4tJwlXyR8HTMIS7uTyHBY-YD0KMYQSFvVCkY6WTtw0hlDu7soJ8LPdorpcJk8DA",
      "julPBaq31nVrNYk6KF9ZgoGd3eNlDm_VXhlO7VaphjyJD6Rxm0yhaA5W19BWYKILEQVlriYEl7a-FA",
      "KSvamCjtBlq-RyUO699JHIxoPA_ANNgf6Egkayo6kovftMrvBsoreK5oaHt4vlmR6Mvqd_GDAsj8fg",
      "5cice-EzJE25GTIKwJIsZS8Jmt_nSCh-JOMap9lGZFDzsJG2Hjhdk4Z0o9Rs059FSbwPnySbxhVUsQ",
      "sv6_CBDDxilAiO5KMcI_SL_YAMufVQQeVvftY7m9CSgLuCqcBT_c1Jydtz2VAWxyJt25eBc791v_Gw",
      "qB5SIYZEFKQrywjz25s4xr7RVXhvLu8bMC5-obvJ9FtoyvQiNGmzi50omL1fs3B0SlIVz8LnjoK1ZQ"
    ]
  },
  "info": {
    "gameCreation": 0,
    "gameDuration": 0,
    "gameEndTimestamp": 1683954964829,
    "gameId": 0,
    "gameMode": "",
    "gameName": "",
    "gameStartTimestamp": 0,
    "gameType": "",
    "gameVersion": "",
    "mapId": 0,
    "participants": [],
    "platformId": "",
    "queueId": 0,
    "teams": [],
    "tournamentCode": ""
  }
}
```

The participants list and `gameEndTimestamp` are the only correct values in the response.

**Expected Result**  

I would expect valid, non-zero fields. In particular, I have confirmed in the documentation that 0 is not a valid `gameId` or `mapId` but the other fields seem to be invalid as well.

**Developer Impact**  

* Impact: My application produced an error while trying to parse this response due to the missing information. I am unsure if requests missing a lot of data like this are intended behavior, or if the application should keep retrying the `matchId` assuming it would be eventually return a valid response.
* Frequency: It appears to just be this one game id. I haven't found another sample.

**Player Impact**

Users are unable to see the summary of this game.

**Issue Comments**  

_If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project._

**Comment by BlossomiShymae** [comment]
Same as issue #642 I believe.

You received a valid HTTP response but the match data is not (no need to retry). This happens when a game "breaks" so nearly all fields in `InfoDto` are set to default values. You can programmatically check using `gameCreation == 0` if the match is bad. :>

**Comment by thebetioplane** [comment]
Thanks for the info! It does seem to be a duplicate of that issue. On Twitter there is mention of server disconnects yesterday and today so that is probably the root cause.
