### ISSUE TITLE
[BUG] `champion-mastery-v4` started returning unencrypted PUUIDs

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#767]
**Bug/Problem Description**  
The `champion-mastery-v4` endpoints recently started returning an unencrypted `puuid` field in `ChampionMasteryDto` on some accounts:
* `champion-mastery-v4.getAllChampionMasteries`
* `champion-mastery-v4.getChampionMastery`
* `champion-mastery-v4.getTopChampionMasteries`
(`champion-mastery-v4.getChampionMasteryScore` only returns an int)

**Expected Result**  
The new `puuid` field should be encrypted like other PUUIDs, some base64 garbo.

**Actual Result**  
The `puuid` field contains a regular UUID.

**Impact/Preconditions/Repro**  
Not really a security problem besides for GDPR

* Frequency: Always or never depending on the summoner

Accounts with the bug: `ma5tery` on EUW or NA1
(Accounts without bug: `LugnutsK` on NA1, `ggoedarkintaqt` on EUW -- no "puuid" field is returned at all)

Probably something to do with how recently the account was played on or champion masteries were updated. 

---

This is also a docs issue since `puuid` isn't listed in `ChampionMasteryDto`'s docs :)

**Comment by geozukunft** [comment]
My expectation is that this is in preperation of adding puuids to the remaining league endpoints as requested in PR #708 so will for sure be interesting if we can expect a change to champion-mastery-v5 soon. Maybe @lucasMesquitaBorges can give us some insight there 🙂

**Comment by lucasMesquitaBorges** [comment]
Yes @geozukunft it's correct.
Thanks for the noticing of unencrypted PUUIDs being returned on `champion-mastery-v4`. The encryption was added some weeks ago.

I'm working to improve docs soon to cover `puuid` instead of `summonerId`. Right now even the endpoints by puuid have `summonerId` in swagger.

**Comment by lucasMesquitaBorges** [comment]
`puuid` added to the swagger docs in `champion-mastery-v4` endpoints.

**Comment by MingweiSamuel** [comment]
Thanks @lucasMesquitaBorges appreciate the transparency and work!
