### ISSUE TITLE
League byPosition returned incorrect results

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#77]
When i call the league/v4/positions API for summoner NA-Alicopter (UREwqFgK-MQdOAWRHlybSpRDxbiWFRmD1V6XAhmHe5Z1Ld0 with my encryptionkey) multiple times, I get different results (those two results in calls 1 second from each other)
![image](https://user-images.githubusercontent.com/14201457/51973097-2f9f6d00-247d-11e9-813e-b90dc34e61a1.png)
![image](https://user-images.githubusercontent.com/14201457/51973160-4b0a7800-247d-11e9-82c1-28fdb10bac9b.png)

(League Points are not the same / League Name is sometimes filled, sometimes it's not)

**Comment by stelar7** [comment]
related to #70?

**Comment by trebonius0** [comment]
i'm not 100% sure, thar's why i opened the issue

**Comment by RiotTuxedo** [comment]
Yep it's related. #70 was confirmed to be a bug and a deploy went out the other day to resolve it. I'm guessing you got different responses as this was being deployed. The second response with the *APEX* position, is correct.
