### ISSUE TITLE
[Account]  Help me evaluate whether it violates Riot's convention

### ISSUE THREAD

**Issue by LvBay** [RiotGames/developer-relations#776]
**Account Information**
I am a developer in Portal: FIREFIRE

**Issue Description**  
I saw this description at [Game Integrity](https://developer.riotgames.com/docs/lol#developer-api-policy_game-integrity): `Products cannot identify or analyze players who are deliberately hidden by the game.`

 I have some doubts about this:

A summoner has set a 'hidden record' in the game. If my product queries and display his record through the lcu api, does this violate Riot's convention?

**Comment by Token07** [comment]
This issue tracker is for issues with the API, not for inquiries. The appropriate piece to ask would be in an application on the developer portal or in the discord server linked in the README.

**Comment by LvBay** [comment]
> This issue tracker is for issues with the API, not for inquiries. The appropriate piece to ask would be in an application on the developer portal or in the discord server linked in the README.

I am more concerned about whether the usage complies with Riot's regulations, rather than the function of the API

**Comment by Token07** [comment]
> I am more concerned about whether the usage complies with Riot's regulations, rather than the function of the API

Then your issue is inappropriate for this bug tracker as you do not have a bug report that is in the scope of the developer relations team. As I previously said, the appropriate place to ask is the developer portal, which is where questions about 3rd party apps are handled and policy questions responded to authoritatively. The developer relations team members that are responsible for answering questions like this do not check nor respond to issues posted here.

**Comment by LvBay** [comment]
Ok I got it. BTW, is the developer portal always slow to respond? I submitted a product registration there and haven't heard back for over a week

**Comment by Token07** [comment]
> Ok I got it. BTW, is the developer portal always slow to respond? I submitted a product registration there and haven't heard back for over a week

It normally takes a week or 2 to get a response. Occasionally longer, especially if they're waiting on an response from a different team

**Comment by LvBay** [comment]
thanks
