### ISSUE TITLE
docs: league-v4.LeaguePositionDTO.position missing description

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#78]
super tiny issue

for LeaguePositionDTO

https://developer.riotgames.com/api-methods/#league-v4/GET_getAllLeaguePositionsForSummoner
shows

position | string | (Legal values: APEX, TOP, JUNGLE, MIDDLE, BOTTOM, UTILITY, NONE)
-- | -- | --

but the description is missing for https://developer.riotgames.com/api-methods/#league-v4/GET_getPositionalLeagueEntries

position | string | <empty>
-- | -- | --

Just needs to have the description copied over, many thanks 💌

**Comment by RiotTuxedo** [comment]
Should be updated now.
