### ISSUE TITLE
[Account] INVALID ACCOUNT

### ISSUE THREAD

**Issue by WhoIsBest** [RiotGames/developer-relations#782]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)? 
-> Whoisbest5v5

Have you played any of Riot's games or did you just create an account for the Developer Portal? 
-> I just created it for developing 

**Issue Description**  
A clear and concise description of what the issue is. 
-> Whenever it logged in successfully, a warning ⚠️ message is showing (see below 👇)

INVALID ACCOUNT
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter](https://twitter.com/RiotGamesDevRel), during office hours on [Discord](https://discord.gg/riotgamesdevrel), or create an [GitHub issue](https://github.com/RiotGames/developer-relations/issues/new?template=account_issue.md&title=%5BAccount%5D+).

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

-> Service is on product servers now
Https://who.is-best.net 
Please, fix the problem before a disaster

Ps. Thank you 🙏 for your help in advance 
Best regards
© Who Is Best, Inc.

**Comment by lucasMesquitaBorges** [comment]
Hey @WhoIsBest checking your account it seems to be in the correct state.

Did you manage to fix it via player support? Are you being able to access developer portal?
