### ISSUE TITLE
[BUG] Not really a bug but a request: Api for Queue information

### ISSUE THREAD

**Issue by ZeroKun265** [RiotGames/developer-relations#784]
**Bug Description**  
It would be cool if there was an api to get queue information when in the launcher, like queue time, queue mode etc..

**Problem Description**  
As linux does not have a clear way to get Discord RPC working the best solution is to use the local api to make calls about the match and then use something like pypresence to make a custom RPC for discord on linux.
The problem is that there is no way to tell wether or not someone is in queue or not, i tried both with local api and regular developer api.
I think it would be a nice to have, as it could bring a bit more parity between Linux and Windows players.
I personally forked a script from another to try and add this but then i discovered that it's not possible for now

**Expected Result**  
A simple endpoint like `https://127.0.0.1:2999/liveclientdata/queuedata` that returns 404 when in game and 200 when on the client not playing a game.
The response could contain something like
```json
{
    "inQueue": "yes",
    "queueType": "ranked-duo",
    "queueTime": 123456,
} 
```

**Developer Impact**  
To get parity between windows and linux discord RPC only this info would be needed, as images for the various gamemodes could be fetched elsewhere. I noticed that the local api only starts when the game itself does, so maybe it would be simpler to make a different api for the client that stops working when in game and works when no match is being played?
Still it doesn't seem too much of an issue both implementation-wise and as maybe cheating? as no valuable information is being exposed

**Player Impact**  
It would bring more parity between windows and linux gamers

**Comment by geozukunft** [comment]
The LCU is able to give you that information.

**Comment by ZeroKun265** [comment]
Oh that's fantastic. I couldn't find it, thanks.
I guess I'll use that then
