### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ducksauce13** [RiotGames/developer-relations#788]
C:\Users\Jesse\AppData\Local\Temp\PKM4729.tmp

**Comment by Token07** [comment]
https://support.riotgames.com

**Comment by AsatoDesu** [comment]
C:\Users\PC\AppData\Local\Temp\PKMEBF1.tmp

**Comment by DarkIntaqt** [comment]
/Applications/League of Legends.app/Contents/LoL/CLOSE-THIS-ISSUE.tmp

**Comment by tisbells** [comment]
Closing as there isn't enough information to tell what this is about.
