### ISSUE TITLE
docs: lol-status-v3.Translation incorrect "updated_at" -> "heading" field in documentation

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#79]
https://developer.riotgames.com/api-methods/#lol-status-v3/GET_getShardData

example call: https://euw1.api.riotgames.com/lol/status/v3/shard-data

For the `Translation` DTO, docs have:

NAME | DATA TYPE | DESCRIPTION
-- | -- | --
locale | string |  
content | string |  
updated_at | string

But it should be

NAME | DATA TYPE | DESCRIPTION
-- | -- | --
locale | string |  
content | string |  
__**heading**__ | string

**Comment by Querijn** [comment]
Result of that call: https://irule.at/riot/api/requests/12.json

This breaks my application due to the fact it generates structs from the swagger, which is based on the documentation.

**Comment by MingweiSamuel** [comment]
Hello, any updates on this issue?
```json
                                {
                                    "locale": "fr_FR",
                                    "content": "Nous avons désactivé les transferts pendant la préparation de la fin de saison classée. Les transferts seront de nouveau accessibles une fois les récompenses distribuées.",
                                    "heading": "Récompenses de fin de saison"
                                }
```

**Comment by MingweiSamuel** [comment]
Seems like #102 is related

**Comment by RiotTuxedo** [comment]
The documentation has been updated. Thanks for the report. Sorry about the delay on this.
