### ISSUE TITLE
[BUG] 404 response from get account by access token

### ISSUE THREAD

**Issue by hynnnnn** [RiotGames/developer-relations#790]
We are attempting to get user data from `/riot/account/v1/accounts/me` but regardless of what account I use I'm getting a 404 response. Specifically:

```
{
    "status": {
        "status_code": 404,
        "message": "Data not found - No results found for player"
    }
}
```

We have not changed any of our code, this endpoint has simply stopped working for us. Please advise.

EDIT: Upon further testing, only the accounts with riot IDs set up are able to be found by this endpoint. Is this required/intentional?

**Comment by f3ar161** [comment]
Hi @hynnnnn. We've made a validation with the team that owns this service. 

This is an expected response when a player doesn't have a riot id. 

Riot ID is required to use this service.
