### ISSUE TITLE
queues.json Arena queueId(s) are missing and map.json Arena mapId is missing

### ISSUE THREAD

**Issue by DarkIntaqt** [RiotGames/developer-relations#792]
---
# QueueIds

https://static.developer.riotgames.com/docs/lol/queues.json this file does not contain the queueId(s) for arena
## Expected 
```json
...
{
        "queueId": 1700,
        "map": "Arena",
        "description": "Arena",
        "notes": "Arena"
},
{
        "queueId": 1701,
        "map": "Arena",
        "description": "1v0 (Arena)",
        "notes": "1v0 (Arena)"
},
{
        "queueId": 1704,
        "map": "Arena",
        "description": "4v0 (Arena)",
        "notes": "4v0 (Arena)"
},
...
```
---
# MapId

https://static.developer.riotgames.com/docs/lol/maps.json should contain the mapId for arena (30)
## Expected
```json
...
{
    "mapId": 30,
    "mapName": "Arena",
    "notes": "Arena map"
 }
```

*Please note that I added these JSON examples by hand, they can contain spelling/syntax mistakes*

**Comment by tisbells** [comment]
We're looking into this!

**Comment by stelar7** [comment]
@lucasMesquitaBorges Most likely from cdragon https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/queues.json

**Comment by DarkIntaqt** [comment]
Got it exactly from there. However, I have not found a single game with these queueIds (1701, 1704) yet.

**Comment by geozukunft** [comment]
In a couple of days I should be able to confirm if they have been used at all.

**Comment by lucasMesquitaBorges** [comment]
Cool! Thank you all!
I will add the map and `queueId` 1700. Other two are of our internal environments. Cdragon probably got it from client.

If anyone find it in a match from API please let me know.

**Comment by lucasMesquitaBorges** [comment]
New map and queue were added.
