### ISSUE TITLE
[BUG][match-v5] Some Arena matches not returning arena-specific fields

### ISSUE THREAD

**Issue by gnardini** [RiotGames/developer-relations#793]
**Bug Description**  
There are a lot of Arena games in the Match-v5 API that don't have info about arena-specific things like teams, placement and augments. In these games half the players have `teamId` 100 and the other half 200. Fields `playerSubteamId`,  `subteamPlacement`, `placement` and all the augment ones are 0. There are a lot of other games that have proper values for all those fields and proper team ids (4 teams), so I'm wondering if it's possible to fix it for the other games.

As an example game_id that has this problem you can see KR_6604607115

**Developer Impact**  
Well I'm trying to process Arena games for a website I'm making (https://lolsociety.com/) and I have to throw away a large number of them because of this issue. It makes me spend processing power in useless games and I make a lot of requests to the API that are lost. It costs money to both of us basically.

**Repro Steps**  

Make a v5 API call in the Asia region with game id KR_6604607115 (I think the url is https://asia.api.riotgames.com/lol/match/v5/matches/KR_6604607115 ).
See that Arena-specific fields are empty, so it's not possible to determine who won or who is on what team.

**Comment by geozukunft** [comment]
Do you have any estimates how many games are affected by this issue?

**Comment by MingweiSamuel** [comment]
Seems to be the case for `EUW1_6511808246` as well

**Comment by gnardini** [comment]
I started to measure recently but so far about 70% of games have this issue while the other 30% have the proper fields. 

For those not on Twitter a Rioter said that devs are aware of the issue but made no promises on fixing it: https://twitter.com/CestDommage/status/1683519906673827843

**Comment by tisbells** [comment]
We're looking into this!

**Comment by f3ar161** [comment]
Hi @gnardini. We've made some research and updates about this issue. Could you confirm if you're still facing it??? if so, could you provide latest games ids about it???

**Comment by geozukunft** [comment]
I am unfortunatley not yet done with processing all Arena games globally but it seems to me that the original estimate of 70% of games is way to high. Out of 1.7mil games in euw1 between launch of Arena and 2023-08-17 I've only got 580 games with defective fields. vn2 same timeframe out of 1.1mil games ~1000 games with the bugged fields. 
By the end of the week I should be able to have processed the reminder of arena games in the smaller platforms and can give a conclusion if the issue is completely fixed. 

PS: If the person/team who fixed the issue has some spare time and maybe want/s to write a article for the techblog how that issue happend and how it was solved I think that would be pretty cool 😃

**Comment by f3ar161** [comment]
Hi @geozukunft Let us know about the final result!

**Comment by f3ar161** [comment]
@geozukunft I got the telemetry report from the team that owns this service, the current % games with this issue is <0.1%. There's not been any updates nor planned work around this so far, quick glance says it was 90 games out of 50000.

**Comment by geozukunft** [comment]
@f3ar161 That seems like a more reasonable amount. As said in the other message the number already seems far lower and more in line with the general amount of bugs present in match data generally

**Comment by geozukunft** [comment]
Hey @f3ar161 got the data for VN2 in the end with ~2.5 mil games we had 2247 bugged games. Means I can confirm the <0.1% of games with defect data. Altough they were present up until Arena was deactivated. I guess we'll see what happens when the gamemode comes back at the end of the year.

**Comment by gnardini** [comment]
I was only analyzing games in real-time and since Arena is no longer live I'm no longer analyzing Arena games, but happy to see error rate came down for when it comes back in December :)

I also wrote a workaround where if the data is not there I try to deduce the teams from the timeline info, which worked pretty well.
