### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Legen9s** [RiotGames/developer-relations#794]
**Bug Description**  
when loading screen apears it crashes and says error occurred: C:\Users\Intel\AppData\Local\Temp\PKM2251.tmp

**Problem Description**  
i cant get into the game

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

* Frequency: idk
* Severity: cannot play the game
* Quantity: idk
* Region: idk im in euw
* Etc

**Comment by DarkIntaqt** [comment]
Please report this issue [here](http://support.riotgames.com) and **close this issue**. Github isn't made for reporting in game bugs.  
Additionally, if you attach a file it would be quite cool if you send a bit more than the file path. No one can access a file based on its local path on your computer, that's not how the internet works.
