### ISSUE TITLE
[BUG] League-V4 not returning tier/division for CHERRY queue

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#795]
League-V4 is returning a response that does not include any real rank detail.

```
[
    {
        "queueType": "CHERRY",
        "summonerId": "5wegK53V4Cd0FWNcLUHacYXY0JZMWhXp4PlEQS7KDo5-ryuu",
        "summonerName": "GGoE DarkIntaqt",
        "leaguePoints": 0,
        "wins": 7,
        "losses": 11,
        "veteran": false,
        "inactive": false,
        "freshBlood": true,
        "hotStreak": false
    }
]
```

Ideally this would include the tier, division, and ratedRating for Arena.

**Comment by tisbells** [comment]
We're looking into this!

**Comment by lpturmel** [comment]
any news on this issue? Just want to assess whether I update my code in the meantime or leave it as is until the fix rolls out.

**Comment by tisbells** [comment]
@lpturmel This is still under review, I'd leave as is for now. Will post an update once I have one!

**Comment by tayebsaheb** [comment]
@tisbells following up on this, seems to still not be resolved. Also what is a cherry queue type and why is it happening for them only?

**Comment by f3ar161** [comment]
Hi @bangingheads The Arena mode right now does not include any rank details at the moment, for now it is not considered that the service will return this information.
