### ISSUE TITLE
[DOCS] match-v5 participant fields clarification  

### ISSUE THREAD

**Issue by geozukunft** [RiotGames/developer-relations#801]
As there are sadly no docs about most fields in the match-v5 I am putting this here as this was a question asked on the community Discord almost a year ago that nobody was able to answer:

What exactly do following fields store:
`totalHealsOnTeammates`
`totalHeal`

There are games out there like EUW1_6166633015 were totalHeal is smaller than totalHealsOnTeammates on champions.
Tested in a custom game the champion that got healed by another champion had the totalHeal field be 0 so totalHeal can't be all forms of self heals (totalHealsOnTeammates is sadly missing on customs data when fetched through the client) 

So the question here is exactly which types of healings from whom (teammates / items / abilites ) in which direction (from teammate to player or from player to teammates ) count for which of these 2 values exactly. 

scope: lol 
api: match-v5
topic: developer portal
topic: documentation

**Comment by tisbells** [comment]
This is what I received:
Whenever we apply positive health (which translates to all heals in the game but not things like regeneration) we increment `totalHealsOnTeammates` by the amount of health received.  This is post modified, so if you heal someone missing 5 health for 100 you will get +5 `totalHealsOnTeammates`
`totalHeal `-- as above, but includes healing enemies, jungle monsters, yourself, etc.

Hope this helps!

**Comment by geozukunft** [comment]
Thank you very much this helps a lot.
