### ISSUE TITLE
[BUG][FEATURE REQUEST] lolesports api bugs and suggestions

### ISSUE THREAD

**Issue by victti** [RiotGames/developer-relations#806]
Not sure if this is the right place to report bugs from the lolesports api (not the website) but doing it anyway. Even if its not the right place I hope it gets to whoever does the code there!

**Bug/Problem Description**  
The API has differents problems that haven't been fixed over years now:
 - Missing trincket: Some players have their trincket missing on the item list for the whole game or randomly disappears after a few minutes.
 - Missing Viego items: Every time Viego transforms into someone else he loses all his items and they never come back.
 - Missing minor runes: When a player selects two equal minor runes (Adaptive Force, Attack Speed, Armor, MR) only one is shown (for a total of 2 instead of 3).
 - Missing tear items: When an item that uses Tear of the Goddess is upgraded, the item disappears from the item list.
 - Some stats not working: Critical Chance and Tenacity values doesn't work.

**Suggestions**
- Remove Critical Chance and Tenacity from the stats as I'm pretty sure they don't work on the internal API itself as well.
- Add a totalDamageDealtToChampions stat to each player or to each team so championDamageShare can actually be meaniful. None wants to know the damage share of each player, their real damage is more meaningful than that.
- Add a stackingBuffs stat that shows Veigar, Senna and other champions stackable passives.
- Add the total XP of each player.
- Add the summoner spells of each player.

**Comment by Token07** [comment]
The lolesports API wasn't intended for public consumption (but its usage is allowed), so any support for it will be minimal.

**Comment by tisbells** [comment]
Closing this out as we do not support the lolesports API. I passed this feedback over to the owning team.
