### ISSUE TITLE
[BUG] Can't open "how to verify" document on the portal FAQ page

### ISSUE THREAD

**Issue by DarkIntaqt** [RiotGames/developer-relations#808]
The link https://docs.google.com/document/d/e/2PACX-1vRqj2TwTWhvbWzuzv25Rs9VPMnYlrn7ShHiepMAfTDlZiiUeI7gBkzQE6cwEOqY8lymXE_gMDO_SZnN/pub shown [here](https://developer.riotgames.com/docs/faqs#_verification-for-production-applications) is not available for me:
> You are not allowed to open this document

**Comment by tisbells** [comment]
Thanks for letting us know, we'll get this fixed.

**Comment by tisbells** [comment]
Hi! This was updated. Let us know if there are still issues opening this. https://developer.riotgames.com/how-to-verify-site.html

**Comment by geozukunft** [comment]
Works thank you

**Comment by DarkIntaqt** [comment]
It works, thanks a lot ^^
