### ISSUE TITLE
[BUG] Vanguard is banning agents if they have malware or virus on their computer

### ISSUE THREAD

**Issue by mu-revenge** [RiotGames/developer-relations#809]
**Bug Description**  
Me and a couple of people have already faced the issue but if you download any kind of malicious file on your computer, vangurd detects it as a "third-party software" and bans the players permanently.

**Comment by geozukunft** [comment]
Hey there,

Well, isn't that a creative excuse for getting banned? I must admit, blaming Vanguard for taking a stand against malware and viruses is quite the twist! Kudos for the ingenuity.

But fear not, intrepid gamer! Your quest for answers shall not go unanswered. It seems your plight has reached a point where the grand expertise of the Github community might not be enough. I present to you, drumroll please... the legendary realm of support.riotgames.com!

Yes, you heard that right. The land where issues are untangled, mysteries are solved, and excuses are, well, sometimes politely redirected. The mighty wizards of Riot Games Support are here to listen to your tale of woe and provide you with the guidance you seek.

So, gather your courage, dust off your antivirus armor, and embark on a journey to the support portal. There, you shall find the answers you crave, and who knows, maybe even a remedy for this peculiar case of "third-party software" banishment.

May your ban-free adventures continue, and may your malware-filled days be but a distant memory.

Best of luck,
geo

**Comment by tisbells** [comment]
Hi there - We are only able to address issues related to the API. Please visit player support for this issue. https://support.riotgames.com/hc/en-us
