### ISSUE TITLE
[DOCS] Emerald missing in docs page

### ISSUE THREAD

**Issue by meesvandongen** [RiotGames/developer-relations#813]
The following page https://developer.riotgames.com/docs/lol does not list the emerald league in the Icons and Emblems section.

**Comment by bangingheads** [comment]
More importantly these are the old emblems and do not include the new wing emblems.

**Comment by tisbells** [comment]
Thanks for pointing this out, will talk to the team about getting this updated

**Comment by zbee** [comment]
Any update available for this, even in terms of a possible timeline?

**Comment by tisbells** [comment]
Hey there, these were updated: https://developer.riotgames.com/docs/lol#getting-help-and-staying-up-to-date
