### ISSUE TITLE
[BUG] LeagueV4 - by-summoner returning empty array

### ISSUE THREAD

**Issue by victorhurchella** [RiotGames/developer-relations#819]
**Error description**
The endpoint `/lol/league/v4/entries/by-summoner/{encryptedSummonerId}` is returning an empty array with status 200.

**Problem description**  
I'm trying to get some information from the player, but the endpoint just returns an empty array.

**Expected result**  
Expected to return an array `Set[LeagueEntryDTO]`

**Actual result**  
Returned an empty array, with status 200.
![image](https://github.com/RiotGames/developer-relations/assets/104106268/a2e9197d-4a91-4cfe-aec9-b2128ab0f4cf)

**Developer impact**  
I cant get the information i need for my application to work properly, it happens on every call.

* Frequency: Every API call.
* Severity: When it happens, I can't figure out the player's tier to follow the flow of my application.

**Impact on players  
Describe how this affects League of Legends players. Include the frequency and severity of the problem.

* Frequency: Every time a user visits the site, they experience this problem. Every 100 or so visits, the problem occurs.
* Severity: When this error occurs, the user can't use my app, because I can't return which tier they fit into.
* Region: Affects BR1 players

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Do a GET in `/lol/league/v4/entries/by-summoner/{encryptedSummonerId}`

**Comment by bangingheads** [comment]
This is expected behavior.

As noted it is a set of league entries the summoner is currently ranked in. This will be empty if the summoner has not fully placed in any ranked queue.

**Comment by victorhurchella** [comment]
@bangingheads Got it, thanks for your attention
