### ISSUE TITLE
League data from previous seasons is still accessible

### ISSUE THREAD

**Issue by meeggteam** [RiotGames/developer-relations#82]
When i call /lol/league/v4/leagues/{leagueId} API using previous season's league id (e.g. 8c6da0a0-10c4-11e9-831e-c81f66e41892, KR), it still give me data.

I also reported it at discord #riot-api
https://discordapp.com/channels/187652476080488449/379429593829867521/544700005416435771

Thank you

**Comment by RiotTuxedo** [comment]
Talked with the team that owns ranked. They're okay with this behavior.
