### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by PMtHk** [RiotGames/developer-relations#821]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

I just created this account for dev portal 
riot id : pmthk

**Issue Description**  
A clear and concise description of what the issue is.

INVALID ACCOUNT
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter](https://twitter.com/RiotGamesDevRel), during office hours on [Discord](https://discord.gg/riotgamesdevrel), or create an [GitHub issue](https://github.com/RiotGames/developer-relations/issues/new?template=account_issue.md&title=%5BAccount%5D+).

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

Step 1 , I try logging on developer portal
Step 2 , got message " i have tried login on developer portal. but it says "You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter](https://twitter.com/RiotGamesDevRel), during office hours on [Discord](https://discord.gg/riotgamesdevrel), or create an [GitHub issue](https://github.com/RiotGames/developer-relations/issues/new?template=account_issue.md&title=%5BAccount%5D+).""

**Issue Context**
Please add any additional context that is useful.

I just created this id for using dev portals and using Riot APIs,
but from today, i cannot access the portal with these messages.

**Comment by Token07** [comment]
Check this page:
https://support-leagueoflegends.riotgames.com/hc/ko/articles/360044383973-%EC%A0%9C-%EA%B3%84%EC%A0%95%EC%9D%B4-%EC%9E%A0%EA%B2%BC%EC%8A%B5%EB%8B%88%EB%8B%A4-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC-%ED%95%98%EB%82%98%EC%9A%94-

**Comment by PMtHk** [comment]
Thanks @Token07
