### ISSUE TITLE
[DOCS][BUG] Undocumented `val-content-v1.ContentDto.totems` field

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#823]
Seems to only return an empty array right now, so no idea what type it is.

**Comment by MingweiSamuel** [comment]
#604

**Comment by tisbells** [comment]
Thanks for the feedback, will take this (and 604) back to the VAL team and see what I can find out. I'll comment back whenever I have additional info to share.

**Comment by MingweiSamuel** [comment]
Closing in favor of keeping everything in #604
