### ISSUE TITLE
Missing College From List For Job Application

### ISSUE THREAD

**Issue by BrettShadow4** [RiotGames/developer-relations#824]
I was looking to apply for the Software Engineer Internship but when asked for my college (Gateway Technical College), it's not there. Which prevents me from applying. When also looking for where to go to have this problem resolved, I just get led to customer support for game-specific problems. So I don't know if this is where I am supposed to go for this issue but if it could either get resolved or if someone could tell me where I am supposed to go for assistance that would be great!

**Comment by Token07** [comment]
This isn't something that Developer Relations can help with unfortunately. Player support is probably a better choice.

**Comment by BrettShadow4** [comment]
Ok, I will try player support. Thank you for the help.
