### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by FastRexx** [RiotGames/developer-relations#826]
FastRexx

Signing in to Riot Client
We're redirecting you now. You will be asked to open a link to Riot Client. its saying this but it wont work or log me in

asking for help. waiting. closing and reopening it.

**Comment by geozukunft** [comment]
Ah, the classic tale of someone lost on the way to Riot Client, desperately seeking guidance in the wrong neighborhood! 🗺️ Fear not, dear traveler, for your passport to Youbanistan is ready! 🎫✈️ It appears you've taken a detour to the GitHub repo, but this isn't the place for your login adventures. The realm of GitHub issues is reserved for API-related discussions and concerns, not individual game woes.

For assistance with signing into Riot Client, I suggest you contact the official support channels. They'll be your trusty guides on this quest. Safe travels, and may your login issues be swiftly resolved! 🌟🔑✨

Oh, looks like we have a ticket to Youbanistan in the making! 🎫✈️ It appears someone missed the memo that this chat is for Riot Games 3rd Party APIs-related discussions, not a tech support hotline for individual game issues. For technical difficulties with Riot Client, you might want to venture over to the official support channels, where the experts can assist you properly. We're here to discuss APIs, not troubleshoot your client problems. Safe travels to Youbanistan! 🌍✈️

**Comment by tisbells** [comment]
Hi - Closing this out as we can only address issues that pertain to the Riot public API. Please contact player support for other issues: https://support.riotgames.com/hc/en-us
