### ISSUE TITLE
[BUG] `champion-mastery-v4.getChampionMasteryScore returns 404 configuration error

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#830]
https://euw1.api.riotgames.com/lol/champion-mastery/v4/scores/by-summoner/<[Ma5tery](https://championmastery.gg/summoner?summoner=ma5tery&region=EUW&lang=en_US)'s encrypted summoner ID>

Returns
```
{
    "status": {
        "message": "Data not found - Server cannot locate endpoint - possibly a configuration issue",
        "status_code": 404
    }
}
```

Instead of
```
990
```

**Comment by tisbells** [comment]
Checking on this, will share updates when I receive them

**Comment by MingweiSamuel** [comment]
(Note that the by-PUUID version of this enpoint works as normal)

**Comment by lucasMesquitaBorges** [comment]
The score endpoint by summonerID was fixed.

Note that the champion mastery endpoints by summonerID are deprecated and will be REMOVED on December 15.

See https://twitter.com/RiotGamesDevRel/status/1729627427398410243 for more information!
