### ISSUE TITLE
[BUG] 503 - Service Unavailable when getting active shard from asia cluster

### ISSUE THREAD

**Issue by void-nick** [RiotGames/developer-relations#832]
**Bug Description**  
I have constant calls to the account API to get the active shard of Valorant players (https://asia.api.riotgames.com/riot/account/v1/active-shards/by-game/val/by-puuid/:puuid), but I get a lot of 503 responses only for this cluster.

**Expected Result**  
A 200 status code response with the active shard of a Valorant player.

**Actual Result**  
503 status code response.

**Developer Impact**  
There's a lot of jobs being queued for a long time since my system tests this cluster almost every minute. I can redirect the calls to another cluster, but it's gonna reduce my rate limit for that region.

* Frequency: Every API call. Once every ~5 API calls.
* Severity: When it happens, it slows my system.
* Cost: Forces the API rate limit of my app to be divided by two.
* Region: This affects players in AP and KR.

**Repro Steps**  

1. Make multiple calls to https://asia.api.riotgames.com/riot/account/v1/active-shards/by-game/val/by-puuid/:puuid for different puuids
2. Check status code and response data;

**Comment by tisbells** [comment]
Closing this out as we've had no recent reports of this issue. Feel free to reopen if you continue experiencing issues.

**Comment by void-nick** [comment]
> Closing this out as we've had no recent reports of this issue. Feel free to reopen if you continue experiencing issues.

It seems to be solved. I haven't seen the errors last weeks. Thanks
