### ISSUE TITLE
LoL Migration to Riot IDs

### ISSUE THREAD

**Issue by geozukunft** [RiotGames/developer-relations#833]
As was announced today in following post https://www.riotgames.com/en/news/summoner-name-riot-ID League is shifting away from summonerNames. 
Does this mean that all apps that have access to League endpoints will gain access to account-v1 or will summoner-v4 change to accepting Riot IDs with the name + tag instead of the summoner name? 
And if we get access to account-v1 does that mean that league will also finally support an active shard endpoint? 

labels:
api: account-v1
api: summoner-v4
scope: lol
scope: riot
topic: riot games api

**Comment by geozukunft** [comment]
https://twitter.com/RiotGamesDevRel/status/1713987675307524113

https://www.riotgames.com/en/DevRel/summoner-names-to-riot-id

**Comment by geozukunft** [comment]
Ok the question with the active shard endpoint remains otherwise I'll need to have the player enter gameName + Tag + Platform cause the blog post only mentions gameName + Tag

**Comment by DarkIntaqt** [comment]
> you can still ask for a region, however that defeats the purpose of a globally unique id

**Comment by geozukunft** [comment]
Copying this over from the lol-dev chat in Discord for the sake of completeness:

> I feel like this is a PSA for everyone so I'd prefer to keep it here instead of using app notes
> We have a key that has around 1.6x the rate limit on summoner-v4 (compared to account-v4) and that endpoint is per league shard.
> (We have 16 league shards with 1600 req/minute each and with the transition, we are expected to drop down to 3 clusters, 1k req/minute each)

> Are League keys expected to get rate limit increases to compensate for this change?

**Comment by geozukunft** [comment]
An additional thing I just noticed is that to be able to get the information that is provided in summoner-v4 like the profile icon or summoner level I am now forced to first call account-v1 and then summoner-v4 effectively doubling the amount of API calls needed to get the informatio. Which leads to longer execution times for the lookup of a single summoner. 

Is there any kind of solution planned for this? @tisbells

**Comment by RiotTuxedo** [comment]
Many of this feedback is specifically for the use case of looking up a player you haven't encountered before, right? Once you come across a player you should make future queries for that player by puuid and skip the account-v1 lookup.

This the ability to refresh a players profile icon and level is unchanged, but your ability to translate a riot id to a puuid has an account-v1 rate limit.

**Comment by geozukunft** [comment]
Correct this affects lookups of new players that are yet unknown/uncached.

**Comment by thomasmarton** [comment]
> This the ability to refresh a players profile icon and level is unchanged, but your ability to translate a riot id to a puuid has an account-v1 rate limit.

How about refreshing the player's name? 
Also in our example, we are talking about a higher rate limit multiplied by all league of legends shard. Once this change is out, we will have a lower rate limit and it'll only be multiplied 3 times (1 if we want to follow the recommendation and use the nearest cluster)

**Comment by RiotTuxedo** [comment]
Would have to follow up and see if the riot id will be cached and provided as part of the response from summoner service.

At the very least, the riot id is cached and provided in the response of match history. Which means you could do one or all of the following:

1. Refresh the riot id when a user manually clicks refresh
2. Refresh the riot id in the background on some interval
3. Passively look for a new riot id when processing matches

I believe the original article mentioned that a free name change is going from 1 month to 1 year so it should be less likely that a player changes their riot id.

Curious to hear about if there are other cases that might require frequent name lookups.

**Comment by geozukunft** [comment]
![image](https://github.com/RiotGames/developer-relations/assets/20288857/acd58b89-a00d-484f-ac07-f45222929eba)

Picture is from match data from 12 hours ago. The fields exist the data doesn't. Same case on PBE as well from a game I played just a couple of hours ago.

**Comment by thomasmarton** [comment]
>  believe the original article mentioned that a free name change is going from 1 month to 1 year so it should be less likely that a player changes their riot id.
> Curious to hear about if there are other cases that might require frequent name lookups.

As a player yourself, how would you feel if you changed name and you'd still be called your old name for months to come?
A more aggressive cache window just isn't the solution.

Having summonercore maintain an up-to-date version of someone's Riot ID can be a good alternative cause it offers us the same feature set we already have and optimize for, without any compromises.

Another thing to mention that was pointed out to me: We were the first post on /r/league for almost 3 days straight and we appeared on the LCS, both of them resulting in insane spikes in our traffic. With the new limits, we would've lost more than half of our new users from that day, resulting in really bad player experience (for something that is 100% outside our control). With our current limits and our caching solution, we were able to handle both of these traffic surges with ease.

Riot recommends us to smooth out our traffic and try not to cause any spikes. The name to ID endpoints are the only ones we cannot control, we need to be able to have spikes in the event of reddit hugs (or lolesports hugs?)

**Comment by DarkIntaqt** [comment]
> I believe the original article mentioned that a free name change is going from 1 month to 1 year so it should be less likely that a player changes their riot id.

Players can still rename using RP. It would be fatal to my apps when people look up their riot id and another profile shows up, as it is still in my cache, while these accounts renamed. 
That results in the question how long a riot id is blocked, when it comes to renaming away from it to be taken by another player?

**Comment by tisbells** [comment]
For DevRel visibility - RiotIDName + RiotIdTag was requested for `match-v5` (fields included but empty), `summoner-v4`, `spectator-v4` 
In these issues https://github.com/RiotGames/developer-relations/issues/837, https://github.com/RiotGames/developer-relations/issues/838, https://github.com/RiotGames/developer-relations/issues/834

**Comment by ElijahKSmith** [comment]
How will the Tournament callbacks change? Currently it only returns the Summoner Name as the means of identifying players in the match, will puuids or similar be returned instead?

**Comment by tisbells** [comment]
> How will the Tournament callbacks change? Currently it only returns the Summoner Name as the means of identifying players in the match, will puuids or similar be returned instead?

We're wrapping up how this will be handled and will post a wider communication once things are finalized. Will do our best to get this info out by end of week.

**Comment by tisbells** [comment]
> > How will the Tournament callbacks change? Currently it only returns the Summoner Name as the means of identifying players in the match, will puuids or similar be returned instead?
> 
> We're wrapping up how this will be handled and will post a wider communication once things are finalized. Will do our best to get this info out by end of week.

We now have a new endpoint for getting the PUUIDs! https://developer.riotgames.com/apis#tournament-v5/GET_getGames

This will provide the same payload of tournament callbacks + participant PUUIDs. You can also use this endpoint to check if the game was recorded and help debug callbacks. If the endpoint returns the game, it means a callback was attempted. Please let us know if any of you run into problems with this.

**Comment by ElijahKSmith** [comment]
> > > How will the Tournament callbacks change? Currently it only returns the Summoner Name as the means of identifying players in the match, will puuids or similar be returned instead?
> > 
> > 
> > We're wrapping up how this will be handled and will post a wider communication once things are finalized. Will do our best to get this info out by end of week.
> 
> We now have a new endpoint for getting the PUUIDs for Tournaments! https://developer.riotgames.com/apis#tournament-v5/GET_getGames
> 
> This will provide the same payload of tournament callbacks + participant PUUIDs. You can also use this endpoint to check if the game was recorded and help debug callbacks. If the endpoint returns the game, it means a callback was attempted. Please let us know if any of you run into problems with this.

This new endpoint probably closes issues like #663

**Comment by Querijn** [comment]
Got a bug that might be relevant: 

https://discord.com/channels/187652476080488449/379429593829867521/1173816311655174194

> Hello, i'm trying to get puuid from gameName and tagLine, but there is a case (as following figures) doesn't work. 
> 
> get puuid of Hide on bush (asia) by using summoner-v4 api. [does work]
> get gameName and tagLine by using accounts-by-puuid. [does work]
> get puuid using gameName and tagLine by using accounts-by-riot-id. -> 404 Error [DOES NOT WORK]
> 
> It works fine for the other summoners, but it returns 404 error for the case of  Hide on bush. I'd like to know if there are more unintentional (?) cases.

Sounds like the severity is fairly high, but I can't determine the priority since I don't know how widespread this problem is, nor what is causing it.

**Comment by tisbells** [comment]
Thanks @Querijn, I've raised this for review

**Comment by Querijn** [comment]
Got some additional information: A user determined that the cause is that the account-by-riot-id API ignores spaces for both tagLine and gameName. It appears that this inconsistency causes errors on the API side.

**Comment by ElijahKSmith** [comment]
> > > How will the Tournament callbacks change? Currently it only returns the Summoner Name as the means of identifying players in the match, will puuids or similar be returned instead?
> > 
> > 
> > We're wrapping up how this will be handled and will post a wider communication once things are finalized. Will do our best to get this info out by end of week.
> 
> We now have a new endpoint for getting the PUUIDs for Tournaments! https://developer.riotgames.com/apis#tournament-v5/GET_getGames
> 
> This will provide the same payload of tournament callbacks + participant PUUIDs. You can also use this endpoint to check if the game was recorded and help debug callbacks. If the endpoint returns the game, it means a callback was attempted. Please let us know if any of you run into problems with this.

Seeing an issue with one of my tournament codes on the new endpoint, the same value is being returned for all PUUIDs and it isn't a real PUUID. Is there something that might cause this? Wrote in my app messages which code we're seeing this on.

**Comment by tisbells** [comment]
@ElijahKSmith I relayed this issue and was told the new endpoint will only work for tournaments created after Nov 10 when the endpoint went live. Tournaments prior to this weren't recording the puuid so it would be null. We're updating the API swagger to reflect this as well. I've also reached out to you via app messaging if you think this doesn't quite cover what's going wrong for you.

**Comment by wonkyunglee-ps** [comment]
To add to @Querijn 's point, there is a summoner whose gameName is "Hide on bush" and whose tagLine is "KR1 " (with a space following the 1). This summoner is NOT EQUIVALENT TO "Hide on bush#KR1" (= Faker). Can a tagLine be created that ends with a space?

**Comment by wonkyunglee** [comment]
To add to @Querijn 's point, there is a summoner whose gameName is "Hide on bush" and whose tagLine is "KR1 " (with a space following the 1). This summoner is NOT EQUIVALENT TO "Hide on bush#KR1" (= Faker). Can a tagLine be created that ends with a space?

**Comment by ElijahKSmith** [comment]
> @ElijahKSmith I relayed this issue and was told the new endpoint will only work for tournaments created after Nov 10 when the endpoint went live. Tournaments prior to this weren't recording the puuid so it would be null. We're updating the API swagger to reflect this as well. I've also reached out to you via app messaging if you think this doesn't quite cover what's going wrong for you.

Hmmm that's strange, I have a mix of codes both working and not working from the same tournament that was created on October 13th, with all codes in that list being created between October 30 - November 7. I'll reach out in the app notes with more information.

**Comment by tisbells** [comment]
- **Space issue**: This should now be fixed, but let me know if this is still causing any issues. tagLines can include any unicode except `#`, including ending with a space. @wonkyunglee @Querijn 

- **Tournament-V5**: Thanks for the additional info, I'll see what they have to say on this and report back soon. @ElijahKSmith

**Comment by geozukunft** [comment]
I just tried creating an account with a tagline that contained emojis (which is a valid unicode char) that didn't work same goes for : * / \ ? ! which all didn't work either and I could only get the space working if it was encased in 2 alphanumeric chars

**Comment by sdomi4** [comment]
`%` is also not allowed it seems (which is a good thing, so please don't fix that)

**Comment by tisbells** [comment]
- **Unicode characters**: Raised these outliers and received corrected info that you may use any unicode _letter_. 

- **Tournament-V5**: @ElijahKSmith The team verified that the PUUID was in fact being recorded from early November before the endpoint was actually live. Once I get confirmation that they expect ALL matches from Nov 1 onward to have a real PUUID present, I will update the documentation on our site. 

Apologies for the confusion with these two items.

**Comment by Querijn** [comment]
[tft-league-v1](https://developer.riotgames.com/apis#tft-league-v1) does not have any endpoints for PUUID, only summoner ID. [/tft/league/v1/entries/by-summoner/{summonerId}](https://developer.riotgames.com/apis#tft-league-v1/GET_getLeagueEntriesForSummoner) might not be suitable for deprecation, since it's the only endpoint for getting league entries by summoner. Deprecating this means that there will be no way to get league entries by summoner.

**Comment by lucasMesquitaBorges** [comment]
@Querijn Right now, only the [/tft/summoner/v1/summoners/by-name/{summonerName}](https://developer.riotgames.com/apis#tft-summoner-v1/GET_getBySummonerName) was deprecated.

You can continue to use [/tft/league/v1/entries/by-summoner/{summonerId}](https://developer.riotgames.com/apis#tft-league-v1/GET_getLeagueEntriesForSummoner) for the flow you mentioned.

For the long term we are working to provide all endpoints `by-puuid` where we have the existing `by-summonerID`. This will also decrease the amount of requests you have to make in order to exchange puuid to summonerIDs.

**Comment by Gurimarukin** [comment]
I've came across this riot ID:
![image](https://github.com/RiotGames/developer-relations/assets/18679417/ed30cad0-7d6f-4966-aeec-2318d644e71d)

I see that the question of spaces in `tagLine` was discussed above.

I this expected behaviour?  
In my case, can `    IIIIIllllIIl#EUW` and `IIIIIllllIIl#EUW` be two different accounts? (Sorry for the poor barcode example ^^)  
If yes, I have an issue with of the trimming in my text input and my app's url :/
