### ISSUE TITLE
[BUG] match-v5 empty RiotIdName + RiotIdTag 

### ISSUE THREAD

**Issue by geozukunft** [RiotGames/developer-relations#834]
**Bug Description**  
The RiotIdName + RiotIdTag is empty.

**Problem Description**  
Both fields should contain their respective data in the match data. 

**Expected Result**  
Include the name and tag for every participant.

**Actual Result**  
The fields are included but are empty. 

**Developer Impact**  
In respect to the changes from moving from summonerNames to Riot IDs this will make it no longer possible to determine the players names based on the match data. Especially in context to what @RiotTuxedo said in #833 that one could update a players Name + Tag using match data. 

* Frequency: Every Match Data 
* Severity: Not able to save on API calls to account-v1 and starting Nov 20th not able to directly get the participants names by just getting match data.
* Cost: Need to do additional API calls to account-v1 which introduces additional costs both on my and Riots side.
* Efficiency: Makes the already in the future more inefficient system even less efficient.

**Player Impact**  
Players will see this impact if a website with non increased rate limits on account-v1 gets Reddit hugged or featured on big social media channels and thus get short but impactful bursts of new users thus leading to 429s/wait times for users when wanting to see their data.

**Preconditions**  
What conditions must be met in order for this bug to occur?

* Every game is affected there is no special precondition this is the case for live servers as well as PBE1

**Repro Steps**  

1. Fetch the match history of any player 
2. Get a matchId
3. Fetch the match data

labels:
api: match-v5
scope: lol
topic: riot games api

**Comment by RiotLizz** [comment]
Thanks for noting this. The game team is working to have this and should be resolved soon (end of week).

**Comment by tisbells** [comment]
Hey folks - This was more involved than we initially thought so it's taking a bit longer to get things resolved. Waiting on feedback from the owning team and will follow up here once we have more info.

**Comment by geozukunft** [comment]
It looks like it is working for PBE games again PBE1_4461884170

**Comment by geozukunft** [comment]
I assume this will go live with 13.23

**Comment by lucasMesquitaBorges** [comment]
Hi, new matches are now returning `riotIdGameName` and `riotIdTagline` filled!

**Comment by victorhaynes** [comment]
Yup I hit match v5 yesterday and it's working (old matches too IIRC.
