### ISSUE TITLE
[BUG] Region issue with dev site endpoint `Get account by riot id`

### ISSUE THREAD

**Issue by CurtisGreen** [RiotGames/developer-relations#835]
**Bug Description**  
On the developer website the [get account by riot id](https://developer.riotgames.com/apis#account-v1/GET_getByRiotId) endpoint has the option to select the "ESPORTS" region but doesn't have the option to select "SEA" like other endpoints.

![image](https://github.com/RiotGames/developer-relations/assets/9402065/ee10939d-d058-4ab6-bc88-4d9d470dae39)

**Expected Result**  
I expect to be able to select the SEA region

**Actual Result**  
I cannot select the SEA region

**Developer Impact**  
I cannot test this endpoint for the SEA region from the dev site

**Comment by Token07** [comment]
> There are three routing values for account-v1; americas, asia, and europe. You can query for any account in any region. We recommend using the nearest cluster.
