### ISSUE TITLE
[FR] spectator-v4 return riotIdName + riotIdTag

### ISSUE THREAD

**Issue by geozukunft** [RiotGames/developer-relations#838]
With summonerNames being phased out it would be nice to get the riotIdName + riotIdTag to replace the current summonerName field in the response of spectator-v4 and have those new values be represented in that endpoint.

labels:
api: spectator-v4
scope: lol
topic: riot games api
type: feature request

**Comment by lucasMesquitaBorges** [comment]
Hi! Unfortunately we have no plans to include RiotID's on spectator-v4 endpoints.
