### ISSUE TITLE
[BUG] TOURNAMENT-V5 Tournament code is invalid when you want to create the lobby

### ISSUE THREAD

**Issue by PetitPanda06** [RiotGames/developer-relations#839]
**Bug Description**  
We tried to create a lobby with a code from the TOURNAMENT-V5 api and we get the message "The Tournament code you have entered is invalid"

**Problem Description**  
We generated 3 tournament codes for a BO3 but it look like we couldn't create a lobby with ONE of the code. I tried the code directly in the developer portal and it look valid. I confirm we are on the TOURNAMENT V5 api and not the TOURNAMENT-STUB

Code in question : NA04cbd-a419d28d-95fd-4902-b142-16a185de14fa

Code look valid in the API but the whe we try to create a lobby it say the code is invalid.

**Expected Result**  
Lobby should be created and player able to join.

**Actual Result**  
Lobby is not created and we have a message  "The Tournament code you have entered is invalid"

**Developer Impact**  

* Frequency: Unknown - Will have more information as we use more tournament code
* Severity: Minor , the players can't start the match and we just generate a new code for them.
* Cost: No additional cost
* Efficiency: We need to create more tournament
* User emails: We get request from users that the tournament code is not working and need a new one.

**Player Impact**  
We use those codes in a small league. Currently, the player contact the admins of the league to get a new code when it's not valid.

**Preconditions**  
We are not sure of why the issue occurred. Most tournament code worked on our side.

**Repro Steps**  

1. Generate a tournament code with the TOURNAMENT V5 api
2. Use the code to create a lobby

Thank you

**Comment by bangingheads** [comment]
Relevant to be posted in #828

**Comment by tisbells** [comment]
Hey there - Are you still having issues creating lobbies with other tournament codes? We didn't see any errors on our end with the code in the description.
