### ISSUE TITLE
Season Filter in Match-V4 matchlists filter returns no matches

### ISSUE THREAD

**Issue by AP-Cohen** [RiotGames/developer-relations#84]
Utilizing the above pull results in a non-full response. For instance:

Going to this page: https://na1.api.riotgames.com/lol/match/v4/matchlists/by-account/(Summoner)?queue=420&season=11&endIndex=146&beginIndex=100&api_key= 

leads to:

https://irule.at/riot/api/requests/15.json 

When it should be leading to a more expansive matchlist. Was working up until this morning, not sure if anything changed.

**Comment by AP-Cohen** [comment]
I found the issue, the season has shifted; no sign of this anywhere else but I just ran some tests to see if there were any holes. Resolved I guess

**Comment by RiotTuxedo** [comment]
Internally the season is compared to timestamps, so when the configuration for those timestamps are updated the season can change. This is probably the best practice for third party developers as well. Specifically, to store the timestamp of a match and then compare it to a dictionary of timestamps for a season in a specific region.

**Comment by Colorfulstan** [comment]
> Internally the season is compared to timestamps, so when the configuration for those timestamps are updated the season can change. This is probably the best practice for third party developers as well. Specifically, to store the timestamp of a match and then compare it to a dictionary of timestamps for a season in a specific region.

Sooo... could we get a public list of those timestamps then? =)

**Comment by RiotTuxedo** [comment]
That's definitely a possibility, but we wouldn't be able to commit to providing future timestamps in a timely manner. It would likely be a manual process.

**Comment by RiotTuxedo** [comment]
I'm thinking about how to reformat the season constants to include this information.
https://developer.riotgames.com/game-constants.html

As a note, these aren't definitive timestamps, we may adjust them in the future to be more accurate.

```
seasonId 12
PRESEASON_2019
Default: Nov 13th, 2018 @ 12am UTC-8

OC1   Nov 12th, 2018 @ 5:05am  UTC-8
KR    Nov 12th, 2018 @ 7:05am  UTC-8
JP1   Nov 12th, 2018 @ 7:05am  UTC-8
RU    Nov 12th, 2018 @ 1:05pm  UTC-8
TR1   Nov 12th, 2018 @ 1:05pm  UTC-8
EUN1  Nov 12th, 2018 @ 3:05pm  UTC-8
EUW1  Nov 12th, 2018 @ 4:05pm  UTC-8
BR1   Nov 12th, 2018 @ 6:05pm  UTC-8
LA2   Nov 12th, 2018 @ 7:05pm  UTC-8
LA1   Nov 12th, 2018 @ 10:05pm UTC-8
NA1   Nov 13th, 2018 @ 12:05am UTC-8


seasonId 13
SEASON_2019
Default: Jan 24th, 2019 @ 12am UTC-8

OC1   Jan 23rd, 2019 @ 11:00am UTC-8
KR    Jan 23rd, 2019 @ 11:10am UTC-8
JP1   Jan 23rd, 2019 @ 11:10am UTC-8
RU    Jan 23rd, 2019 @ 4:00pm  UTC-8
EUN1  Jan 23rd, 2019 @ 6:00pm  UTC-8
TR1   Jan 23rd, 2019 @ 7:00pm  UTC-8
EUW1  Jan 23rd, 2019 @ 9:00pm  UTC-8
BR1   Jan 23rd, 2019 @ 11:00pm UTC-8
LA2   Jan 24th, 2019 @ 12:00am UTC-8
LA1   Jan 24th, 2019 @ 2:00am  UTC-8
NA1   Jan 24th, 2019 @ 3:00am  UTC-8
```
