### ISSUE TITLE
[BUG] Dev Portal Creating Personal Apps returns "Failed to create application"

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#840]
The developer portal is failing to create personal applications returning a "Failed to create application".

This happens no matter the app title, description, url, or game focus.

Production applications are unaffected.

**Comment by tisbells** [comment]
Having the team look into this now

**Comment by tisbells** [comment]
Hi - This seems resolved on our end if you would like to verify.

**Comment by bangingheads** [comment]
Works for me now thank you!

**Comment by PantengZhao** [comment]
wokrs for me now! thanks
