### ISSUE TITLE
[BUG] kr league v4 api isnt working

### ISSUE THREAD

**Issue by skotchdopolepet** [RiotGames/developer-relations#841]
**Bug Description**  
kr league v4 api isnt working

**Problem Description**  
i try to do a proper call and it just doesnt work. other regions (vn/euw/na) work almost flawlessly.
i had trouble with kr in the part week but it would solve itself in a minute.
this one is constant (more then an hour). 

**Expected Result**  
works - 200

**Actual Result**  
doesnt work
i get the code 503

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call. 
* Severity: my code doesnt work bcs of it :(  complete blocker

**Comment by tisbells** [comment]
Thanks for pointing this out, we'll take a look.

**Comment by skotchdopolepet** [comment]
it works now luckily, it was just buged before, its fixed somehow :) @tisbells
