### ISSUE TITLE
Kiran0329[Account]  has been hacked, I've been trying to contact support for two days, still no response, any devs or there or anyone who can help me

### ISSUE THREAD

**Issue by Kiran0329** [RiotGames/developer-relations#842]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

**Issue Description**  
A clear and concise description of what the issue is.

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by kodbilenadam** [comment]
> Ah, the classic tale of someone lost on the way to Riot Client, desperately seeking guidance in the wrong neighborhood! 🗺️ Fear not, dear traveler, for your passport to Youbanistan is ready! 🎫✈️ It appears you've taken a detour to the GitHub repo, but this isn't the place for your login adventures. The realm of GitHub issues is reserved for API-related discussions and concerns, not individual game woes.
> 
> For assistance with signing into Riot Client, I suggest you contact the official support channels. They'll be your trusty guides on this quest. Safe travels, and may your login issues be swiftly resolved! 🌟🔑✨
> 
> Oh, looks like we have a ticket to Youbanistan in the making! 🎫✈️ It appears someone missed the memo that this chat is for Riot Games 3rd Party APIs-related discussions, not a tech support hotline for individual game issues. For technical difficulties with Riot Client, you might want to venture over to the official support channels, where the experts can assist you properly. We're here to discuss APIs, not troubleshoot your client problems. Safe travels to Youbanistan! 🌍✈️
> Quote by @geozukunft

**Comment by Kiran0329** [comment]
The support isn't responding, can you please help me by any chance?

**Comment by Querijn** [comment]
Nobody here can help you.

**Comment by tisbells** [comment]
Hi! We are only able to support issues/questions relating to Riot's public API. Please reach out to [player support](https://support.riotgames.com/hc/en-us) for help.
