### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KevinIsYellow** [RiotGames/developer-relations#844]
**Bug Description**  
ISO recruitment XP bug

**Problem Description**  
I have been playing several match to grind Iso, it did show results, but every time I enter a new match and finish it, the XP counter resets back to zero, and it happened all the time

**Expected Result**  
The XP could be counted, because I want to play Iso as fast as I could. 

**Actual Result**  
What actually happened after you performed the above steps? Include screenshots, logs, or a description.

**Comment by geozukunft** [comment]
It's important to note that GitHub is not the appropriate platform for reporting in-game issues like the recruitment XP bug you're facing. GitHub is primarily used for tracking technical issues related to software development. For game-related problems, including the XP bug you described, it's best to contact Riot Support directly through their support website. They have a dedicated team to assist players with in-game issues and will be able to provide you with the most effective support. Please refrain from posting game-related problems on GitHub, as it's not the right channel for such concerns. Reach out to Riot Support, and they'll help you get back to your gaming adventures smoothly! 😊🎮
 
https://support.riotgames.com

**Comment by tisbells** [comment]
Closing this out as we are only able to support issues/questions relating to Riot's public API.
