### ISSUE TITLE
[Account] Invalid account

### ISSUE THREAD

**Issue by Seeyou2000** [RiotGames/developer-relations#848]
**Account Information**
My Developer Portal ID is vkdlxjshqk7
API Key was approved and used.

**Issue Description**  
I logged in to the Developer Portal, but the following error message occurred and I couldn't log in.
INVALID ACCOUNT
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on Twitter, during office hours on Discord, or create an GitHub issue.

**What I've Tried**
I changed it to save the api key in the env file because I think my account is blocked because I posted the API key publicly on GitHub.

- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
I'd like you to restore the funky account so I can work again using the api key.

**Comment by Token07** [comment]
[This will probably help](https://support-leagueoflegends.riotgames.com/hc/ko/articles/360044383973-%EC%A0%9C-%EA%B3%84%EC%A0%95%EC%9D%B4-%EC%9E%A0%EA%B2%BC%EC%8A%B5%EB%8B%88%EB%8B%A4-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC-%ED%95%98%EB%82%98%EC%9A%94-)

**Comment by tisbells** [comment]
We're looking into this for you.

**Comment by f3ar161** [comment]
Hi @Seeyou2000 to unblock your account pls go to this link and he proceeds to unblock it to unblock it 
[https://account.kr.riotgames.com/](https://account.kr.riotgames.com/)
