### ISSUE TITLE
[BUG] random 503 Service Unavailable - TFT V1, TW region

### ISSUE THREAD

**Issue by sisyphusla** [RiotGames/developer-relations#849]
**Bug Description**

Sometimes the response to a TFTV1 API request is 503. This occurs in the TW region and appears to be random, with no rate limit exceeded. I encounter a random 503 error regardless of whether I am using the DEVELOPMENT API KEY or the PRODUCTION API KEYS. On my website, I utilize the following APIs:
- `/tft/league/v1/challenger`
- `/tft/league/v1/grandmaster`
- `/tft/summoner/v1/summoners/by-name/{summonerName}`
- `/tft/league/v1/entries/by-summoner/{summonerId}`

**Problem Description**  

Most developers do not expect a 503 error and are often unprepared to handle it appropriately, resulting in repeated retries of the request.
I randomly tested by `/tft/summoner/v1/summoners/by-name/{summonerName}` the TFT API of several servers and found several routes that would return 503: `VN2 SG2 PH2 TH2 TW2`. 
And routes that normally returned 200: `BR1 KR OC1 JP1 NA1 TR1 LA1`

**Expected Result**  

- The API should work with a 200 response.

**Actual Result**  

- The API does not work. Error code 503 is received.

**Developer Impact**  

This issue consistently affects every API call, causing significant operational disruptions. The inability to process requests results in my code not functioning as intended. 

My member ID : 580899
APP ID : 651572

**Comment by JackWillz** [comment]
Confirmed also for SUMMONER-V4 for VN & TW

**Comment by xSoundbreaker** [comment]
Hello. Me and a friend are trying to create a bot but we are also getting error 503 for PH2. We are getting error 503 on the following APIs:

1) https://na1.api.riotgames.com/lol/summoner/v4/summoners/by-name/
2) https://na1.api.riotgames.com/lol/league/v4/entries/by-summoner/%7BsummonerId%7D
3) https://na1.api.riotgames.com/tft/league/v1/entries/by-summoner/%7BsummonerId%7D

**Comment by nhayhoc** [comment]
confirm in VN

**Comment by tisbells** [comment]
Hey there, we're looking into this and will let you know when we have updates

**Comment by exzib** [comment]
Also having this issue, eating up our queue workers due to retries :(

**Comment by f3ar161** [comment]
Quick update here, the root cause was probably due to some updated regions. Now everything is back to normal.
