### ISSUE TITLE
[BUG] Cannot create application on beta.developers

### ISSUE THREAD

**Issue by Satont** [RiotGames/developer-relations#850]
**Bug Description**  
I cannot create application on `beta.developer` portal with my app id.

**Problem Description**  
I get 
```json
{
    "httpStatus":  500,
    "errorCode":  "INTERNAL_SERVER_ERROR"
}
```

Response from riot api.

```
Request URL:
https://api.developer.riotgames.com/api/xdp/v1/rso-client
Request Method:
POST
```

**Expected Result**  
Should create

**Actual Result**  
I get 
```json
{
    "httpStatus":  500,
    "errorCode":  "INTERNAL_SERVER_ERROR"
}
```

Response from riot api.

```
Request URL:
https://api.developer.riotgames.com/api/xdp/v1/rso-client
Request Method:
POST
```
![image](https://github.com/RiotGames/developer-relations/assets/42675886/51225ae0-73ce-4dc7-afb0-21a1703505d4)

**Developer Impact**  

**Player Impact**  

**Preconditions**  

**Issue Comments**  
App id: `653921`.

**Comment by tisbells** [comment]
Hey there, we will take a look and see what's going on.

**Comment by f3ar161** [comment]
Hi @Satont  could you provide the application info, including the image url to validate that your data is correct? send this info to: **devrel-rg@riotgames.com**

**Comment by f3ar161** [comment]
Hey @Satont, I was doing some research and testing with your App ID 653921. I was able to create an app with out any problem. Probably the data your using is not correct or the image is corrupted in any case. Could you pls try again and if you face a similar problem send us the app info to make a deeper validation.

**Comment by Satont** [comment]
@f3ar161 it is just created rn with the same data i used before, i didn't change anything.
