### ISSUE TITLE
[BUG] 'Multiple' tagLine accounts

### ISSUE THREAD

**Issue by daedaluxs** [RiotGames/developer-relations#851]
It seems the first account with a gameName is both query-able under their *actual* tagLine, and na1 (on na1).
Both queries return status 200, however while the correct query returns puuid, gameName, and tagLine, querying with 'na1' generic only returns a puuid.
Creating other accounts with the same gameName do not have multiple tagLines.

This is problematic, as it is inconsistent. I highly doubt this is intentional, and can trip up 3rd party systems soon here.

I'd expect the query with the 'na1' generic to return nothing, or the same 'puuid, gameName, and tagLine' as a proper request.

Account-v1 /by-riot-id

**Comment by lucasMesquitaBorges** [comment]
Hi @daedaluxs thanks for reporting this issue!

We are working on this and as soon we have updates I'll let you know

**Comment by lucasMesquitaBorges** [comment]
Hey @daedaluxs this was fixed. If an account already have a set RiotID, requesting by the default of `summoner#region` will return a 404 status code
