### ISSUE TITLE
[BUG] sometimes gameName and tagLine are case-sensitive

### ISSUE THREAD

**Issue by trialo96** [RiotGames/developer-relations#856]
**Bug Description**  
Are gameName and tagLine case-insensitive or not?

**Problem Description**  
A clear and concise description of what the problem is.
![image](https://github.com/RiotGames/developer-relations/assets/67891553/5741e3c8-718d-4e77-9b76-b9fe9fe883a6)
```
{
    "puuid": "something",
    "gameName": "T1 Gumayusi",
    "tagLine": "KR1"
}
```
--> case-insensitive

can search summoner by case-insensitive gameName and tagLine

![image](https://github.com/RiotGames/developer-relations/assets/67891553/4eba50de-07a6-4853-8514-f3b09855a2fe)
```
{
    "status": {
        "status_code": 404,
        "message": "Data not found - No results found for player with riot id hide on bush#kr1"
    }
}
```

![image](https://github.com/RiotGames/developer-relations/assets/67891553/77b893c0-8bef-441a-aa08-a422cecda3be)
```
{
    "status": {
        "status_code": 404,
        "message": "Data not found - No results found for player with riot id Hide on bush#kr1"
    }
}
```
--> case-sensitive

not found ;(

![image](https://github.com/RiotGames/developer-relations/assets/67891553/9987b16e-99fd-435a-8a99-45e29ac1711c)
```
{
    "puuid": "something",
    "gameName": "Hide on bush",
    "tagLine": "KR1"
}
```

only exact match can search `Hide on bush`

**Expected Result**  
can search summoner by case-insensitive gameName and tagLine

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: not all times but for some summoners

**Comment by DarkIntaqt** [comment]
Hi, any updates on this? I got several user complaints that users weren't able to find their or a pros profile (e.g. faker, even mentioned above), just because the capitalisation was not entirely right. 
Would love to see this resolved ^^

**Comment by tisbells** [comment]
> Hi, any updates on this? I got several user complaints that users weren't able to find their or a pros profile (e.g. faker, even mentioned above), just because the capitalisation was not entirely right. Would love to see this resolved ^^

I've just sent a follow-up on this one - will let you know as soon as I have an update

**Comment by tisbells** [comment]
Hi! I've been told Riot IDs should be case-insensitive and we expect this is now resolved. Please let us know if this still seems to be a problem.

**Comment by trialo96** [comment]
Thanks! :)
