### ISSUE TITLE
[BUG] 2 brand colors are the same on the brand color page

### ISSUE THREAD

**Issue by meesvandongen** [RiotGames/developer-relations#859]
The brand colors on https://brand.riotgames.com/en-us/league-of-legends/color/ seem odd, with gold 2 and gold 3 having the same colors. I wonder if this is an oversight or an intended result. Could someone of the UI team clarify this?

I have a suspicion the right color is `#CDBE91`

**Comment by tisbells** [comment]
Hi, Developer Relations doesn't own this site, but we will pass this on to the relevant team.
