### ISSUE TITLE
Adding win/loss to Machlist endpoint

### ISSUE THREAD

**Issue by cohenu** [RiotGames/developer-relations#86]
**Background**
Everyone today looks at winrates and it is probably the most valuable stats you can have. Today in order to create a winrate for a summoner, the only option is through Matchlist (1) -> Match (20). This creates a lot of requests (21 per summoner) to the Match endpoint when it is very limited. Now let's say you have 10 summoners in a single game, this ends up with 21*10 = 210 requests.

**Possible solution**
Adding an indication to the Matchlist endpoint whether a summoner won or lost can massively decrease the number of requests needed to generate winrate. It turns out to be simply 1 request per summoner rather than 21.

**How I think it should look like:**
            [platformId] => EUW1,
            [gameId] => 3931425032
            [champion] => 83
            [queue] => 420
            [season] => 13
            [timestamp] => 1550221835761
            [role] => SOLO
            [lane] => TOP
            **[win] => true/false**

Feel free to add your suggestions and if you agree please comment!!

Thanks!

**Comment by Querijn** [comment]
Hey there,

I share your sentiment, but something you can do is cache results you have by game id, and check these before you make a request. This means you only look up a single game once.

**Comment by joshuaolufs** [comment]
I 100% support this.

I would suggest that you don't use a boolean for the value though since there are other valid ways for a game to end, like remakes or aborting for patches etc. Instead you should just use what the "/lol/match/v4/matches/{matchId}" endpoint uses [Win, Fail, Remake] or whatever to keep things consistent. It would only add 2 bits of data per record to have this.

**Comment by extrail** [comment]
Hey, is there any progress on this?
Sending match requests just to know if a player won a match or not is ridiculously inefficient.

**Comment by cohenu** [comment]
+1 on the progress question.
This feature will help reduce a-lot of our match requests and it will allow us to display more detailed data on season statistics.

**Comment by LewisLarsen** [comment]
Support this, whilst there are alternatives, this would make our lives easier.

**Comment by iaace-NA** [comment]
I don't think riot should spend resources to get this implemented. If you're going to display a match history for someone, it would also typically include data from `.../v4/matches/matchId` like K/D/A, cs, items, etc, which means that you'd have to pull data for each match anyway (the way things are done right now).

If you're going to implement this riot, don't make it a boolean value so our winrates will accurately account for remakes. (e.g. 'win' 'loss' 'remake', 'w' 'l' 'r', 0 1 2)

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported, feel free to re-open or comment if you feel this is in error.
