### ISSUE TITLE
[BUG] Developer Keys Return 403 on all endpoints

### ISSUE THREAD

**Issue by bangingheads** [RiotGames/developer-relations#860]
Using developer keys on all endpoints are returning 403. This is happening for me as well as others in the developer discord.

Production keys are unaffected.

**Comment by kimjongha99** [comment]
Please fix private key API call 403 bug.

**Comment by tisbells** [comment]
This has been escalated for review, will report back once we have updates

**Comment by tisbells** [comment]
A fix for this will be underway today. We'll post back here once we expect things to be resolved.

**Comment by tisbells** [comment]
Should be fixed now, please let us know if not

**Comment by kdebord-fhsu** [comment]
I have a project that uses the riot dev API code that is due on Tuesday, so I'm praying it will be fixed by then so I can show it to the professor.

**Comment by geozukunft** [comment]
It is already fixed.
