### ISSUE TITLE
[Account] account is in a funky state

### ISSUE THREAD

**Issue by jeondoh** [RiotGames/developer-relations#866]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)? developer ID = sideholic
Have you played any of Riot's games or did you just create an account for the Developer Portal? - i made developer protal account

**Issue Description**  
1. Log in to the developer site(https://developer.riotgames.com/) with my ID(sideholic) 
2. The error screen as below appears
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter], during office hours on [Discord], or create an [GitHub issue]

**What I've Tried**
What steps have you tried to resolve the issue.

- [O] Log out of the Developer Portal
- [O] Attempt to log in via "Incognito Mode"
- [O] Clear your browser cookies
- [O] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1 - immediately after logging in to developer.riotgames.com
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by Token07** [comment]
If the account you're trying to use is KR, check https://github.com/RiotGames/developer-relations/issues/848#issuecomment-1836859697

**Comment by jeondoh** [comment]
I activated my account again. Thank you
