### ISSUE TITLE
How can i get encrypted account id?

### ISSUE THREAD

**Issue by Lessyzz** [RiotGames/developer-relations#867]
I have an application for League of Legends. I get live game datas. As far as i understand (after riot id update) i need to encrypted account id, how can i get it?

**Comment by tisbells** [comment]
Hi! Please see our blog and documentation for help with Summoner Name to Riot ID. 
https://www.riotgames.com/en/DevRel/summoner-names-to-riot-id
https://developer.riotgames.com/docs/lol#summoner-names-to-riot-ids
