### ISSUE TITLE
[BUG] Sudden crash in VALORANT

### ISSUE THREAD

**Issue by VSinha25** [RiotGames/developer-relations#869]
**Bug Description**  
After disconnecting the headphones to change it, the game suddenly crashed.

**Problem Description**  
I removed and connected my headphones twice and, the first time my voice was reaching my teammates but I couldn't hear anything and the second time the moment I removed the headphones, the game suddenly crashed.

**Expected Result**  
I expected that first of all the game shouldn't crash for just removing the headphones from device and second the software should be fine no matter ho many sound devices are managed.

**Actual Result**  
Read problem description

**Comment by Querijn** [comment]
This is not Valorant's support, you need to make a ticket over at https://support.riotgames.com

**Comment by tisbells** [comment]
Hi, we can only help with things relating to Riot's public API. Please visit [player support](https://support.riotgames.com/hc/en-us) for game crashes.
