### ISSUE TITLE
[BUG] Riot login does not work

### ISSUE THREAD

**Issue by blteblte** [RiotGames/developer-relations#873]
[??] So after few hours of searching where the heck I could report such an issue, I found at least something where anyone would actually read it - github. I understand this is not a place, but where one could actually find the one?

**Bug Description**  
Riot login form (https://authenticate.riotgames.com/) throws error 400 after login with the following response body:
```
{
    "type": "error",
    "error": "invalid_request",
    "country": "lva",
    "captcha": {
        "type": "hcaptcha",
        "hcaptcha": {
            "key": "019f1553-3845-481c-a6f5-5a60ccf6d830",
            "data": "y8nj5eOdQuQCnDSEVh/sz1VEZD/WTiW+6CjRn3Rfw1/VVxeKgHS5u/45oBtUJvt9jbihgFYd86Bat7BAESNJKuJU1MZS4ippRjShcshvBFduyE0RfF46P/g//gy0"
        }
    }
}
```

**The message displayed on UI**

Oops! Something went wrong
Sorry, we're having some trouble right now. Please try again.

**Devices**  
Chrome win10, Safari iOs (other not checked)

**Comment by tisbells** [comment]
Closing this out as we've received no other reports of this and it doesn't seem related to the developer portal or Riot API. If you continue to have login issues, please visit [Riot support](https://support.riotgames.com/hc/en-us).

**Comment by Jelles** [comment]
You cannot visit riot support you have to login... This issue is still here.

**Comment by Jelles** [comment]
You cannot visit riot support you have to login... This issue is still here.
