### ISSUE TITLE
[BUG][DOCS] `spectator-v4` docs `Participant` missing new fields `puuid` and `summonerId`, `CurrentGameParticipant` missing new `puuid`, docs still have removed (?) `FeaturedGameInfo.gameStartTime` field

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#879]
`Participant` docs (current)
  
Name | Data Type | Description
-- | -- | --
bot | boolean | Flag indicating whether or not this participant is a bot
spell2Id | long | The ID of the second summoner spell used by this participant
profileIconId | long | The ID of the profile icon used by this participant
summonerName | string | The summoner name of this participant
championId | long | The ID of the champion played by this participant
teamId | long | The team ID of this participant, indicating the participant's team
spell1Id | long | The ID of the first summoner spell used by this participant

Are missing these two fields:

Name | Data Type | Description
-- | -- | --
puuid | string | Encrypted PUUID. Exact length of 78 characters.
summonerId | string | Encrypted summoner ID. Max length 63 characters.

---

`CurrentGameParticipant` docs are missing `puuid` as well

---

Additionally, it seems the `spectator-v4.FeaturedGameInfo.gameStartTime` field is no longer returned

**Comment by AoshiW** [comment]
looks like the puuid is not encrypted for `CurrentGameParticipant`

**Comment by f3ar161** [comment]
hey Hi @MingweiSamuel docs are now updated.

**Comment by f3ar161** [comment]
this field **gameStartTime** comes in [getCurrentGameInfoBySummoner](https://developer.riotgames.com/apis#spectator-v4/GET_getCurrentGameInfoBySummoner)
