### ISSUE TITLE
Developer Portal email not verified

### ISSUE THREAD

**Issue by fronow** [RiotGames/developer-relations#882]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
#aeBas
Have you played any of Riot's games or did you just create an account for the Developer Portal?
I created the account only for the Dev Portal

**Issue Description**  
I have confirmed my email, yet the developer portal still indicates that my email is unverified

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x ] Attempt to log in via "Incognito Mode"
- [x ] Clear your browser cookies
- [x ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.
![image](https://github.com/RiotGames/developer-relations/assets/60842516/dec259c4-3643-48fa-82f4-fa8057b06cac)

**Comment by tisbells** [comment]
Hi there - we're looking into this issue.

**Comment by lucasMesquitaBorges** [comment]
Please try "Logout" and make the auth flow again. If the email is verified it should be enough.

Let me know if this fixes the issue
