### ISSUE TITLE
[Account] Unable to login to the developer portal

### ISSUE THREAD

**Issue by aikenahac** [RiotGames/developer-relations#883]
**Account Information**
What's your summoner name aikendev?
Have you played any of Riot's games or did you just create an account for the Developer Portal? Just for the developer portal.

**Issue Description**  
When attempting to log into the developer portal I get an error "Oops something went wrong". The response code for the login request is 400 and the response body seems to be related to the captcha (see attached images).

![image](https://github.com/RiotGames/developer-relations/assets/30961404/3c9474d4-f44e-44ea-83d3-d50b05542e95)
![image](https://github.com/RiotGames/developer-relations/assets/30961404/e8a96f5f-f0fb-43ce-b3b4-39e0e00f5e6b)

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Attempt to login to the developer portal.
2. Wait

**Comment by tisbells** [comment]
Hi there - we're looking into this issue.

**Comment by tisbells** [comment]
Hi! We need a bit more info. Please send us a message at https://support-developer.riotgames.com/hc/en-us, reference this issue and provide your full Riot ID in your submission.
