### ISSUE TITLE
[BUG] No results found for player with puuid

### ISSUE THREAD

**Issue by colin-jiang** [RiotGames/developer-relations#885]
**Bug Description**  
API doesnt return any gameName/tagline info for some puuids

**Problem Description**  
For rare cases, using /riot/account/v1/accounts/by-puuid/{puuid} endpoint returns puuid not found, below is an example
<img width="723" alt="Screen Shot 2024-01-31 at 5 39 54 PM" src="https://github.com/RiotGames/developer-relations/assets/24196322/fca7dbf4-e135-4c10-b432-e65a7f24fc4b">
<img width="997" alt="Screen Shot 2024-01-31 at 5 40 05 PM" src="https://github.com/RiotGames/developer-relations/assets/24196322/07893c04-a571-4d99-93df-6e3a496ebf6b">

This puuid was found in league-v4 ladder results, and also contains recent matches (last match 11 days ago)

<img width="719" alt="Screen Shot 2024-01-31 at 5 38 28 PM" src="https://github.com/RiotGames/developer-relations/assets/24196322/78096bcb-348f-4646-9ebb-3903263e11f3">
<img width="309" alt="Screen Shot 2024-01-31 at 5 38 38 PM" src="https://github.com/RiotGames/developer-relations/assets/24196322/4e884001-5e3e-4bee-b156-105c6b09a401">

Looked in most recent match data, and gameName/tagline is outdated in there

**Expected Result**  
Return gameName and tagline

**Actual Result**  
<img width="997" alt="Screen Shot 2024-01-31 at 5 40 05 PM" src="https://github.com/RiotGames/developer-relations/assets/24196322/25d474fb-5812-47b2-a835-505c2e444e4c">

**Developer Impact**  
Can't get a player's name

* Frequency: Only happens with this player

**Player Impact**  

**Preconditions**  
Specific puuid

**Repro Steps**  
Use /riot/account/v1/accounts/by-puuid/{puuid} for this puuid

**Issue Comments**

**Comment by tisbells** [comment]
Hey there, unfortunately we're unable to troubleshoot this instance since it is an isolated case. If this begins happening frequently feel free to reopen.
