### ISSUE TITLE
[BUG] [LOL] Tournament code - Error joining game

### ISSUE THREAD

**Issue by szunyogh** [RiotGames/developer-relations#888]
**Bug Description**  
The tournament code generated by the api (lol) doesn't work. If entered within the game, it returns an error message: "Error joining game"

**Problem Description**  
It also applies to codes generated on the Riot Games api page 
https://developer.riotgames.com/apis
https://developer.riotgames.com/apis#tournament-v5/POST_createTournamentCode
The region: EUNE

**Comment by tisbells** [comment]
Hey there, we're aware of this issue and it is actively being worked on. I don't currently have an ETA on a fix, but we'll let the community know as soon as we have more info.

**Comment by tisbells** [comment]
This is still being worked on, but here is a temporary workaround:

Requirement: At least one person must successfully make it into the tournament game lobby. If the code fails for all players, you will still need to use custom lobbies for now or generate an alternate tournament code. 

If some players are unable to join the tournament lobby via tournament code, here is how they can all get into the tournament lobby together:

1. The players that can’t get into the lobby send friend requests to a player that has successfully joined the lobby.
2. The player(s) in the lobby accept the friend requests
3. The player(s) in the lobby invite the other players to the lobby

**Comment by tisbells** [comment]
Hey there, some updates were made with patch 14.4 yesterday. Is this issue still occurring for you?

**Comment by szunyogh** [comment]
@tisbells Unfortunately, it's still not good.

**Comment by Butcovetc** [comment]
Same situation - generated code by TOURNAMENT-V5. User are not able connect lobby using it. 
Region: EUNE
Error: The tournament coed you have entered is invalid.

**Comment by tisbells** [comment]
Hey there, additional updates were made yesterday that should have resolved the tournament issues for all regions. Would appreciate if some folks could test it out and let me know if things still seem bugged.

**Comment by Butcovetc** [comment]
Hello, 
evrething is working perfect for me. 

Thank you for a updates.
