### ISSUE TITLE
Problem with /lol/match/v4/matchlists endpoint

### ISSUE THREAD

**Issue by d-obuchowski** [RiotGames/developer-relations#89]
Hi
I have problem with "/lol/match/v4/matchlists/by-account/{encryptedAccountId}." endpoint.
That endpoint returns one of matches(with match_id "2130474730") where the user did not take part.
Is that a bug ?
name of summoner: "In The End"

**Comment by Querijn** [comment]
Hey there, 

I recommend adding your region with your request. that match id could be on any server, but only one gives the correct result.

Your summoner had a namechange, but his summoner id still matches; he's participantId 10.

This is no bug.

**Comment by d-obuchowski** [comment]
ok, thank you for your response
