### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by gabrieleribotta** [RiotGames/developer-relations#891]
I'm new to this so i don't really know how it works but if i execute this code:
`fetch("https://europe.api.riotgames.com/riot/account/v1/accounts/by-puuid/PUUID?api_key=API_KEY", { 
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
      "Accept-Language": "it-IT,it;q=0.7",
      "Accept-Charset": "application/x-www-form-urlencoded; charset=UTF-8",
      "Origin": "https://developer.riotgames.com"
    })
    .then((data)=>dati.json())
    .then((test)=>{
      answer=test
    })`
    with the right api key and puuid i get the "failed to fetch" error and this in the console: 
`Access to fetch at 'https://europe.api.riotgames.com/riot/account/v1/accounts/by-puuid/PUUID?api_key=API_KEY' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
I wonder what is the problem.
Thanks in advance

**Comment by DarkIntaqt** [comment]
Please don't send requests over a website to the api, as this would expose your API key to the public. You need to have a server in between, that does the requests for you. You can use a library and expressjs for that or cloudflare workers. 

**This GitHub is for bugs with the api, not for understanding problems.** Could you please close this issue and join the [discord](https://discord.gg/riotgamesdevrel) for any further questions?
