### ISSUE TITLE
[BUG] Spectator mode not working for either client or command line

### ISSUE THREAD

**Issue by uncgopher** [RiotGames/developer-relations#892]
**Bug Description**  
When trying to spectate a game, in any Riot-supported region, the game is never launched and remains with a black screen. This happens regardless of trying to launch spectator mode from the client (right clicking on a friend and clicking spectate) or from the command line (e.g. TrackingThePros or OP.GG).

**Problem Description**  
The observer API endpoint (example: http://spectator.kr.lol.pvp.net:8080/observer-mode/rest/consumer/getGameMetaData/KR/2147483647/1881404841005357707/token ) responds with an error message stating "game metadata isn't found". 

**Expected Result**  
The observer API starts returning game data chunks so the client can start spectating the game

**Actual Result**  
Black screen and the endpoint returns an error.

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call. Once every ~100 API calls.
* Severity: When it happens, my whole website crashes.
* Cost: Requires me to run X more servers to compensate for the issue costing me on average $200 of additional spend a month.
* Efficiency: Requires me to make 10x more API calls than necessary to compensate for the issue.
* User emails: I get frequent emails from users asking me about this issue.
* Etc

**Player Impact**  
This has completely disabled the ability for anyone to spectate games.

* Frequency: Every time, every game
* Region: All regions

**Comment by uncgopher** [comment]
Quick update - I've heard second hand that some servers still have working spectator mode. Twitch.tv/SaltyTeemo is currently spectating games, but appears to only be in Turkey (and maybe Singapore + Japan).

**Comment by hackoh** [comment]
The client should be fixed.
2147483647 is the max value of integer so that's a bug of the client.
In only JP1 platform, the client uses correct game id (from what i've seen).

**Comment by domisum** [comment]
Even when starting the spectator client using the correct match number, the logs show that it is parsed as a 32 bit signed int and if the match number is above the maximum value, it defaults to the maximum value.

> 000000.988| ALWAYS| GameStartData::GameID=2147483647

The match numbers in regions TR and JP are below the max value, which is why they are the only regions with a working spectator feature.

This seems like a (newly introduced?) bug in the spectator client.

**Comment by tisbells** [comment]
Hey there, does this still seem to be an issue?

**Comment by uncgopher** [comment]
Everything appears to be working properly again after the patch and maintenance window, thanks!

**Comment by VinventN** [comment]
I have been getting the "unable to download spectator data error" for about a week now.  (EUW)

**Comment by tisbells** [comment]
Closing this out as spectating seems to be working as expected and we haven't received recent reports of Spectator issues. If you continue to experience issues, feel free to reopen or create a new issue.
