### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by dusdn0224** [RiotGames/developer-relations#893]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?

summoner name: 피아노의자
riot id: dusdn0224

Have you played any of Riot's games or did you just create an account for the Developer Portal?

I have an account for Riot

**Issue Description**  
A clear and concise description of what the issue is.

INVALID ACCOUNT
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter](https://twitter.com/RiotGamesDevRel), during office hours on [Discord](https://discord.gg/riotgamesdevrel), or create an [GitHub issue](https://github.com/RiotGames/developer-relations/issues/new?template=account_issue.md&title=%5BAccount%5D+).

**What I've Tried**
What steps have you tried to resolve the issue.

- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by tisbells** [comment]
Hey there, please visit this link to fix this: https://account.kr.riotgames.com/

[Support Article](https://support-leagueoflegends.riotgames.com/hc/ko/articles/360044383973-%EA%B3%84%EC%A0%95-%EB%B9%84%ED%99%9C%EC%84%B1%ED%99%94-%EC%9E%A0%EA%B8%88-%ED%95%B4%EC%A0%9C-%EB%B0%8F-%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4-%EC%97%B4%EB%9E%8C-%EC%95%88%EB%82%B4)

Let us know if this doesn't work!
