### ISSUE TITLE
[BUG] `match-v5` empty `riotIdName` on participants data

### ISSUE THREAD

**Issue by keelus** [RiotGames/developer-relations#899]
**Bug Description**  
The participant's `riotIdName` is empty.

**Problem Description**  
This field should contain the player's riot account's name, but the field is empty (the field `summonerName` is not empty, but it shows the player's old name, not the current riot name + tag system's one)

**Expected Result**  
The field `riotIdName` should contain player's riot account's name

**Actual Result**  
Participant's `riotIdName` field is empty.

**Developer Impact**  
Not being able to fetch other player's real riot name and tag when reading a match information, thus having to make a call per player by it's puuid to get it's riot name and tag.

* Frequency: Every match call.
* Efficiency: Requires me to make one API call per player (at least, for 9 players) to compensate for the issue.

**Player Impact**  
When using the app, the user would not be able to navigate to other player profiles from a game's information (at least if I dont do the x9 API calls to get the riot name).

**Preconditions**  
Every match that I have tried is affected by this (EUW1 live).

**Repro Steps**  
1. Fetch the match history of any player
2. Get a matchId
3. Fetch the match data

**Comment by DarkIntaqt** [comment]
hi, could you please provide a matchId?

**Comment by bangingheads** [comment]
Newer matches you are looking for ``riotIdGameName`` and ``riotIdTagline``

**Comment by keelus** [comment]
I see, in the API documentation appears `riotIdName` instead of the `riotIdGameName` so I was fetching the incorrect value, thank you!
Would be nice to have this updated though :)

[https://developer.riotgames.com/apis#match-v5/GET_getMatch](https://developer.riotgames.com/apis#match-v5/GET_getMatch)
