### ISSUE TITLE
SPECTATOR-V4 CurrentGameParticipant wrong documentation

### ISSUE THREAD

**Issue by ipatix** [RiotGames/developer-relations#9]
![grafik](https://user-images.githubusercontent.com/8502545/49194472-91f7c680-f383-11e8-97aa-912b380a2763.png)
The returned json for CurrentGameParticipant returns a string for the encrypted summonerId like you'd expect. The documentation is still outdated, though.

**Comment by ipatix** [comment]
Apparently this is also wrong for "PlayerDto" from the MATCH V4 API.

It's probably wrong in a few more placed I'd guess.

**Comment by jluzonpr** [comment]
Fixed these 2 instances. I tried 2 different formats and will make them be consistent later once I get feedback on what people feel is better and/or more intuitive.

**Comment by jluzonpr** [comment]
@Gchorba @Strebeck plz close

**Comment by Strebeck** [comment]
Closing Issue, thanks all.
