### ISSUE TITLE
[BUG] Developer Keys Return 403 on all endpoints

### ISSUE THREAD

**Issue by DarkIntaqt** [RiotGames/developer-relations#900]
Using a regenerated developer key is returning 403 on all endpoints. This is happening for me as well as others in the developer discord.
Tested for dev keys and personal keys. Too afraid to test with prod keys. 
Same as #860, but I think a new issue is more helpful than reopening an old one

**Comment by carlioso3000** [comment]
Im having exact same problem right now. None endpoints are working. All of them are returning a 403 as response

**Comment by norm4nn** [comment]
Same issue. I hope they will resolve it until Monday, cuz I have to show my project at uni.

**Comment by felipecomarques** [comment]
I'm having the same problem. I've already tried regenerating the key, and it doesn't work. Frustrating

**Comment by VkareGit** [comment]
I'm having the same problem. I've already tried regenerating the key and use some of the endpoints that  by looking into https://developer.riotgames.com/api-status/ should work but still got 403.

**Comment by DarkIntaqt** [comment]
> I'm having the same problem. I've already tried regenerating the key and use some of the endpoints that by looking into https://developer.riotgames.com/api-status/ should work but still got 403.

It’s not that the api is down, it’s just that new keys are invalid.

**Comment by norm4nn** [comment]
It seems that now instead of 403 - forbidden error, we are getting 400 - invalid token. Same for you guys or is it just my case?

**Comment by AoshiW** [comment]
> It seems that now instead of 403 - forbidden error, we are getting 400 - invalid token. Same for you guys or is it just my case?
I tested it now and everything works, try to generate a new token

**Comment by norm4nn** [comment]
> I tested it now and everything works, try to generate a new token
Regenerated, and I'm getting 403 error again ;/

**Comment by VkareGit** [comment]
> > It seems that now instead of 403 - forbidden error, we are getting 400 - invalid token. Same for you guys or is it just my case?
> 
> I tested it now and everything works, try to generate a new token

It works now for me too, I didnt even needed to regenerate my token.

**Comment by DarkIntaqt** [comment]
The issue is fixed for me too, can I close this issue or does anyone still has trouble?

**Comment by carlioso3000** [comment]
Fixed for me too

**Comment by wakakuriko** [comment]
is this bug happening again?
