### ISSUE TITLE
[BUG] 403 Forbidden with valid API keys

### ISSUE THREAD

**Issue by cjbdatasolutions** [RiotGames/developer-relations#901]
**Bug Description**  
Using valid, active API keys on any Riot API endpoint results in a "403 forbidden" response.

**Problem Description**  
This makes it impossible to develop applications dependent on any Riot API.

**Expected Result**  
A "200 success" response + applicable payload for the endpoint.

**Actual Result**  
A "403 forbidden" response + no payload.

**Developer Impact**  
I am unable to develop my application that depends on Riot APIs to be available and functioning correctly.

* Frequency: Every API call.
* Severity: When it happens no useful data can be obtained from any Riot API.
* Cost: Requires me to touch grass instead of become a billionaire not unlike Bruce Wayne.
* Efficiency: Requires me to submit a bug report for an issue the devs are and have been painfully aware of.

**Player Impact**  
This doesn't significantly impact League of Legends players outside of myself and any developers that are interested in using a node.js client library for Riot APIs.

* Frequency: Every time the user tries to hit a Riot API endpoint.
* Severity: When this bug happens angel's weep down tears from the heavens.
* Quantity: There are 2,000,000,000 users that are affected by this bug probably.
* Region: This affects anyone trying to use Riot APIs.

**Preconditions**  
What conditions must be met in order for this bug to occur?

* Have a Riot API key
* Make a request to any Riot API endpoint
* ????
* Profit

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Make a request to any Riot API endpoint using a valid API key to authenticate.

**Comment by geozukunft** [comment]
duplicate of #900 
also 2bil users?????????

**Comment by cjbdatasolutions** [comment]
"probably"

**Comment by geozukunft** [comment]
That would be 26,6% of the earths population btw.

**Comment by cjbdatasolutions** [comment]
I know right? Oh man we gotta get this fixed; and quick!

**Comment by geozukunft** [comment]
You can also just close this issue as it is a duplicate of #900 there is no need to have 2 issues for 1 problem.

**Comment by cjbdatasolutions** [comment]
You're right, that might actually be the root cause. If I close this bug
maybe it will work!!

**Comment by cjbdatasolutions** [comment]
Closing this bug out to help with the effort of resolving it.
