### ISSUE TITLE
getActiveMatchByTournamentCode

### ISSUE THREAD

**Issue by riccefarias** [RiotGames/developer-relations#91]
/lol/spectator/v4/active-games/byTournamentCode/{TournamentCode}

At this moment, to know if a Tournament game was started, i need to check every minute for each player of a team, and compare the participants, but... if i can get a match by code, will be possible to check with only one request.

**Comment by RiotTuxedo** [comment]
An endpoint already exists for this.

/lol/tournament/v4/lobby-events/by-code/{tournamentCode}

`
[
    {
        "timestamp": "1234567890000",
        "eventType": "ChampSelectStartedEvent" //Champ Select Begins
    },
    {
        "timestamp": "1234567890000",
        "eventType": "GameAllocationStartedEvent" //Loading Screen Begins
    },
    {
        "timestamp": "1234567890000",
        "eventType": "GameAllocatedToLsmEvent" //Game Begins
    }
]
`

**Comment by riccefarias** [comment]
I cant access it if the tournament wasnt created from my app?

**Comment by RiotTuxedo** [comment]
Sure, but that's by design. If you happen to know which participants are in a given tournament match there are sub-optimal ways to achieve the same result but the goal of tournaments is to stream line the process for tournament providers.
