### ISSUE TITLE
[BUG] Riot Login with Passwordmanager: Redirected to Facebook

### ISSUE THREAD

**Issue by JonnyBDev** [RiotGames/developer-relations#911]
**Bug Description**  
Using the central RIOT Login (https://authenticate.riotgames.com/) with a password manager and auto-fill turned on results in a redirect to Facebook instead of logging in with the provided credentials.

**Problem Description**  
I am using a password manager for my credentials. I am using Keeper with the "Autofill" option for forms. While visiting the the login form described above, Keeper fills out my username and password and is trying to submit the form. That's where the problem occurs. It seems like my password manager detects the "Facebook" login button as submit button instead of the actual one. Unfortunately I can only speak for myself with Keeper but this results in a loop of redirects to Facebook with the only option to disable the autofill or spamming the ESC key to stop the redirect.

I am aware that this is not an actual "bug", more likely an unwanted sideeffect of incorrect naming of a button class. Would be good to know if other password managers face the same issue here.

**Expected Result**  
Expected result would be to use the provided credentials and login instead of getting redirected to Facebook.

**Actual Result**  
My password manager is using the Facebook button as submit button instead of the actual submit button.

**Developer Impact**  
* Frequency: Every login to Riotgames if using password manager with autofill
* Efficiency: Requires me to workaround the functions of my password manager

**Player Impact**  
* Frequency: Every login to Riotgames if using password manager with autofill
* Severity: Users with not much IT background could find it difficult to login if they are using a password manager

**Preconditions**  
Using a password manager. I am using Keeper in the latest version with Autofill for forms activated

**Repro Steps**  
- Setup the credentials in your password manager
- Activate "autofill forms"
- Visit the login of Riotgames

**Issue Comments**  
As mentioned above I haven't tested the behaviour with other password managers. If you, the reader, are using a different password manager feel free to contribute your experience to this issue.

![image](https://github.com/RiotGames/developer-relations/assets/20868670/8ed3bffa-4024-486b-b3af-523dd0984b5d)

**Comment by DarkIntaqt** [comment]
While this might not actually be related to this repo, I had these issues too. Several times, also from logging in on the devrel portal

**Comment by JonnyBDev** [comment]
> While this might not actually be related to this repo, I had these issues too. Several times, also from logging in on the devrel portal

Thought about putting it into this repo or not. But I think it fits the description of **"The purpose of this repo is exclusively bug reporting for tools in the Riot Games Developer Ecosystem."**

If not feel free to correct me and send me some other links where I could submit this issue. But it's good to know that you are having the same problem with another password manager.
