### ISSUE TITLE
[BUG] Dropped TFT matches from match history (/tft/match/v1/)

### ISSUE THREAD

**Issue by whyando** [RiotGames/developer-relations#919]
**Bug Description**  
Some TFT games are missing from match history. (/tft/match/v1/)

* Frequency:
Unfortunately I don't have a lot of additional context but at least two users reporting the same issue so far

* User impact:
Their matches are not showing up in match history sites

* Severity
Severity is low unless more players are affected but wanted to make a report anyway

* Details

For this user (euw1 Nälgazz#EUW), from the api their most recent games are:
[
    "EUW1_6922141981",
    "EUW1_6921884438",
    "EUW1_6917767554",
    "EUW1_6917709186",
    "EUW1_6917680714",
]
EUW1_6922141981 (3rd place / 2 hours ago)
EUW1_6921884438 (2nd place / 11 hours ago)
EUW1_6917767554 (8th place / 3 days ago)
EUW1_6917709186 (2nd place / 3 days ago)
EUW1_6917680714 (8th place / 4 days ago)

In the screenshot from the user, we see the first and last games are present, but not the middle two.

![Capture_decran_2024-04-30_014431](https://github.com/RiotGames/developer-relations/assets/934217/1579d312-84f8-47bf-b706-d61646431fae)

**Comment by tisbells** [comment]
Hey there, we're looking into a couple other reports of missing TFT matches to see if there is an underlying issue, but the matches you referenced above we were able to find in match history. I'll post back here if I get additional info.

**Comment by tisbells** [comment]
Closing this out as the team was able to confirm TFT match history is working as expected.
