### ISSUE TITLE
[BUG] /userinfo endpoint not returning cpid

### ISSUE THREAD

**Issue by SidiaDevelopment** [RiotGames/developer-relations#920]
**Bug Description**  
I am asking for the cpid scope on SSO authorization, then request the /userinfo enpoint for that user and expect a cpid value, since a few weeks ago it is not returning that value anymore.

**Problem Description**  
I am building my authorization link like this: 
```js
 return authorizeUrl
        + "?redirect_uri=" + encodeURI(redirectUrl ?? "")
        + "&client_id=" + clientId
        + "&response_type=code"
        + "&scope=openid+offline_access+cpid"
        + "&state=" + secret
        + "&prompt=login";
```

But the user is neither asked if he wants to offer his cpid information, nor is it returned.

**Expected Result**  
I am expecting a "cpid" value from the /userinfo endpoint

**Actual Result**  
No "cpid" value returned

**Player Impact**  
Players outside of EUW cannot register with the app because of this. EUW players can only do that because we currently fallback to EUW1 as a value if we dont get one returned

**Repro Steps**  
 - Send user the authorization link
 - user grants authorization
 - request `/userinfo` endpoint
 - see missing `cpid` value

**Comment by tisbells** [comment]
Hey there, we're looking into this. Can you please send us your app ID/RSO client ID [here](https://support-developer.riotgames.com/)?

**Comment by SidiaDevelopment** [comment]
Submitted my IDs, Ticket ID is 101210028

**Comment by f3ar161** [comment]
Hey hi @SidiaDevelopment this issue is solved. could you confirm your having the cpid back?

**Comment by SidiaDevelopment** [comment]
> Hey hi @SidiaDevelopment this issue is solved. could you confirm your having the cpid back?

I sadly cannot really test this as now the league-v4/by-summoner is now returning 503 which is breaking the app flow, ill log the result of /userinfo seperately later

**Comment by SidiaDevelopment** [comment]
Users from other regions than EUW1 can now register with the app again, so yes, it works, just EUW is down for now

**Comment by SidiaDevelopment** [comment]
The endpoint seems to have recovered and I can now confirm, everything working as expected!
