### ISSUE TITLE
[DOCS][BUG] New queue ID `1710` "Arena" missing in `queues.json` (2v2v2v2v2v2v2v2?)

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#921]
[queues.json](https://static.developer.riotgames.com/docs/lol/queues.json)

Example match ID: `JP1_444997552`
https://asia.api.riotgames.com/lol/match/v5/matches/JP1_444997552
```json
{
  "info": {
    "endOfGameResult": "GameComplete",
    "gameCreation": 1714670766771,
    "gameDuration": 1508,
    "gameEndTimestamp": 1714672296364,
    "gameId": 444997552,
    "gameMode": "CHERRY",
    "gameName": "teambuilder-match-444997552",
    "gameStartTimestamp": 1714670787808,
    "gameType": "MATCHED_GAME",
    "gameVersion": "14.9.580.2108",
    "mapId": 30,
    "participants": ...,
    "platformId": "JP1",
    "queueId": 1710,
    "teams": ...,
    "tournamentCode": ""
  },
  ...
}
```

According to https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/queues.json queue 1710 is "Arena", I guess replacing 1700 (also "Arena")

**Comment by MingweiSamuel** [comment]
And I supposed `1700` should be marked deprecated in the notes?

**Comment by DarkIntaqt** [comment]
There are still games being played in 1700, it's not deprecated. Tbh, I haven't seen a single game with the queueId 1710, but it seems like you found one. 
QueueId 1700 game: EUW1_6924258289

**Comment by MingweiSamuel** [comment]
Hmm, interesting, I wonder if it depends on how many people you queue up with

**Comment by geozukunft** [comment]
I can't say from the top of my head which ids it was last year. But one id was basically for solo or duo queued and the other one was when people did a full lobby queue together

**Comment by tisbells** [comment]
Heyo, 1700 is the standard Arena queue, 1710 is for the 16 player lobby. We'll get the doc updated shortly.

**Comment by tisbells** [comment]
[queues.json](https://static.developer.riotgames.com/docs/lol/queues.json) has been updated to include queue 1710
