### ISSUE TITLE
Sound inside Deadlocks ultimate in Valorant is incredibly loud, when someone shoots the "cacoon" you need to take off your headphones.[BUG] 

### ISSUE THREAD

**Issue by jettseth** [RiotGames/developer-relations#931]
**Bug Description**  
I mean its not really a bug, just an annoying part of the game which will hurt peoples ears.

**Problem Description**  
When Deadlock use her ultimate on you, and you are inside the cacoon, all sounds are fine except when someone shoots the "cacoon" that you are in. That sound is incredibly loud, a lot louder than all other sounds in the game, which hurts your ears.

**Expected Result**  
I lowered the audio but then i could not hear other important sounds in the game and that sound was still too loud. 

**Actual Result**  

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call. Once every ~100 API calls.
* Severity: When it happens, my whole website crashes.
* Cost: Requires me to run X more servers to compensate for the issue costing me on average $200 of additional spend a month.
* Efficiency: Requires me to make 10x more API calls than necessary to compensate for the issue.
* User emails: I get frequent emails from users asking me about this issue.
* Etc

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

* Frequency: Every time the user visits the site, they experience this issue. Once every ~100 visits this issue occurs.
* Severity: When this bug happens, a user is unable to use my site. I have 200 visits to my site each day, so it affects 50% of site visits.
* Quantity: There are ~1k players that experience this issue.
* Region: This affects players in NA and EUW.
* Etc

**Preconditions**  
What conditions must be met in order for this bug to occur?

* First condition
* Second condition

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Step 1
1. Step 2

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by BlossomiShymae** [comment]
Hii there! This place is for any issues relating to the Riot Games API, not game support or suggestions. https://support.riotgames.com/ is the right place.

**Comment by jettseth** [comment]
Okey thanks, but i want to talk/submit a ticket to the valorant developers
not the support.

Den fre 17 maj 2024 kl 02:20 skrev Blossomi Shymae ***@***.***

**Comment by Token07** [comment]
There is no way to submit a ticket to the developers. This system is intended for issues with the Riot Games API, which provides game data and assets to developers not employed by Riot. Any issues outside of that will not be acted on or forwarded.

**Comment by tisbells** [comment]
Hi there - As mentioned above, you will need to submit suspected game bugs to[ Riot support](https://support-valorant.riotgames.com/hc/en-us). They will review and funnel to the relevant teams.
