### ISSUE TITLE
[BUG] champion-masters-v4 endpoints returns incorrect `summonerId`

### ISSUE THREAD

**Issue by AoshiW** [RiotGames/developer-relations#932]
**Bug Description** 
if I try to use `summonerId` from  champion-masters-v4 in summoner-v4 I get:
```json
{
    "status": {
        "message": "Bad request - java.lang.NumberFormatException: For input string: \\\"undefined\\\"",
        "status_code": 400
    }
}
```

**Problem Description**  
it is impossible to use `summonerId` in other endpoints

**Comment by tisbells** [comment]
Hey, we heard back that for some time now, champion mastery only supports by PUUID. The team made an update and summonerID should no longer appear in champion-mastery-v4 API. It's still listed as available in the docs as of this moment, but will be removed shortly.

**Comment by tisbells** [comment]
These docs were updated, so closing this out.
