### ISSUE TITLE
[BUG] Match Data Response RiotIdName is null

### ISSUE THREAD

**Issue by Seiori** [RiotGames/developer-relations#937]
Responses from the Api when getting the Match Data, the RiotIdTagline is populated but the RiotIdName is not (Null)

In vast majority of cases, the SummonerName field is populated. So I am curious what the preference is here. Is only one of these values supposed to be populated?

**Expected Result**  
RiotIdName to be populated similiar to RiotIdTagline.

Example: Seiori#2001

RiotIdName: Seiori
RiotIdTagline: 2001

**Actual Result**  
RiotIdName is returned as Null

Example: Seiori#2001

RiotIdName: Null
RiotIdTagline: 2001

**Developer Impact**  
I made a call to get the last 100 Games for my personal account "Seiori#2001"

I then got the match data for all 100 games. And displayed every participant with their RiotIdName and RiotIdTagline

Scrolling through all 100 displayed games => 1000 players.

Not a single one displayed any informaton for the RiotIdName value. But all displayed information for the RiotIdTagline

**Player Impact**  
In terms of the game, none. In terms of a player impact when visiting my site. Well every single match value in my match history display. Has no information for the participants in the games in regards to their RiotIdName

**Preconditions**  
Load a valid match data for a valid match id

**Repro Steps**  
Same as above

**Issue Comments**  
What is the purpose of the SummonerName field. Is this simply leftover from the migration to Riot Ids. Or is this intended to be used instead? This value is out dated either way.

**Comment by AoshiW** [comment]
riot changed `riotIdName` to `riotIdGameName` some time ago (#899)

**Comment by Seiori** [comment]
Mhm suprised I didn't find that ticket when I looked it up. But yeah okay I see the problem then the object I have been using was looking for this field. I see on the Api it mentions this field and riotIdGameName. Thank you for that :)
