### ISSUE TITLE
highestAchievedSeasonTier is missing in MATCH-V4

### ISSUE THREAD

**Issue by sydsim** [RiotGames/developer-relations#94]
Hi! While I'm using MATCH-V4 API, I found that `highestAchievedSeasonTier` is missing for a few participants in the many results.
ex) https://kr.api.riotgames.com/lol/match/v4/matches/3567996958

In the above example, participant 1, 2, 3, 5, 9, 10 don't have `highestAchievedSeasonTier`, but they played rank and had tier in last season.
For example, participant 1 is [응가스멜]( https://www.op.gg/summoner/userName=응가스멜), got diamond in last season.

**Comment by raitono** [comment]
I noticed this as well. I believe it is a result of the change to the loading screen where they only show boarders for the current season now. If the player is currently unranked, they seem to be missing this field.

**Comment by MingweiSamuel** [comment]
I'm guessing the underlying service removed the field, so it should probably be removed from the docs. Could a Rioter confirm?

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported.
