### ISSUE TITLE
[BUG] swiftplay Missing from VAL-MATCH-V1

### ISSUE THREAD

**Issue by danblock97** [RiotGames/developer-relations#942]
**Bug Description**  
swiftplay on PC is missing from the list of queues to select from

**Problem Description**  
The queue path parameter from [/val/match/v1/recent-matches/by-queue/{queue}](https://developer.riotgames.com/apis#val-match-v1/GET_getRecent) was recently updated for console queues including console_swiftplay however we are missing the option for swiftplay on PC Valorant

**Expected Result**  
I expect to be able to query [/val/match/v1/recent-matches/by-queue/{queue}](https://developer.riotgames.com/apis#val-match-v1/GET_getRecent) by swiftplay as the queue

**Actual Result**  
Can't query swiftplay using [/val/match/v1/recent-matches/by-queue/{queue}](https://developer.riotgames.com/apis#val-match-v1/GET_getRecent)

**Developer Impact**  
Either unable to get Swiftplay games via the API or we have to go through the matchlist for this information

Requires extra work and extra api calls for something that could be resolved by adding the queue to the list.

**Player Impact**  
Due to possible complexity issues in getting Swiftplay, some apps may not include it even though it is a highly played mode.

**Repro Steps**  
Visit [/val/match/v1/recent-matches/by-queue/{queue}](https://developer.riotgames.com/apis#val-match-v1/GET_getRecent) and try to find swiftplay in the queue parameter dropdown.

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by raimannma** [comment]
![Bildschirmfoto vom 2024-07-17 18-10-22](https://github.com/user-attachments/assets/2e6e2a5f-6824-49cf-8524-063bac504280)

Still missing

**Comment by tisbells** [comment]
Hey there, sorry for the delay - There was some additional work needed and this is now expected to be available on August 14. If this changes again, I'll post an update here.

**Comment by tisbells** [comment]
Actually just got an update that they were able to get this added a few moments ago. Please let us know if you still have issues accessing this queue.

**Comment by raimannma** [comment]
> Actually just got an update that they were able to get this added a few moments ago. Please let us know if you still have issues accessing this queue.

Great! Works for me!
