### ISSUE TITLE
[DOCS][BUG] Queuetypes `870`, `880`, `890` undocumented in in `queues.json`

### ISSUE THREAD

**Issue by emsquellen** [RiotGames/developer-relations#946]
**Bug Description**  
The queue.json provided at https://static.developer.riotgames.com/docs/lol/queues.json does not contain the new vs AI modes that were introduced in 14.6

**Problem Description**  
When navigating to queues.json, 870, 880 and 890 are not listed, even though when querying a game that was played in the modes giving a new, undocumented queueID.

**Expected Result**  
```
{
    "queueId": 870,
    "map": "Summoner's Rift",
    "description": "Co-op vs. AI Intro Bot games",
    "notes": null
},
{
    "queueId": 880,
    "map": "Summoner's Rift",
    "description": "Co-op vs. AI Beginner Bot games",
    "notes": null

},
{
    "queueId": 890,
    "map": "Summoner's Rift",
    "description": "Co-op vs. AI Intermediate Bot games",
    "notes": null
}
```

**Developer Impact**  
When requesting matches, I find queueIDs which are undocumented

**Comment by tisbells** [comment]
Hiya - these were added. These queue IDs also replaced 830, 840, and 850 in March of this year. We're updating the docs so this is noted for those queue IDs.
