### ISSUE TITLE
[BUG] `console_competitive` missing from `/val/match/console/v1/recent-matches/by-queue/{queue}`

### ISSUE THREAD

**Issue by PenguinDevs** [RiotGames/developer-relations#952]
**Bug Description**  
The competitive console queue is missing from [/val/match/console/v1/recent-matches/by-queue/{queue}](https://developer.riotgames.com/apis#val-console-match-v1/GET_getRecent) the list of console queue types available.

This is similar to [https://github.com/RiotGames/developer-relations/issues/942](https://github.com/RiotGames/developer-relations/issues/942), except this bug report is for the console competitive queue.

**Problem Description**  
Other queue types for console such as console_unrated, console_swiftplay, console_hurm, console_deathmatch are available for the [/val/match/console/v1/recent-matches/by-queue/{queue}](https://developer.riotgames.com/apis#val-console-match-v1/GET_getRecent) endpoint. But because the console_competitive is a new queue, it is missing from the initial release of the console match lists endpoint.

**Expected Result**  
To be able to retrieve a list of match ids for the console_competitive queue from [/val/match/console/v1/recent-matches/by-queue/{queue}](https://developer.riotgames.com/apis#val-console-match-v1/GET_getRecent)

**Actual Result**  
When attempting to GET https://na.api.riotgames.com/val/match/console/v1/recent-matches/by-queue/console_competitive, the response received is `{"status":{"message":"Bad request - Path parameter 'queue' must be one of [console_unrated, console_swiftplay, console_hurm, console_deathmatch]. Invalid value 'console_competitive' given.","status_code":400}}`

**Developer Impact**  
Inability to fetch recent console competitive games in the past 10 minutes through a single request. The alternatives are to instead seek for games of this queue type through the player's console match lists [/val/match/console/v1/matches/{matchId}](https://developer.riotgames.com/apis#val-console-match-v1/GET_getMatch) for a large amount of players, and thus numerous API calls.

**Player Impact**  
Some apps may need to omit the console competitive queue type in features that for example require a collation of many valorant matches in a particular episode or act.

**Preconditions**  
None.

**Repro Steps**  
`curl -H 'X-Riot-Token: YOUR TOKEN' 'https://{shard}.api.riotgames.com/val/match/console/v1/recent-matches/by-queue/console_competitive'`

**Issue Comments**  
If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by tisbells** [comment]
Hi - We're checking in on this.

**Comment by PenguinDevs** [comment]
Hello, are there any updates on this?

**Comment by raimannma** [comment]
It's fixed already!

**Comment by PenguinDevs** [comment]
I should've checked before sending that, ty!
