### ISSUE TITLE
[BUG] RSO `/riot/account/v1/accounts/me` always returns `404` for Valorant console only players

### ISSUE THREAD

**Issue by PenguinDevs** [RiotGames/developer-relations#956]
**Bug Description**  
It appears that Valorant console players who have not played any other Riot Games games in the past including Valorant on Windows are returning `404` from the [/riot/account/v1/accounts/me](https://developer.riotgames.com/apis#account-v1/GET_getByAccessToken) endpoint. I will be referring to these players as Valorant console only players in this report. Other types of players return `200` from this endpoint.

These players DO have a game name and tag line that can be used to retrieve their puuids from the [/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}](https://developer.riotgames.com/apis#account-v1/GET_getByRiotId) endpoint. This puuid can also be used in other endpoints such as [/val/match/console/v1/matchlists/by-puuid/{puuid}](https://developer.riotgames.com/apis#val-console-match-v1/GET_getMatchlist).

I am not the only one facing this issue. Other developers such as @Henrik-3 are also facing this same issue with their applications.

Popular sites such as [tracker.gg](https://tracker.gg/valorant) and [op.gg](https://valorant.op.gg/) fail to authorise through RSO for these Valorant console only players.

Even when these Valorant console only players attempt to add their Riot Games account as a social connection in Discord, it returns them with an error 'Failed to connect your Riot Games account to Discord' after signing in through RSO and then being redirected to the oauth callback page for Discord.
![image](https://github.com/user-attachments/assets/19899539-cc65-44f3-9f3f-2f5bcbab19a1)

Please not that this is what I suspect. I do not have a whole lot of users to confidently confirm that this is the case, though based on the recent cases, most of these users have this condition in common.

**Expected Result**
Users who have played other Riot Games games that is not just Valorant console, including Valorant on windows returns 200 with the `puuid`, `gameName` and `tagLine`. This is the expected result for the Valorant console only players too.

**Actual Result**  
A `404` with the response `{"status":{"status_code":404,"message":"Data not found - No results found for player or no longer available"}}` is received when using the [/riot/account/v1/accounts/me](https://developer.riotgames.com/apis#account-v1/GET_getByAccessToken) endpoint. The result is the same across the three shards: `AMERICAS`, `ASIA`, and `EUROPE`.

**Developer Impact**  
I am unable to obtain the user's puuid, game name and tag line once the RSO have been authenticated and redirected the user to the oauth callback page. Instead, Even if I was to ask for the user's input to type their game name and tag line, I am unable to verify that it is the same as the game name and tag line (or puuid) received from RSO.

**Player Impact**  
These users are unable to use third party applications that require RSO and the puuid that is obtained from RSO.

**Preconditions**  
A new Riot Games account that has not played any Riot Games games in the past, with access to the Valorant console beta. This account should have played a Valorant console match, meaning that it will also have a game name and tag line.

As of 14/07/2024, these are some of the accounts that are facing this issue (provided with consent):
- OUMXYY#9820
- Inwards7#5223
- GLITCHYLOL101#8715

**Repro Steps**  
1. Log in through RSO with an account that is described in the above preconditions.
2. Retrieve the code received from RSO in the oauth callback.
3. Obtain the `access_token` from https://auth.riotgames.com/token with `grant_type: 'authorization_code'` This should be a bearer token as specified by `token_type`.
4. Pass in `Authorization: '{token_type} {access_token}'` as the headers to [/riot/account/v1/accounts/me](https://developer.riotgames.com/apis#account-v1/GET_getByAccessToken), which will return `404`.

**Issue Comments**  
If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by tisbells** [comment]
Hey there, we're checking in on this and will let you know once we have more info.

**Comment by f3ar161** [comment]
HI @PenguinDevs could you send us the tokens that are currently having this issue? 

To: devrel-rg@riotgames.com

**Comment by PenguinDevs** [comment]
I've sent an email

**Comment by f3ar161** [comment]
hey hi @PenguinDevs, it's fixed. Could you double check?

**Comment by PenguinDevs** [comment]
Thanks a lot, however, I can't seem to be able to get a response from users who were still impacted by this issue to test the fix. Though I can confirm that I haven't been getting any reports of this issue since the public beta for console was released.

**Comment by f3ar161** [comment]
Got it, I'll let this one open for a bit in case we get any news.
