### ISSUE TITLE
[BUG] DataDragon does not include swarm champions

### ISSUE THREAD

**Issue by DarkIntaqt** [RiotGames/developer-relations#958]
**BUG**
Swarm champions, for example `Strawberry_Jinx` (3151) are not included in datadragon. JSONs as well as images are nowhere to be found. 

**Impact**
To support the new mode SWARM for my site, I now have to manually add champion ids and images or gather these from other sources. 

Items are somehow included / available.

**Comment by tisbells** [comment]
Hey there, we spoke to the team who owns this data and they unfortunately do not have plans to update this. Apologies for the inconvenience that this causes.

**Comment by DarkIntaqt** [comment]
That's very unfortunate. Not providing essential game assets officially is a huge loss to the developer ecosystem, thanks for the response though :/
