### ISSUE TITLE
Event WARD_PLACED has UNDEFINED wardType for some events

### ISSUE THREAD

**Issue by heerakli** [RiotGames/developer-relations#96]
Looks like for some wards (e.g. VISION_WARD) this event has UNDEFINED value. And some of events are duplicated and some of them has no creatorId
For example region **NA** match_id **2992274783** I printed all WARD_PLACED events:
`{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":25144}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":25144}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":25144}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":25144}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":10,"timestamp":41381}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":3,"timestamp":56595}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":75324}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":75324}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":7,"timestamp":122624}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":125495}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":125495}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":5,"timestamp":132137}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":9,"timestamp":138243}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":6,"timestamp":144249}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":175678}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":175678}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":175678}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":175678}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":225865}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":225865}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":225865}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":225865}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":9,"timestamp":245645}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":3,"timestamp":246173}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":7,"timestamp":251695}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":5,"timestamp":258559}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":6,"timestamp":265228}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":276058}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":276058}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":276058}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":276058}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":10,"timestamp":299138}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":326258}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":326258}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":326258}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":326258}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":376267}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":376267}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":376267}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":376267}
{"type":"WARD_PLACED","wardType":"CONTROL_WARD","creatorId":10,"timestamp":410930}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":2,"timestamp":425195}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":426482}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":426482}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":426482}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":426482}
{"type":"WARD_PLACED","wardType":"CONTROL_WARD","creatorId":6,"timestamp":442233}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":9,"timestamp":465206}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":476673}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":476673}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":476673}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":476673}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":3,"timestamp":487935}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":5,"timestamp":489024}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":6,"timestamp":496758}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":7,"timestamp":498111}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":526877}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":526877}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":526877}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":526877}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":4,"timestamp":532793}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":10,"timestamp":559981}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":8,"timestamp":566391}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":577131}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":577131}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":577131}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":577131}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":581223}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":5,"timestamp":583083}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":4,"timestamp":589771}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":6,"timestamp":613010}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":627158}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":627158}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":627158}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":627158}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":6,"timestamp":656615}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":674893}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":677401}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":677401}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":677401}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":677401}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":700162}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":703617}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":3,"timestamp":714459}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":6,"timestamp":721771}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":724589}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":727636}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":727636}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":727636}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":727636}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":9,"timestamp":734965}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":5,"timestamp":738694}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":5,"timestamp":742135}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":5,"timestamp":754000}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":777874}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":777874}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":777874}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":777874}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":778543}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":790237}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":7,"timestamp":791690}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":8,"timestamp":792189}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":8,"timestamp":797834}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":4,"timestamp":801431}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":802982}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":815587}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":826924}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":827914}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":827914}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":827914}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":827914}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":10,"timestamp":835043}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":839186}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":5,"timestamp":841074}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":855607}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":867452}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":7,"timestamp":875655}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":877932}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":877932}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":877932}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":877932}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":9,"timestamp":882233}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":3,"timestamp":886089}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":904938}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":912587}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":916550}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":2,"timestamp":917546}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":928187}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":928187}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":928187}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":928187}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":935393}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":945249}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":2,"timestamp":953812}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":956255}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":971072}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":5,"timestamp":972302}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":978242}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":978242}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":978242}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":978242}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":980257}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":4,"timestamp":995272}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":996889}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1006758}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1028287}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1028287}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1028287}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1028287}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":5,"timestamp":1044876}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":5,"timestamp":1049077}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1063384}
{"type":"WARD_PLACED","wardType":"SIGHT_WARD","creatorId":5,"timestamp":1075278}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":8,"timestamp":1075840}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1078546}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1078546}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1078546}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1078546}
{"type":"WARD_PLACED","wardType":"CONTROL_WARD","creatorId":8,"timestamp":1079404}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":3,"timestamp":1082653}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1083412}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1103583}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1105354}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":9,"timestamp":1110304}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1113169}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1128580}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1128580}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1128580}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1128580}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":7,"timestamp":1144957}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":10,"timestamp":1168645}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1171851}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1178587}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1178587}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1178587}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1178587}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1185101}
{"type":"WARD_PLACED","wardType":"BLUE_TRINKET","creatorId":5,"timestamp":1198735}
{"type":"WARD_PLACED","wardType":"YELLOW_TRINKET","creatorId":4,"timestamp":1213014}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1215559}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1228720}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1228720}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1228720}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1228720}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1243859}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1269578}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1277110}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1278793}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1278793}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":1278793}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":1278793}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":2,"timestamp":1297530}`

**Comment by WxWatch** [comment]
What champions are these? A lot of champions produce vision-granting artifacts that count as WARD_PLACED (Teemo shrooms, etc)

**Comment by heerakli** [comment]
In this game summoners played with: Kayle, Kayn, Aatrox, Kai'sa, Karma (blue team) and Camile, Elise, Lux, Ashe, Bard (red team). 
Few months ago in timeline we constantly received VISION_WARD type, then we start to receive UNDEFINED. Now I can't find VISION_WARD event in any game
And I'm curious about first three events in this match, looks like it's the same event, because timestamp is the same
`{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":25144}
{"type":"WARD_PLACED","wardType":"UNDEFINED","timestamp":25144}
{"type":"WARD_PLACED","wardType":"UNDEFINED","creatorId":6,"timestamp":25144}`

**Comment by heerakli** [comment]
looks like VISION_WARD became CONTROL_WARD, that's my problem. I missed that. so I don't have question anymore, sorry and thank you
