### ISSUE TITLE
False ban issue [Account] 

### ISSUE THREAD

**Issue by Akeylan** [RiotGames/developer-relations#961]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Akeylan#Okami

Have you played any of Riot's games or did you just create an account for the Developer Portal?
I played only valorant [and just installed other games but didn't played it long time ago]

**Issue Description**  
A clear and concise description of what the issue is.
I was playing my ranked game normally I was kayo on split map and suddenly game stopped with big error screen mentioning rules of section 7 
First u thought game crashed but when I opened riot client I realized I got ban for accusing of cheating 
While only things that I use and it's 3rd party software are these : razer synapse 3 , tracker , outplayed [recording software]

**What I've Tried**
What steps have you tried to resolve the issue.
I tried ticketing through many tickets but answer was same from crankz bot or other admins which they all were saying " ban is rightful " while it's not and I'm nearly 4 years valorant player and I know how vanguard works why would I use cheats on my 4 year 191k vp spent account ? 🤔 [it's not why should use it on main , it's why would I do using it even when I know vanguard ]
I'm fan of sentinels since 2023 , I'm watching nearly all matches of VCT tournaments as kuch as I can 
I have been collecting all limited edition bundles like champions and VCTs and bundles like arcane and ignite
I have many friends that they know I'm not cheating
I also don't use any software that give me visual advantage and only thing is I turn HDR on which is a system option
Only thing that I can thing of this ban is : 
Razer synapse 3 installs [ macro ] files automatically and when u delete them manually razer synapse 3 doesnt loads up 
Only yhing possible is vanguard detecting them as macro [i never configed them , i tried to use them and then i googled that its illegal on valorant and #INSTANTLY deleted them BUT it doesn't matter u delete or don't because razer synapse 3 holds files , I tried on fresh system and I saw it still does it

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

I know I'm not cheating and I request help I never cheated in valorant and I will not in future even 
Pls help me in this thing
My discord if we needed to contact : Akeyaln

**Comment by raimannma** [comment]
that's something for the account support, nothing for developer relations, please contact riot account support

**Comment by Akeylan** [comment]
> that's something for the account support, nothing for developer relations, please contact riot account support

I did it on website and they didn't help me and all I hear is " ban is rightful " what should I do ? 🫠 I'm literally getting ignored because I'm getting counted as cheater while I'm not 🥲

**Comment by raimannma** [comment]
> > that's something for the account support, nothing for developer relations, please contact riot account support
> 
> I did it on website and they didn't help me and all I hear is " ban is rightful " what should I do ? 🫠 I'm literally getting ignored because I'm getting counted as cheater while I'm not 🥲

If they say ban is rightful then it probably is. We here are mostly third party developers, you won't get any account support here.

**Comment by Akeylan** [comment]
It's not rightful because I know I'm not cheating because it's 4years of life spent in valorant already 🥲
 You don't know any other to get help sir ? If not I'm not bothering u anymore
And 1 more question 
U guys don't relate to bans causing from softwares like razer synapse 3 or whatever like keyboard or mouse software ?

**Comment by raimannma** [comment]
Account Support is the only one that could help you.

Sometimes there are false positives Bans from Vanguard but Support should notice that.

**Comment by tisbells** [comment]
Hey there, please visit [Riot Support](https://support.riotgames.com/).
