### ISSUE TITLE
HELP iglesiaNiPiccolo#3681

### ISSUE THREAD

**Issue by andre123700** [RiotGames/developer-relations#962]
**Account Information**
iglesiaNiPiccolo#3681
Have you played any of Riot's games or did you just create an account for the Developer Portal? yes

**Issue Description**  
my account in valorant says its been permanently suspended, someone is using my account to play, i dont know what to do, one time i logged in and ist currently in a match, im from philippines, if you will check the location, im always playing, and this past few days someones been logging into my account and its from other country, maybe hes the one using hacks or cheats, cmon, ive been playing valorant for years, please check and have my account recovered, i have made payments for skins on that account, cmon, dont do this, review and help me
**What I've Tried**
i submitted a ticket and god knows where that ticket went

- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by raimannma** [comment]
Please contact the account support, nothing we can do here!

**Comment by andre123700** [comment]
i dont know where to go,

**Comment by andre123700** [comment]
im just a man who click play valorant, i dont know about these sites and stuff

**Comment by raimannma** [comment]
> im just a man who click play valorant, i dont know about these sites and stuff

https://letmegooglethat.com/?q=riot+support

**Comment by tisbells** [comment]
Hey there, please visit [Riot Support](https://support.riotgames.com/).
