### ISSUE TITLE
[BUG] New TFT games do not appear in tft-match-v1 or match-v5

### ISSUE THREAD

**Issue by whyando** [RiotGames/developer-relations#964]
As per the title, processing new tft games is down, and no new games have been published for the last 2/3 hours.
This affects all players in all servers.

An example player who does have games within the last 2/3 hours but do not appear in the API:
region: TH2
riot id: skpeee#TH2

**Comment by philliplakis** [comment]
Same with League

**Comment by whyando** [comment]
appears to be all fixed 🙏
