### ISSUE TITLE
[BUG] MATCH-V5 is returning 404 for new games since 8am UTC 26th July

### ISSUE THREAD

**Issue by philliplakis** [RiotGames/developer-relations#965]
**Problem Description**  
New matches since 8am UTC on the 26th July 2024 are returning `404` from the API

**Expected Result**  
When requesting from the API for a known match from a user, the timeline should be returned.

**Actual Result**  
We are receiving a `404`

**Developer Impact**  

* Frequency: Every API call. 

**Player Impact**  

* Frequency: Every time the user visits the site, they experience this issue. 

**Some example MatchIds**
```
NA1_5062563443
VN2_515891422
NA1_5062550725
PH2_59887398
```

**Comment by showtimezz** [comment]
Is this still the case? I took a look at some of the provided ID's from Riot's API portal, they seem to be working. 
![image](https://github.com/user-attachments/assets/e03cea1d-c751-44a9-92a1-5e0551b892bd)

Did you try it on Riot's portal to rule out an implementation error?

**Comment by tisbells** [comment]
Closing this out as this doesn't seem to be occurring any longer. If you're still experiencing this, feel free to let us know.
