### ISSUE TITLE
Undocumented queue id 67

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#97]
A game with queueId 67 was recently found, there doesnt seem to be any queue with that id in the docs.

Game id 557630302 on LA2

**Comment by Querijn** [comment]
Game indicates that it's an ARAM, in March 2018. ID for Howling Abyss is 65.

**Comment by RiotTuxedo** [comment]
I've updated the game constants to include this queue. To my knowledge, this queue hasn't been active since 2017. The game you found is likely the result of a QA process that happens when we start the platform up.
