### ISSUE TITLE
[Feature request] "SWARM_DefeatMiniBosses": seperated by miniboss type 

### ISSUE THREAD

**Issue by Yuanara** [RiotGames/developer-relations#972]
a substat that seperates the total defeated minibosses by type

**Comment by tisbells** [comment]
Hi! While these unfortunately weren't feasible updates during the run of Swarm mode, we appreciate the feature requests. Closing this out in addition to https://github.com/RiotGames/developer-relations/issues/971, https://github.com/RiotGames/developer-relations/issues/970, and https://github.com/RiotGames/developer-relations/issues/969
