### ISSUE TITLE
i cant reach game client 

### ISSUE THREAD

**Issue by Mmlnava** [RiotGames/developer-relations#978]
![Screenshot 2024-08-01 125408](https://github.com/user-attachments/assets/3a908c0a-2453-4b16-91cd-a3af9be540fe)
Today, I wanted to play as usual, but after choosing the hero, the client often closes the game and gives me the option to reconnect. And after finishing the game, I gave it a rest and even a TFT play, but the same problem happened to me again and I decided. I tried with another account on another server (EUW) and I encountered the same problem again and it gave me an error in that account, which I am uploading here now.

**Comment by raimannma** [comment]
Instead of spamming issues here you could just reach out for the player support.
This Ticket system is meant for Developers working with the API.

**Comment by tisbells** [comment]
Please reach out to [Player Support](https://support.riotgames.com/) for game client issues.
