### ISSUE TITLE
Match-v4 missing rune bonus stat fields

### ISSUE THREAD

**Issue by raitono** [RiotGames/developer-relations#98]
Preconditions

1. None

        Steps to Reproduce

1. Execute a get request for this URL:
`https://na1.api.riotgames.com/lol/match/v4/matches/2998335096`

        Expected Result

1. I expect the returned JSON data to match the form described within the API documentation. Specifically, I would not expect to find fields which have not been documented.

        Actual Result

1. The JSON data returns additional undocumented fields.
Specifically, the Rune bonus stats are not present in the documentation. These are found as the fields statPerk0, statPerk1, and statPerk2 on the ParticipantStatsDto.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported. Feel free to reopen/comment if you feel this is in error.
