### ISSUE TITLE
Executing VAL-CONSOLE-MATCH-V1 endpoints against the BR region returns an error

### ISSUE THREAD

**Issue by serkanbal** [RiotGames/developer-relations#981]
**Bug Description**  
Executing VAL-CONSOLE-MATCH-V1 endpoints against BR region returns error **even though Brazil is part of the console open beta.**

**Problem Description**  
Executing VAL-CONSOLE-MATCH-V1 endpoints against BR region returns the following error:
```
{
  "status": {
    "message": "Bad request - Invalid routing value br",
    "status_code": 400
  }
}
```
Also, BR region cannot be selected in the drop down menu at `https://developer.riotgames.com/apis#val-console-match-v1`

**Expected Result**  
It should be possible to call VAL-CONSOLE-MATCH-V1 endpoints against BR region and BR region should be an option at the developer website.

**Actual Result**  
Executing VAL-CONSOLE-MATCH-V1 endpoints against BR region returns the error above and BR region is absent in the drop down menu at the developer website.

**Developer Impact**  
We are currently manually redirecting the BR region calls to NA, since I believe BR is a sub-region of the greater NA region. However, for code-cleanliness and consistency's sake, we should be able to get the same response from the BR region.

* Frequency: Every BR region VAL-CONSOLE-MATCH-V1 call.
* Severity: Low. Implemented the manual workaround mentioned under Developer Impact.
* Efficiency: Medium. This forces us to use NA region for BR console calls. This might be a problem in the future since we are using NA call limit for both NA and BR at the moment.

**Player Impact**  
None. The workaround above ensures that players are unaffected.

**Comment by PenguinDevs** [comment]
I am pretty sure the br and latam shares the na shard for matches including na. Try executing your requests for br in the na shard.

**Comment by serkanbal** [comment]
> I am pretty sure the br and latam shares the na shard for matches. Try executing your requests for br using the na shard.

This is what we are doing currently as a workaround. We are manually redirecting the BR region calls to NA, however, for code-cleanliness and consistency's sake, we should be able to get the same response from the BR region.

**Comment by tisbells** [comment]
Hey there, BR and LATAM were added!
