### ISSUE TITLE
Cannot login to Developer Portal for 4 days

### ISSUE THREAD

**Issue by dvijeniii05** [RiotGames/developer-relations#984]
**Account Information**

Riot id ==> J4V4DOV#4763
I play Valorant (haven't played for long time) but mainly now using the account for Developer Portal as I have an API key etc setup.

**Issue Description**  

I am struggling to login to my main Developer account using any login systems of Riot. Cannot do it through Dev. Portal nor just Riot website, i keep receiving the following error: “Ooops! Something went wrong. Sorry we are having some trouble right now. Please try again” (display on screenshot attached). This is happening for last 3 days now. I have checked all emails in my inbox and there are no info in regards to any changes or anything. 

But I can login to the actual game, like Valiant accepts my credentials etc, it is only Dev portal issue.

<img width="458" alt="Screenshot 2024-09-01 at 17 07 06" src="https://github.com/user-attachments/assets/77943337-0d23-402c-8f8a-4a7f0c3be073">

**What I've Tried**
Clearing cookies, using deferent device, different browsers etc, nothing helps. BUT I found that I can login to other Dev. accounts (tried my friends).

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [x] Attempt to login via a secondary device (mobile or different computer)

**Comment by f3ar161** [comment]
Hey hi, @dvijeniii05 where are you located? your account might be disable due to inactivity.

**Comment by dvijeniii05** [comment]
Hey @f3ar161 . My region is Europe and country is the UK. Appreciate your suggestion but struggling to understand how could one stay active with the developer account? I've been using api-key etc as my app is still in development, and notified the support team when requesting the api-key for the app. They said all good etc. i've also havent received any communication emails that would note that account is getting disabled for any reason.

And just to clarify i'm able to login to my account in-game and play under it. It is just the Dev account that i am not able to get into :(

**Comment by dvijeniii05** [comment]
UPD: looked into network logs while logging in and I'm getting 400: Bad Request if that helps to anyone :( 
<img width="310" alt="Screenshot 2024-09-05 at 09 12 28" src="https://github.com/user-attachments/assets/de22f0c0-f4f8-4bd0-8c18-3c68142548bc">

**Comment by dvijeniii05** [comment]
Solved, it works when I use username instead of email
