### ISSUE TITLE
[65edgar3#LAN]  Problema al entrar a pantalla de carga despues de la seleccion de campeones

### ISSUE THREAD

**Issue by 65edgar3** [RiotGames/developer-relations#985]
![imagen_2024-09-02_212109875](https://github.com/user-attachments/assets/5f845937-fc3d-4039-94b0-57e4b7b1cde7)
Jugué dos partidas en ARAM, todo normal. Quise volver a jugar una 3era pero después de la selección de campeones en ARAM sucede que no entro a pantalla de carga, reinicie cliente de Riot y el juego en si. Reporte bug pero pensé que todo se había solucionado y no había sanción lo cual fue erróneo, me pusieron en cola de baja preferencia y al querer jugar una 4ta partida sucedió lo mismo después de la selección de campeones no me dejo entrar a la pantalla de carga lo cual ocasiono 2 surrenders y sancion para mi por algo que no tengo en mis manos. Espero puedan leer y poder solucionarlo

**Comment by 65edgar3** [comment]
Cabe mencionar tambien que me aparecio un mensaje del cual no tengo foto que me decia de copiar un "Full memory dump" y me mando a esta pagina poara hacer saber al equipo de desarrolladores  (No se si estoy en el correcto), le pique a copiar el contenido en el portapapeles pero al pegarlo no me mostraba nada solo una foto que yo habia copiado un dia anterior por dejar mi pc encendida
![image](https://github.com/user-attachments/assets/33f96cdf-be1e-447f-9583-5779cb14769a)
(Imagen de la ventana con el mensaje)

**Comment by Cypherous** [comment]
From a quick google translate this seems to be something you will want to take up with support as this github repo is related to 3rd party developers not the actual game client

Open a ticket at https://support-leagueoflegends.riotgames.com

**Comment by 65edgar3** [comment]
Thanks!
