### ISSUE TITLE
v4 Match Data is occasionally missing data

### ISSUE THREAD

**Issue by MitchellRomney** [RiotGames/developer-relations#99]
>     Preconditions
I have a script running through a list of matches. Grabbing match info through MatchId.

>     Steps to Reproduce
It's getting snagged specifically on match(`matchId=235008689`) because the payload seems to be missing the firstInhibitorKill field. If you make a GET request to `https://oc1.api.riotgames.com/lol/match/v4/matches/235008689` you will find that firstInhibitorKill is missing.

>     Expected Result

That all fields would be present in the response, regardless of possible value.

>     Actual Result

firstInhibitorKill field is missing from response.

This happened to be the 12th match it was looping through in a list, so for the first 11 this field was there like normal.

Is there a reason this field is missing specifically from this game? Is this potentially happening with other fields sporadically throughout matches?

**Comment by stelar7** [comment]
Missing fields can be due to the value being 0/null.
The fact that the game is just over 20min might suggest that one team surrendered, and thus no inhib was destroyed.

**Comment by MitchellRomney** [comment]
> Missing fields can be due to the value being 0/null.
> The fact that the game is just over 20min might suggest that one team surrendered, and thus no inhib was destroyed.

Thanks for the reply Stelar. You're right, looking through the timeline the game must have been surrendered before an inhibitor died.

I guess my question then is; why is this field specifically acting different to just about every other field? There was 0 baron's killed, but `baronKills` is there, along with a very large number of other fields that equal 0. 

Should all fields not follow the same sort of convention, and for redundancy sake always return the same amount of fields regardless of their values?

**Comment by stelar7** [comment]
I am not sure why the api only removes some fields.
The most common action when using json with missing fields is to assume the value is `0/null/false`

**Comment by RiotTuxedo** [comment]
@MitchellRomney would you consider this issue resolved and thus can be closed?

**Comment by MitchellRomney** [comment]
Hey @RiotTuxedo, I've resolved the info by adding a conditional check that each field exists before it attempts to use the field.

Happy for this to be closed! Just thought it may be worth posing the question why data from SoloQ matches can't reliably return the same fields regardless of the specific data from the game. Isn't it easier to just return, for example, `firstInhibitorKill: false` on all players when a game has surrendered without an inhibitors being taken, instead of removing the field entirely from the response?

**Comment by RiotTuxedo** [comment]
It's an opinionated decision. As an example, the Google JSON Style Guide also suggests removing fields where the value is `null`.

https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Empty/Null_Property_Values#Empty/Null_Property_Values

As for whether it's easier to set it as `null`, `false`, or removing the key altogether can depend on the language or the way the service is implemented. If you're the developer and believe the best practice is to omit a field if the value is null and you find that it is easier in the language/service you're working with to leave a value as null, then you might see how this behavior exists.

**Comment by stsatlantis** [comment]
Hello, 
is it possible to mark the field in the documentation somehow that they are optional or may not represent?

**Comment by MingweiSamuel** [comment]
@stsatlantis I have a openapi schema which keeps a [manual list](https://github.com/MingweiSamuel/riotapi-schema/blob/master/src/data/dtoOptional.json) of which fields are optional (can be null/missing) and uses that to generate an [openapi spec](http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.json).
https://github.com/MingweiSamuel/riotapi-schema
http://www.mingweisamuel.com/riotapi-schema/tool/
