### ISSUE TITLE
[Account] Purchasinf 

### ISSUE THREAD

**Issue by 7loppy4** [RiotGames/developer-relations#995]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?  Lpyツ#none
Have you played any of Riot's games or did you just create an account for the Developer Portal?
I play

**Issue Description**  
A clear and concise description of what the issue is.
When I clicked Pay to buy vp my game glitched so I restarted it and when i wanted to try again I got some error, and my money was took away from my account

**What I've Tried**
What steps have you tried to resolve the issue.
I restarted client, restarted pc

- [x] Log out of the Developer Portal
- [ ] Attempt to log in via "Incognito Mode"
- [ ] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Step 1
1. Step 2

**Issue Context**
Please add any additional context that is useful.

**Comment by raimannma** [comment]
Please contact official riot support, this ticket system is for third party developers.

**Comment by bangingheads** [comment]
https://support.riotgames.com
