### ISSUE TITLE
[Account] "a Critical error has occurred and the process must be terminated"

### ISSUE THREAD

**Issue by BiggestBoi03** [RiotGames/developer-relations#998]
**Account Information**
My IGN on Riot is Equmenical#4645
I normally play both TFT and League of Legends

**Issue Description**  
When I was trying to load TFT and League of Legends I would get the message prompt from the title, Prior to this happening my game were struggling to load and would need to be relaunched from the client multiple times for it to begin working.

**What I've Tried**
I Have tried different game modes, closing my launcher, restarting my PC and reinstalling riot launcher

**Repro Steps**
I'm not sure how to have this problem replicated

I Have the Crash dump if it is needed

**Comment by BlossomiShymae** [comment]
You will need to submit a ticket to game support. This place is for issues relating to the Riot API Developer Ecosystem. :>

https://support.riotgames.com/
